/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "controlador.v:1" *)
module controlador_estacionamiento(clk, rst, sensor_vehicule, sensor_moved_vehicule, password_input, open_gate, close_gate, alarm_wrong_pin, alarm_blocked);
  (* src = "controlador.v:86" *)
  wire _000_;
  (* src = "controlador.v:86" *)
  wire _001_;
  (* src = "controlador.v:86" *)
  wire _002_;
  (* src = "controlador.v:86" *)
  wire [2:0] _003_;
  (* src = "controlador.v:86" *)
  wire _004_;
  (* src = "controlador.v:125" *)
  (* unused_bits = "3" *)
  wire [31:0] _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire [6:0] _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire [7:0] _023_;
  wire [3:0] _024_;
  wire [1:0] _025_;
  wire [15:0] _026_;
  wire [7:0] _027_;
  wire [15:0] _028_;
  wire [7:0] _029_;
  wire [15:0] _030_;
  wire _031_;
  (* src = "controlador.v:124|controlador.v:95|<techmap.v>:432" *)
  wire [1:0] _032_;
  (* src = "controlador.v:124|controlador.v:95|<techmap.v>:432" *)
  wire [5:0] _033_;
  (* src = "controlador.v:72|<techmap.v>:260|<techmap.v>:203" *)
  wire [31:0] _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  (* src = "controlador.v:126|<techmap.v>:260|<techmap.v>:203" *)
  wire [31:0] _038_;
  wire _039_;
  wire _040_;
  (* src = "controlador.v:119|controlador.v:95|<techmap.v>:445" *)
  wire _041_;
  (* src = "controlador.v:131|controlador.v:95|<techmap.v>:445" *)
  wire _042_;
  (* src = "controlador.v:124|controlador.v:95|<techmap.v>:445" *)
  wire _043_;
  (* src = "controlador.v:119|controlador.v:95|<techmap.v>:445" *)
  wire _044_;
  (* src = "controlador.v:124|controlador.v:95|<techmap.v>:445" *)
  wire _045_;
  (* src = "controlador.v:126|<techmap.v>:260|<techmap.v>:221" *)
  wire _046_;
  (* src = "controlador.v:11" *)
  output alarm_blocked;
  reg alarm_blocked;
  (* src = "controlador.v:10" *)
  output alarm_wrong_pin;
  reg alarm_wrong_pin;
  (* src = "controlador.v:2" *)
  input clk;
  (* src = "controlador.v:9" *)
  output close_gate;
  reg close_gate;
  (* src = "controlador.v:26" *)
  reg [2:0] counter;
  (* src = "controlador.v:8" *)
  output open_gate;
  reg open_gate;
  (* src = "controlador.v:7" *)
  input [15:0] password_input;
  (* src = "controlador.v:3" *)
  input rst;
  (* src = "controlador.v:5" *)
  input sensor_moved_vehicule;
  (* src = "controlador.v:4" *)
  input sensor_vehicule;
  (* onehot = 32'd1 *)
  reg [6:0] state;
  assign _023_[0] = _030_[0] |(* src = "controlador.v:54" *)  password_input[1];
  assign _023_[1] = password_input[2] |(* src = "controlador.v:54" *)  password_input[3];
  assign _023_[2] = password_input[4] |(* src = "controlador.v:54" *)  _030_[5];
  assign _023_[3] = _030_[6] |(* src = "controlador.v:54" *)  password_input[7];
  assign _023_[4] = _030_[8] |(* src = "controlador.v:54" *)  _030_[9];
  assign _023_[5] = _030_[10] |(* src = "controlador.v:54" *)  password_input[11];
  assign _023_[6] = _030_[12] |(* src = "controlador.v:54" *)  _030_[13];
  assign _023_[7] = password_input[14] |(* src = "controlador.v:54" *)  password_input[15];
  assign _024_[0] = _023_[0] |(* src = "controlador.v:54" *)  _023_[1];
  assign _024_[1] = _023_[2] |(* src = "controlador.v:54" *)  _023_[3];
  assign _024_[2] = _023_[4] |(* src = "controlador.v:54" *)  _023_[5];
  assign _024_[3] = _023_[6] |(* src = "controlador.v:54" *)  _023_[7];
  assign _025_[0] = _024_[0] |(* src = "controlador.v:54" *)  _024_[1];
  assign _025_[1] = _024_[2] |(* src = "controlador.v:54" *)  _024_[3];
  assign _018_ = _025_[0] |(* src = "controlador.v:54" *)  _025_[1];
  assign _022_ = state[1] | state[0];
  assign _014_[6] = _012_ | _013_;
  assign _014_[4] = _009_ | _010_;
  assign _021_ = state[6] | state[0];
  assign _014_[0] = state[1] | _006_;
  assign _014_[3] = state[3] | _008_;
  assign _016_ = _036_ | _027_[0];
  assign _045_ = state[5] |(* src = "controlador.v:124|controlador.v:95|<techmap.v>:445" *)  state[0];
  assign _028_[0] = _005_[0] &(* src = "controlador.v:126" *)  counter[1];
  assign _029_[0] = _028_[0] &(* src = "controlador.v:126" *)  _026_[1];
  assign _041_ = _022_ |(* src = "controlador.v:119|controlador.v:95|<techmap.v>:445" *)  state[6];
  assign _042_ = state[3] |(* src = "controlador.v:131|controlador.v:95|<techmap.v>:445" *)  _021_;
  assign _043_ = state[5] |(* src = "controlador.v:124|controlador.v:95|<techmap.v>:445" *)  _021_;
  assign _044_ = state[1] |(* src = "controlador.v:119|controlador.v:95|<techmap.v>:445" *)  _021_;
  assign _020_ = ~(* src = "controlador.v:54" *) _018_;
  assign _031_ = _040_ ? (* src = "controlador.v:126" *) alarm_wrong_pin : 1'h1;
  assign _003_[0] = _045_ ? (* src = "controlador.v:124|controlador.v:95|<techmap.v>:445" *) _033_[0] : counter[0];
  assign _003_[1] = _045_ ? (* src = "controlador.v:124|controlador.v:95|<techmap.v>:445" *) _033_[1] : counter[1];
  assign _003_[2] = _045_ ? (* src = "controlador.v:124|controlador.v:95|<techmap.v>:445" *) _033_[2] : counter[2];
  assign _004_ = _041_ ? (* src = "controlador.v:119|controlador.v:95|<techmap.v>:445" *) state[6] : open_gate;
  assign _000_ = _042_ ? (* src = "controlador.v:131|controlador.v:95|<techmap.v>:445" *) state[3] : alarm_blocked;
  assign _001_ = _043_ ? (* src = "controlador.v:124|controlador.v:95|<techmap.v>:445" *) _032_[0] : alarm_wrong_pin;
  assign _002_ = _044_ ? (* src = "controlador.v:119|controlador.v:95|<techmap.v>:445" *) state[1] : close_gate;
  assign _019_ = ~sensor_moved_vehicule;
  assign _015_ = ~sensor_vehicule;
  assign _017_ = ~_016_;
  assign _036_ = ~(* src = "controlador.v:72" *) _037_;
  assign _035_ = ~(* src = "controlador.v:72" *) _034_[31];
  assign _039_ = ~(* src = "controlador.v:126" *) _038_[31];
  always @(posedge clk or posedge rst)
    if (rst)
      state[0] <= 1;
    else
      state[0] <= _014_[0];
  always @(posedge clk or posedge rst)
    if (rst)
      state[1] <= 0;
    else
      state[1] <= _007_;
  always @(posedge clk or posedge rst)
    if (rst)
      state[2] <= 0;
    else
      state[2] <= state[4];
  always @(posedge clk or posedge rst)
    if (rst)
      state[3] <= 0;
    else
      state[3] <= _014_[3];
  always @(posedge clk or posedge rst)
    if (rst)
      state[4] <= 0;
    else
      state[4] <= _014_[4];
  always @(posedge clk or posedge rst)
    if (rst)
      state[5] <= 0;
    else
      state[5] <= _011_;
  always @(posedge clk or posedge rst)
    if (rst)
      state[6] <= 0;
    else
      state[6] <= _014_[6];
  (* src = "controlador.v:86" *)
  always @(posedge clk or posedge rst)
    if (rst)
      close_gate <= 0;
    else
      close_gate <= _002_;
  (* src = "controlador.v:86" *)
  always @(posedge clk or posedge rst)
    if (rst)
      alarm_wrong_pin <= 0;
    else
      alarm_wrong_pin <= _001_;
  (* src = "controlador.v:86" *)
  always @(posedge clk or posedge rst)
    if (rst)
      alarm_blocked <= 0;
    else
      alarm_blocked <= _000_;
  (* src = "controlador.v:86" *)
  always @(posedge clk or posedge rst)
    if (rst)
      open_gate <= 0;
    else
      open_gate <= _004_;
  (* src = "controlador.v:86" *)
  always @(posedge clk or posedge rst)
    if (rst)
      counter[0] <= 0;
    else
      counter[0] <= _003_[0];
  (* src = "controlador.v:86" *)
  always @(posedge clk or posedge rst)
    if (rst)
      counter[1] <= 0;
    else
      counter[1] <= _003_[1];
  (* src = "controlador.v:86" *)
  always @(posedge clk or posedge rst)
    if (rst)
      counter[2] <= 0;
    else
      counter[2] <= _003_[2];
  assign _027_[0] = _026_[1] &(* src = "controlador.v:72|<techmap.v>:260|<techmap.v>:221" *)  _026_[0];
  assign _034_[31] = counter[2] |(* src = "controlador.v:72|<techmap.v>:260|<techmap.v>:229" *)  _027_[0];
  assign _026_[0] = counter[1] &(* src = "controlador.v:125|<techmap.v>:260|<techmap.v>:221" *)  counter[0];
  assign _038_[1] = counter[1] &(* src = "controlador.v:126|<techmap.v>:260|<techmap.v>:221" *)  _038_[0];
  assign _046_ = _026_[1] &(* src = "controlador.v:126|<techmap.v>:260|<techmap.v>:229" *)  _038_[1];
  assign _038_[0] = counter[0] |(* src = "controlador.v:126|<techmap.v>:260|<techmap.v>:212" *)  _005_[0];
  assign _038_[31] = counter[2] |(* src = "controlador.v:126|<techmap.v>:260|<techmap.v>:221" *)  _046_;
  assign _030_[0] = password_input[0] ^(* src = "controlador.v:54" *)  1'h1;
  assign _030_[5] = password_input[5] ^(* src = "controlador.v:54" *)  1'h1;
  assign _030_[6] = password_input[6] ^(* src = "controlador.v:54" *)  1'h1;
  assign _030_[8] = password_input[8] ^(* src = "controlador.v:54" *)  1'h1;
  assign _030_[9] = password_input[9] ^(* src = "controlador.v:54" *)  1'h1;
  assign _030_[10] = password_input[10] ^(* src = "controlador.v:54" *)  1'h1;
  assign _030_[12] = password_input[12] ^(* src = "controlador.v:54" *)  1'h1;
  assign _030_[13] = password_input[13] ^(* src = "controlador.v:54" *)  1'h1;
  assign _007_ = sensor_moved_vehicule & state[6];
  assign _008_ = _016_ & state[5];
  assign _013_ = _020_ & state[2];
  assign _012_ = _019_ & state[6];
  assign _011_ = _018_ & state[2];
  assign _010_ = _017_ & state[5];
  assign _006_ = _015_ & state[0];
  assign _009_ = sensor_vehicule & state[0];
  assign _037_ = _035_ | _027_[0];
  assign _033_[0] = _005_[0] &(* src = "controlador.v:124|controlador.v:95|<techmap.v>:434" *)  state[5];
  assign _033_[1] = _005_[1] &(* src = "controlador.v:124|controlador.v:95|<techmap.v>:434" *)  state[5];
  assign _033_[2] = _005_[2] &(* src = "controlador.v:124|controlador.v:95|<techmap.v>:434" *)  state[5];
  assign _040_ = _039_ | _029_[0];
  assign _032_[0] = _031_ &(* src = "controlador.v:124|controlador.v:95|<techmap.v>:434" *)  state[5];
  assign _005_[0] = counter[0] ^(* src = "controlador.v:72|<techmap.v>:263" *)  1'h1;
  assign _026_[1] = counter[2] ^(* src = "controlador.v:72|<techmap.v>:262" *)  1'h1;
  assign _005_[1] = counter[1] ^(* src = "controlador.v:125|<techmap.v>:263" *)  counter[0];
  assign _005_[2] = counter[2] ^(* src = "controlador.v:125|<techmap.v>:263" *)  _026_[0];
  assign _005_[31:4] = 28'h0000000;
  assign { _014_[5], _014_[2:1] } = { _011_, state[4], _007_ };
  assign _026_[15:2] = 14'h3fff;
  assign _027_[7:1] = 7'h7f;
  assign _028_[15:1] = { 14'h3fff, _026_[1] };
  assign _029_[7:1] = 7'h7f;
  assign { _030_[15:14], _030_[11], _030_[7], _030_[4:1] } = { password_input[15:14], password_input[11], password_input[7], password_input[4:1] };
  assign _032_[1] = 1'h0;
  assign _033_[5:3] = 3'h0;
  assign _034_[30:0] = { _034_[31], _034_[31], _034_[31], _034_[31], _034_[31], _034_[31], _034_[31], _034_[31], _034_[31], _034_[31], _034_[31], _034_[31], _034_[31], _034_[31], _034_[31], _034_[31], _034_[31], _034_[31], _034_[31], _034_[31], _034_[31], _034_[31], _034_[31], _034_[31], _034_[31], _034_[31], _034_[31], _034_[31], _034_[31], _026_[0], counter[0] };
  assign _038_[30:2] = { _038_[31], _038_[31], _038_[31], _038_[31], _038_[31], _038_[31], _038_[31], _038_[31], _038_[31], _038_[31], _038_[31], _038_[31], _038_[31], _038_[31], _038_[31], _038_[31], _038_[31], _038_[31], _038_[31], _038_[31], _038_[31], _038_[31], _038_[31], _038_[31], _038_[31], _038_[31], _038_[31], _038_[31], _038_[31] };
endmodule
