/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "controlador.v:1" *)
module controlador_estacionamiento(clk, rst, sensor_vehicule, sensor_moved_vehicule, password_input, open_gate, close_gate, alarm_wrong_pin, alarm_blocked);
  (* src = "controlador.v:86" *)
  wire _000_;
  (* src = "controlador.v:86" *)
  wire _001_;
  (* src = "controlador.v:86" *)
  wire _002_;
  (* src = "controlador.v:86" *)
  wire [2:0] _003_;
  (* src = "controlador.v:86" *)
  wire _004_;
  (* src = "controlador.v:125" *)
  (* unused_bits = "3" *)
  wire [31:0] _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire [6:0] _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire [7:0] _028_;
  wire [3:0] _029_;
  wire [1:0] _030_;
  wire _031_;
  wire [15:0] _032_;
  wire [7:0] _033_;
  wire [15:0] _034_;
  wire [7:0] _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire [15:0] _040_;
  wire [1:0] _041_;
  wire [1:0] _042_;
  wire [1:0] _043_;
  wire [1:0] _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  (* src = "controlador.v:54" *)
  wire _050_;
  (* src = "controlador.v:72" *)
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  (* src = "controlador.v:124|controlador.v:95|<techmap.v>:432" *)
  wire [1:0] _055_;
  wire _056_;
  wire _057_;
  (* src = "controlador.v:124|controlador.v:95|<techmap.v>:432" *)
  wire [5:0] _058_;
  wire [2:0] _059_;
  (* src = "controlador.v:72|<techmap.v>:260|<techmap.v>:203" *)
  wire [31:0] _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  (* src = "controlador.v:126|<techmap.v>:260|<techmap.v>:203" *)
  wire [31:0] _064_;
  wire _065_;
  wire _066_;
  (* src = "controlador.v:119|controlador.v:95|<techmap.v>:445" *)
  wire _067_;
  (* src = "controlador.v:131|controlador.v:95|<techmap.v>:445" *)
  wire _068_;
  (* src = "controlador.v:124|controlador.v:95|<techmap.v>:445" *)
  wire _069_;
  (* src = "controlador.v:119|controlador.v:95|<techmap.v>:445" *)
  wire _070_;
  (* src = "controlador.v:124|controlador.v:95|<techmap.v>:445" *)
  wire _071_;
  (* src = "controlador.v:126|<techmap.v>:260|<techmap.v>:221" *)
  wire _072_;
  (* src = "controlador.v:11" *)
  output alarm_blocked;
  reg alarm_blocked;
  (* src = "controlador.v:10" *)
  output alarm_wrong_pin;
  reg alarm_wrong_pin;
  (* src = "controlador.v:2" *)
  input clk;
  (* src = "controlador.v:9" *)
  output close_gate;
  reg close_gate;
  (* src = "controlador.v:26" *)
  reg [2:0] counter;
  (* src = "controlador.v:8" *)
  output open_gate;
  reg open_gate;
  (* src = "controlador.v:7" *)
  input [15:0] password_input;
  (* src = "controlador.v:3" *)
  input rst;
  (* src = "controlador.v:5" *)
  input sensor_moved_vehicule;
  (* src = "controlador.v:4" *)
  input sensor_vehicule;
  (* onehot = 32'd1 *)
  reg [6:0] state;
  assign _028_[0] = _040_[0] |(* src = "controlador.v:54" *)  password_input[1];
  assign _028_[1] = password_input[2] |(* src = "controlador.v:54" *)  password_input[3];
  assign _028_[2] = password_input[4] |(* src = "controlador.v:54" *)  _040_[5];
  assign _028_[3] = _040_[6] |(* src = "controlador.v:54" *)  password_input[7];
  assign _028_[4] = _040_[8] |(* src = "controlador.v:54" *)  _040_[9];
  assign _028_[5] = _040_[10] |(* src = "controlador.v:54" *)  password_input[11];
  assign _028_[6] = _040_[12] |(* src = "controlador.v:54" *)  _040_[13];
  assign _028_[7] = password_input[14] |(* src = "controlador.v:54" *)  password_input[15];
  assign _029_[0] = _028_[0] |(* src = "controlador.v:54" *)  _028_[1];
  assign _029_[1] = _028_[2] |(* src = "controlador.v:54" *)  _028_[3];
  assign _029_[2] = _028_[4] |(* src = "controlador.v:54" *)  _028_[5];
  assign _029_[3] = _028_[6] |(* src = "controlador.v:54" *)  _028_[7];
  assign _030_[0] = _029_[0] |(* src = "controlador.v:54" *)  _029_[1];
  assign _030_[1] = _029_[2] |(* src = "controlador.v:54" *)  _029_[3];
  assign _045_ = _030_[0] |(* src = "controlador.v:54" *)  _030_[1];
  assign _046_ = rst | _041_[1];
  assign _027_ = state[1] | state[0];
  assign _016_[6] = _014_ | _015_;
  assign _047_ = rst | _042_[1];
  assign _048_ = rst | _043_[1];
  assign _016_[4] = _011_ | _012_;
  assign _016_[3] = _009_ | _010_;
  assign _026_ = state[6] | state[0];
  assign _031_ = state[1] | _006_;
  assign _016_[0] = _031_ | rst;
  assign _049_ = rst | _044_[1];
  assign _051_ = _062_ | _033_[0];
  assign _071_ = state[5] |(* src = "controlador.v:124|controlador.v:95|<techmap.v>:445" *)  state[0];
  assign _034_[0] = _005_[0] &(* src = "controlador.v:126" *)  counter[1];
  assign _035_[0] = _034_[0] &(* src = "controlador.v:126" *)  _032_[1];
  assign _067_ = _027_ |(* src = "controlador.v:119|controlador.v:95|<techmap.v>:445" *)  state[6];
  assign _068_ = state[3] |(* src = "controlador.v:131|controlador.v:95|<techmap.v>:445" *)  _026_;
  assign _069_ = state[5] |(* src = "controlador.v:124|controlador.v:95|<techmap.v>:445" *)  _026_;
  assign _070_ = state[1] |(* src = "controlador.v:119|controlador.v:95|<techmap.v>:445" *)  _026_;
  assign _036_ = rst | sensor_moved_vehicule;
  assign _037_ = rst | _050_;
  assign _038_ = rst | _051_;
  assign _039_ = rst | sensor_vehicule;
  assign _050_ = ~(* src = "controlador.v:54" *) _045_;
  assign _018_ = ~_046_;
  assign _025_ = ~_047_;
  assign _021_ = ~_048_;
  assign _024_ = ~_036_;
  assign _023_ = ~_037_;
  assign _022_ = ~_038_;
  assign _017_ = ~_039_;
  assign _020_ = ~_049_;
  assign _003_[0] = rst ? (* src = "controlador.v:87" *) 1'h0 : _059_[0];
  assign _003_[1] = rst ? (* src = "controlador.v:87" *) 1'h0 : _059_[1];
  assign _003_[2] = rst ? (* src = "controlador.v:87" *) 1'h0 : _059_[2];
  assign _004_ = rst ? (* src = "controlador.v:87" *) 1'h0 : _052_;
  assign _000_ = rst ? (* src = "controlador.v:87" *) 1'h0 : _053_;
  assign _054_ = _066_ ? (* src = "controlador.v:126" *) alarm_wrong_pin : 1'h1;
  assign _001_ = rst ? (* src = "controlador.v:87" *) 1'h0 : _056_;
  assign _002_ = rst ? (* src = "controlador.v:87" *) 1'h0 : _057_;
  assign _059_[0] = _071_ ? (* src = "controlador.v:124|controlador.v:95|<techmap.v>:445" *) _058_[0] : counter[0];
  assign _059_[1] = _071_ ? (* src = "controlador.v:124|controlador.v:95|<techmap.v>:445" *) _058_[1] : counter[1];
  assign _059_[2] = _071_ ? (* src = "controlador.v:124|controlador.v:95|<techmap.v>:445" *) _058_[2] : counter[2];
  assign _052_ = _067_ ? (* src = "controlador.v:119|controlador.v:95|<techmap.v>:445" *) state[6] : open_gate;
  assign _053_ = _068_ ? (* src = "controlador.v:131|controlador.v:95|<techmap.v>:445" *) state[3] : alarm_blocked;
  assign _056_ = _069_ ? (* src = "controlador.v:124|controlador.v:95|<techmap.v>:445" *) _055_[0] : alarm_wrong_pin;
  assign _057_ = _070_ ? (* src = "controlador.v:119|controlador.v:95|<techmap.v>:445" *) state[1] : close_gate;
  assign _019_ = ~rst;
  assign _062_ = ~(* src = "controlador.v:72" *) _063_;
  assign _061_ = ~(* src = "controlador.v:72" *) _060_[31];
  assign _065_ = ~(* src = "controlador.v:126" *) _064_[31];
  always @(posedge clk)
      state[0] <= _016_[0];
  always @(posedge clk)
      state[1] <= _007_;
  always @(posedge clk)
      state[2] <= _008_;
  always @(posedge clk)
      state[3] <= _016_[3];
  always @(posedge clk)
      state[4] <= _016_[4];
  always @(posedge clk)
      state[5] <= _013_;
  always @(posedge clk)
      state[6] <= _016_[6];
  (* src = "controlador.v:86" *)
  always @(posedge clk)
      close_gate <= _002_;
  (* src = "controlador.v:86" *)
  always @(posedge clk)
      alarm_wrong_pin <= _001_;
  (* src = "controlador.v:86" *)
  always @(posedge clk)
      alarm_blocked <= _000_;
  (* src = "controlador.v:86" *)
  always @(posedge clk)
      open_gate <= _004_;
  (* src = "controlador.v:86" *)
  always @(posedge clk)
      counter[0] <= _003_[0];
  (* src = "controlador.v:86" *)
  always @(posedge clk)
      counter[1] <= _003_[1];
  (* src = "controlador.v:86" *)
  always @(posedge clk)
      counter[2] <= _003_[2];
  assign _005_[0] = counter[0] ^(* src = "controlador.v:126|<techmap.v>:262" *)  1'h1;
  assign _032_[1] = counter[2] ^(* src = "controlador.v:126|<techmap.v>:262" *)  1'h1;
  assign _033_[0] = _032_[1] &(* src = "controlador.v:72|<techmap.v>:260|<techmap.v>:229" *)  _032_[0];
  assign _060_[31] = counter[2] |(* src = "controlador.v:72|<techmap.v>:260|<techmap.v>:221" *)  _033_[0];
  assign _032_[0] = counter[1] &(* src = "controlador.v:125|<techmap.v>:260|<techmap.v>:221" *)  counter[0];
  assign _064_[1] = counter[1] &(* src = "controlador.v:126|<techmap.v>:260|<techmap.v>:221" *)  _064_[0];
  assign _072_ = _032_[1] &(* src = "controlador.v:126|<techmap.v>:260|<techmap.v>:229" *)  _064_[1];
  assign _064_[0] = counter[0] |(* src = "controlador.v:126|<techmap.v>:260|<techmap.v>:212" *)  _005_[0];
  assign _064_[31] = counter[2] |(* src = "controlador.v:126|<techmap.v>:260|<techmap.v>:221" *)  _072_;
  assign _040_[0] = password_input[0] ^(* src = "controlador.v:54" *)  1'h1;
  assign _040_[5] = password_input[5] ^(* src = "controlador.v:54" *)  1'h1;
  assign _040_[6] = password_input[6] ^(* src = "controlador.v:54" *)  1'h1;
  assign _040_[8] = password_input[8] ^(* src = "controlador.v:54" *)  1'h1;
  assign _040_[9] = password_input[9] ^(* src = "controlador.v:54" *)  1'h1;
  assign _040_[10] = password_input[10] ^(* src = "controlador.v:54" *)  1'h1;
  assign _040_[12] = password_input[12] ^(* src = "controlador.v:54" *)  1'h1;
  assign _040_[13] = password_input[13] ^(* src = "controlador.v:54" *)  1'h1;
  assign _041_[1] = sensor_moved_vehicule ^ 1'h1;
  assign _007_ = _018_ & state[6];
  assign _042_[1] = _050_ ^ 1'h1;
  assign _043_[1] = sensor_vehicule ^ 1'h1;
  assign _015_ = _025_ & state[2];
  assign _014_ = _024_ & state[6];
  assign _013_ = _023_ & state[2];
  assign _012_ = _022_ & state[5];
  assign _011_ = _021_ & state[0];
  assign _010_ = _019_ & state[3];
  assign _006_ = _017_ & state[0];
  assign _009_ = _020_ & state[5];
  assign _044_[1] = _051_ ^ 1'h1;
  assign _008_ = _019_ & state[4];
  assign _063_ = _061_ | _033_[0];
  assign _058_[0] = _005_[0] &(* src = "controlador.v:124|controlador.v:95|<techmap.v>:434" *)  state[5];
  assign _058_[1] = _005_[1] &(* src = "controlador.v:124|controlador.v:95|<techmap.v>:434" *)  state[5];
  assign _058_[2] = _005_[2] &(* src = "controlador.v:124|controlador.v:95|<techmap.v>:434" *)  state[5];
  assign _066_ = _065_ | _035_[0];
  assign _055_[0] = _054_ &(* src = "controlador.v:124|controlador.v:95|<techmap.v>:434" *)  state[5];
  assign _005_[1] = counter[1] ^(* src = "controlador.v:125|<techmap.v>:263" *)  counter[0];
  assign _005_[2] = counter[2] ^(* src = "controlador.v:125|<techmap.v>:263" *)  _032_[0];
  assign _005_[31:4] = 28'h0000000;
  assign { _016_[5], _016_[2:1] } = { _013_, _008_, _007_ };
  assign _032_[15:2] = 14'h3fff;
  assign _033_[7:1] = 7'h7f;
  assign _034_[15:1] = { 14'h3fff, _032_[1] };
  assign _035_[7:1] = 7'h7f;
  assign { _040_[15:14], _040_[11], _040_[7], _040_[4:1] } = { password_input[15:14], password_input[11], password_input[7], password_input[4:1] };
  assign _041_[0] = rst;
  assign _042_[0] = rst;
  assign _043_[0] = rst;
  assign _044_[0] = rst;
  assign _055_[1] = 1'h0;
  assign _058_[5:3] = 3'h0;
  assign _060_[30:0] = { _060_[31], _060_[31], _060_[31], _060_[31], _060_[31], _060_[31], _060_[31], _060_[31], _060_[31], _060_[31], _060_[31], _060_[31], _060_[31], _060_[31], _060_[31], _060_[31], _060_[31], _060_[31], _060_[31], _060_[31], _060_[31], _060_[31], _060_[31], _060_[31], _060_[31], _060_[31], _060_[31], _060_[31], _060_[31], _032_[0], counter[0] };
  assign _064_[30:2] = { _064_[31], _064_[31], _064_[31], _064_[31], _064_[31], _064_[31], _064_[31], _064_[31], _064_[31], _064_[31], _064_[31], _064_[31], _064_[31], _064_[31], _064_[31], _064_[31], _064_[31], _064_[31], _064_[31], _064_[31], _064_[31], _064_[31], _064_[31], _064_[31], _064_[31], _064_[31], _064_[31], _064_[31], _064_[31] };
endmodule
