/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "cajeroAutomatico.v:1" *)
module cajero_automatico(clk, rst, TARJETA_RECIBIDA, TIPO_TRANS, MONTO_STB, DIGITO_STB, DIGITO, PIN, MONTO, BALANCE_INICIAL, BALANCE_ACTUALIZADO, ENTREGAR_DINERO, PIN_INCORRECTO, ADVERTENCIA, BLOQUEO, FONDOS_INSUFICIENTES);
  (* src = "cajeroAutomatico.v:107" *)
  wire _0000_;
  (* src = "cajeroAutomatico.v:107" *)
  wire _0001_;
  (* src = "cajeroAutomatico.v:107" *)
  wire _0002_;
  (* src = "cajeroAutomatico.v:107" *)
  wire _0003_;
  (* src = "cajeroAutomatico.v:107" *)
  wire _0004_;
  (* src = "cajeroAutomatico.v:107" *)
  wire _0005_;
  (* src = "cajeroAutomatico.v:107" *)
  wire [1:0] _0006_;
  (* src = "cajeroAutomatico.v:107" *)
  wire [1:0] _0007_;
  (* src = "cajeroAutomatico.v:107" *)
  wire [15:0] _0008_;
  wire _0009_;
  wire _0010_;
  wire _0011_;
  wire _0012_;
  wire _0013_;
  wire _0014_;
  wire _0015_;
  wire _0016_;
  wire _0017_;
  wire _0018_;
  wire _0019_;
  wire _0020_;
  wire _0021_;
  wire _0022_;
  wire _0023_;
  wire _0024_;
  wire _0025_;
  wire _0026_;
  wire _0027_;
  wire _0028_;
  wire _0029_;
  wire _0030_;
  wire _0031_;
  wire _0032_;
  wire _0033_;
  wire _0034_;
  wire _0035_;
  wire _0036_;
  wire _0037_;
  wire _0038_;
  wire _0039_;
  wire _0040_;
  wire _0041_;
  wire _0042_;
  wire _0043_;
  wire _0044_;
  wire _0045_;
  wire _0046_;
  wire _0047_;
  wire _0048_;
  wire _0049_;
  wire _0050_;
  wire _0051_;
  wire _0052_;
  wire _0053_;
  wire _0054_;
  wire _0055_;
  wire _0056_;
  wire _0057_;
  wire _0058_;
  wire _0059_;
  wire _0060_;
  wire _0061_;
  wire _0062_;
  wire _0063_;
  wire _0064_;
  wire _0065_;
  wire _0066_;
  wire _0067_;
  wire _0068_;
  wire _0069_;
  wire _0070_;
  wire _0071_;
  wire _0072_;
  wire _0073_;
  wire _0074_;
  wire _0075_;
  wire _0076_;
  wire _0077_;
  wire _0078_;
  wire _0079_;
  wire _0080_;
  wire _0081_;
  wire _0082_;
  wire _0083_;
  wire _0084_;
  wire _0085_;
  wire _0086_;
  wire _0087_;
  wire _0088_;
  wire _0089_;
  wire _0090_;
  wire _0091_;
  wire _0092_;
  wire _0093_;
  wire _0094_;
  wire _0095_;
  wire _0096_;
  wire _0097_;
  wire _0098_;
  wire _0099_;
  wire _0100_;
  wire _0101_;
  wire _0102_;
  wire _0103_;
  wire _0104_;
  wire _0105_;
  wire _0106_;
  wire _0107_;
  wire _0108_;
  wire _0109_;
  wire _0110_;
  wire _0111_;
  wire _0112_;
  wire _0113_;
  wire _0114_;
  wire _0115_;
  wire _0116_;
  wire _0117_;
  wire _0118_;
  wire _0119_;
  wire _0120_;
  wire _0121_;
  wire _0122_;
  wire _0123_;
  wire _0124_;
  wire _0125_;
  wire _0126_;
  wire _0127_;
  wire _0128_;
  wire _0129_;
  wire _0130_;
  wire _0131_;
  wire _0132_;
  wire _0133_;
  wire _0134_;
  wire _0135_;
  wire _0136_;
  wire _0137_;
  wire _0138_;
  wire _0139_;
  wire _0140_;
  wire _0141_;
  wire _0142_;
  wire _0143_;
  wire _0144_;
  wire _0145_;
  wire _0146_;
  wire _0147_;
  wire _0148_;
  wire _0149_;
  wire _0150_;
  wire _0151_;
  wire _0152_;
  wire _0153_;
  wire _0154_;
  wire _0155_;
  wire _0156_;
  wire _0157_;
  wire _0158_;
  wire _0159_;
  wire _0160_;
  wire _0161_;
  wire _0162_;
  wire _0163_;
  wire _0164_;
  wire _0165_;
  wire _0166_;
  wire _0167_;
  wire _0168_;
  wire _0169_;
  wire _0170_;
  wire _0171_;
  wire _0172_;
  wire _0173_;
  wire _0174_;
  wire _0175_;
  wire _0176_;
  wire _0177_;
  wire _0178_;
  wire _0179_;
  wire _0180_;
  wire _0181_;
  wire _0182_;
  wire _0183_;
  wire _0184_;
  wire _0185_;
  wire _0186_;
  wire _0187_;
  wire _0188_;
  wire _0189_;
  wire _0190_;
  wire _0191_;
  wire _0192_;
  wire _0193_;
  wire _0194_;
  wire _0195_;
  wire _0196_;
  wire _0197_;
  wire _0198_;
  wire _0199_;
  wire _0200_;
  wire _0201_;
  wire _0202_;
  wire _0203_;
  wire _0204_;
  wire _0205_;
  wire _0206_;
  wire _0207_;
  wire _0208_;
  wire _0209_;
  wire _0210_;
  wire _0211_;
  wire _0212_;
  wire _0213_;
  wire _0214_;
  wire _0215_;
  wire _0216_;
  wire _0217_;
  wire _0218_;
  wire _0219_;
  wire _0220_;
  wire _0221_;
  wire _0222_;
  wire _0223_;
  wire _0224_;
  wire _0225_;
  wire _0226_;
  wire _0227_;
  wire _0228_;
  wire _0229_;
  wire _0230_;
  wire _0231_;
  wire _0232_;
  wire _0233_;
  wire _0234_;
  wire _0235_;
  wire _0236_;
  wire _0237_;
  wire _0238_;
  wire _0239_;
  wire _0240_;
  wire _0241_;
  wire _0242_;
  wire _0243_;
  wire _0244_;
  wire _0245_;
  wire _0246_;
  wire _0247_;
  wire _0248_;
  wire _0249_;
  wire _0250_;
  wire _0251_;
  wire _0252_;
  wire _0253_;
  wire _0254_;
  wire _0255_;
  wire _0256_;
  wire _0257_;
  wire _0258_;
  wire _0259_;
  wire _0260_;
  wire _0261_;
  wire _0262_;
  wire _0263_;
  wire _0264_;
  wire _0265_;
  wire _0266_;
  wire _0267_;
  wire _0268_;
  wire _0269_;
  wire _0270_;
  wire _0271_;
  wire _0272_;
  wire _0273_;
  wire _0274_;
  wire _0275_;
  wire _0276_;
  wire _0277_;
  wire _0278_;
  wire _0279_;
  wire _0280_;
  wire _0281_;
  wire _0282_;
  wire _0283_;
  wire _0284_;
  wire _0285_;
  wire _0286_;
  wire _0287_;
  wire _0288_;
  wire _0289_;
  wire _0290_;
  wire _0291_;
  wire _0292_;
  wire _0293_;
  wire _0294_;
  wire _0295_;
  wire _0296_;
  wire _0297_;
  wire _0298_;
  wire _0299_;
  wire _0300_;
  wire _0301_;
  wire _0302_;
  wire _0303_;
  wire _0304_;
  wire _0305_;
  wire _0306_;
  wire _0307_;
  wire _0308_;
  wire _0309_;
  wire _0310_;
  wire _0311_;
  wire _0312_;
  wire _0313_;
  wire _0314_;
  wire _0315_;
  wire _0316_;
  wire _0317_;
  wire _0318_;
  wire _0319_;
  wire _0320_;
  wire _0321_;
  wire _0322_;
  wire _0323_;
  wire _0324_;
  wire _0325_;
  wire _0326_;
  wire _0327_;
  wire _0328_;
  wire _0329_;
  wire _0330_;
  wire _0331_;
  wire _0332_;
  wire _0333_;
  wire _0334_;
  wire _0335_;
  wire _0336_;
  wire _0337_;
  wire _0338_;
  wire _0339_;
  wire _0340_;
  wire _0341_;
  wire _0342_;
  wire _0343_;
  wire _0344_;
  wire _0345_;
  wire _0346_;
  wire _0347_;
  wire _0348_;
  wire _0349_;
  wire _0350_;
  wire _0351_;
  wire _0352_;
  wire _0353_;
  wire _0354_;
  wire _0355_;
  wire _0356_;
  wire _0357_;
  wire _0358_;
  wire _0359_;
  wire _0360_;
  wire _0361_;
  wire _0362_;
  wire _0363_;
  wire _0364_;
  wire _0365_;
  wire _0366_;
  wire _0367_;
  wire _0368_;
  wire _0369_;
  wire _0370_;
  wire _0371_;
  wire _0372_;
  wire _0373_;
  wire _0374_;
  wire _0375_;
  wire _0376_;
  wire _0377_;
  wire _0378_;
  wire _0379_;
  wire _0380_;
  wire _0381_;
  wire _0382_;
  wire _0383_;
  wire _0384_;
  wire _0385_;
  wire _0386_;
  wire _0387_;
  wire _0388_;
  wire _0389_;
  wire _0390_;
  wire _0391_;
  wire _0392_;
  wire _0393_;
  wire _0394_;
  wire _0395_;
  wire _0396_;
  wire _0397_;
  wire _0398_;
  wire _0399_;
  wire _0400_;
  wire _0401_;
  wire _0402_;
  wire _0403_;
  wire _0404_;
  wire _0405_;
  wire _0406_;
  wire _0407_;
  wire _0408_;
  wire _0409_;
  wire _0410_;
  wire _0411_;
  wire _0412_;
  wire _0413_;
  wire _0414_;
  wire _0415_;
  wire _0416_;
  wire _0417_;
  wire _0418_;
  wire _0419_;
  wire _0420_;
  wire _0421_;
  wire _0422_;
  wire _0423_;
  wire _0424_;
  wire _0425_;
  wire _0426_;
  wire _0427_;
  wire _0428_;
  wire _0429_;
  wire _0430_;
  wire _0431_;
  wire _0432_;
  wire _0433_;
  wire _0434_;
  wire _0435_;
  wire _0436_;
  wire _0437_;
  wire _0438_;
  wire _0439_;
  wire _0440_;
  wire _0441_;
  wire _0442_;
  wire _0443_;
  wire _0444_;
  wire _0445_;
  wire _0446_;
  wire _0447_;
  wire _0448_;
  wire _0449_;
  wire _0450_;
  wire _0451_;
  wire _0452_;
  wire _0453_;
  wire _0454_;
  wire _0455_;
  wire _0456_;
  wire _0457_;
  wire _0458_;
  wire _0459_;
  wire _0460_;
  wire _0461_;
  wire _0462_;
  wire _0463_;
  wire _0464_;
  wire _0465_;
  wire _0466_;
  wire _0467_;
  wire _0468_;
  wire _0469_;
  wire _0470_;
  wire _0471_;
  wire _0472_;
  wire _0473_;
  wire _0474_;
  wire _0475_;
  wire _0476_;
  wire _0477_;
  wire _0478_;
  wire _0479_;
  wire _0480_;
  wire _0481_;
  wire _0482_;
  wire _0483_;
  wire _0484_;
  wire _0485_;
  wire _0486_;
  wire _0487_;
  wire _0488_;
  wire _0489_;
  wire _0490_;
  wire _0491_;
  wire _0492_;
  wire _0493_;
  wire _0494_;
  wire _0495_;
  wire _0496_;
  wire _0497_;
  wire _0498_;
  wire _0499_;
  wire _0500_;
  wire _0501_;
  wire _0502_;
  wire _0503_;
  wire _0504_;
  wire _0505_;
  wire _0506_;
  wire _0507_;
  wire _0508_;
  wire _0509_;
  wire _0510_;
  wire _0511_;
  wire _0512_;
  wire _0513_;
  wire _0514_;
  (* src = "cajeroAutomatico.v:17" *)
  output ADVERTENCIA;
  (* src = "cajeroAutomatico.v:14" *)
  output BALANCE_ACTUALIZADO;
  (* src = "cajeroAutomatico.v:12" *)
  input [63:0] BALANCE_INICIAL;
  (* src = "cajeroAutomatico.v:18" *)
  output BLOQUEO;
  (* src = "cajeroAutomatico.v:9" *)
  input [3:0] DIGITO;
  (* src = "cajeroAutomatico.v:8" *)
  input DIGITO_STB;
  (* src = "cajeroAutomatico.v:15" *)
  output ENTREGAR_DINERO;
  (* src = "cajeroAutomatico.v:19" *)
  output FONDOS_INSUFICIENTES;
  (* src = "cajeroAutomatico.v:11" *)
  input [31:0] MONTO;
  (* src = "cajeroAutomatico.v:7" *)
  input MONTO_STB;
  (* src = "cajeroAutomatico.v:10" *)
  input [15:0] PIN;
  (* src = "cajeroAutomatico.v:16" *)
  output PIN_INCORRECTO;
  (* src = "cajeroAutomatico.v:5" *)
  input TARJETA_RECIBIDA;
  (* src = "cajeroAutomatico.v:6" *)
  input TIPO_TRANS;
  (* src = "cajeroAutomatico.v:3" *)
  input clk;
  (* src = "cajeroAutomatico.v:37" *)
  wire [1:0] digitos_ingresados;
  (* src = "cajeroAutomatico.v:34" *)
  wire [1:0] intentos;
  (* src = "cajeroAutomatico.v:36" *)
  wire [15:0] pin_tecleado;
  (* src = "cajeroAutomatico.v:4" *)
  input rst;
  (* onehot = 32'd1 *)
  (* unused_bits = "7" *)
  wire [7:0] state;
  NOT _0515_ (
    .A(intentos[1]),
    .Y(_0016_)
  );
  NOT _0516_ (
    .A(rst),
    .Y(_0017_)
  );
  NOT _0517_ (
    .A(state[5]),
    .Y(_0018_)
  );
  NOT _0518_ (
    .A(state[2]),
    .Y(_0019_)
  );
  NOT _0519_ (
    .A(state[0]),
    .Y(_0020_)
  );
  NOT _0520_ (
    .A(state[3]),
    .Y(_0021_)
  );
  NOT _0521_ (
    .A(MONTO_STB),
    .Y(_0022_)
  );
  NOT _0522_ (
    .A(TIPO_TRANS),
    .Y(_0023_)
  );
  NOT _0523_ (
    .A(digitos_ingresados[0]),
    .Y(_0024_)
  );
  NOT _0524_ (
    .A(pin_tecleado[2]),
    .Y(_0025_)
  );
  NOT _0525_ (
    .A(pin_tecleado[5]),
    .Y(_0026_)
  );
  NOT _0526_ (
    .A(pin_tecleado[7]),
    .Y(_0027_)
  );
  NOT _0527_ (
    .A(pin_tecleado[9]),
    .Y(_0028_)
  );
  NOT _0528_ (
    .A(pin_tecleado[12]),
    .Y(_0029_)
  );
  NOT _0529_ (
    .A(pin_tecleado[15]),
    .Y(_0030_)
  );
  NOT _0530_ (
    .A(ENTREGAR_DINERO),
    .Y(_0031_)
  );
  NOT _0531_ (
    .A(BALANCE_ACTUALIZADO),
    .Y(_0032_)
  );
  NOT _0532_ (
    .A(intentos[0]),
    .Y(_0033_)
  );
  NOT _0533_ (
    .A(BALANCE_INICIAL[0]),
    .Y(_0034_)
  );
  NOT _0534_ (
    .A(BALANCE_INICIAL[1]),
    .Y(_0035_)
  );
  NOT _0535_ (
    .A(BALANCE_INICIAL[2]),
    .Y(_0036_)
  );
  NOT _0536_ (
    .A(BALANCE_INICIAL[3]),
    .Y(_0037_)
  );
  NOT _0537_ (
    .A(BALANCE_INICIAL[5]),
    .Y(_0038_)
  );
  NOT _0538_ (
    .A(BALANCE_INICIAL[6]),
    .Y(_0039_)
  );
  NOT _0539_ (
    .A(BALANCE_INICIAL[7]),
    .Y(_0040_)
  );
  NOT _0540_ (
    .A(BALANCE_INICIAL[8]),
    .Y(_0041_)
  );
  NOT _0541_ (
    .A(BALANCE_INICIAL[9]),
    .Y(_0042_)
  );
  NOT _0542_ (
    .A(BALANCE_INICIAL[10]),
    .Y(_0043_)
  );
  NOT _0543_ (
    .A(BALANCE_INICIAL[11]),
    .Y(_0044_)
  );
  NOT _0544_ (
    .A(BALANCE_INICIAL[13]),
    .Y(_0045_)
  );
  NOT _0545_ (
    .A(BALANCE_INICIAL[14]),
    .Y(_0046_)
  );
  NOT _0546_ (
    .A(BALANCE_INICIAL[15]),
    .Y(_0047_)
  );
  NOT _0547_ (
    .A(BALANCE_INICIAL[16]),
    .Y(_0048_)
  );
  NOT _0548_ (
    .A(BALANCE_INICIAL[17]),
    .Y(_0049_)
  );
  NOT _0549_ (
    .A(BALANCE_INICIAL[18]),
    .Y(_0050_)
  );
  NOT _0550_ (
    .A(BALANCE_INICIAL[19]),
    .Y(_0051_)
  );
  NOT _0551_ (
    .A(BALANCE_INICIAL[20]),
    .Y(_0052_)
  );
  NOT _0552_ (
    .A(BALANCE_INICIAL[21]),
    .Y(_0053_)
  );
  NOT _0553_ (
    .A(BALANCE_INICIAL[22]),
    .Y(_0054_)
  );
  NOT _0554_ (
    .A(BALANCE_INICIAL[23]),
    .Y(_0055_)
  );
  NOT _0555_ (
    .A(BALANCE_INICIAL[24]),
    .Y(_0056_)
  );
  NOT _0556_ (
    .A(BALANCE_INICIAL[26]),
    .Y(_0057_)
  );
  NOT _0557_ (
    .A(BALANCE_INICIAL[27]),
    .Y(_0058_)
  );
  NOT _0558_ (
    .A(BALANCE_INICIAL[28]),
    .Y(_0059_)
  );
  NOT _0559_ (
    .A(BALANCE_INICIAL[30]),
    .Y(_0060_)
  );
  NOT _0560_ (
    .A(BALANCE_INICIAL[31]),
    .Y(_0061_)
  );
  NOT _0561_ (
    .A(BALANCE_INICIAL[57]),
    .Y(_0062_)
  );
  NOT _0562_ (
    .A(BALANCE_INICIAL[59]),
    .Y(_0063_)
  );
  NOT _0563_ (
    .A(MONTO[1]),
    .Y(_0064_)
  );
  NOT _0564_ (
    .A(MONTO[2]),
    .Y(_0065_)
  );
  NOT _0565_ (
    .A(MONTO[3]),
    .Y(_0066_)
  );
  NOT _0566_ (
    .A(MONTO[4]),
    .Y(_0067_)
  );
  NOT _0567_ (
    .A(MONTO[5]),
    .Y(_0068_)
  );
  NOT _0568_ (
    .A(MONTO[6]),
    .Y(_0069_)
  );
  NOT _0569_ (
    .A(MONTO[7]),
    .Y(_0070_)
  );
  NOT _0570_ (
    .A(MONTO[8]),
    .Y(_0071_)
  );
  NOT _0571_ (
    .A(MONTO[9]),
    .Y(_0072_)
  );
  NOT _0572_ (
    .A(MONTO[10]),
    .Y(_0073_)
  );
  NOT _0573_ (
    .A(MONTO[11]),
    .Y(_0074_)
  );
  NOT _0574_ (
    .A(MONTO[12]),
    .Y(_0075_)
  );
  NOT _0575_ (
    .A(MONTO[13]),
    .Y(_0076_)
  );
  NOT _0576_ (
    .A(MONTO[14]),
    .Y(_0077_)
  );
  NOT _0577_ (
    .A(MONTO[15]),
    .Y(_0078_)
  );
  NOT _0578_ (
    .A(MONTO[16]),
    .Y(_0079_)
  );
  NOT _0579_ (
    .A(MONTO[18]),
    .Y(_0080_)
  );
  NOT _0580_ (
    .A(MONTO[19]),
    .Y(_0081_)
  );
  NOT _0581_ (
    .A(MONTO[20]),
    .Y(_0082_)
  );
  NOT _0582_ (
    .A(MONTO[21]),
    .Y(_0083_)
  );
  NOT _0583_ (
    .A(MONTO[22]),
    .Y(_0084_)
  );
  NOT _0584_ (
    .A(MONTO[23]),
    .Y(_0085_)
  );
  NOT _0585_ (
    .A(MONTO[24]),
    .Y(_0086_)
  );
  NOT _0586_ (
    .A(MONTO[25]),
    .Y(_0087_)
  );
  NOT _0587_ (
    .A(MONTO[26]),
    .Y(_0088_)
  );
  NOT _0588_ (
    .A(MONTO[27]),
    .Y(_0089_)
  );
  NOT _0589_ (
    .A(MONTO[28]),
    .Y(_0090_)
  );
  NOT _0590_ (
    .A(MONTO[29]),
    .Y(_0091_)
  );
  NOT _0591_ (
    .A(MONTO[30]),
    .Y(_0092_)
  );
  NOT _0592_ (
    .A(MONTO[31]),
    .Y(_0093_)
  );
  NOT _0593_ (
    .A(PIN[2]),
    .Y(_0094_)
  );
  NOT _0594_ (
    .A(PIN[5]),
    .Y(_0095_)
  );
  NOT _0595_ (
    .A(PIN[7]),
    .Y(_0096_)
  );
  NOT _0596_ (
    .A(PIN[9]),
    .Y(_0097_)
  );
  NOT _0597_ (
    .A(PIN[12]),
    .Y(_0098_)
  );
  NOT _0598_ (
    .A(PIN[15]),
    .Y(_0099_)
  );
  NOT _0599_ (
    .A(state[1]),
    .Y(_0100_)
  );
  NAND _0600_ (
    .A(digitos_ingresados[0]),
    .B(digitos_ingresados[1]),
    .Y(_0101_)
  );
  NOT _0601_ (
    .A(_0101_),
    .Y(_0102_)
  );
  NAND _0602_ (
    .A(DIGITO_STB),
    .B(_0102_),
    .Y(_0103_)
  );
  NAND _0603_ (
    .A(state[2]),
    .B(_0103_),
    .Y(_0104_)
  );
  NOR _0604_ (
    .A(_0021_),
    .B(intentos[0]),
    .Y(_0105_)
  );
  NOR _0605_ (
    .A(intentos[1]),
    .B(_0021_),
    .Y(_0106_)
  );
  NAND _0606_ (
    .A(_0016_),
    .B(state[3]),
    .Y(_0107_)
  );
  NOR _0607_ (
    .A(_0105_),
    .B(_0106_),
    .Y(_0108_)
  );
  NAND _0608_ (
    .A(_0104_),
    .B(_0108_),
    .Y(_0109_)
  );
  NOR _0609_ (
    .A(state[4]),
    .B(_0109_),
    .Y(_0110_)
  );
  NOR _0610_ (
    .A(rst),
    .B(_0110_),
    .Y(_0015_)
  );
  NOR _0611_ (
    .A(_0020_),
    .B(TARJETA_RECIBIDA),
    .Y(_0111_)
  );
  NOR _0612_ (
    .A(rst),
    .B(_0111_),
    .Y(_0112_)
  );
  NAND _0613_ (
    .A(_0018_),
    .B(_0112_),
    .Y(_0014_)
  );
  NAND _0614_ (
    .A(state[2]),
    .B(DIGITO_STB),
    .Y(_0113_)
  );
  NOR _0615_ (
    .A(digitos_ingresados[0]),
    .B(_0113_),
    .Y(_0114_)
  );
  NAND _0616_ (
    .A(_0019_),
    .B(state[0]),
    .Y(_0115_)
  );
  NAND _0617_ (
    .A(_0019_),
    .B(_0020_),
    .Y(_0116_)
  );
  NAND _0618_ (
    .A(_0113_),
    .B(_0115_),
    .Y(_0117_)
  );
  NOR _0619_ (
    .A(_0024_),
    .B(_0117_),
    .Y(_0118_)
  );
  NOR _0620_ (
    .A(_0114_),
    .B(_0118_),
    .Y(_0119_)
  );
  NOR _0621_ (
    .A(rst),
    .B(_0119_),
    .Y(_0006_[0])
  );
  NAND _0622_ (
    .A(DIGITO_STB),
    .B(digitos_ingresados[0]),
    .Y(_0120_)
  );
  NOR _0623_ (
    .A(_0104_),
    .B(_0120_),
    .Y(_0121_)
  );
  NOR _0624_ (
    .A(digitos_ingresados[1]),
    .B(_0121_),
    .Y(_0122_)
  );
  NAND _0625_ (
    .A(_0104_),
    .B(_0116_),
    .Y(_0123_)
  );
  NAND _0626_ (
    .A(_0017_),
    .B(_0123_),
    .Y(_0124_)
  );
  NOR _0627_ (
    .A(_0122_),
    .B(_0124_),
    .Y(_0006_[1])
  );
  NOR _0628_ (
    .A(rst),
    .B(_0113_),
    .Y(_0125_)
  );
  NOT _0629_ (
    .A(_0125_),
    .Y(_0126_)
  );
  NAND _0630_ (
    .A(DIGITO[0]),
    .B(_0125_),
    .Y(_0127_)
  );
  NOR _0631_ (
    .A(rst),
    .B(_0117_),
    .Y(_0128_)
  );
  NAND _0632_ (
    .A(pin_tecleado[0]),
    .B(_0128_),
    .Y(_0129_)
  );
  NAND _0633_ (
    .A(_0127_),
    .B(_0129_),
    .Y(_0008_[0])
  );
  NAND _0634_ (
    .A(DIGITO[1]),
    .B(_0125_),
    .Y(_0130_)
  );
  NAND _0635_ (
    .A(pin_tecleado[1]),
    .B(_0128_),
    .Y(_0131_)
  );
  NAND _0636_ (
    .A(_0130_),
    .B(_0131_),
    .Y(_0008_[1])
  );
  NAND _0637_ (
    .A(DIGITO[2]),
    .B(_0125_),
    .Y(_0132_)
  );
  NAND _0638_ (
    .A(pin_tecleado[2]),
    .B(_0128_),
    .Y(_0133_)
  );
  NAND _0639_ (
    .A(_0132_),
    .B(_0133_),
    .Y(_0008_[2])
  );
  NAND _0640_ (
    .A(DIGITO[3]),
    .B(_0125_),
    .Y(_0134_)
  );
  NAND _0641_ (
    .A(pin_tecleado[3]),
    .B(_0128_),
    .Y(_0135_)
  );
  NAND _0642_ (
    .A(_0134_),
    .B(_0135_),
    .Y(_0008_[3])
  );
  NAND _0643_ (
    .A(pin_tecleado[0]),
    .B(_0125_),
    .Y(_0136_)
  );
  NAND _0644_ (
    .A(pin_tecleado[4]),
    .B(_0128_),
    .Y(_0137_)
  );
  NAND _0645_ (
    .A(_0136_),
    .B(_0137_),
    .Y(_0008_[4])
  );
  NAND _0646_ (
    .A(pin_tecleado[1]),
    .B(_0125_),
    .Y(_0138_)
  );
  NAND _0647_ (
    .A(pin_tecleado[5]),
    .B(_0128_),
    .Y(_0139_)
  );
  NAND _0648_ (
    .A(_0138_),
    .B(_0139_),
    .Y(_0008_[5])
  );
  NAND _0649_ (
    .A(pin_tecleado[2]),
    .B(_0125_),
    .Y(_0140_)
  );
  NAND _0650_ (
    .A(pin_tecleado[6]),
    .B(_0128_),
    .Y(_0141_)
  );
  NAND _0651_ (
    .A(_0140_),
    .B(_0141_),
    .Y(_0008_[6])
  );
  NAND _0652_ (
    .A(pin_tecleado[3]),
    .B(_0125_),
    .Y(_0142_)
  );
  NAND _0653_ (
    .A(pin_tecleado[7]),
    .B(_0128_),
    .Y(_0143_)
  );
  NAND _0654_ (
    .A(_0142_),
    .B(_0143_),
    .Y(_0008_[7])
  );
  NAND _0655_ (
    .A(pin_tecleado[4]),
    .B(_0125_),
    .Y(_0144_)
  );
  NAND _0656_ (
    .A(pin_tecleado[8]),
    .B(_0128_),
    .Y(_0145_)
  );
  NAND _0657_ (
    .A(_0144_),
    .B(_0145_),
    .Y(_0008_[8])
  );
  NAND _0658_ (
    .A(pin_tecleado[5]),
    .B(_0125_),
    .Y(_0146_)
  );
  NAND _0659_ (
    .A(pin_tecleado[9]),
    .B(_0128_),
    .Y(_0147_)
  );
  NAND _0660_ (
    .A(_0146_),
    .B(_0147_),
    .Y(_0008_[9])
  );
  NAND _0661_ (
    .A(pin_tecleado[6]),
    .B(_0125_),
    .Y(_0148_)
  );
  NAND _0662_ (
    .A(pin_tecleado[10]),
    .B(_0128_),
    .Y(_0149_)
  );
  NAND _0663_ (
    .A(_0148_),
    .B(_0149_),
    .Y(_0008_[10])
  );
  NAND _0664_ (
    .A(pin_tecleado[7]),
    .B(_0125_),
    .Y(_0150_)
  );
  NAND _0665_ (
    .A(pin_tecleado[11]),
    .B(_0128_),
    .Y(_0151_)
  );
  NAND _0666_ (
    .A(_0150_),
    .B(_0151_),
    .Y(_0008_[11])
  );
  NAND _0667_ (
    .A(pin_tecleado[8]),
    .B(_0125_),
    .Y(_0152_)
  );
  NAND _0668_ (
    .A(pin_tecleado[12]),
    .B(_0128_),
    .Y(_0153_)
  );
  NAND _0669_ (
    .A(_0152_),
    .B(_0153_),
    .Y(_0008_[12])
  );
  NAND _0670_ (
    .A(pin_tecleado[9]),
    .B(_0125_),
    .Y(_0154_)
  );
  NAND _0671_ (
    .A(pin_tecleado[13]),
    .B(_0128_),
    .Y(_0155_)
  );
  NAND _0672_ (
    .A(_0154_),
    .B(_0155_),
    .Y(_0008_[13])
  );
  NAND _0673_ (
    .A(pin_tecleado[10]),
    .B(_0125_),
    .Y(_0156_)
  );
  NAND _0674_ (
    .A(pin_tecleado[14]),
    .B(_0128_),
    .Y(_0157_)
  );
  NAND _0675_ (
    .A(_0156_),
    .B(_0157_),
    .Y(_0008_[14])
  );
  NAND _0676_ (
    .A(pin_tecleado[11]),
    .B(_0125_),
    .Y(_0158_)
  );
  NAND _0677_ (
    .A(pin_tecleado[15]),
    .B(_0128_),
    .Y(_0159_)
  );
  NAND _0678_ (
    .A(_0158_),
    .B(_0159_),
    .Y(_0008_[15])
  );
  NAND _0679_ (
    .A(state[0]),
    .B(_0021_),
    .Y(_0160_)
  );
  NAND _0680_ (
    .A(_0017_),
    .B(_0160_),
    .Y(_0161_)
  );
  NOT _0681_ (
    .A(_0161_),
    .Y(_0162_)
  );
  NAND _0682_ (
    .A(_0021_),
    .B(_0033_),
    .Y(_0163_)
  );
  NAND _0683_ (
    .A(state[3]),
    .B(intentos[0]),
    .Y(_0164_)
  );
  NAND _0684_ (
    .A(_0160_),
    .B(_0164_),
    .Y(_0165_)
  );
  NAND _0685_ (
    .A(_0017_),
    .B(_0163_),
    .Y(_0166_)
  );
  NOR _0686_ (
    .A(_0165_),
    .B(_0166_),
    .Y(_0007_[0])
  );
  NOR _0687_ (
    .A(_0033_),
    .B(_0107_),
    .Y(_0167_)
  );
  NAND _0688_ (
    .A(_0017_),
    .B(_0167_),
    .Y(_0168_)
  );
  NOR _0689_ (
    .A(_0016_),
    .B(_0165_),
    .Y(_0169_)
  );
  NOR _0690_ (
    .A(_0167_),
    .B(_0169_),
    .Y(_0170_)
  );
  NOR _0691_ (
    .A(rst),
    .B(_0170_),
    .Y(_0007_[1])
  );
  NOR _0692_ (
    .A(_0022_),
    .B(_0023_),
    .Y(_0171_)
  );
  NAND _0693_ (
    .A(MONTO_STB),
    .B(TIPO_TRANS),
    .Y(_0172_)
  );
  NAND _0694_ (
    .A(_0060_),
    .B(MONTO[30]),
    .Y(_0173_)
  );
  NAND _0695_ (
    .A(_0061_),
    .B(MONTO[31]),
    .Y(_0174_)
  );
  NAND _0696_ (
    .A(_0173_),
    .B(_0174_),
    .Y(_0175_)
  );
  NOR _0697_ (
    .A(_0061_),
    .B(MONTO[31]),
    .Y(_0176_)
  );
  NAND _0698_ (
    .A(BALANCE_INICIAL[31]),
    .B(_0093_),
    .Y(_0177_)
  );
  NAND _0699_ (
    .A(BALANCE_INICIAL[30]),
    .B(_0092_),
    .Y(_0178_)
  );
  NAND _0700_ (
    .A(BALANCE_INICIAL[29]),
    .B(_0091_),
    .Y(_0179_)
  );
  NAND _0701_ (
    .A(_0177_),
    .B(_0178_),
    .Y(_0180_)
  );
  NOR _0702_ (
    .A(_0175_),
    .B(_0180_),
    .Y(_0181_)
  );
  NAND _0703_ (
    .A(_0179_),
    .B(_0181_),
    .Y(_0182_)
  );
  NOR _0704_ (
    .A(BALANCE_INICIAL[28]),
    .B(_0090_),
    .Y(_0183_)
  );
  NOR _0705_ (
    .A(BALANCE_INICIAL[29]),
    .B(_0091_),
    .Y(_0184_)
  );
  NOR _0706_ (
    .A(_0183_),
    .B(_0184_),
    .Y(_0185_)
  );
  NOR _0707_ (
    .A(_0059_),
    .B(MONTO[28]),
    .Y(_0186_)
  );
  NOR _0708_ (
    .A(_0182_),
    .B(_0186_),
    .Y(_0187_)
  );
  NAND _0709_ (
    .A(_0185_),
    .B(_0187_),
    .Y(_0188_)
  );
  NAND _0710_ (
    .A(BALANCE_INICIAL[25]),
    .B(_0087_),
    .Y(_0189_)
  );
  NAND _0711_ (
    .A(BALANCE_INICIAL[26]),
    .B(_0088_),
    .Y(_0190_)
  );
  NAND _0712_ (
    .A(_0058_),
    .B(MONTO[27]),
    .Y(_0191_)
  );
  NAND _0713_ (
    .A(BALANCE_INICIAL[27]),
    .B(_0089_),
    .Y(_0192_)
  );
  NOR _0714_ (
    .A(BALANCE_INICIAL[26]),
    .B(_0088_),
    .Y(_0193_)
  );
  NAND _0715_ (
    .A(_0057_),
    .B(MONTO[26]),
    .Y(_0194_)
  );
  NAND _0716_ (
    .A(_0191_),
    .B(_0192_),
    .Y(_0195_)
  );
  NAND _0717_ (
    .A(_0190_),
    .B(_0194_),
    .Y(_0196_)
  );
  NOR _0718_ (
    .A(_0195_),
    .B(_0196_),
    .Y(_0197_)
  );
  NAND _0719_ (
    .A(_0189_),
    .B(_0197_),
    .Y(_0198_)
  );
  NOR _0720_ (
    .A(BALANCE_INICIAL[24]),
    .B(_0086_),
    .Y(_0199_)
  );
  NOR _0721_ (
    .A(BALANCE_INICIAL[25]),
    .B(_0087_),
    .Y(_0200_)
  );
  NOR _0722_ (
    .A(_0199_),
    .B(_0200_),
    .Y(_0201_)
  );
  NOR _0723_ (
    .A(_0056_),
    .B(MONTO[24]),
    .Y(_0202_)
  );
  NOR _0724_ (
    .A(_0198_),
    .B(_0202_),
    .Y(_0203_)
  );
  NAND _0725_ (
    .A(_0201_),
    .B(_0203_),
    .Y(_0204_)
  );
  NOR _0726_ (
    .A(_0188_),
    .B(_0204_),
    .Y(_0205_)
  );
  NOR _0727_ (
    .A(_0053_),
    .B(MONTO[21]),
    .Y(_0206_)
  );
  NAND _0728_ (
    .A(_0055_),
    .B(MONTO[23]),
    .Y(_0207_)
  );
  NOR _0729_ (
    .A(BALANCE_INICIAL[22]),
    .B(_0084_),
    .Y(_0208_)
  );
  NOR _0730_ (
    .A(_0054_),
    .B(MONTO[22]),
    .Y(_0209_)
  );
  NOR _0731_ (
    .A(_0208_),
    .B(_0209_),
    .Y(_0210_)
  );
  NAND _0732_ (
    .A(BALANCE_INICIAL[23]),
    .B(_0085_),
    .Y(_0211_)
  );
  NAND _0733_ (
    .A(_0207_),
    .B(_0211_),
    .Y(_0212_)
  );
  NOR _0734_ (
    .A(_0206_),
    .B(_0212_),
    .Y(_0213_)
  );
  NAND _0735_ (
    .A(_0210_),
    .B(_0213_),
    .Y(_0214_)
  );
  NOR _0736_ (
    .A(BALANCE_INICIAL[20]),
    .B(_0082_),
    .Y(_0215_)
  );
  NOR _0737_ (
    .A(BALANCE_INICIAL[21]),
    .B(_0083_),
    .Y(_0216_)
  );
  NOR _0738_ (
    .A(_0215_),
    .B(_0216_),
    .Y(_0217_)
  );
  NOR _0739_ (
    .A(_0052_),
    .B(MONTO[20]),
    .Y(_0218_)
  );
  NOR _0740_ (
    .A(_0214_),
    .B(_0218_),
    .Y(_0219_)
  );
  NAND _0741_ (
    .A(_0217_),
    .B(_0219_),
    .Y(_0220_)
  );
  NOT _0742_ (
    .A(_0220_),
    .Y(_0221_)
  );
  NOR _0743_ (
    .A(_0049_),
    .B(MONTO[17]),
    .Y(_0222_)
  );
  NOR _0744_ (
    .A(_0050_),
    .B(MONTO[18]),
    .Y(_0223_)
  );
  NOR _0745_ (
    .A(_0051_),
    .B(MONTO[19]),
    .Y(_0224_)
  );
  NOR _0746_ (
    .A(BALANCE_INICIAL[19]),
    .B(_0081_),
    .Y(_0225_)
  );
  NOR _0747_ (
    .A(BALANCE_INICIAL[18]),
    .B(_0080_),
    .Y(_0226_)
  );
  NAND _0748_ (
    .A(_0050_),
    .B(MONTO[18]),
    .Y(_0227_)
  );
  NOR _0749_ (
    .A(_0224_),
    .B(_0225_),
    .Y(_0228_)
  );
  NOR _0750_ (
    .A(_0223_),
    .B(_0226_),
    .Y(_0229_)
  );
  NAND _0751_ (
    .A(_0228_),
    .B(_0229_),
    .Y(_0230_)
  );
  NOR _0752_ (
    .A(_0222_),
    .B(_0230_),
    .Y(_0231_)
  );
  NAND _0753_ (
    .A(_0048_),
    .B(MONTO[16]),
    .Y(_0232_)
  );
  NAND _0754_ (
    .A(_0049_),
    .B(MONTO[17]),
    .Y(_0233_)
  );
  NAND _0755_ (
    .A(_0232_),
    .B(_0233_),
    .Y(_0234_)
  );
  NAND _0756_ (
    .A(BALANCE_INICIAL[16]),
    .B(_0079_),
    .Y(_0235_)
  );
  NAND _0757_ (
    .A(_0231_),
    .B(_0235_),
    .Y(_0236_)
  );
  NOR _0758_ (
    .A(_0220_),
    .B(_0236_),
    .Y(_0237_)
  );
  NAND _0759_ (
    .A(_0205_),
    .B(_0237_),
    .Y(_0238_)
  );
  NOR _0760_ (
    .A(_0234_),
    .B(_0238_),
    .Y(_0239_)
  );
  NOR _0761_ (
    .A(BALANCE_INICIAL[14]),
    .B(_0077_),
    .Y(_0240_)
  );
  NOR _0762_ (
    .A(BALANCE_INICIAL[15]),
    .B(_0078_),
    .Y(_0241_)
  );
  NOR _0763_ (
    .A(_0240_),
    .B(_0241_),
    .Y(_0242_)
  );
  NOR _0764_ (
    .A(_0047_),
    .B(MONTO[15]),
    .Y(_0243_)
  );
  NOR _0765_ (
    .A(_0046_),
    .B(MONTO[14]),
    .Y(_0244_)
  );
  NOR _0766_ (
    .A(_0045_),
    .B(MONTO[13]),
    .Y(_0245_)
  );
  NOR _0767_ (
    .A(_0243_),
    .B(_0244_),
    .Y(_0246_)
  );
  NAND _0768_ (
    .A(_0242_),
    .B(_0246_),
    .Y(_0247_)
  );
  NOR _0769_ (
    .A(_0245_),
    .B(_0247_),
    .Y(_0248_)
  );
  NOT _0770_ (
    .A(_0248_),
    .Y(_0249_)
  );
  NOR _0771_ (
    .A(BALANCE_INICIAL[12]),
    .B(_0075_),
    .Y(_0250_)
  );
  NOR _0772_ (
    .A(BALANCE_INICIAL[13]),
    .B(_0076_),
    .Y(_0251_)
  );
  NOR _0773_ (
    .A(_0250_),
    .B(_0251_),
    .Y(_0252_)
  );
  NAND _0774_ (
    .A(BALANCE_INICIAL[12]),
    .B(_0075_),
    .Y(_0253_)
  );
  NAND _0775_ (
    .A(_0252_),
    .B(_0253_),
    .Y(_0254_)
  );
  NOR _0776_ (
    .A(_0249_),
    .B(_0254_),
    .Y(_0255_)
  );
  NOR _0777_ (
    .A(_0044_),
    .B(MONTO[11]),
    .Y(_0256_)
  );
  NAND _0778_ (
    .A(BALANCE_INICIAL[11]),
    .B(_0074_),
    .Y(_0257_)
  );
  NOR _0779_ (
    .A(BALANCE_INICIAL[11]),
    .B(_0074_),
    .Y(_0258_)
  );
  NAND _0780_ (
    .A(_0044_),
    .B(MONTO[11]),
    .Y(_0259_)
  );
  NOR _0781_ (
    .A(_0256_),
    .B(_0258_),
    .Y(_0260_)
  );
  NOR _0782_ (
    .A(BALANCE_INICIAL[10]),
    .B(_0073_),
    .Y(_0261_)
  );
  NOR _0783_ (
    .A(_0043_),
    .B(MONTO[10]),
    .Y(_0262_)
  );
  NOR _0784_ (
    .A(_0261_),
    .B(_0262_),
    .Y(_0263_)
  );
  NAND _0785_ (
    .A(_0260_),
    .B(_0263_),
    .Y(_0264_)
  );
  NAND _0786_ (
    .A(_0041_),
    .B(MONTO[8]),
    .Y(_0265_)
  );
  NAND _0787_ (
    .A(_0042_),
    .B(MONTO[9]),
    .Y(_0266_)
  );
  NAND _0788_ (
    .A(_0265_),
    .B(_0266_),
    .Y(_0267_)
  );
  NOR _0789_ (
    .A(_0042_),
    .B(MONTO[9]),
    .Y(_0268_)
  );
  NAND _0790_ (
    .A(BALANCE_INICIAL[9]),
    .B(_0072_),
    .Y(_0269_)
  );
  NAND _0791_ (
    .A(BALANCE_INICIAL[8]),
    .B(_0071_),
    .Y(_0270_)
  );
  NOR _0792_ (
    .A(_0267_),
    .B(_0268_),
    .Y(_0271_)
  );
  NAND _0793_ (
    .A(_0270_),
    .B(_0271_),
    .Y(_0272_)
  );
  NOR _0794_ (
    .A(_0264_),
    .B(_0272_),
    .Y(_0273_)
  );
  NOR _0795_ (
    .A(BALANCE_INICIAL[6]),
    .B(_0069_),
    .Y(_0274_)
  );
  NAND _0796_ (
    .A(_0040_),
    .B(MONTO[7]),
    .Y(_0275_)
  );
  NAND _0797_ (
    .A(BALANCE_INICIAL[7]),
    .B(_0070_),
    .Y(_0276_)
  );
  NOR _0798_ (
    .A(_0039_),
    .B(MONTO[6]),
    .Y(_0277_)
  );
  NOR _0799_ (
    .A(_0038_),
    .B(MONTO[5]),
    .Y(_0278_)
  );
  NOR _0800_ (
    .A(_0274_),
    .B(_0277_),
    .Y(_0279_)
  );
  NAND _0801_ (
    .A(_0275_),
    .B(_0276_),
    .Y(_0280_)
  );
  NOR _0802_ (
    .A(_0278_),
    .B(_0280_),
    .Y(_0281_)
  );
  NAND _0803_ (
    .A(_0279_),
    .B(_0281_),
    .Y(_0282_)
  );
  NOR _0804_ (
    .A(BALANCE_INICIAL[4]),
    .B(_0067_),
    .Y(_0283_)
  );
  NOR _0805_ (
    .A(BALANCE_INICIAL[5]),
    .B(_0068_),
    .Y(_0284_)
  );
  NOR _0806_ (
    .A(_0283_),
    .B(_0284_),
    .Y(_0285_)
  );
  NAND _0807_ (
    .A(BALANCE_INICIAL[4]),
    .B(_0067_),
    .Y(_0286_)
  );
  NAND _0808_ (
    .A(_0285_),
    .B(_0286_),
    .Y(_0287_)
  );
  NOR _0809_ (
    .A(_0282_),
    .B(_0287_),
    .Y(_0288_)
  );
  NOR _0810_ (
    .A(_0037_),
    .B(MONTO[3]),
    .Y(_0289_)
  );
  NAND _0811_ (
    .A(BALANCE_INICIAL[3]),
    .B(_0066_),
    .Y(_0290_)
  );
  NOR _0812_ (
    .A(BALANCE_INICIAL[3]),
    .B(_0066_),
    .Y(_0291_)
  );
  NAND _0813_ (
    .A(_0037_),
    .B(MONTO[3]),
    .Y(_0292_)
  );
  NAND _0814_ (
    .A(_0290_),
    .B(_0292_),
    .Y(_0293_)
  );
  NAND _0815_ (
    .A(_0036_),
    .B(MONTO[2]),
    .Y(_0294_)
  );
  NAND _0816_ (
    .A(BALANCE_INICIAL[2]),
    .B(_0065_),
    .Y(_0295_)
  );
  NAND _0817_ (
    .A(_0294_),
    .B(_0295_),
    .Y(_0296_)
  );
  NOR _0818_ (
    .A(_0293_),
    .B(_0296_),
    .Y(_0297_)
  );
  NOR _0819_ (
    .A(BALANCE_INICIAL[1]),
    .B(_0064_),
    .Y(_0298_)
  );
  NAND _0820_ (
    .A(_0035_),
    .B(MONTO[1]),
    .Y(_0299_)
  );
  NAND _0821_ (
    .A(BALANCE_INICIAL[1]),
    .B(_0064_),
    .Y(_0300_)
  );
  NOR _0822_ (
    .A(_0034_),
    .B(MONTO[0]),
    .Y(_0301_)
  );
  NOR _0823_ (
    .A(_0298_),
    .B(_0301_),
    .Y(_0302_)
  );
  NAND _0824_ (
    .A(_0300_),
    .B(_0302_),
    .Y(_0303_)
  );
  NAND _0825_ (
    .A(_0299_),
    .B(_0303_),
    .Y(_0304_)
  );
  NAND _0826_ (
    .A(_0297_),
    .B(_0304_),
    .Y(_0305_)
  );
  NOR _0827_ (
    .A(_0289_),
    .B(_0294_),
    .Y(_0306_)
  );
  NOR _0828_ (
    .A(_0291_),
    .B(_0306_),
    .Y(_0307_)
  );
  NAND _0829_ (
    .A(_0305_),
    .B(_0307_),
    .Y(_0308_)
  );
  NAND _0830_ (
    .A(_0288_),
    .B(_0308_),
    .Y(_0309_)
  );
  NOR _0831_ (
    .A(_0282_),
    .B(_0285_),
    .Y(_0310_)
  );
  NAND _0832_ (
    .A(_0274_),
    .B(_0276_),
    .Y(_0311_)
  );
  NAND _0833_ (
    .A(_0275_),
    .B(_0311_),
    .Y(_0312_)
  );
  NOR _0834_ (
    .A(_0310_),
    .B(_0312_),
    .Y(_0313_)
  );
  NAND _0835_ (
    .A(_0309_),
    .B(_0313_),
    .Y(_0314_)
  );
  NAND _0836_ (
    .A(_0273_),
    .B(_0314_),
    .Y(_0315_)
  );
  NAND _0837_ (
    .A(_0267_),
    .B(_0269_),
    .Y(_0316_)
  );
  NOR _0838_ (
    .A(_0264_),
    .B(_0316_),
    .Y(_0317_)
  );
  NAND _0839_ (
    .A(_0257_),
    .B(_0261_),
    .Y(_0318_)
  );
  NAND _0840_ (
    .A(_0259_),
    .B(_0318_),
    .Y(_0319_)
  );
  NOR _0841_ (
    .A(_0317_),
    .B(_0319_),
    .Y(_0320_)
  );
  NAND _0842_ (
    .A(_0315_),
    .B(_0320_),
    .Y(_0321_)
  );
  NAND _0843_ (
    .A(_0255_),
    .B(_0321_),
    .Y(_0322_)
  );
  NOR _0844_ (
    .A(_0249_),
    .B(_0252_),
    .Y(_0323_)
  );
  NOR _0845_ (
    .A(_0242_),
    .B(_0243_),
    .Y(_0324_)
  );
  NOR _0846_ (
    .A(_0323_),
    .B(_0324_),
    .Y(_0325_)
  );
  NAND _0847_ (
    .A(_0322_),
    .B(_0325_),
    .Y(_0326_)
  );
  NAND _0848_ (
    .A(_0239_),
    .B(_0326_),
    .Y(_0327_)
  );
  NAND _0849_ (
    .A(_0231_),
    .B(_0234_),
    .Y(_0328_)
  );
  NOR _0850_ (
    .A(_0224_),
    .B(_0227_),
    .Y(_0329_)
  );
  NOR _0851_ (
    .A(_0225_),
    .B(_0329_),
    .Y(_0330_)
  );
  NAND _0852_ (
    .A(_0328_),
    .B(_0330_),
    .Y(_0331_)
  );
  NAND _0853_ (
    .A(_0221_),
    .B(_0331_),
    .Y(_0332_)
  );
  NOR _0854_ (
    .A(_0214_),
    .B(_0217_),
    .Y(_0333_)
  );
  NAND _0855_ (
    .A(_0208_),
    .B(_0211_),
    .Y(_0334_)
  );
  NAND _0856_ (
    .A(_0207_),
    .B(_0334_),
    .Y(_0335_)
  );
  NOR _0857_ (
    .A(_0333_),
    .B(_0335_),
    .Y(_0336_)
  );
  NAND _0858_ (
    .A(_0332_),
    .B(_0336_),
    .Y(_0337_)
  );
  NAND _0859_ (
    .A(_0205_),
    .B(_0337_),
    .Y(_0338_)
  );
  NOR _0860_ (
    .A(_0198_),
    .B(_0201_),
    .Y(_0339_)
  );
  NAND _0861_ (
    .A(_0192_),
    .B(_0193_),
    .Y(_0340_)
  );
  NAND _0862_ (
    .A(_0191_),
    .B(_0340_),
    .Y(_0341_)
  );
  NOR _0863_ (
    .A(_0339_),
    .B(_0341_),
    .Y(_0342_)
  );
  NOR _0864_ (
    .A(_0188_),
    .B(_0342_),
    .Y(_0343_)
  );
  NOR _0865_ (
    .A(_0182_),
    .B(_0185_),
    .Y(_0344_)
  );
  NOR _0866_ (
    .A(_0173_),
    .B(_0176_),
    .Y(_0345_)
  );
  NOR _0867_ (
    .A(_0344_),
    .B(_0345_),
    .Y(_0346_)
  );
  NAND _0868_ (
    .A(_0174_),
    .B(_0346_),
    .Y(_0347_)
  );
  NOR _0869_ (
    .A(_0343_),
    .B(_0347_),
    .Y(_0348_)
  );
  NAND _0870_ (
    .A(_0338_),
    .B(_0348_),
    .Y(_0349_)
  );
  NOT _0871_ (
    .A(_0349_),
    .Y(_0350_)
  );
  NAND _0872_ (
    .A(_0327_),
    .B(_0350_),
    .Y(_0351_)
  );
  NAND _0873_ (
    .A(_0034_),
    .B(MONTO[0]),
    .Y(_0352_)
  );
  NAND _0874_ (
    .A(_0297_),
    .B(_0352_),
    .Y(_0353_)
  );
  NOR _0875_ (
    .A(_0303_),
    .B(_0353_),
    .Y(_0354_)
  );
  NAND _0876_ (
    .A(_0273_),
    .B(_0354_),
    .Y(_0355_)
  );
  NAND _0877_ (
    .A(_0255_),
    .B(_0288_),
    .Y(_0356_)
  );
  NOR _0878_ (
    .A(_0355_),
    .B(_0356_),
    .Y(_0357_)
  );
  NAND _0879_ (
    .A(_0239_),
    .B(_0357_),
    .Y(_0358_)
  );
  NOR _0880_ (
    .A(BALANCE_INICIAL[37]),
    .B(BALANCE_INICIAL[38]),
    .Y(_0359_)
  );
  NOT _0881_ (
    .A(_0359_),
    .Y(_0360_)
  );
  NOR _0882_ (
    .A(BALANCE_INICIAL[41]),
    .B(BALANCE_INICIAL[42]),
    .Y(_0361_)
  );
  NOR _0883_ (
    .A(BALANCE_INICIAL[52]),
    .B(BALANCE_INICIAL[55]),
    .Y(_0362_)
  );
  NOR _0884_ (
    .A(BALANCE_INICIAL[60]),
    .B(BALANCE_INICIAL[63]),
    .Y(_0363_)
  );
  NOR _0885_ (
    .A(BALANCE_INICIAL[50]),
    .B(BALANCE_INICIAL[61]),
    .Y(_0364_)
  );
  NOR _0886_ (
    .A(BALANCE_INICIAL[56]),
    .B(BALANCE_INICIAL[62]),
    .Y(_0365_)
  );
  NAND _0887_ (
    .A(_0364_),
    .B(_0365_),
    .Y(_0366_)
  );
  NOR _0888_ (
    .A(BALANCE_INICIAL[33]),
    .B(BALANCE_INICIAL[39]),
    .Y(_0367_)
  );
  NOR _0889_ (
    .A(BALANCE_INICIAL[35]),
    .B(BALANCE_INICIAL[44]),
    .Y(_0368_)
  );
  NAND _0890_ (
    .A(_0367_),
    .B(_0368_),
    .Y(_0369_)
  );
  NOR _0891_ (
    .A(_0366_),
    .B(_0369_),
    .Y(_0370_)
  );
  NAND _0892_ (
    .A(_0063_),
    .B(_0362_),
    .Y(_0371_)
  );
  NOR _0893_ (
    .A(BALANCE_INICIAL[34]),
    .B(BALANCE_INICIAL[36]),
    .Y(_0372_)
  );
  NOR _0894_ (
    .A(BALANCE_INICIAL[32]),
    .B(BALANCE_INICIAL[47]),
    .Y(_0373_)
  );
  NAND _0895_ (
    .A(_0372_),
    .B(_0373_),
    .Y(_0374_)
  );
  NOR _0896_ (
    .A(_0371_),
    .B(_0374_),
    .Y(_0375_)
  );
  NAND _0897_ (
    .A(_0370_),
    .B(_0375_),
    .Y(_0376_)
  );
  NOR _0898_ (
    .A(BALANCE_INICIAL[40]),
    .B(BALANCE_INICIAL[46]),
    .Y(_0377_)
  );
  NOR _0899_ (
    .A(BALANCE_INICIAL[51]),
    .B(BALANCE_INICIAL[53]),
    .Y(_0378_)
  );
  NAND _0900_ (
    .A(_0377_),
    .B(_0378_),
    .Y(_0379_)
  );
  NAND _0901_ (
    .A(_0062_),
    .B(_0363_),
    .Y(_0380_)
  );
  NOR _0902_ (
    .A(BALANCE_INICIAL[49]),
    .B(BALANCE_INICIAL[58]),
    .Y(_0381_)
  );
  NAND _0903_ (
    .A(_0361_),
    .B(_0381_),
    .Y(_0382_)
  );
  NOR _0904_ (
    .A(_0380_),
    .B(_0382_),
    .Y(_0383_)
  );
  NOR _0905_ (
    .A(BALANCE_INICIAL[43]),
    .B(BALANCE_INICIAL[45]),
    .Y(_0384_)
  );
  NOR _0906_ (
    .A(BALANCE_INICIAL[48]),
    .B(BALANCE_INICIAL[54]),
    .Y(_0385_)
  );
  NAND _0907_ (
    .A(_0384_),
    .B(_0385_),
    .Y(_0386_)
  );
  NOR _0908_ (
    .A(_0360_),
    .B(_0386_),
    .Y(_0387_)
  );
  NAND _0909_ (
    .A(_0383_),
    .B(_0387_),
    .Y(_0388_)
  );
  NOR _0910_ (
    .A(_0379_),
    .B(_0388_),
    .Y(_0389_)
  );
  NAND _0911_ (
    .A(_0358_),
    .B(_0389_),
    .Y(_0390_)
  );
  NOR _0912_ (
    .A(_0376_),
    .B(_0390_),
    .Y(_0391_)
  );
  NAND _0913_ (
    .A(_0351_),
    .B(_0391_),
    .Y(_0392_)
  );
  NOR _0914_ (
    .A(_0172_),
    .B(_0392_),
    .Y(_0393_)
  );
  NOR _0915_ (
    .A(FONDOS_INSUFICIENTES),
    .B(_0393_),
    .Y(_0394_)
  );
  NAND _0916_ (
    .A(_0020_),
    .B(FONDOS_INSUFICIENTES),
    .Y(_0395_)
  );
  NAND _0917_ (
    .A(_0018_),
    .B(_0395_),
    .Y(_0396_)
  );
  NAND _0918_ (
    .A(_0017_),
    .B(_0396_),
    .Y(_0397_)
  );
  NOR _0919_ (
    .A(_0394_),
    .B(_0397_),
    .Y(_0004_)
  );
  NAND _0920_ (
    .A(intentos[1]),
    .B(state[3]),
    .Y(_0398_)
  );
  NOT _0921_ (
    .A(_0398_),
    .Y(_0399_)
  );
  NOR _0922_ (
    .A(BLOQUEO),
    .B(_0399_),
    .Y(_0400_)
  );
  NOR _0923_ (
    .A(_0161_),
    .B(_0400_),
    .Y(_0002_)
  );
  NAND _0924_ (
    .A(ADVERTENCIA),
    .B(_0162_),
    .Y(_0401_)
  );
  NAND _0925_ (
    .A(_0168_),
    .B(_0401_),
    .Y(_0000_)
  );
  NOR _0926_ (
    .A(state[3]),
    .B(PIN_INCORRECTO),
    .Y(_0402_)
  );
  NOR _0927_ (
    .A(_0161_),
    .B(_0402_),
    .Y(_0005_)
  );
  NAND _0928_ (
    .A(_0171_),
    .B(_0392_),
    .Y(_0403_)
  );
  NAND _0929_ (
    .A(_0031_),
    .B(_0403_),
    .Y(_0404_)
  );
  NOR _0930_ (
    .A(state[0]),
    .B(_0031_),
    .Y(_0405_)
  );
  NOR _0931_ (
    .A(state[5]),
    .B(_0405_),
    .Y(_0406_)
  );
  NAND _0932_ (
    .A(_0017_),
    .B(_0404_),
    .Y(_0407_)
  );
  NOR _0933_ (
    .A(_0406_),
    .B(_0407_),
    .Y(_0003_)
  );
  NOR _0934_ (
    .A(_0023_),
    .B(_0392_),
    .Y(_0408_)
  );
  NOR _0935_ (
    .A(_0022_),
    .B(_0408_),
    .Y(_0409_)
  );
  NOR _0936_ (
    .A(BALANCE_ACTUALIZADO),
    .B(_0409_),
    .Y(_0410_)
  );
  NOR _0937_ (
    .A(state[0]),
    .B(_0032_),
    .Y(_0411_)
  );
  NOR _0938_ (
    .A(state[5]),
    .B(_0411_),
    .Y(_0412_)
  );
  NOR _0939_ (
    .A(rst),
    .B(_0412_),
    .Y(_0413_)
  );
  NOT _0940_ (
    .A(_0413_),
    .Y(_0414_)
  );
  NOR _0941_ (
    .A(_0410_),
    .B(_0414_),
    .Y(_0001_)
  );
  NOR _0942_ (
    .A(_0030_),
    .B(PIN[15]),
    .Y(_0415_)
  );
  NOR _0943_ (
    .A(pin_tecleado[15]),
    .B(_0099_),
    .Y(_0416_)
  );
  NOR _0944_ (
    .A(_0415_),
    .B(_0416_),
    .Y(_0417_)
  );
  NOR _0945_ (
    .A(pin_tecleado[9]),
    .B(_0097_),
    .Y(_0418_)
  );
  NOR _0946_ (
    .A(_0026_),
    .B(PIN[5]),
    .Y(_0419_)
  );
  NAND _0947_ (
    .A(pin_tecleado[5]),
    .B(_0095_),
    .Y(_0420_)
  );
  NOR _0948_ (
    .A(_0029_),
    .B(PIN[12]),
    .Y(_0421_)
  );
  NOR _0949_ (
    .A(pin_tecleado[12]),
    .B(_0098_),
    .Y(_0422_)
  );
  NOR _0950_ (
    .A(_0421_),
    .B(_0422_),
    .Y(_0423_)
  );
  NAND _0951_ (
    .A(pin_tecleado[11]),
    .B(PIN[11]),
    .Y(_0424_)
  );
  NOT _0952_ (
    .A(_0424_),
    .Y(_0425_)
  );
  NOR _0953_ (
    .A(pin_tecleado[11]),
    .B(PIN[11]),
    .Y(_0426_)
  );
  NOT _0954_ (
    .A(_0426_),
    .Y(_0427_)
  );
  NAND _0955_ (
    .A(_0424_),
    .B(_0427_),
    .Y(_0428_)
  );
  NOR _0956_ (
    .A(_0425_),
    .B(_0426_),
    .Y(_0429_)
  );
  NOR _0957_ (
    .A(_0025_),
    .B(PIN[2]),
    .Y(_0430_)
  );
  NOR _0958_ (
    .A(pin_tecleado[2]),
    .B(_0094_),
    .Y(_0431_)
  );
  NOR _0959_ (
    .A(pin_tecleado[6]),
    .B(PIN[6]),
    .Y(_0432_)
  );
  NOT _0960_ (
    .A(_0432_),
    .Y(_0433_)
  );
  NAND _0961_ (
    .A(pin_tecleado[6]),
    .B(PIN[6]),
    .Y(_0434_)
  );
  NAND _0962_ (
    .A(_0433_),
    .B(_0434_),
    .Y(_0435_)
  );
  NOR _0963_ (
    .A(pin_tecleado[0]),
    .B(PIN[0]),
    .Y(_0436_)
  );
  NOT _0964_ (
    .A(_0436_),
    .Y(_0437_)
  );
  NAND _0965_ (
    .A(pin_tecleado[0]),
    .B(PIN[0]),
    .Y(_0438_)
  );
  NAND _0966_ (
    .A(_0437_),
    .B(_0438_),
    .Y(_0439_)
  );
  NOR _0967_ (
    .A(pin_tecleado[13]),
    .B(PIN[13]),
    .Y(_0440_)
  );
  NOT _0968_ (
    .A(_0440_),
    .Y(_0441_)
  );
  NAND _0969_ (
    .A(pin_tecleado[13]),
    .B(PIN[13]),
    .Y(_0442_)
  );
  NAND _0970_ (
    .A(_0441_),
    .B(_0442_),
    .Y(_0443_)
  );
  NOR _0971_ (
    .A(pin_tecleado[1]),
    .B(PIN[1]),
    .Y(_0444_)
  );
  NOT _0972_ (
    .A(_0444_),
    .Y(_0445_)
  );
  NAND _0973_ (
    .A(pin_tecleado[1]),
    .B(PIN[1]),
    .Y(_0446_)
  );
  NOT _0974_ (
    .A(_0446_),
    .Y(_0447_)
  );
  NOR _0975_ (
    .A(_0444_),
    .B(_0447_),
    .Y(_0448_)
  );
  NAND _0976_ (
    .A(_0445_),
    .B(_0446_),
    .Y(_0449_)
  );
  NOR _0977_ (
    .A(pin_tecleado[7]),
    .B(_0096_),
    .Y(_0450_)
  );
  NOR _0978_ (
    .A(pin_tecleado[5]),
    .B(_0095_),
    .Y(_0451_)
  );
  NAND _0979_ (
    .A(_0026_),
    .B(PIN[5]),
    .Y(_0452_)
  );
  NOR _0980_ (
    .A(_0027_),
    .B(PIN[7]),
    .Y(_0453_)
  );
  NOR _0981_ (
    .A(_0028_),
    .B(PIN[9]),
    .Y(_0454_)
  );
  NAND _0982_ (
    .A(pin_tecleado[8]),
    .B(PIN[8]),
    .Y(_0455_)
  );
  NOR _0983_ (
    .A(pin_tecleado[8]),
    .B(PIN[8]),
    .Y(_0456_)
  );
  NOT _0984_ (
    .A(_0456_),
    .Y(_0457_)
  );
  NAND _0985_ (
    .A(_0455_),
    .B(_0457_),
    .Y(_0458_)
  );
  NOR _0986_ (
    .A(_0418_),
    .B(_0430_),
    .Y(_0459_)
  );
  NAND _0987_ (
    .A(_0458_),
    .B(_0459_),
    .Y(_0460_)
  );
  NOR _0988_ (
    .A(_0431_),
    .B(_0451_),
    .Y(_0461_)
  );
  NAND _0989_ (
    .A(_0428_),
    .B(_0461_),
    .Y(_0462_)
  );
  NOR _0990_ (
    .A(_0460_),
    .B(_0462_),
    .Y(_0463_)
  );
  NAND _0991_ (
    .A(pin_tecleado[4]),
    .B(PIN[4]),
    .Y(_0464_)
  );
  NOR _0992_ (
    .A(pin_tecleado[4]),
    .B(PIN[4]),
    .Y(_0465_)
  );
  NOT _0993_ (
    .A(_0465_),
    .Y(_0466_)
  );
  NAND _0994_ (
    .A(_0464_),
    .B(_0466_),
    .Y(_0467_)
  );
  NOR _0995_ (
    .A(pin_tecleado[14]),
    .B(PIN[14]),
    .Y(_0468_)
  );
  NOT _0996_ (
    .A(_0468_),
    .Y(_0469_)
  );
  NAND _0997_ (
    .A(pin_tecleado[14]),
    .B(PIN[14]),
    .Y(_0470_)
  );
  NOT _0998_ (
    .A(_0470_),
    .Y(_0471_)
  );
  NOR _0999_ (
    .A(_0468_),
    .B(_0471_),
    .Y(_0472_)
  );
  NAND _1000_ (
    .A(_0469_),
    .B(_0470_),
    .Y(_0473_)
  );
  NAND _1001_ (
    .A(_0467_),
    .B(_0473_),
    .Y(_0474_)
  );
  NOR _1002_ (
    .A(pin_tecleado[10]),
    .B(PIN[10]),
    .Y(_0475_)
  );
  NOT _1003_ (
    .A(_0475_),
    .Y(_0476_)
  );
  NAND _1004_ (
    .A(pin_tecleado[10]),
    .B(PIN[10]),
    .Y(_0477_)
  );
  NAND _1005_ (
    .A(_0476_),
    .B(_0477_),
    .Y(_0478_)
  );
  NAND _1006_ (
    .A(_0449_),
    .B(_0478_),
    .Y(_0479_)
  );
  NOR _1007_ (
    .A(_0474_),
    .B(_0479_),
    .Y(_0480_)
  );
  NAND _1008_ (
    .A(_0463_),
    .B(_0480_),
    .Y(_0481_)
  );
  NAND _1009_ (
    .A(pin_tecleado[3]),
    .B(PIN[3]),
    .Y(_0482_)
  );
  NOR _1010_ (
    .A(pin_tecleado[3]),
    .B(PIN[3]),
    .Y(_0483_)
  );
  NOT _1011_ (
    .A(_0483_),
    .Y(_0484_)
  );
  NAND _1012_ (
    .A(_0482_),
    .B(_0484_),
    .Y(_0485_)
  );
  NAND _1013_ (
    .A(_0435_),
    .B(_0485_),
    .Y(_0486_)
  );
  NOR _1014_ (
    .A(_0450_),
    .B(_0453_),
    .Y(_0487_)
  );
  NAND _1015_ (
    .A(_0423_),
    .B(_0487_),
    .Y(_0488_)
  );
  NOR _1016_ (
    .A(_0486_),
    .B(_0488_),
    .Y(_0489_)
  );
  NAND _1017_ (
    .A(_0439_),
    .B(_0443_),
    .Y(_0490_)
  );
  NOR _1018_ (
    .A(_0419_),
    .B(_0454_),
    .Y(_0491_)
  );
  NAND _1019_ (
    .A(_0417_),
    .B(_0491_),
    .Y(_0492_)
  );
  NOR _1020_ (
    .A(_0490_),
    .B(_0492_),
    .Y(_0493_)
  );
  NAND _1021_ (
    .A(_0489_),
    .B(_0493_),
    .Y(_0494_)
  );
  NAND _1022_ (
    .A(_0423_),
    .B(_0467_),
    .Y(_0495_)
  );
  NOR _1023_ (
    .A(_0486_),
    .B(_0495_),
    .Y(_0496_)
  );
  NAND _1024_ (
    .A(_0443_),
    .B(_0487_),
    .Y(_0497_)
  );
  NOR _1025_ (
    .A(_0472_),
    .B(_0497_),
    .Y(_0498_)
  );
  NAND _1026_ (
    .A(_0496_),
    .B(_0498_),
    .Y(_0499_)
  );
  NAND _1027_ (
    .A(_0439_),
    .B(_0478_),
    .Y(_0500_)
  );
  NOR _1028_ (
    .A(_0499_),
    .B(_0500_),
    .Y(_0501_)
  );
  NOR _1029_ (
    .A(_0430_),
    .B(_0431_),
    .Y(_0502_)
  );
  NAND _1030_ (
    .A(_0452_),
    .B(_0502_),
    .Y(_0503_)
  );
  NOR _1031_ (
    .A(_0418_),
    .B(_0454_),
    .Y(_0504_)
  );
  NAND _1032_ (
    .A(_0458_),
    .B(_0504_),
    .Y(_0505_)
  );
  NOR _1033_ (
    .A(_0503_),
    .B(_0505_),
    .Y(_0506_)
  );
  NAND _1034_ (
    .A(_0417_),
    .B(_0420_),
    .Y(_0507_)
  );
  NOR _1035_ (
    .A(_0448_),
    .B(_0507_),
    .Y(_0508_)
  );
  NAND _1036_ (
    .A(_0506_),
    .B(_0508_),
    .Y(_0509_)
  );
  NOR _1037_ (
    .A(_0429_),
    .B(_0509_),
    .Y(_0510_)
  );
  NOR _1038_ (
    .A(_0481_),
    .B(_0494_),
    .Y(_0511_)
  );
  NAND _1039_ (
    .A(_0501_),
    .B(_0510_),
    .Y(_0512_)
  );
  NAND _1040_ (
    .A(_0017_),
    .B(state[6]),
    .Y(_0513_)
  );
  NOR _1041_ (
    .A(_0512_),
    .B(_0513_),
    .Y(_0009_)
  );
  NOR _1042_ (
    .A(_0101_),
    .B(_0126_),
    .Y(_0013_)
  );
  NOR _1043_ (
    .A(rst),
    .B(_0100_),
    .Y(_0012_)
  );
  NAND _1044_ (
    .A(state[0]),
    .B(TARJETA_RECIBIDA),
    .Y(_0514_)
  );
  NOR _1045_ (
    .A(rst),
    .B(_0514_),
    .Y(_0011_)
  );
  NOR _1046_ (
    .A(_0511_),
    .B(_0513_),
    .Y(_0010_)
  );
  DFF _1047_ (
    .C(clk),
    .D(_0014_),
    .Q(state[0])
  );
  DFF _1048_ (
    .C(clk),
    .D(_0009_),
    .Q(state[1])
  );
  DFF _1049_ (
    .C(clk),
    .D(_0015_),
    .Q(state[2])
  );
  DFF _1050_ (
    .C(clk),
    .D(_0010_),
    .Q(state[3])
  );
  DFF _1051_ (
    .C(clk),
    .D(_0011_),
    .Q(state[4])
  );
  DFF _1052_ (
    .C(clk),
    .D(_0012_),
    .Q(state[5])
  );
  DFF _1053_ (
    .C(clk),
    .D(_0013_),
    .Q(state[6])
  );
  (* src = "cajeroAutomatico.v:107" *)
  DFF _1054_ (
    .C(clk),
    .D(_0001_),
    .Q(BALANCE_ACTUALIZADO)
  );
  (* src = "cajeroAutomatico.v:107" *)
  DFF _1055_ (
    .C(clk),
    .D(_0003_),
    .Q(ENTREGAR_DINERO)
  );
  (* src = "cajeroAutomatico.v:107" *)
  DFF _1056_ (
    .C(clk),
    .D(_0005_),
    .Q(PIN_INCORRECTO)
  );
  (* src = "cajeroAutomatico.v:107" *)
  DFF _1057_ (
    .C(clk),
    .D(_0000_),
    .Q(ADVERTENCIA)
  );
  (* src = "cajeroAutomatico.v:107" *)
  DFF _1058_ (
    .C(clk),
    .D(_0002_),
    .Q(BLOQUEO)
  );
  (* src = "cajeroAutomatico.v:107" *)
  DFF _1059_ (
    .C(clk),
    .D(_0004_),
    .Q(FONDOS_INSUFICIENTES)
  );
  (* src = "cajeroAutomatico.v:107" *)
  DFF _1060_ (
    .C(clk),
    .D(_0007_[0]),
    .Q(intentos[0])
  );
  (* src = "cajeroAutomatico.v:107" *)
  DFF _1061_ (
    .C(clk),
    .D(_0007_[1]),
    .Q(intentos[1])
  );
  (* src = "cajeroAutomatico.v:107" *)
  DFF _1062_ (
    .C(clk),
    .D(_0008_[0]),
    .Q(pin_tecleado[0])
  );
  (* src = "cajeroAutomatico.v:107" *)
  DFF _1063_ (
    .C(clk),
    .D(_0008_[1]),
    .Q(pin_tecleado[1])
  );
  (* src = "cajeroAutomatico.v:107" *)
  DFF _1064_ (
    .C(clk),
    .D(_0008_[2]),
    .Q(pin_tecleado[2])
  );
  (* src = "cajeroAutomatico.v:107" *)
  DFF _1065_ (
    .C(clk),
    .D(_0008_[3]),
    .Q(pin_tecleado[3])
  );
  (* src = "cajeroAutomatico.v:107" *)
  DFF _1066_ (
    .C(clk),
    .D(_0008_[4]),
    .Q(pin_tecleado[4])
  );
  (* src = "cajeroAutomatico.v:107" *)
  DFF _1067_ (
    .C(clk),
    .D(_0008_[5]),
    .Q(pin_tecleado[5])
  );
  (* src = "cajeroAutomatico.v:107" *)
  DFF _1068_ (
    .C(clk),
    .D(_0008_[6]),
    .Q(pin_tecleado[6])
  );
  (* src = "cajeroAutomatico.v:107" *)
  DFF _1069_ (
    .C(clk),
    .D(_0008_[7]),
    .Q(pin_tecleado[7])
  );
  (* src = "cajeroAutomatico.v:107" *)
  DFF _1070_ (
    .C(clk),
    .D(_0008_[8]),
    .Q(pin_tecleado[8])
  );
  (* src = "cajeroAutomatico.v:107" *)
  DFF _1071_ (
    .C(clk),
    .D(_0008_[9]),
    .Q(pin_tecleado[9])
  );
  (* src = "cajeroAutomatico.v:107" *)
  DFF _1072_ (
    .C(clk),
    .D(_0008_[10]),
    .Q(pin_tecleado[10])
  );
  (* src = "cajeroAutomatico.v:107" *)
  DFF _1073_ (
    .C(clk),
    .D(_0008_[11]),
    .Q(pin_tecleado[11])
  );
  (* src = "cajeroAutomatico.v:107" *)
  DFF _1074_ (
    .C(clk),
    .D(_0008_[12]),
    .Q(pin_tecleado[12])
  );
  (* src = "cajeroAutomatico.v:107" *)
  DFF _1075_ (
    .C(clk),
    .D(_0008_[13]),
    .Q(pin_tecleado[13])
  );
  (* src = "cajeroAutomatico.v:107" *)
  DFF _1076_ (
    .C(clk),
    .D(_0008_[14]),
    .Q(pin_tecleado[14])
  );
  (* src = "cajeroAutomatico.v:107" *)
  DFF _1077_ (
    .C(clk),
    .D(_0008_[15]),
    .Q(pin_tecleado[15])
  );
  (* src = "cajeroAutomatico.v:107" *)
  DFF _1078_ (
    .C(clk),
    .D(_0006_[0]),
    .Q(digitos_ingresados[0])
  );
  (* src = "cajeroAutomatico.v:107" *)
  DFF _1079_ (
    .C(clk),
    .D(_0006_[1]),
    .Q(digitos_ingresados[1])
  );
endmodule
