/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "cajeroAutomatico.v:1" *)
module cajero_automatico(clk, rst, TARJETA_RECIBIDA, TIPO_TRANS, MONTO_STB, DIGITO_STB, DIGITO, PIN, MONTO, BALANCE_INICIAL, BALANCE_ACTUALIZADO, ENTREGAR_DINERO, PIN_INCORRECTO, ADVERTENCIA, BLOQUEO, FONDOS_INSUFICIENTES);
  (* src = "cajeroAutomatico.v:98" *)
  wire _0000_;
  (* src = "cajeroAutomatico.v:98" *)
  wire _0001_;
  (* src = "cajeroAutomatico.v:98" *)
  wire _0002_;
  (* src = "cajeroAutomatico.v:98" *)
  wire _0003_;
  (* src = "cajeroAutomatico.v:98" *)
  wire _0004_;
  (* src = "cajeroAutomatico.v:98" *)
  wire _0005_;
  (* src = "cajeroAutomatico.v:98" *)
  wire [1:0] _0006_;
  (* src = "cajeroAutomatico.v:98" *)
  wire [1:0] _0007_;
  (* src = "cajeroAutomatico.v:98" *)
  wire [15:0] _0008_;
  wire _0009_;
  wire _0010_;
  wire _0011_;
  wire _0012_;
  wire _0013_;
  wire _0014_;
  wire _0015_;
  wire _0016_;
  wire _0017_;
  wire _0018_;
  wire _0019_;
  wire _0020_;
  wire _0021_;
  wire _0022_;
  wire _0023_;
  wire _0024_;
  wire _0025_;
  wire _0026_;
  wire _0027_;
  wire _0028_;
  wire _0029_;
  wire _0030_;
  wire _0031_;
  wire _0032_;
  wire _0033_;
  wire _0034_;
  wire _0035_;
  wire _0036_;
  wire _0037_;
  wire _0038_;
  wire _0039_;
  wire _0040_;
  wire _0041_;
  wire _0042_;
  wire _0043_;
  wire _0044_;
  wire _0045_;
  wire _0046_;
  wire _0047_;
  wire _0048_;
  wire _0049_;
  wire _0050_;
  wire _0051_;
  wire _0052_;
  wire _0053_;
  wire _0054_;
  wire _0055_;
  wire _0056_;
  wire _0057_;
  wire _0058_;
  wire _0059_;
  wire _0060_;
  wire _0061_;
  wire _0062_;
  wire _0063_;
  wire _0064_;
  wire _0065_;
  wire _0066_;
  wire _0067_;
  wire _0068_;
  wire _0069_;
  wire _0070_;
  wire _0071_;
  wire _0072_;
  wire _0073_;
  wire _0074_;
  wire _0075_;
  wire _0076_;
  wire _0077_;
  wire _0078_;
  wire _0079_;
  wire _0080_;
  wire _0081_;
  wire _0082_;
  wire _0083_;
  wire _0084_;
  wire _0085_;
  wire _0086_;
  wire _0087_;
  wire _0088_;
  wire _0089_;
  wire _0090_;
  wire _0091_;
  wire _0092_;
  wire _0093_;
  wire _0094_;
  wire _0095_;
  wire _0096_;
  wire _0097_;
  wire _0098_;
  wire _0099_;
  wire _0100_;
  wire _0101_;
  wire _0102_;
  wire _0103_;
  wire _0104_;
  wire _0105_;
  wire _0106_;
  wire _0107_;
  wire _0108_;
  wire _0109_;
  wire _0110_;
  wire _0111_;
  wire _0112_;
  wire _0113_;
  wire _0114_;
  wire _0115_;
  wire _0116_;
  wire _0117_;
  wire _0118_;
  wire _0119_;
  wire _0120_;
  wire _0121_;
  wire _0122_;
  wire _0123_;
  wire _0124_;
  wire _0125_;
  wire _0126_;
  wire _0127_;
  wire _0128_;
  wire _0129_;
  wire _0130_;
  wire _0131_;
  wire _0132_;
  wire _0133_;
  wire _0134_;
  wire _0135_;
  wire _0136_;
  wire _0137_;
  wire _0138_;
  wire _0139_;
  wire _0140_;
  wire _0141_;
  wire _0142_;
  wire _0143_;
  wire _0144_;
  wire _0145_;
  wire _0146_;
  wire _0147_;
  wire _0148_;
  wire _0149_;
  wire _0150_;
  wire _0151_;
  wire _0152_;
  wire _0153_;
  wire _0154_;
  wire _0155_;
  wire _0156_;
  wire _0157_;
  wire _0158_;
  wire _0159_;
  wire _0160_;
  wire _0161_;
  wire _0162_;
  wire _0163_;
  wire _0164_;
  wire _0165_;
  wire _0166_;
  wire _0167_;
  wire _0168_;
  wire _0169_;
  wire _0170_;
  wire _0171_;
  wire _0172_;
  wire _0173_;
  wire _0174_;
  wire _0175_;
  wire _0176_;
  wire _0177_;
  wire _0178_;
  wire _0179_;
  wire _0180_;
  wire _0181_;
  wire _0182_;
  wire _0183_;
  wire _0184_;
  wire _0185_;
  wire _0186_;
  wire _0187_;
  wire _0188_;
  wire _0189_;
  wire _0190_;
  wire _0191_;
  wire _0192_;
  wire _0193_;
  wire _0194_;
  wire _0195_;
  wire _0196_;
  wire _0197_;
  wire _0198_;
  wire _0199_;
  wire _0200_;
  wire _0201_;
  wire _0202_;
  wire _0203_;
  wire _0204_;
  wire _0205_;
  wire _0206_;
  wire _0207_;
  wire _0208_;
  wire _0209_;
  wire _0210_;
  wire _0211_;
  wire _0212_;
  wire _0213_;
  wire _0214_;
  wire _0215_;
  wire _0216_;
  wire _0217_;
  wire _0218_;
  wire _0219_;
  wire _0220_;
  wire _0221_;
  wire _0222_;
  wire _0223_;
  wire _0224_;
  wire _0225_;
  wire _0226_;
  wire _0227_;
  wire _0228_;
  wire _0229_;
  wire _0230_;
  wire _0231_;
  wire _0232_;
  wire _0233_;
  wire _0234_;
  wire _0235_;
  wire _0236_;
  wire _0237_;
  wire _0238_;
  wire _0239_;
  wire _0240_;
  wire _0241_;
  wire _0242_;
  wire _0243_;
  wire _0244_;
  wire _0245_;
  wire _0246_;
  wire _0247_;
  wire _0248_;
  wire _0249_;
  wire _0250_;
  wire _0251_;
  wire _0252_;
  wire _0253_;
  wire _0254_;
  wire _0255_;
  wire _0256_;
  wire _0257_;
  wire _0258_;
  wire _0259_;
  wire _0260_;
  wire _0261_;
  wire _0262_;
  wire _0263_;
  wire _0264_;
  wire _0265_;
  wire _0266_;
  wire _0267_;
  wire _0268_;
  wire _0269_;
  wire _0270_;
  wire _0271_;
  wire _0272_;
  wire _0273_;
  wire _0274_;
  wire _0275_;
  wire _0276_;
  wire _0277_;
  wire _0278_;
  wire _0279_;
  wire _0280_;
  wire _0281_;
  wire _0282_;
  wire _0283_;
  wire _0284_;
  wire _0285_;
  wire _0286_;
  wire _0287_;
  wire _0288_;
  wire _0289_;
  wire _0290_;
  wire _0291_;
  wire _0292_;
  wire _0293_;
  wire _0294_;
  wire _0295_;
  wire _0296_;
  wire _0297_;
  wire _0298_;
  wire _0299_;
  wire _0300_;
  wire _0301_;
  wire _0302_;
  wire _0303_;
  wire _0304_;
  wire _0305_;
  wire _0306_;
  wire _0307_;
  wire _0308_;
  wire _0309_;
  wire _0310_;
  wire _0311_;
  wire _0312_;
  wire _0313_;
  wire _0314_;
  wire _0315_;
  wire _0316_;
  wire _0317_;
  wire _0318_;
  wire _0319_;
  wire _0320_;
  wire _0321_;
  wire _0322_;
  wire _0323_;
  wire _0324_;
  wire _0325_;
  wire _0326_;
  wire _0327_;
  wire _0328_;
  wire _0329_;
  wire _0330_;
  wire _0331_;
  wire _0332_;
  wire _0333_;
  wire _0334_;
  wire _0335_;
  wire _0336_;
  wire _0337_;
  wire _0338_;
  wire _0339_;
  wire _0340_;
  wire _0341_;
  wire _0342_;
  wire _0343_;
  wire _0344_;
  wire _0345_;
  wire _0346_;
  wire _0347_;
  wire _0348_;
  wire _0349_;
  wire _0350_;
  wire _0351_;
  wire _0352_;
  wire _0353_;
  wire _0354_;
  wire _0355_;
  wire _0356_;
  wire _0357_;
  wire _0358_;
  wire _0359_;
  wire _0360_;
  wire _0361_;
  wire _0362_;
  wire _0363_;
  wire _0364_;
  wire _0365_;
  wire _0366_;
  wire _0367_;
  wire _0368_;
  wire _0369_;
  wire _0370_;
  wire _0371_;
  wire _0372_;
  wire _0373_;
  wire _0374_;
  wire _0375_;
  wire _0376_;
  wire _0377_;
  wire _0378_;
  wire _0379_;
  wire _0380_;
  wire _0381_;
  wire _0382_;
  wire _0383_;
  wire _0384_;
  wire _0385_;
  wire _0386_;
  wire _0387_;
  wire _0388_;
  wire _0389_;
  wire _0390_;
  wire _0391_;
  wire _0392_;
  wire _0393_;
  wire _0394_;
  wire _0395_;
  wire _0396_;
  wire _0397_;
  wire _0398_;
  wire _0399_;
  wire _0400_;
  wire _0401_;
  wire _0402_;
  wire _0403_;
  wire _0404_;
  wire _0405_;
  wire _0406_;
  wire _0407_;
  wire _0408_;
  wire _0409_;
  wire _0410_;
  wire _0411_;
  wire _0412_;
  wire _0413_;
  wire _0414_;
  wire _0415_;
  wire _0416_;
  wire _0417_;
  wire _0418_;
  wire _0419_;
  wire _0420_;
  wire _0421_;
  wire _0422_;
  wire _0423_;
  wire _0424_;
  wire _0425_;
  wire _0426_;
  wire _0427_;
  wire _0428_;
  wire _0429_;
  wire _0430_;
  wire _0431_;
  wire _0432_;
  wire _0433_;
  wire _0434_;
  wire _0435_;
  wire _0436_;
  wire _0437_;
  wire _0438_;
  wire _0439_;
  wire _0440_;
  wire _0441_;
  wire _0442_;
  wire _0443_;
  wire _0444_;
  wire _0445_;
  wire _0446_;
  wire _0447_;
  wire _0448_;
  wire _0449_;
  wire _0450_;
  wire _0451_;
  wire _0452_;
  wire _0453_;
  wire _0454_;
  wire _0455_;
  wire _0456_;
  wire _0457_;
  wire _0458_;
  wire _0459_;
  wire _0460_;
  wire _0461_;
  wire _0462_;
  wire _0463_;
  wire _0464_;
  wire _0465_;
  wire _0466_;
  wire _0467_;
  wire _0468_;
  wire _0469_;
  wire _0470_;
  wire _0471_;
  wire _0472_;
  wire _0473_;
  wire _0474_;
  wire _0475_;
  wire _0476_;
  wire _0477_;
  wire _0478_;
  wire _0479_;
  wire _0480_;
  wire _0481_;
  wire _0482_;
  wire _0483_;
  wire _0484_;
  wire _0485_;
  wire _0486_;
  wire _0487_;
  wire _0488_;
  wire _0489_;
  wire _0490_;
  wire _0491_;
  wire _0492_;
  wire _0493_;
  wire _0494_;
  wire _0495_;
  wire _0496_;
  wire _0497_;
  wire _0498_;
  wire _0499_;
  wire _0500_;
  wire _0501_;
  wire _0502_;
  wire _0503_;
  wire _0504_;
  wire _0505_;
  wire _0506_;
  wire _0507_;
  wire _0508_;
  wire _0509_;
  wire _0510_;
  wire _0511_;
  wire _0512_;
  wire _0513_;
  wire _0514_;
  wire _0515_;
  wire _0516_;
  wire _0517_;
  wire _0518_;
  wire _0519_;
  wire _0520_;
  wire _0521_;
  wire _0522_;
  wire _0523_;
  wire _0524_;
  wire _0525_;
  wire _0526_;
  wire _0527_;
  wire _0528_;
  wire _0529_;
  wire _0530_;
  wire _0531_;
  wire _0532_;
  wire _0533_;
  wire _0534_;
  wire _0535_;
  wire _0536_;
  wire _0537_;
  wire _0538_;
  wire _0539_;
  wire _0540_;
  wire _0541_;
  wire _0542_;
  wire _0543_;
  wire _0544_;
  wire _0545_;
  wire _0546_;
  wire _0547_;
  (* src = "cajeroAutomatico.v:17" *)
  output ADVERTENCIA;
  (* src = "cajeroAutomatico.v:14" *)
  output BALANCE_ACTUALIZADO;
  (* src = "cajeroAutomatico.v:12" *)
  input [63:0] BALANCE_INICIAL;
  (* src = "cajeroAutomatico.v:18" *)
  output BLOQUEO;
  (* src = "cajeroAutomatico.v:9" *)
  input [3:0] DIGITO;
  (* src = "cajeroAutomatico.v:8" *)
  input DIGITO_STB;
  (* src = "cajeroAutomatico.v:15" *)
  output ENTREGAR_DINERO;
  (* src = "cajeroAutomatico.v:19" *)
  output FONDOS_INSUFICIENTES;
  (* src = "cajeroAutomatico.v:11" *)
  input [31:0] MONTO;
  (* src = "cajeroAutomatico.v:7" *)
  input MONTO_STB;
  (* src = "cajeroAutomatico.v:10" *)
  input [15:0] PIN;
  (* src = "cajeroAutomatico.v:16" *)
  output PIN_INCORRECTO;
  (* src = "cajeroAutomatico.v:5" *)
  input TARJETA_RECIBIDA;
  (* src = "cajeroAutomatico.v:6" *)
  input TIPO_TRANS;
  (* src = "cajeroAutomatico.v:3" *)
  input clk;
  (* src = "cajeroAutomatico.v:36" *)
  wire [1:0] digitos_ingresados;
  (* src = "cajeroAutomatico.v:33" *)
  wire [1:0] intentos;
  (* src = "cajeroAutomatico.v:35" *)
  wire [15:0] pin_tecleado;
  (* src = "cajeroAutomatico.v:4" *)
  input rst;
  (* onehot = 32'd1 *)
  wire [6:0] state;
  NOT _0548_ (
    .A(rst),
    .Y(_0016_)
  );
  NOT _0549_ (
    .A(state[5]),
    .Y(_0017_)
  );
  NOT _0550_ (
    .A(state[3]),
    .Y(_0018_)
  );
  NOT _0551_ (
    .A(state[2]),
    .Y(_0019_)
  );
  NOT _0552_ (
    .A(state[0]),
    .Y(_0020_)
  );
  NOT _0553_ (
    .A(DIGITO_STB),
    .Y(_0021_)
  );
  NOT _0554_ (
    .A(MONTO_STB),
    .Y(_0022_)
  );
  NOT _0555_ (
    .A(TIPO_TRANS),
    .Y(_0023_)
  );
  NOT _0556_ (
    .A(digitos_ingresados[0]),
    .Y(_0024_)
  );
  NOT _0557_ (
    .A(pin_tecleado[0]),
    .Y(_0025_)
  );
  NOT _0558_ (
    .A(pin_tecleado[2]),
    .Y(_0026_)
  );
  NOT _0559_ (
    .A(pin_tecleado[5]),
    .Y(_0027_)
  );
  NOT _0560_ (
    .A(pin_tecleado[9]),
    .Y(_0028_)
  );
  NOT _0561_ (
    .A(pin_tecleado[13]),
    .Y(_0029_)
  );
  NOT _0562_ (
    .A(ENTREGAR_DINERO),
    .Y(_0030_)
  );
  NOT _0563_ (
    .A(BALANCE_ACTUALIZADO),
    .Y(_0031_)
  );
  NOT _0564_ (
    .A(BALANCE_INICIAL[0]),
    .Y(_0032_)
  );
  NOT _0565_ (
    .A(BALANCE_INICIAL[1]),
    .Y(_0033_)
  );
  NOT _0566_ (
    .A(BALANCE_INICIAL[2]),
    .Y(_0034_)
  );
  NOT _0567_ (
    .A(BALANCE_INICIAL[3]),
    .Y(_0035_)
  );
  NOT _0568_ (
    .A(BALANCE_INICIAL[5]),
    .Y(_0036_)
  );
  NOT _0569_ (
    .A(BALANCE_INICIAL[6]),
    .Y(_0037_)
  );
  NOT _0570_ (
    .A(BALANCE_INICIAL[7]),
    .Y(_0038_)
  );
  NOT _0571_ (
    .A(BALANCE_INICIAL[8]),
    .Y(_0039_)
  );
  NOT _0572_ (
    .A(BALANCE_INICIAL[9]),
    .Y(_0040_)
  );
  NOT _0573_ (
    .A(BALANCE_INICIAL[10]),
    .Y(_0041_)
  );
  NOT _0574_ (
    .A(BALANCE_INICIAL[11]),
    .Y(_0042_)
  );
  NOT _0575_ (
    .A(BALANCE_INICIAL[13]),
    .Y(_0043_)
  );
  NOT _0576_ (
    .A(BALANCE_INICIAL[14]),
    .Y(_0044_)
  );
  NOT _0577_ (
    .A(BALANCE_INICIAL[15]),
    .Y(_0045_)
  );
  NOT _0578_ (
    .A(BALANCE_INICIAL[16]),
    .Y(_0046_)
  );
  NOT _0579_ (
    .A(BALANCE_INICIAL[17]),
    .Y(_0047_)
  );
  NOT _0580_ (
    .A(BALANCE_INICIAL[18]),
    .Y(_0048_)
  );
  NOT _0581_ (
    .A(BALANCE_INICIAL[19]),
    .Y(_0049_)
  );
  NOT _0582_ (
    .A(BALANCE_INICIAL[20]),
    .Y(_0050_)
  );
  NOT _0583_ (
    .A(BALANCE_INICIAL[21]),
    .Y(_0051_)
  );
  NOT _0584_ (
    .A(BALANCE_INICIAL[22]),
    .Y(_0052_)
  );
  NOT _0585_ (
    .A(BALANCE_INICIAL[23]),
    .Y(_0053_)
  );
  NOT _0586_ (
    .A(BALANCE_INICIAL[24]),
    .Y(_0054_)
  );
  NOT _0587_ (
    .A(BALANCE_INICIAL[26]),
    .Y(_0055_)
  );
  NOT _0588_ (
    .A(BALANCE_INICIAL[27]),
    .Y(_0056_)
  );
  NOT _0589_ (
    .A(BALANCE_INICIAL[28]),
    .Y(_0057_)
  );
  NOT _0590_ (
    .A(BALANCE_INICIAL[30]),
    .Y(_0058_)
  );
  NOT _0591_ (
    .A(BALANCE_INICIAL[31]),
    .Y(_0059_)
  );
  NOT _0592_ (
    .A(BALANCE_INICIAL[57]),
    .Y(_0060_)
  );
  NOT _0593_ (
    .A(BALANCE_INICIAL[59]),
    .Y(_0061_)
  );
  NOT _0594_ (
    .A(MONTO[1]),
    .Y(_0062_)
  );
  NOT _0595_ (
    .A(MONTO[2]),
    .Y(_0063_)
  );
  NOT _0596_ (
    .A(MONTO[3]),
    .Y(_0064_)
  );
  NOT _0597_ (
    .A(MONTO[4]),
    .Y(_0065_)
  );
  NOT _0598_ (
    .A(MONTO[5]),
    .Y(_0066_)
  );
  NOT _0599_ (
    .A(MONTO[6]),
    .Y(_0067_)
  );
  NOT _0600_ (
    .A(MONTO[7]),
    .Y(_0068_)
  );
  NOT _0601_ (
    .A(MONTO[8]),
    .Y(_0069_)
  );
  NOT _0602_ (
    .A(MONTO[9]),
    .Y(_0070_)
  );
  NOT _0603_ (
    .A(MONTO[10]),
    .Y(_0071_)
  );
  NOT _0604_ (
    .A(MONTO[11]),
    .Y(_0072_)
  );
  NOT _0605_ (
    .A(MONTO[12]),
    .Y(_0073_)
  );
  NOT _0606_ (
    .A(MONTO[13]),
    .Y(_0074_)
  );
  NOT _0607_ (
    .A(MONTO[14]),
    .Y(_0075_)
  );
  NOT _0608_ (
    .A(MONTO[15]),
    .Y(_0076_)
  );
  NOT _0609_ (
    .A(MONTO[16]),
    .Y(_0077_)
  );
  NOT _0610_ (
    .A(MONTO[18]),
    .Y(_0078_)
  );
  NOT _0611_ (
    .A(MONTO[19]),
    .Y(_0079_)
  );
  NOT _0612_ (
    .A(MONTO[20]),
    .Y(_0080_)
  );
  NOT _0613_ (
    .A(MONTO[21]),
    .Y(_0081_)
  );
  NOT _0614_ (
    .A(MONTO[22]),
    .Y(_0082_)
  );
  NOT _0615_ (
    .A(MONTO[23]),
    .Y(_0083_)
  );
  NOT _0616_ (
    .A(MONTO[24]),
    .Y(_0084_)
  );
  NOT _0617_ (
    .A(MONTO[25]),
    .Y(_0085_)
  );
  NOT _0618_ (
    .A(MONTO[26]),
    .Y(_0086_)
  );
  NOT _0619_ (
    .A(MONTO[27]),
    .Y(_0087_)
  );
  NOT _0620_ (
    .A(MONTO[28]),
    .Y(_0088_)
  );
  NOT _0621_ (
    .A(MONTO[29]),
    .Y(_0089_)
  );
  NOT _0622_ (
    .A(MONTO[30]),
    .Y(_0090_)
  );
  NOT _0623_ (
    .A(MONTO[31]),
    .Y(_0091_)
  );
  NOT _0624_ (
    .A(PIN[0]),
    .Y(_0092_)
  );
  NOT _0625_ (
    .A(PIN[2]),
    .Y(_0093_)
  );
  NOT _0626_ (
    .A(PIN[5]),
    .Y(_0094_)
  );
  NOT _0627_ (
    .A(PIN[9]),
    .Y(_0095_)
  );
  NOT _0628_ (
    .A(PIN[13]),
    .Y(_0096_)
  );
  NOT _0629_ (
    .A(state[1]),
    .Y(_0097_)
  );
  NOR _0630_ (
    .A(_0021_),
    .B(_0024_),
    .Y(_0098_)
  );
  NAND _0631_ (
    .A(DIGITO_STB),
    .B(digitos_ingresados[0]),
    .Y(_0099_)
  );
  NAND _0632_ (
    .A(digitos_ingresados[1]),
    .B(_0098_),
    .Y(_0100_)
  );
  NAND _0633_ (
    .A(state[2]),
    .B(_0100_),
    .Y(_0101_)
  );
  NOR _0634_ (
    .A(state[4]),
    .B(state[3]),
    .Y(_0102_)
  );
  NAND _0635_ (
    .A(_0101_),
    .B(_0102_),
    .Y(_0103_)
  );
  NOT _0636_ (
    .A(_0103_),
    .Y(_0104_)
  );
  NOR _0637_ (
    .A(rst),
    .B(_0104_),
    .Y(_0015_)
  );
  NOR _0638_ (
    .A(_0020_),
    .B(TARJETA_RECIBIDA),
    .Y(_0105_)
  );
  NOR _0639_ (
    .A(rst),
    .B(_0105_),
    .Y(_0106_)
  );
  NAND _0640_ (
    .A(_0017_),
    .B(_0106_),
    .Y(_0014_)
  );
  NOR _0641_ (
    .A(state[2]),
    .B(state[0]),
    .Y(_0107_)
  );
  NAND _0642_ (
    .A(digitos_ingresados[0]),
    .B(_0107_),
    .Y(_0108_)
  );
  NAND _0643_ (
    .A(state[2]),
    .B(_0099_),
    .Y(_0109_)
  );
  NAND _0644_ (
    .A(_0108_),
    .B(_0109_),
    .Y(_0110_)
  );
  NOR _0645_ (
    .A(DIGITO_STB),
    .B(digitos_ingresados[0]),
    .Y(_0111_)
  );
  NAND _0646_ (
    .A(_0016_),
    .B(_0110_),
    .Y(_0112_)
  );
  NOR _0647_ (
    .A(_0111_),
    .B(_0112_),
    .Y(_0006_[0])
  );
  NOR _0648_ (
    .A(digitos_ingresados[1]),
    .B(_0098_),
    .Y(_0113_)
  );
  NAND _0649_ (
    .A(digitos_ingresados[1]),
    .B(_0107_),
    .Y(_0114_)
  );
  NAND _0650_ (
    .A(_0101_),
    .B(_0114_),
    .Y(_0115_)
  );
  NAND _0651_ (
    .A(_0016_),
    .B(_0115_),
    .Y(_0116_)
  );
  NOR _0652_ (
    .A(_0113_),
    .B(_0116_),
    .Y(_0006_[1])
  );
  NOR _0653_ (
    .A(_0019_),
    .B(_0021_),
    .Y(_0117_)
  );
  NOR _0654_ (
    .A(state[2]),
    .B(_0020_),
    .Y(_0118_)
  );
  NOR _0655_ (
    .A(_0117_),
    .B(_0118_),
    .Y(_0119_)
  );
  NAND _0656_ (
    .A(pin_tecleado[0]),
    .B(_0119_),
    .Y(_0120_)
  );
  NAND _0657_ (
    .A(DIGITO[0]),
    .B(_0117_),
    .Y(_0121_)
  );
  NAND _0658_ (
    .A(_0120_),
    .B(_0121_),
    .Y(_0122_)
  );
  NOT _0659_ (
    .A(_0122_),
    .Y(_0123_)
  );
  NOR _0660_ (
    .A(rst),
    .B(_0123_),
    .Y(_0008_[0])
  );
  NAND _0661_ (
    .A(pin_tecleado[1]),
    .B(_0119_),
    .Y(_0124_)
  );
  NAND _0662_ (
    .A(DIGITO[1]),
    .B(_0117_),
    .Y(_0125_)
  );
  NAND _0663_ (
    .A(_0124_),
    .B(_0125_),
    .Y(_0126_)
  );
  NOT _0664_ (
    .A(_0126_),
    .Y(_0127_)
  );
  NOR _0665_ (
    .A(rst),
    .B(_0127_),
    .Y(_0008_[1])
  );
  NAND _0666_ (
    .A(pin_tecleado[2]),
    .B(_0119_),
    .Y(_0128_)
  );
  NAND _0667_ (
    .A(DIGITO[2]),
    .B(_0117_),
    .Y(_0129_)
  );
  NAND _0668_ (
    .A(_0128_),
    .B(_0129_),
    .Y(_0130_)
  );
  NOT _0669_ (
    .A(_0130_),
    .Y(_0131_)
  );
  NOR _0670_ (
    .A(rst),
    .B(_0131_),
    .Y(_0008_[2])
  );
  NAND _0671_ (
    .A(pin_tecleado[3]),
    .B(_0119_),
    .Y(_0132_)
  );
  NAND _0672_ (
    .A(DIGITO[3]),
    .B(_0117_),
    .Y(_0133_)
  );
  NAND _0673_ (
    .A(_0132_),
    .B(_0133_),
    .Y(_0134_)
  );
  NOT _0674_ (
    .A(_0134_),
    .Y(_0135_)
  );
  NOR _0675_ (
    .A(rst),
    .B(_0135_),
    .Y(_0008_[3])
  );
  NAND _0676_ (
    .A(pin_tecleado[4]),
    .B(_0119_),
    .Y(_0136_)
  );
  NAND _0677_ (
    .A(pin_tecleado[0]),
    .B(_0117_),
    .Y(_0137_)
  );
  NAND _0678_ (
    .A(_0136_),
    .B(_0137_),
    .Y(_0138_)
  );
  NOT _0679_ (
    .A(_0138_),
    .Y(_0139_)
  );
  NOR _0680_ (
    .A(rst),
    .B(_0139_),
    .Y(_0008_[4])
  );
  NAND _0681_ (
    .A(pin_tecleado[5]),
    .B(_0119_),
    .Y(_0140_)
  );
  NAND _0682_ (
    .A(pin_tecleado[1]),
    .B(_0117_),
    .Y(_0141_)
  );
  NAND _0683_ (
    .A(_0140_),
    .B(_0141_),
    .Y(_0142_)
  );
  NOT _0684_ (
    .A(_0142_),
    .Y(_0143_)
  );
  NOR _0685_ (
    .A(rst),
    .B(_0143_),
    .Y(_0008_[5])
  );
  NAND _0686_ (
    .A(pin_tecleado[6]),
    .B(_0119_),
    .Y(_0144_)
  );
  NAND _0687_ (
    .A(pin_tecleado[2]),
    .B(_0117_),
    .Y(_0145_)
  );
  NAND _0688_ (
    .A(_0144_),
    .B(_0145_),
    .Y(_0146_)
  );
  NOT _0689_ (
    .A(_0146_),
    .Y(_0147_)
  );
  NOR _0690_ (
    .A(rst),
    .B(_0147_),
    .Y(_0008_[6])
  );
  NAND _0691_ (
    .A(pin_tecleado[7]),
    .B(_0119_),
    .Y(_0148_)
  );
  NAND _0692_ (
    .A(pin_tecleado[3]),
    .B(_0117_),
    .Y(_0149_)
  );
  NAND _0693_ (
    .A(_0148_),
    .B(_0149_),
    .Y(_0150_)
  );
  NOT _0694_ (
    .A(_0150_),
    .Y(_0151_)
  );
  NOR _0695_ (
    .A(rst),
    .B(_0151_),
    .Y(_0008_[7])
  );
  NAND _0696_ (
    .A(pin_tecleado[8]),
    .B(_0119_),
    .Y(_0152_)
  );
  NAND _0697_ (
    .A(pin_tecleado[4]),
    .B(_0117_),
    .Y(_0153_)
  );
  NAND _0698_ (
    .A(_0152_),
    .B(_0153_),
    .Y(_0154_)
  );
  NOT _0699_ (
    .A(_0154_),
    .Y(_0155_)
  );
  NOR _0700_ (
    .A(rst),
    .B(_0155_),
    .Y(_0008_[8])
  );
  NAND _0701_ (
    .A(pin_tecleado[9]),
    .B(_0119_),
    .Y(_0156_)
  );
  NAND _0702_ (
    .A(pin_tecleado[5]),
    .B(_0117_),
    .Y(_0157_)
  );
  NAND _0703_ (
    .A(_0156_),
    .B(_0157_),
    .Y(_0158_)
  );
  NOT _0704_ (
    .A(_0158_),
    .Y(_0159_)
  );
  NOR _0705_ (
    .A(rst),
    .B(_0159_),
    .Y(_0008_[9])
  );
  NAND _0706_ (
    .A(pin_tecleado[10]),
    .B(_0119_),
    .Y(_0160_)
  );
  NAND _0707_ (
    .A(pin_tecleado[6]),
    .B(_0117_),
    .Y(_0161_)
  );
  NAND _0708_ (
    .A(_0160_),
    .B(_0161_),
    .Y(_0162_)
  );
  NOT _0709_ (
    .A(_0162_),
    .Y(_0163_)
  );
  NOR _0710_ (
    .A(rst),
    .B(_0163_),
    .Y(_0008_[10])
  );
  NAND _0711_ (
    .A(pin_tecleado[11]),
    .B(_0119_),
    .Y(_0164_)
  );
  NAND _0712_ (
    .A(pin_tecleado[7]),
    .B(_0117_),
    .Y(_0165_)
  );
  NAND _0713_ (
    .A(_0164_),
    .B(_0165_),
    .Y(_0166_)
  );
  NOT _0714_ (
    .A(_0166_),
    .Y(_0167_)
  );
  NOR _0715_ (
    .A(rst),
    .B(_0167_),
    .Y(_0008_[11])
  );
  NAND _0716_ (
    .A(pin_tecleado[12]),
    .B(_0119_),
    .Y(_0168_)
  );
  NAND _0717_ (
    .A(pin_tecleado[8]),
    .B(_0117_),
    .Y(_0169_)
  );
  NAND _0718_ (
    .A(_0168_),
    .B(_0169_),
    .Y(_0170_)
  );
  NOT _0719_ (
    .A(_0170_),
    .Y(_0171_)
  );
  NOR _0720_ (
    .A(rst),
    .B(_0171_),
    .Y(_0008_[12])
  );
  NAND _0721_ (
    .A(pin_tecleado[13]),
    .B(_0119_),
    .Y(_0172_)
  );
  NAND _0722_ (
    .A(pin_tecleado[9]),
    .B(_0117_),
    .Y(_0173_)
  );
  NAND _0723_ (
    .A(_0172_),
    .B(_0173_),
    .Y(_0174_)
  );
  NOT _0724_ (
    .A(_0174_),
    .Y(_0175_)
  );
  NOR _0725_ (
    .A(rst),
    .B(_0175_),
    .Y(_0008_[13])
  );
  NAND _0726_ (
    .A(pin_tecleado[14]),
    .B(_0119_),
    .Y(_0176_)
  );
  NAND _0727_ (
    .A(pin_tecleado[10]),
    .B(_0117_),
    .Y(_0177_)
  );
  NAND _0728_ (
    .A(_0176_),
    .B(_0177_),
    .Y(_0178_)
  );
  NOT _0729_ (
    .A(_0178_),
    .Y(_0179_)
  );
  NOR _0730_ (
    .A(rst),
    .B(_0179_),
    .Y(_0008_[14])
  );
  NAND _0731_ (
    .A(pin_tecleado[15]),
    .B(_0119_),
    .Y(_0180_)
  );
  NAND _0732_ (
    .A(pin_tecleado[11]),
    .B(_0117_),
    .Y(_0181_)
  );
  NAND _0733_ (
    .A(_0180_),
    .B(_0181_),
    .Y(_0182_)
  );
  NOT _0734_ (
    .A(_0182_),
    .Y(_0183_)
  );
  NOR _0735_ (
    .A(rst),
    .B(_0183_),
    .Y(_0008_[15])
  );
  NAND _0736_ (
    .A(_0018_),
    .B(state[0]),
    .Y(_0184_)
  );
  NOT _0737_ (
    .A(_0184_),
    .Y(_0185_)
  );
  NOR _0738_ (
    .A(rst),
    .B(_0185_),
    .Y(_0186_)
  );
  NAND _0739_ (
    .A(_0016_),
    .B(_0184_),
    .Y(_0187_)
  );
  NOR _0740_ (
    .A(state[3]),
    .B(intentos[0]),
    .Y(_0188_)
  );
  NOT _0741_ (
    .A(_0188_),
    .Y(_0189_)
  );
  NAND _0742_ (
    .A(state[3]),
    .B(intentos[0]),
    .Y(_0190_)
  );
  NOT _0743_ (
    .A(_0190_),
    .Y(_0191_)
  );
  NAND _0744_ (
    .A(_0189_),
    .B(_0190_),
    .Y(_0192_)
  );
  NOR _0745_ (
    .A(_0187_),
    .B(_0192_),
    .Y(_0007_[0])
  );
  NOR _0746_ (
    .A(intentos[1]),
    .B(_0018_),
    .Y(_0193_)
  );
  NOR _0747_ (
    .A(intentos[1]),
    .B(_0190_),
    .Y(_0194_)
  );
  NAND _0748_ (
    .A(intentos[1]),
    .B(_0184_),
    .Y(_0195_)
  );
  NOR _0749_ (
    .A(_0191_),
    .B(_0195_),
    .Y(_0196_)
  );
  NOR _0750_ (
    .A(_0194_),
    .B(_0196_),
    .Y(_0197_)
  );
  NOR _0751_ (
    .A(rst),
    .B(_0197_),
    .Y(_0007_[1])
  );
  NOR _0752_ (
    .A(_0022_),
    .B(_0023_),
    .Y(_0198_)
  );
  NAND _0753_ (
    .A(MONTO_STB),
    .B(TIPO_TRANS),
    .Y(_0199_)
  );
  NAND _0754_ (
    .A(_0058_),
    .B(MONTO[30]),
    .Y(_0200_)
  );
  NAND _0755_ (
    .A(_0059_),
    .B(MONTO[31]),
    .Y(_0201_)
  );
  NAND _0756_ (
    .A(_0200_),
    .B(_0201_),
    .Y(_0202_)
  );
  NOR _0757_ (
    .A(_0059_),
    .B(MONTO[31]),
    .Y(_0203_)
  );
  NAND _0758_ (
    .A(BALANCE_INICIAL[31]),
    .B(_0091_),
    .Y(_0204_)
  );
  NAND _0759_ (
    .A(BALANCE_INICIAL[30]),
    .B(_0090_),
    .Y(_0205_)
  );
  NAND _0760_ (
    .A(BALANCE_INICIAL[29]),
    .B(_0089_),
    .Y(_0206_)
  );
  NAND _0761_ (
    .A(_0204_),
    .B(_0205_),
    .Y(_0207_)
  );
  NOR _0762_ (
    .A(_0202_),
    .B(_0207_),
    .Y(_0208_)
  );
  NAND _0763_ (
    .A(_0206_),
    .B(_0208_),
    .Y(_0209_)
  );
  NOR _0764_ (
    .A(BALANCE_INICIAL[28]),
    .B(_0088_),
    .Y(_0210_)
  );
  NOR _0765_ (
    .A(BALANCE_INICIAL[29]),
    .B(_0089_),
    .Y(_0211_)
  );
  NOR _0766_ (
    .A(_0210_),
    .B(_0211_),
    .Y(_0212_)
  );
  NOR _0767_ (
    .A(_0057_),
    .B(MONTO[28]),
    .Y(_0213_)
  );
  NOR _0768_ (
    .A(_0209_),
    .B(_0213_),
    .Y(_0214_)
  );
  NAND _0769_ (
    .A(_0212_),
    .B(_0214_),
    .Y(_0215_)
  );
  NAND _0770_ (
    .A(_0056_),
    .B(MONTO[27]),
    .Y(_0216_)
  );
  NAND _0771_ (
    .A(BALANCE_INICIAL[27]),
    .B(_0087_),
    .Y(_0217_)
  );
  NAND _0772_ (
    .A(_0216_),
    .B(_0217_),
    .Y(_0218_)
  );
  NOR _0773_ (
    .A(BALANCE_INICIAL[26]),
    .B(_0086_),
    .Y(_0219_)
  );
  NAND _0774_ (
    .A(_0055_),
    .B(MONTO[26]),
    .Y(_0220_)
  );
  NAND _0775_ (
    .A(BALANCE_INICIAL[26]),
    .B(_0086_),
    .Y(_0221_)
  );
  NAND _0776_ (
    .A(_0220_),
    .B(_0221_),
    .Y(_0222_)
  );
  NOR _0777_ (
    .A(_0218_),
    .B(_0222_),
    .Y(_0223_)
  );
  NOR _0778_ (
    .A(BALANCE_INICIAL[24]),
    .B(_0084_),
    .Y(_0224_)
  );
  NOR _0779_ (
    .A(BALANCE_INICIAL[25]),
    .B(_0085_),
    .Y(_0225_)
  );
  NOR _0780_ (
    .A(_0224_),
    .B(_0225_),
    .Y(_0226_)
  );
  NAND _0781_ (
    .A(BALANCE_INICIAL[25]),
    .B(_0085_),
    .Y(_0227_)
  );
  NOR _0782_ (
    .A(_0054_),
    .B(MONTO[24]),
    .Y(_0228_)
  );
  NAND _0783_ (
    .A(_0226_),
    .B(_0227_),
    .Y(_0229_)
  );
  NOR _0784_ (
    .A(_0228_),
    .B(_0229_),
    .Y(_0230_)
  );
  NAND _0785_ (
    .A(_0223_),
    .B(_0230_),
    .Y(_0231_)
  );
  NOR _0786_ (
    .A(_0215_),
    .B(_0231_),
    .Y(_0232_)
  );
  NOR _0787_ (
    .A(_0051_),
    .B(MONTO[21]),
    .Y(_0233_)
  );
  NAND _0788_ (
    .A(_0053_),
    .B(MONTO[23]),
    .Y(_0234_)
  );
  NOR _0789_ (
    .A(BALANCE_INICIAL[22]),
    .B(_0082_),
    .Y(_0235_)
  );
  NOR _0790_ (
    .A(_0052_),
    .B(MONTO[22]),
    .Y(_0236_)
  );
  NOR _0791_ (
    .A(_0235_),
    .B(_0236_),
    .Y(_0237_)
  );
  NAND _0792_ (
    .A(BALANCE_INICIAL[23]),
    .B(_0083_),
    .Y(_0238_)
  );
  NAND _0793_ (
    .A(_0234_),
    .B(_0238_),
    .Y(_0239_)
  );
  NOR _0794_ (
    .A(_0233_),
    .B(_0239_),
    .Y(_0240_)
  );
  NAND _0795_ (
    .A(_0237_),
    .B(_0240_),
    .Y(_0241_)
  );
  NOR _0796_ (
    .A(BALANCE_INICIAL[20]),
    .B(_0080_),
    .Y(_0242_)
  );
  NOR _0797_ (
    .A(BALANCE_INICIAL[21]),
    .B(_0081_),
    .Y(_0243_)
  );
  NOR _0798_ (
    .A(_0242_),
    .B(_0243_),
    .Y(_0244_)
  );
  NOR _0799_ (
    .A(_0050_),
    .B(MONTO[20]),
    .Y(_0245_)
  );
  NOR _0800_ (
    .A(_0241_),
    .B(_0245_),
    .Y(_0246_)
  );
  NAND _0801_ (
    .A(_0244_),
    .B(_0246_),
    .Y(_0247_)
  );
  NOT _0802_ (
    .A(_0247_),
    .Y(_0248_)
  );
  NOR _0803_ (
    .A(_0047_),
    .B(MONTO[17]),
    .Y(_0249_)
  );
  NOR _0804_ (
    .A(_0048_),
    .B(MONTO[18]),
    .Y(_0250_)
  );
  NOR _0805_ (
    .A(_0049_),
    .B(MONTO[19]),
    .Y(_0251_)
  );
  NOR _0806_ (
    .A(BALANCE_INICIAL[19]),
    .B(_0079_),
    .Y(_0252_)
  );
  NOR _0807_ (
    .A(BALANCE_INICIAL[18]),
    .B(_0078_),
    .Y(_0253_)
  );
  NAND _0808_ (
    .A(_0048_),
    .B(MONTO[18]),
    .Y(_0254_)
  );
  NOR _0809_ (
    .A(_0251_),
    .B(_0252_),
    .Y(_0255_)
  );
  NOR _0810_ (
    .A(_0250_),
    .B(_0253_),
    .Y(_0256_)
  );
  NAND _0811_ (
    .A(_0255_),
    .B(_0256_),
    .Y(_0257_)
  );
  NOR _0812_ (
    .A(_0249_),
    .B(_0257_),
    .Y(_0258_)
  );
  NAND _0813_ (
    .A(_0046_),
    .B(MONTO[16]),
    .Y(_0259_)
  );
  NAND _0814_ (
    .A(_0047_),
    .B(MONTO[17]),
    .Y(_0260_)
  );
  NAND _0815_ (
    .A(_0259_),
    .B(_0260_),
    .Y(_0261_)
  );
  NAND _0816_ (
    .A(BALANCE_INICIAL[16]),
    .B(_0077_),
    .Y(_0262_)
  );
  NAND _0817_ (
    .A(_0258_),
    .B(_0262_),
    .Y(_0263_)
  );
  NOR _0818_ (
    .A(_0247_),
    .B(_0263_),
    .Y(_0264_)
  );
  NAND _0819_ (
    .A(_0232_),
    .B(_0264_),
    .Y(_0265_)
  );
  NOR _0820_ (
    .A(_0261_),
    .B(_0265_),
    .Y(_0266_)
  );
  NOR _0821_ (
    .A(BALANCE_INICIAL[14]),
    .B(_0075_),
    .Y(_0267_)
  );
  NOR _0822_ (
    .A(BALANCE_INICIAL[15]),
    .B(_0076_),
    .Y(_0268_)
  );
  NOR _0823_ (
    .A(_0267_),
    .B(_0268_),
    .Y(_0269_)
  );
  NOR _0824_ (
    .A(_0045_),
    .B(MONTO[15]),
    .Y(_0270_)
  );
  NOR _0825_ (
    .A(_0044_),
    .B(MONTO[14]),
    .Y(_0271_)
  );
  NOR _0826_ (
    .A(_0043_),
    .B(MONTO[13]),
    .Y(_0272_)
  );
  NOR _0827_ (
    .A(_0270_),
    .B(_0271_),
    .Y(_0273_)
  );
  NAND _0828_ (
    .A(_0269_),
    .B(_0273_),
    .Y(_0274_)
  );
  NOR _0829_ (
    .A(_0272_),
    .B(_0274_),
    .Y(_0275_)
  );
  NOT _0830_ (
    .A(_0275_),
    .Y(_0276_)
  );
  NOR _0831_ (
    .A(BALANCE_INICIAL[12]),
    .B(_0073_),
    .Y(_0277_)
  );
  NOR _0832_ (
    .A(BALANCE_INICIAL[13]),
    .B(_0074_),
    .Y(_0278_)
  );
  NOR _0833_ (
    .A(_0277_),
    .B(_0278_),
    .Y(_0279_)
  );
  NAND _0834_ (
    .A(BALANCE_INICIAL[12]),
    .B(_0073_),
    .Y(_0280_)
  );
  NAND _0835_ (
    .A(_0279_),
    .B(_0280_),
    .Y(_0281_)
  );
  NOR _0836_ (
    .A(_0276_),
    .B(_0281_),
    .Y(_0282_)
  );
  NOR _0837_ (
    .A(_0042_),
    .B(MONTO[11]),
    .Y(_0283_)
  );
  NAND _0838_ (
    .A(BALANCE_INICIAL[11]),
    .B(_0072_),
    .Y(_0284_)
  );
  NOR _0839_ (
    .A(BALANCE_INICIAL[11]),
    .B(_0072_),
    .Y(_0285_)
  );
  NAND _0840_ (
    .A(_0042_),
    .B(MONTO[11]),
    .Y(_0286_)
  );
  NOR _0841_ (
    .A(_0283_),
    .B(_0285_),
    .Y(_0287_)
  );
  NOR _0842_ (
    .A(BALANCE_INICIAL[10]),
    .B(_0071_),
    .Y(_0288_)
  );
  NOR _0843_ (
    .A(_0041_),
    .B(MONTO[10]),
    .Y(_0289_)
  );
  NOR _0844_ (
    .A(_0288_),
    .B(_0289_),
    .Y(_0290_)
  );
  NAND _0845_ (
    .A(_0287_),
    .B(_0290_),
    .Y(_0291_)
  );
  NAND _0846_ (
    .A(_0039_),
    .B(MONTO[8]),
    .Y(_0292_)
  );
  NAND _0847_ (
    .A(_0040_),
    .B(MONTO[9]),
    .Y(_0293_)
  );
  NAND _0848_ (
    .A(_0292_),
    .B(_0293_),
    .Y(_0294_)
  );
  NOR _0849_ (
    .A(_0040_),
    .B(MONTO[9]),
    .Y(_0295_)
  );
  NAND _0850_ (
    .A(BALANCE_INICIAL[9]),
    .B(_0070_),
    .Y(_0296_)
  );
  NAND _0851_ (
    .A(BALANCE_INICIAL[8]),
    .B(_0069_),
    .Y(_0297_)
  );
  NOR _0852_ (
    .A(_0294_),
    .B(_0295_),
    .Y(_0298_)
  );
  NAND _0853_ (
    .A(_0297_),
    .B(_0298_),
    .Y(_0299_)
  );
  NOR _0854_ (
    .A(_0291_),
    .B(_0299_),
    .Y(_0300_)
  );
  NOR _0855_ (
    .A(BALANCE_INICIAL[6]),
    .B(_0067_),
    .Y(_0301_)
  );
  NAND _0856_ (
    .A(_0038_),
    .B(MONTO[7]),
    .Y(_0302_)
  );
  NAND _0857_ (
    .A(BALANCE_INICIAL[7]),
    .B(_0068_),
    .Y(_0303_)
  );
  NOR _0858_ (
    .A(_0037_),
    .B(MONTO[6]),
    .Y(_0304_)
  );
  NOR _0859_ (
    .A(_0036_),
    .B(MONTO[5]),
    .Y(_0305_)
  );
  NOR _0860_ (
    .A(_0301_),
    .B(_0304_),
    .Y(_0306_)
  );
  NAND _0861_ (
    .A(_0302_),
    .B(_0303_),
    .Y(_0307_)
  );
  NOR _0862_ (
    .A(_0305_),
    .B(_0307_),
    .Y(_0308_)
  );
  NAND _0863_ (
    .A(_0306_),
    .B(_0308_),
    .Y(_0309_)
  );
  NOR _0864_ (
    .A(BALANCE_INICIAL[4]),
    .B(_0065_),
    .Y(_0310_)
  );
  NOR _0865_ (
    .A(BALANCE_INICIAL[5]),
    .B(_0066_),
    .Y(_0311_)
  );
  NOR _0866_ (
    .A(_0310_),
    .B(_0311_),
    .Y(_0312_)
  );
  NAND _0867_ (
    .A(BALANCE_INICIAL[4]),
    .B(_0065_),
    .Y(_0313_)
  );
  NAND _0868_ (
    .A(_0312_),
    .B(_0313_),
    .Y(_0314_)
  );
  NOR _0869_ (
    .A(_0309_),
    .B(_0314_),
    .Y(_0315_)
  );
  NOR _0870_ (
    .A(_0035_),
    .B(MONTO[3]),
    .Y(_0316_)
  );
  NAND _0871_ (
    .A(BALANCE_INICIAL[3]),
    .B(_0064_),
    .Y(_0317_)
  );
  NOR _0872_ (
    .A(BALANCE_INICIAL[3]),
    .B(_0064_),
    .Y(_0318_)
  );
  NAND _0873_ (
    .A(_0035_),
    .B(MONTO[3]),
    .Y(_0319_)
  );
  NAND _0874_ (
    .A(_0317_),
    .B(_0319_),
    .Y(_0320_)
  );
  NAND _0875_ (
    .A(_0034_),
    .B(MONTO[2]),
    .Y(_0321_)
  );
  NAND _0876_ (
    .A(BALANCE_INICIAL[2]),
    .B(_0063_),
    .Y(_0322_)
  );
  NAND _0877_ (
    .A(_0321_),
    .B(_0322_),
    .Y(_0323_)
  );
  NOR _0878_ (
    .A(_0320_),
    .B(_0323_),
    .Y(_0324_)
  );
  NOR _0879_ (
    .A(BALANCE_INICIAL[1]),
    .B(_0062_),
    .Y(_0325_)
  );
  NAND _0880_ (
    .A(_0033_),
    .B(MONTO[1]),
    .Y(_0326_)
  );
  NAND _0881_ (
    .A(BALANCE_INICIAL[1]),
    .B(_0062_),
    .Y(_0327_)
  );
  NOR _0882_ (
    .A(_0032_),
    .B(MONTO[0]),
    .Y(_0328_)
  );
  NOR _0883_ (
    .A(_0325_),
    .B(_0328_),
    .Y(_0329_)
  );
  NAND _0884_ (
    .A(_0327_),
    .B(_0329_),
    .Y(_0330_)
  );
  NAND _0885_ (
    .A(_0326_),
    .B(_0330_),
    .Y(_0331_)
  );
  NAND _0886_ (
    .A(_0324_),
    .B(_0331_),
    .Y(_0332_)
  );
  NOR _0887_ (
    .A(_0316_),
    .B(_0321_),
    .Y(_0333_)
  );
  NOR _0888_ (
    .A(_0318_),
    .B(_0333_),
    .Y(_0334_)
  );
  NAND _0889_ (
    .A(_0332_),
    .B(_0334_),
    .Y(_0335_)
  );
  NAND _0890_ (
    .A(_0315_),
    .B(_0335_),
    .Y(_0336_)
  );
  NOR _0891_ (
    .A(_0309_),
    .B(_0312_),
    .Y(_0337_)
  );
  NAND _0892_ (
    .A(_0301_),
    .B(_0303_),
    .Y(_0338_)
  );
  NAND _0893_ (
    .A(_0302_),
    .B(_0338_),
    .Y(_0339_)
  );
  NOR _0894_ (
    .A(_0337_),
    .B(_0339_),
    .Y(_0340_)
  );
  NAND _0895_ (
    .A(_0336_),
    .B(_0340_),
    .Y(_0341_)
  );
  NAND _0896_ (
    .A(_0300_),
    .B(_0341_),
    .Y(_0342_)
  );
  NAND _0897_ (
    .A(_0294_),
    .B(_0296_),
    .Y(_0343_)
  );
  NOR _0898_ (
    .A(_0291_),
    .B(_0343_),
    .Y(_0344_)
  );
  NAND _0899_ (
    .A(_0284_),
    .B(_0288_),
    .Y(_0345_)
  );
  NAND _0900_ (
    .A(_0286_),
    .B(_0345_),
    .Y(_0346_)
  );
  NOR _0901_ (
    .A(_0344_),
    .B(_0346_),
    .Y(_0347_)
  );
  NAND _0902_ (
    .A(_0342_),
    .B(_0347_),
    .Y(_0348_)
  );
  NAND _0903_ (
    .A(_0282_),
    .B(_0348_),
    .Y(_0349_)
  );
  NOR _0904_ (
    .A(_0276_),
    .B(_0279_),
    .Y(_0350_)
  );
  NOR _0905_ (
    .A(_0269_),
    .B(_0270_),
    .Y(_0351_)
  );
  NOR _0906_ (
    .A(_0350_),
    .B(_0351_),
    .Y(_0352_)
  );
  NAND _0907_ (
    .A(_0349_),
    .B(_0352_),
    .Y(_0353_)
  );
  NAND _0908_ (
    .A(_0266_),
    .B(_0353_),
    .Y(_0354_)
  );
  NAND _0909_ (
    .A(_0258_),
    .B(_0261_),
    .Y(_0355_)
  );
  NOR _0910_ (
    .A(_0251_),
    .B(_0254_),
    .Y(_0356_)
  );
  NOR _0911_ (
    .A(_0252_),
    .B(_0356_),
    .Y(_0357_)
  );
  NAND _0912_ (
    .A(_0355_),
    .B(_0357_),
    .Y(_0358_)
  );
  NAND _0913_ (
    .A(_0248_),
    .B(_0358_),
    .Y(_0359_)
  );
  NOR _0914_ (
    .A(_0241_),
    .B(_0244_),
    .Y(_0360_)
  );
  NAND _0915_ (
    .A(_0235_),
    .B(_0238_),
    .Y(_0361_)
  );
  NAND _0916_ (
    .A(_0234_),
    .B(_0361_),
    .Y(_0362_)
  );
  NOR _0917_ (
    .A(_0360_),
    .B(_0362_),
    .Y(_0363_)
  );
  NAND _0918_ (
    .A(_0359_),
    .B(_0363_),
    .Y(_0364_)
  );
  NAND _0919_ (
    .A(_0232_),
    .B(_0364_),
    .Y(_0365_)
  );
  NAND _0920_ (
    .A(_0217_),
    .B(_0219_),
    .Y(_0366_)
  );
  NAND _0921_ (
    .A(_0216_),
    .B(_0366_),
    .Y(_0367_)
  );
  NAND _0922_ (
    .A(_0223_),
    .B(_0227_),
    .Y(_0368_)
  );
  NOR _0923_ (
    .A(_0226_),
    .B(_0368_),
    .Y(_0369_)
  );
  NOR _0924_ (
    .A(_0367_),
    .B(_0369_),
    .Y(_0370_)
  );
  NOR _0925_ (
    .A(_0215_),
    .B(_0370_),
    .Y(_0371_)
  );
  NOR _0926_ (
    .A(_0209_),
    .B(_0212_),
    .Y(_0372_)
  );
  NOR _0927_ (
    .A(_0200_),
    .B(_0203_),
    .Y(_0373_)
  );
  NOR _0928_ (
    .A(_0372_),
    .B(_0373_),
    .Y(_0374_)
  );
  NAND _0929_ (
    .A(_0201_),
    .B(_0374_),
    .Y(_0375_)
  );
  NOR _0930_ (
    .A(_0371_),
    .B(_0375_),
    .Y(_0376_)
  );
  NAND _0931_ (
    .A(_0365_),
    .B(_0376_),
    .Y(_0377_)
  );
  NOT _0932_ (
    .A(_0377_),
    .Y(_0378_)
  );
  NAND _0933_ (
    .A(_0354_),
    .B(_0378_),
    .Y(_0379_)
  );
  NAND _0934_ (
    .A(_0032_),
    .B(MONTO[0]),
    .Y(_0380_)
  );
  NAND _0935_ (
    .A(_0324_),
    .B(_0380_),
    .Y(_0381_)
  );
  NOR _0936_ (
    .A(_0330_),
    .B(_0381_),
    .Y(_0382_)
  );
  NAND _0937_ (
    .A(_0300_),
    .B(_0382_),
    .Y(_0383_)
  );
  NAND _0938_ (
    .A(_0282_),
    .B(_0315_),
    .Y(_0384_)
  );
  NOR _0939_ (
    .A(_0383_),
    .B(_0384_),
    .Y(_0385_)
  );
  NAND _0940_ (
    .A(_0266_),
    .B(_0385_),
    .Y(_0386_)
  );
  NOR _0941_ (
    .A(BALANCE_INICIAL[60]),
    .B(BALANCE_INICIAL[63]),
    .Y(_0387_)
  );
  NOR _0942_ (
    .A(BALANCE_INICIAL[52]),
    .B(BALANCE_INICIAL[55]),
    .Y(_0388_)
  );
  NOR _0943_ (
    .A(BALANCE_INICIAL[37]),
    .B(BALANCE_INICIAL[38]),
    .Y(_0389_)
  );
  NOT _0944_ (
    .A(_0389_),
    .Y(_0390_)
  );
  NOR _0945_ (
    .A(BALANCE_INICIAL[41]),
    .B(BALANCE_INICIAL[42]),
    .Y(_0391_)
  );
  NOR _0946_ (
    .A(BALANCE_INICIAL[50]),
    .B(BALANCE_INICIAL[61]),
    .Y(_0392_)
  );
  NOR _0947_ (
    .A(BALANCE_INICIAL[56]),
    .B(BALANCE_INICIAL[62]),
    .Y(_0393_)
  );
  NAND _0948_ (
    .A(_0392_),
    .B(_0393_),
    .Y(_0394_)
  );
  NOR _0949_ (
    .A(BALANCE_INICIAL[33]),
    .B(BALANCE_INICIAL[39]),
    .Y(_0395_)
  );
  NOR _0950_ (
    .A(BALANCE_INICIAL[35]),
    .B(BALANCE_INICIAL[44]),
    .Y(_0396_)
  );
  NAND _0951_ (
    .A(_0395_),
    .B(_0396_),
    .Y(_0397_)
  );
  NOR _0952_ (
    .A(_0394_),
    .B(_0397_),
    .Y(_0398_)
  );
  NAND _0953_ (
    .A(_0061_),
    .B(_0388_),
    .Y(_0399_)
  );
  NOR _0954_ (
    .A(BALANCE_INICIAL[34]),
    .B(BALANCE_INICIAL[36]),
    .Y(_0400_)
  );
  NOR _0955_ (
    .A(BALANCE_INICIAL[32]),
    .B(BALANCE_INICIAL[47]),
    .Y(_0401_)
  );
  NAND _0956_ (
    .A(_0400_),
    .B(_0401_),
    .Y(_0402_)
  );
  NOR _0957_ (
    .A(_0399_),
    .B(_0402_),
    .Y(_0403_)
  );
  NAND _0958_ (
    .A(_0398_),
    .B(_0403_),
    .Y(_0404_)
  );
  NOR _0959_ (
    .A(BALANCE_INICIAL[40]),
    .B(BALANCE_INICIAL[46]),
    .Y(_0405_)
  );
  NOR _0960_ (
    .A(BALANCE_INICIAL[51]),
    .B(BALANCE_INICIAL[53]),
    .Y(_0406_)
  );
  NAND _0961_ (
    .A(_0405_),
    .B(_0406_),
    .Y(_0407_)
  );
  NAND _0962_ (
    .A(_0060_),
    .B(_0387_),
    .Y(_0408_)
  );
  NOR _0963_ (
    .A(BALANCE_INICIAL[49]),
    .B(BALANCE_INICIAL[58]),
    .Y(_0409_)
  );
  NAND _0964_ (
    .A(_0391_),
    .B(_0409_),
    .Y(_0410_)
  );
  NOR _0965_ (
    .A(_0408_),
    .B(_0410_),
    .Y(_0411_)
  );
  NOR _0966_ (
    .A(BALANCE_INICIAL[43]),
    .B(BALANCE_INICIAL[45]),
    .Y(_0412_)
  );
  NOR _0967_ (
    .A(BALANCE_INICIAL[48]),
    .B(BALANCE_INICIAL[54]),
    .Y(_0413_)
  );
  NAND _0968_ (
    .A(_0412_),
    .B(_0413_),
    .Y(_0414_)
  );
  NOR _0969_ (
    .A(_0390_),
    .B(_0414_),
    .Y(_0415_)
  );
  NAND _0970_ (
    .A(_0411_),
    .B(_0415_),
    .Y(_0416_)
  );
  NOR _0971_ (
    .A(_0407_),
    .B(_0416_),
    .Y(_0417_)
  );
  NAND _0972_ (
    .A(_0386_),
    .B(_0417_),
    .Y(_0418_)
  );
  NOR _0973_ (
    .A(_0404_),
    .B(_0418_),
    .Y(_0419_)
  );
  NAND _0974_ (
    .A(_0379_),
    .B(_0419_),
    .Y(_0420_)
  );
  NOR _0975_ (
    .A(_0199_),
    .B(_0420_),
    .Y(_0421_)
  );
  NOR _0976_ (
    .A(FONDOS_INSUFICIENTES),
    .B(_0421_),
    .Y(_0422_)
  );
  NAND _0977_ (
    .A(_0020_),
    .B(FONDOS_INSUFICIENTES),
    .Y(_0423_)
  );
  NAND _0978_ (
    .A(_0017_),
    .B(_0423_),
    .Y(_0424_)
  );
  NAND _0979_ (
    .A(_0016_),
    .B(_0424_),
    .Y(_0425_)
  );
  NOR _0980_ (
    .A(_0422_),
    .B(_0425_),
    .Y(_0004_)
  );
  NAND _0981_ (
    .A(intentos[1]),
    .B(state[3]),
    .Y(_0426_)
  );
  NOT _0982_ (
    .A(_0426_),
    .Y(_0427_)
  );
  NOR _0983_ (
    .A(BLOQUEO),
    .B(_0427_),
    .Y(_0428_)
  );
  NOR _0984_ (
    .A(_0187_),
    .B(_0428_),
    .Y(_0002_)
  );
  NOR _0985_ (
    .A(ADVERTENCIA),
    .B(_0194_),
    .Y(_0429_)
  );
  NAND _0986_ (
    .A(_0186_),
    .B(_0426_),
    .Y(_0430_)
  );
  NOR _0987_ (
    .A(_0429_),
    .B(_0430_),
    .Y(_0000_)
  );
  NOR _0988_ (
    .A(PIN_INCORRECTO),
    .B(_0193_),
    .Y(_0431_)
  );
  NOT _0989_ (
    .A(_0431_),
    .Y(_0432_)
  );
  NAND _0990_ (
    .A(_0186_),
    .B(_0432_),
    .Y(_0433_)
  );
  NOR _0991_ (
    .A(_0194_),
    .B(_0433_),
    .Y(_0005_)
  );
  NAND _0992_ (
    .A(_0198_),
    .B(_0420_),
    .Y(_0434_)
  );
  NAND _0993_ (
    .A(_0030_),
    .B(_0434_),
    .Y(_0435_)
  );
  NOR _0994_ (
    .A(state[0]),
    .B(_0030_),
    .Y(_0436_)
  );
  NOR _0995_ (
    .A(state[5]),
    .B(_0436_),
    .Y(_0437_)
  );
  NAND _0996_ (
    .A(_0016_),
    .B(_0435_),
    .Y(_0438_)
  );
  NOR _0997_ (
    .A(_0437_),
    .B(_0438_),
    .Y(_0003_)
  );
  NOR _0998_ (
    .A(_0023_),
    .B(_0420_),
    .Y(_0439_)
  );
  NOR _0999_ (
    .A(_0022_),
    .B(_0439_),
    .Y(_0440_)
  );
  NOR _1000_ (
    .A(BALANCE_ACTUALIZADO),
    .B(_0440_),
    .Y(_0441_)
  );
  NOR _1001_ (
    .A(state[0]),
    .B(_0031_),
    .Y(_0442_)
  );
  NOR _1002_ (
    .A(state[5]),
    .B(_0442_),
    .Y(_0443_)
  );
  NOR _1003_ (
    .A(rst),
    .B(_0443_),
    .Y(_0444_)
  );
  NOT _1004_ (
    .A(_0444_),
    .Y(_0445_)
  );
  NOR _1005_ (
    .A(_0441_),
    .B(_0445_),
    .Y(_0001_)
  );
  NOR _1006_ (
    .A(pin_tecleado[2]),
    .B(_0093_),
    .Y(_0446_)
  );
  NOR _1007_ (
    .A(_0026_),
    .B(PIN[2]),
    .Y(_0447_)
  );
  NOR _1008_ (
    .A(pin_tecleado[9]),
    .B(_0095_),
    .Y(_0448_)
  );
  NOR _1009_ (
    .A(_0025_),
    .B(PIN[0]),
    .Y(_0449_)
  );
  NOR _1010_ (
    .A(pin_tecleado[0]),
    .B(_0092_),
    .Y(_0450_)
  );
  NOR _1011_ (
    .A(_0449_),
    .B(_0450_),
    .Y(_0451_)
  );
  NAND _1012_ (
    .A(pin_tecleado[1]),
    .B(PIN[1]),
    .Y(_0452_)
  );
  NOT _1013_ (
    .A(_0452_),
    .Y(_0453_)
  );
  NOR _1014_ (
    .A(pin_tecleado[1]),
    .B(PIN[1]),
    .Y(_0454_)
  );
  NOT _1015_ (
    .A(_0454_),
    .Y(_0455_)
  );
  NAND _1016_ (
    .A(_0452_),
    .B(_0455_),
    .Y(_0456_)
  );
  NOR _1017_ (
    .A(_0453_),
    .B(_0454_),
    .Y(_0457_)
  );
  NOR _1018_ (
    .A(_0029_),
    .B(PIN[13]),
    .Y(_0458_)
  );
  NOR _1019_ (
    .A(pin_tecleado[13]),
    .B(_0096_),
    .Y(_0459_)
  );
  NOR _1020_ (
    .A(_0458_),
    .B(_0459_),
    .Y(_0460_)
  );
  NOR _1021_ (
    .A(_0028_),
    .B(PIN[9]),
    .Y(_0461_)
  );
  NOR _1022_ (
    .A(pin_tecleado[4]),
    .B(PIN[4]),
    .Y(_0462_)
  );
  NOT _1023_ (
    .A(_0462_),
    .Y(_0463_)
  );
  NAND _1024_ (
    .A(pin_tecleado[4]),
    .B(PIN[4]),
    .Y(_0464_)
  );
  NAND _1025_ (
    .A(_0463_),
    .B(_0464_),
    .Y(_0465_)
  );
  NOR _1026_ (
    .A(pin_tecleado[7]),
    .B(PIN[7]),
    .Y(_0466_)
  );
  NOT _1027_ (
    .A(_0466_),
    .Y(_0467_)
  );
  NAND _1028_ (
    .A(pin_tecleado[7]),
    .B(PIN[7]),
    .Y(_0468_)
  );
  NAND _1029_ (
    .A(_0467_),
    .B(_0468_),
    .Y(_0469_)
  );
  NOR _1030_ (
    .A(pin_tecleado[12]),
    .B(PIN[12]),
    .Y(_0470_)
  );
  NOT _1031_ (
    .A(_0470_),
    .Y(_0471_)
  );
  NAND _1032_ (
    .A(pin_tecleado[12]),
    .B(PIN[12]),
    .Y(_0472_)
  );
  NAND _1033_ (
    .A(_0471_),
    .B(_0472_),
    .Y(_0473_)
  );
  NOR _1034_ (
    .A(pin_tecleado[3]),
    .B(PIN[3]),
    .Y(_0474_)
  );
  NOT _1035_ (
    .A(_0474_),
    .Y(_0475_)
  );
  NAND _1036_ (
    .A(pin_tecleado[3]),
    .B(PIN[3]),
    .Y(_0476_)
  );
  NAND _1037_ (
    .A(_0475_),
    .B(_0476_),
    .Y(_0477_)
  );
  NOR _1038_ (
    .A(pin_tecleado[10]),
    .B(PIN[10]),
    .Y(_0478_)
  );
  NOT _1039_ (
    .A(_0478_),
    .Y(_0479_)
  );
  NAND _1040_ (
    .A(pin_tecleado[10]),
    .B(PIN[10]),
    .Y(_0480_)
  );
  NAND _1041_ (
    .A(_0479_),
    .B(_0480_),
    .Y(_0481_)
  );
  NOR _1042_ (
    .A(pin_tecleado[14]),
    .B(PIN[14]),
    .Y(_0482_)
  );
  NOT _1043_ (
    .A(_0482_),
    .Y(_0483_)
  );
  NAND _1044_ (
    .A(pin_tecleado[14]),
    .B(PIN[14]),
    .Y(_0484_)
  );
  NOT _1045_ (
    .A(_0484_),
    .Y(_0485_)
  );
  NOR _1046_ (
    .A(_0482_),
    .B(_0485_),
    .Y(_0486_)
  );
  NAND _1047_ (
    .A(_0483_),
    .B(_0484_),
    .Y(_0487_)
  );
  NOR _1048_ (
    .A(pin_tecleado[15]),
    .B(PIN[15]),
    .Y(_0488_)
  );
  NOT _1049_ (
    .A(_0488_),
    .Y(_0489_)
  );
  NAND _1050_ (
    .A(pin_tecleado[15]),
    .B(PIN[15]),
    .Y(_0490_)
  );
  NAND _1051_ (
    .A(_0489_),
    .B(_0490_),
    .Y(_0491_)
  );
  NAND _1052_ (
    .A(pin_tecleado[11]),
    .B(PIN[11]),
    .Y(_0492_)
  );
  NOT _1053_ (
    .A(_0492_),
    .Y(_0493_)
  );
  NOR _1054_ (
    .A(pin_tecleado[11]),
    .B(PIN[11]),
    .Y(_0494_)
  );
  NOT _1055_ (
    .A(_0494_),
    .Y(_0495_)
  );
  NOR _1056_ (
    .A(_0493_),
    .B(_0494_),
    .Y(_0496_)
  );
  NAND _1057_ (
    .A(_0492_),
    .B(_0495_),
    .Y(_0497_)
  );
  NOR _1058_ (
    .A(pin_tecleado[5]),
    .B(_0094_),
    .Y(_0498_)
  );
  NAND _1059_ (
    .A(_0027_),
    .B(PIN[5]),
    .Y(_0499_)
  );
  NOR _1060_ (
    .A(_0446_),
    .B(_0498_),
    .Y(_0500_)
  );
  NAND _1061_ (
    .A(_0497_),
    .B(_0500_),
    .Y(_0501_)
  );
  NOR _1062_ (
    .A(_0027_),
    .B(PIN[5]),
    .Y(_0502_)
  );
  NAND _1063_ (
    .A(pin_tecleado[5]),
    .B(_0094_),
    .Y(_0503_)
  );
  NOR _1064_ (
    .A(_0461_),
    .B(_0502_),
    .Y(_0504_)
  );
  NOR _1065_ (
    .A(_0447_),
    .B(_0448_),
    .Y(_0505_)
  );
  NAND _1066_ (
    .A(_0504_),
    .B(_0505_),
    .Y(_0506_)
  );
  NOR _1067_ (
    .A(_0501_),
    .B(_0506_),
    .Y(_0507_)
  );
  NAND _1068_ (
    .A(_0465_),
    .B(_0487_),
    .Y(_0508_)
  );
  NAND _1069_ (
    .A(_0456_),
    .B(_0481_),
    .Y(_0509_)
  );
  NOR _1070_ (
    .A(_0508_),
    .B(_0509_),
    .Y(_0510_)
  );
  NAND _1071_ (
    .A(_0507_),
    .B(_0510_),
    .Y(_0511_)
  );
  NOR _1072_ (
    .A(pin_tecleado[6]),
    .B(PIN[6]),
    .Y(_0512_)
  );
  NOT _1073_ (
    .A(_0512_),
    .Y(_0513_)
  );
  NAND _1074_ (
    .A(pin_tecleado[6]),
    .B(PIN[6]),
    .Y(_0514_)
  );
  NAND _1075_ (
    .A(_0513_),
    .B(_0514_),
    .Y(_0515_)
  );
  NAND _1076_ (
    .A(_0477_),
    .B(_0515_),
    .Y(_0516_)
  );
  NAND _1077_ (
    .A(_0469_),
    .B(_0473_),
    .Y(_0517_)
  );
  NOR _1078_ (
    .A(_0516_),
    .B(_0517_),
    .Y(_0518_)
  );
  NAND _1079_ (
    .A(_0451_),
    .B(_0460_),
    .Y(_0519_)
  );
  NAND _1080_ (
    .A(pin_tecleado[8]),
    .B(PIN[8]),
    .Y(_0520_)
  );
  NOR _1081_ (
    .A(pin_tecleado[8]),
    .B(PIN[8]),
    .Y(_0521_)
  );
  NOT _1082_ (
    .A(_0521_),
    .Y(_0522_)
  );
  NAND _1083_ (
    .A(_0520_),
    .B(_0522_),
    .Y(_0523_)
  );
  NAND _1084_ (
    .A(_0491_),
    .B(_0523_),
    .Y(_0524_)
  );
  NOR _1085_ (
    .A(_0519_),
    .B(_0524_),
    .Y(_0525_)
  );
  NAND _1086_ (
    .A(_0518_),
    .B(_0525_),
    .Y(_0526_)
  );
  NAND _1087_ (
    .A(_0465_),
    .B(_0473_),
    .Y(_0527_)
  );
  NOR _1088_ (
    .A(_0516_),
    .B(_0527_),
    .Y(_0528_)
  );
  NAND _1089_ (
    .A(_0460_),
    .B(_0469_),
    .Y(_0529_)
  );
  NOR _1090_ (
    .A(_0486_),
    .B(_0529_),
    .Y(_0530_)
  );
  NAND _1091_ (
    .A(_0528_),
    .B(_0530_),
    .Y(_0531_)
  );
  NAND _1092_ (
    .A(_0451_),
    .B(_0481_),
    .Y(_0532_)
  );
  NOR _1093_ (
    .A(_0531_),
    .B(_0532_),
    .Y(_0533_)
  );
  NOR _1094_ (
    .A(_0446_),
    .B(_0447_),
    .Y(_0534_)
  );
  NAND _1095_ (
    .A(_0499_),
    .B(_0534_),
    .Y(_0535_)
  );
  NOR _1096_ (
    .A(_0448_),
    .B(_0461_),
    .Y(_0536_)
  );
  NAND _1097_ (
    .A(_0523_),
    .B(_0536_),
    .Y(_0537_)
  );
  NOR _1098_ (
    .A(_0535_),
    .B(_0537_),
    .Y(_0538_)
  );
  NAND _1099_ (
    .A(_0491_),
    .B(_0503_),
    .Y(_0539_)
  );
  NOR _1100_ (
    .A(_0457_),
    .B(_0539_),
    .Y(_0540_)
  );
  NAND _1101_ (
    .A(_0538_),
    .B(_0540_),
    .Y(_0541_)
  );
  NOR _1102_ (
    .A(_0496_),
    .B(_0541_),
    .Y(_0542_)
  );
  NOR _1103_ (
    .A(_0511_),
    .B(_0526_),
    .Y(_0543_)
  );
  NAND _1104_ (
    .A(_0533_),
    .B(_0542_),
    .Y(_0544_)
  );
  NAND _1105_ (
    .A(_0016_),
    .B(state[6]),
    .Y(_0545_)
  );
  NOR _1106_ (
    .A(_0544_),
    .B(_0545_),
    .Y(_0009_)
  );
  NAND _1107_ (
    .A(_0016_),
    .B(state[2]),
    .Y(_0546_)
  );
  NOR _1108_ (
    .A(_0100_),
    .B(_0546_),
    .Y(_0013_)
  );
  NOR _1109_ (
    .A(rst),
    .B(_0097_),
    .Y(_0012_)
  );
  NAND _1110_ (
    .A(state[0]),
    .B(TARJETA_RECIBIDA),
    .Y(_0547_)
  );
  NOR _1111_ (
    .A(rst),
    .B(_0547_),
    .Y(_0011_)
  );
  NOR _1112_ (
    .A(_0543_),
    .B(_0545_),
    .Y(_0010_)
  );
  DFF _1113_ (
    .C(clk),
    .D(_0014_),
    .Q(state[0])
  );
  DFF _1114_ (
    .C(clk),
    .D(_0009_),
    .Q(state[1])
  );
  DFF _1115_ (
    .C(clk),
    .D(_0015_),
    .Q(state[2])
  );
  DFF _1116_ (
    .C(clk),
    .D(_0010_),
    .Q(state[3])
  );
  DFF _1117_ (
    .C(clk),
    .D(_0011_),
    .Q(state[4])
  );
  DFF _1118_ (
    .C(clk),
    .D(_0012_),
    .Q(state[5])
  );
  DFF _1119_ (
    .C(clk),
    .D(_0013_),
    .Q(state[6])
  );
  (* src = "cajeroAutomatico.v:98" *)
  DFF _1120_ (
    .C(clk),
    .D(_0001_),
    .Q(BALANCE_ACTUALIZADO)
  );
  (* src = "cajeroAutomatico.v:98" *)
  DFF _1121_ (
    .C(clk),
    .D(_0003_),
    .Q(ENTREGAR_DINERO)
  );
  (* src = "cajeroAutomatico.v:98" *)
  DFF _1122_ (
    .C(clk),
    .D(_0005_),
    .Q(PIN_INCORRECTO)
  );
  (* src = "cajeroAutomatico.v:98" *)
  DFF _1123_ (
    .C(clk),
    .D(_0000_),
    .Q(ADVERTENCIA)
  );
  (* src = "cajeroAutomatico.v:98" *)
  DFF _1124_ (
    .C(clk),
    .D(_0002_),
    .Q(BLOQUEO)
  );
  (* src = "cajeroAutomatico.v:98" *)
  DFF _1125_ (
    .C(clk),
    .D(_0004_),
    .Q(FONDOS_INSUFICIENTES)
  );
  (* src = "cajeroAutomatico.v:98" *)
  DFF _1126_ (
    .C(clk),
    .D(_0007_[0]),
    .Q(intentos[0])
  );
  (* src = "cajeroAutomatico.v:98" *)
  DFF _1127_ (
    .C(clk),
    .D(_0007_[1]),
    .Q(intentos[1])
  );
  (* src = "cajeroAutomatico.v:98" *)
  DFF _1128_ (
    .C(clk),
    .D(_0008_[0]),
    .Q(pin_tecleado[0])
  );
  (* src = "cajeroAutomatico.v:98" *)
  DFF _1129_ (
    .C(clk),
    .D(_0008_[1]),
    .Q(pin_tecleado[1])
  );
  (* src = "cajeroAutomatico.v:98" *)
  DFF _1130_ (
    .C(clk),
    .D(_0008_[2]),
    .Q(pin_tecleado[2])
  );
  (* src = "cajeroAutomatico.v:98" *)
  DFF _1131_ (
    .C(clk),
    .D(_0008_[3]),
    .Q(pin_tecleado[3])
  );
  (* src = "cajeroAutomatico.v:98" *)
  DFF _1132_ (
    .C(clk),
    .D(_0008_[4]),
    .Q(pin_tecleado[4])
  );
  (* src = "cajeroAutomatico.v:98" *)
  DFF _1133_ (
    .C(clk),
    .D(_0008_[5]),
    .Q(pin_tecleado[5])
  );
  (* src = "cajeroAutomatico.v:98" *)
  DFF _1134_ (
    .C(clk),
    .D(_0008_[6]),
    .Q(pin_tecleado[6])
  );
  (* src = "cajeroAutomatico.v:98" *)
  DFF _1135_ (
    .C(clk),
    .D(_0008_[7]),
    .Q(pin_tecleado[7])
  );
  (* src = "cajeroAutomatico.v:98" *)
  DFF _1136_ (
    .C(clk),
    .D(_0008_[8]),
    .Q(pin_tecleado[8])
  );
  (* src = "cajeroAutomatico.v:98" *)
  DFF _1137_ (
    .C(clk),
    .D(_0008_[9]),
    .Q(pin_tecleado[9])
  );
  (* src = "cajeroAutomatico.v:98" *)
  DFF _1138_ (
    .C(clk),
    .D(_0008_[10]),
    .Q(pin_tecleado[10])
  );
  (* src = "cajeroAutomatico.v:98" *)
  DFF _1139_ (
    .C(clk),
    .D(_0008_[11]),
    .Q(pin_tecleado[11])
  );
  (* src = "cajeroAutomatico.v:98" *)
  DFF _1140_ (
    .C(clk),
    .D(_0008_[12]),
    .Q(pin_tecleado[12])
  );
  (* src = "cajeroAutomatico.v:98" *)
  DFF _1141_ (
    .C(clk),
    .D(_0008_[13]),
    .Q(pin_tecleado[13])
  );
  (* src = "cajeroAutomatico.v:98" *)
  DFF _1142_ (
    .C(clk),
    .D(_0008_[14]),
    .Q(pin_tecleado[14])
  );
  (* src = "cajeroAutomatico.v:98" *)
  DFF _1143_ (
    .C(clk),
    .D(_0008_[15]),
    .Q(pin_tecleado[15])
  );
  (* src = "cajeroAutomatico.v:98" *)
  DFF _1144_ (
    .C(clk),
    .D(_0006_[0]),
    .Q(digitos_ingresados[0])
  );
  (* src = "cajeroAutomatico.v:98" *)
  DFF _1145_ (
    .C(clk),
    .D(_0006_[1]),
    .Q(digitos_ingresados[1])
  );
endmodule
