/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "cajeroAutomatico.v:1" *)
module cajero_automatico(clk, rst, TARJETA_RECIBIDA, TIPO_TRANS, MONTO_STB, DIGITO_STB, DIGITO, PIN, MONTO, BALANCE_INICIAL, BALANCE_ACTUALIZADO, ENTREGAR_DINERO, PIN_INCORRECTO, ADVERTENCIA, BLOQUEO, FONDOS_INSUFICIENTES);
  (* src = "cajeroAutomatico.v:133" *)
  wire _0000_;
  (* src = "cajeroAutomatico.v:133" *)
  wire _0001_;
  (* src = "cajeroAutomatico.v:133" *)
  wire _0002_;
  (* src = "cajeroAutomatico.v:133" *)
  wire _0003_;
  (* src = "cajeroAutomatico.v:133" *)
  wire _0004_;
  (* src = "cajeroAutomatico.v:133" *)
  wire _0005_;
  (* src = "cajeroAutomatico.v:133" *)
  wire [1:0] _0006_;
  (* src = "cajeroAutomatico.v:133" *)
  wire [1:0] _0007_;
  (* src = "cajeroAutomatico.v:133" *)
  wire [15:0] _0008_;
  (* src = "cajeroAutomatico.v:133" *)
  wire _0009_;
  (* src = "cajeroAutomatico.v:133" *)
  wire _0010_;
  (* src = "cajeroAutomatico.v:133" *)
  wire _0011_;
  (* src = "cajeroAutomatico.v:133" *)
  wire _0012_;
  (* src = "cajeroAutomatico.v:133" *)
  wire _0013_;
  (* src = "cajeroAutomatico.v:133" *)
  wire _0014_;
  (* src = "cajeroAutomatico.v:133" *)
  wire _0015_;
  (* src = "cajeroAutomatico.v:133" *)
  wire _0016_;
  (* src = "cajeroAutomatico.v:133" *)
  wire _0017_;
  (* src = "cajeroAutomatico.v:133" *)
  wire _0018_;
  (* src = "cajeroAutomatico.v:133" *)
  wire _0019_;
  (* src = "cajeroAutomatico.v:133" *)
  wire _0020_;
  (* src = "cajeroAutomatico.v:133" *)
  wire _0021_;
  (* src = "cajeroAutomatico.v:133" *)
  wire _0022_;
  (* src = "cajeroAutomatico.v:133" *)
  wire _0023_;
  (* src = "cajeroAutomatico.v:133" *)
  wire _0024_;
  (* src = "cajeroAutomatico.v:133" *)
  wire _0025_;
  (* src = "cajeroAutomatico.v:133" *)
  wire _0026_;
  (* src = "cajeroAutomatico.v:133" *)
  wire _0027_;
  (* src = "cajeroAutomatico.v:133" *)
  wire _0028_;
  (* src = "cajeroAutomatico.v:133" *)
  wire _0029_;
  (* src = "cajeroAutomatico.v:133" *)
  wire _0030_;
  (* src = "cajeroAutomatico.v:133" *)
  wire _0031_;
  (* src = "cajeroAutomatico.v:133" *)
  wire _0032_;
  (* src = "cajeroAutomatico.v:133" *)
  wire _0033_;
  (* src = "cajeroAutomatico.v:133" *)
  wire _0034_;
  (* src = "cajeroAutomatico.v:17" *)
  wire _0035_;
  (* src = "cajeroAutomatico.v:14" *)
  wire _0036_;
  (* src = "cajeroAutomatico.v:12" *)
  wire _0037_;
  (* src = "cajeroAutomatico.v:12" *)
  wire _0038_;
  (* src = "cajeroAutomatico.v:12" *)
  wire _0039_;
  (* src = "cajeroAutomatico.v:12" *)
  wire _0040_;
  (* src = "cajeroAutomatico.v:12" *)
  wire _0041_;
  (* src = "cajeroAutomatico.v:12" *)
  wire _0042_;
  (* src = "cajeroAutomatico.v:12" *)
  wire _0043_;
  (* src = "cajeroAutomatico.v:12" *)
  wire _0044_;
  (* src = "cajeroAutomatico.v:12" *)
  wire _0045_;
  (* src = "cajeroAutomatico.v:12" *)
  wire _0046_;
  (* src = "cajeroAutomatico.v:12" *)
  wire _0047_;
  (* src = "cajeroAutomatico.v:12" *)
  wire _0048_;
  (* src = "cajeroAutomatico.v:12" *)
  wire _0049_;
  (* src = "cajeroAutomatico.v:12" *)
  wire _0050_;
  (* src = "cajeroAutomatico.v:12" *)
  wire _0051_;
  (* src = "cajeroAutomatico.v:12" *)
  wire _0052_;
  (* src = "cajeroAutomatico.v:12" *)
  wire _0053_;
  (* src = "cajeroAutomatico.v:12" *)
  wire _0054_;
  (* src = "cajeroAutomatico.v:12" *)
  wire _0055_;
  (* src = "cajeroAutomatico.v:12" *)
  wire _0056_;
  (* src = "cajeroAutomatico.v:12" *)
  wire _0057_;
  (* src = "cajeroAutomatico.v:12" *)
  wire _0058_;
  (* src = "cajeroAutomatico.v:12" *)
  wire _0059_;
  (* src = "cajeroAutomatico.v:12" *)
  wire _0060_;
  (* src = "cajeroAutomatico.v:12" *)
  wire _0061_;
  (* src = "cajeroAutomatico.v:12" *)
  wire _0062_;
  (* src = "cajeroAutomatico.v:12" *)
  wire _0063_;
  (* src = "cajeroAutomatico.v:12" *)
  wire _0064_;
  (* src = "cajeroAutomatico.v:12" *)
  wire _0065_;
  (* src = "cajeroAutomatico.v:12" *)
  wire _0066_;
  (* src = "cajeroAutomatico.v:12" *)
  wire _0067_;
  (* src = "cajeroAutomatico.v:12" *)
  wire _0068_;
  (* src = "cajeroAutomatico.v:12" *)
  wire _0069_;
  (* src = "cajeroAutomatico.v:12" *)
  wire _0070_;
  (* src = "cajeroAutomatico.v:12" *)
  wire _0071_;
  (* src = "cajeroAutomatico.v:12" *)
  wire _0072_;
  (* src = "cajeroAutomatico.v:12" *)
  wire _0073_;
  (* src = "cajeroAutomatico.v:12" *)
  wire _0074_;
  (* src = "cajeroAutomatico.v:12" *)
  wire _0075_;
  (* src = "cajeroAutomatico.v:12" *)
  wire _0076_;
  (* src = "cajeroAutomatico.v:12" *)
  wire _0077_;
  (* src = "cajeroAutomatico.v:12" *)
  wire _0078_;
  (* src = "cajeroAutomatico.v:12" *)
  wire _0079_;
  (* src = "cajeroAutomatico.v:12" *)
  wire _0080_;
  (* src = "cajeroAutomatico.v:12" *)
  wire _0081_;
  (* src = "cajeroAutomatico.v:12" *)
  wire _0082_;
  (* src = "cajeroAutomatico.v:12" *)
  wire _0083_;
  (* src = "cajeroAutomatico.v:12" *)
  wire _0084_;
  (* src = "cajeroAutomatico.v:12" *)
  wire _0085_;
  (* src = "cajeroAutomatico.v:12" *)
  wire _0086_;
  (* src = "cajeroAutomatico.v:12" *)
  wire _0087_;
  (* src = "cajeroAutomatico.v:12" *)
  wire _0088_;
  (* src = "cajeroAutomatico.v:12" *)
  wire _0089_;
  (* src = "cajeroAutomatico.v:12" *)
  wire _0090_;
  (* src = "cajeroAutomatico.v:12" *)
  wire _0091_;
  (* src = "cajeroAutomatico.v:12" *)
  wire _0092_;
  (* src = "cajeroAutomatico.v:12" *)
  wire _0093_;
  (* src = "cajeroAutomatico.v:12" *)
  wire _0094_;
  (* src = "cajeroAutomatico.v:12" *)
  wire _0095_;
  (* src = "cajeroAutomatico.v:12" *)
  wire _0096_;
  (* src = "cajeroAutomatico.v:12" *)
  wire _0097_;
  (* src = "cajeroAutomatico.v:12" *)
  wire _0098_;
  (* src = "cajeroAutomatico.v:12" *)
  wire _0099_;
  (* src = "cajeroAutomatico.v:12" *)
  wire _0100_;
  (* src = "cajeroAutomatico.v:18" *)
  wire _0101_;
  (* src = "cajeroAutomatico.v:9" *)
  wire _0102_;
  (* src = "cajeroAutomatico.v:9" *)
  wire _0103_;
  (* src = "cajeroAutomatico.v:9" *)
  wire _0104_;
  (* src = "cajeroAutomatico.v:9" *)
  wire _0105_;
  (* src = "cajeroAutomatico.v:8" *)
  wire _0106_;
  (* src = "cajeroAutomatico.v:15" *)
  wire _0107_;
  (* src = "cajeroAutomatico.v:19" *)
  wire _0108_;
  (* src = "cajeroAutomatico.v:11" *)
  wire _0109_;
  (* src = "cajeroAutomatico.v:11" *)
  wire _0110_;
  (* src = "cajeroAutomatico.v:11" *)
  wire _0111_;
  (* src = "cajeroAutomatico.v:11" *)
  wire _0112_;
  (* src = "cajeroAutomatico.v:11" *)
  wire _0113_;
  (* src = "cajeroAutomatico.v:11" *)
  wire _0114_;
  (* src = "cajeroAutomatico.v:11" *)
  wire _0115_;
  (* src = "cajeroAutomatico.v:11" *)
  wire _0116_;
  (* src = "cajeroAutomatico.v:11" *)
  wire _0117_;
  (* src = "cajeroAutomatico.v:11" *)
  wire _0118_;
  (* src = "cajeroAutomatico.v:11" *)
  wire _0119_;
  (* src = "cajeroAutomatico.v:11" *)
  wire _0120_;
  (* src = "cajeroAutomatico.v:11" *)
  wire _0121_;
  (* src = "cajeroAutomatico.v:11" *)
  wire _0122_;
  (* src = "cajeroAutomatico.v:11" *)
  wire _0123_;
  (* src = "cajeroAutomatico.v:11" *)
  wire _0124_;
  (* src = "cajeroAutomatico.v:11" *)
  wire _0125_;
  (* src = "cajeroAutomatico.v:11" *)
  wire _0126_;
  (* src = "cajeroAutomatico.v:11" *)
  wire _0127_;
  (* src = "cajeroAutomatico.v:11" *)
  wire _0128_;
  (* src = "cajeroAutomatico.v:11" *)
  wire _0129_;
  (* src = "cajeroAutomatico.v:11" *)
  wire _0130_;
  (* src = "cajeroAutomatico.v:11" *)
  wire _0131_;
  (* src = "cajeroAutomatico.v:11" *)
  wire _0132_;
  (* src = "cajeroAutomatico.v:11" *)
  wire _0133_;
  (* src = "cajeroAutomatico.v:11" *)
  wire _0134_;
  (* src = "cajeroAutomatico.v:11" *)
  wire _0135_;
  (* src = "cajeroAutomatico.v:11" *)
  wire _0136_;
  (* src = "cajeroAutomatico.v:11" *)
  wire _0137_;
  (* src = "cajeroAutomatico.v:11" *)
  wire _0138_;
  (* src = "cajeroAutomatico.v:11" *)
  wire _0139_;
  (* src = "cajeroAutomatico.v:11" *)
  wire _0140_;
  (* src = "cajeroAutomatico.v:7" *)
  wire _0141_;
  (* src = "cajeroAutomatico.v:10" *)
  wire _0142_;
  (* src = "cajeroAutomatico.v:10" *)
  wire _0143_;
  (* src = "cajeroAutomatico.v:10" *)
  wire _0144_;
  (* src = "cajeroAutomatico.v:10" *)
  wire _0145_;
  (* src = "cajeroAutomatico.v:10" *)
  wire _0146_;
  (* src = "cajeroAutomatico.v:10" *)
  wire _0147_;
  (* src = "cajeroAutomatico.v:10" *)
  wire _0148_;
  (* src = "cajeroAutomatico.v:10" *)
  wire _0149_;
  (* src = "cajeroAutomatico.v:10" *)
  wire _0150_;
  (* src = "cajeroAutomatico.v:10" *)
  wire _0151_;
  (* src = "cajeroAutomatico.v:10" *)
  wire _0152_;
  (* src = "cajeroAutomatico.v:10" *)
  wire _0153_;
  (* src = "cajeroAutomatico.v:10" *)
  wire _0154_;
  (* src = "cajeroAutomatico.v:10" *)
  wire _0155_;
  (* src = "cajeroAutomatico.v:10" *)
  wire _0156_;
  (* src = "cajeroAutomatico.v:10" *)
  wire _0157_;
  (* src = "cajeroAutomatico.v:16" *)
  wire _0158_;
  (* src = "cajeroAutomatico.v:5" *)
  wire _0159_;
  (* src = "cajeroAutomatico.v:6" *)
  wire _0160_;
  wire _0161_;
  wire _0162_;
  wire _0163_;
  wire _0164_;
  wire _0165_;
  wire _0166_;
  wire _0167_;
  (* src = "cajeroAutomatico.v:40" *)
  wire _0168_;
  (* src = "cajeroAutomatico.v:40" *)
  wire _0169_;
  (* src = "cajeroAutomatico.v:37" *)
  wire _0170_;
  (* src = "cajeroAutomatico.v:37" *)
  wire _0171_;
  wire _0172_;
  wire _0173_;
  wire _0174_;
  wire _0175_;
  wire _0176_;
  wire _0177_;
  wire _0178_;
  wire _0179_;
  wire _0180_;
  wire _0181_;
  wire _0182_;
  wire _0183_;
  wire _0184_;
  wire _0185_;
  wire _0186_;
  wire _0187_;
  wire _0188_;
  wire _0189_;
  wire _0190_;
  wire _0191_;
  wire _0192_;
  wire _0193_;
  wire _0194_;
  wire _0195_;
  wire _0196_;
  wire _0197_;
  wire _0198_;
  wire _0199_;
  wire _0200_;
  wire _0201_;
  wire _0202_;
  wire _0203_;
  wire _0204_;
  wire _0205_;
  wire _0206_;
  wire _0207_;
  wire _0208_;
  wire _0209_;
  wire _0210_;
  wire _0211_;
  wire _0212_;
  wire _0213_;
  wire _0214_;
  wire _0215_;
  wire _0216_;
  wire _0217_;
  wire _0218_;
  wire _0219_;
  wire _0220_;
  wire _0221_;
  wire _0222_;
  wire _0223_;
  wire _0224_;
  wire _0225_;
  wire _0226_;
  wire _0227_;
  wire _0228_;
  wire _0229_;
  wire _0230_;
  wire _0231_;
  wire _0232_;
  wire _0233_;
  wire _0234_;
  wire _0235_;
  wire _0236_;
  wire _0237_;
  wire _0238_;
  wire _0239_;
  wire _0240_;
  wire _0241_;
  wire _0242_;
  wire _0243_;
  wire _0244_;
  wire _0245_;
  wire _0246_;
  wire _0247_;
  wire _0248_;
  wire _0249_;
  wire _0250_;
  wire _0251_;
  wire _0252_;
  wire _0253_;
  wire _0254_;
  wire _0255_;
  wire _0256_;
  wire _0257_;
  wire _0258_;
  wire _0259_;
  wire _0260_;
  wire _0261_;
  wire _0262_;
  wire _0263_;
  wire _0264_;
  wire _0265_;
  wire _0266_;
  wire _0267_;
  wire _0268_;
  wire _0269_;
  wire _0270_;
  wire _0271_;
  wire _0272_;
  wire _0273_;
  wire _0274_;
  wire _0275_;
  wire _0276_;
  wire _0277_;
  wire _0278_;
  wire _0279_;
  wire _0280_;
  wire _0281_;
  wire _0282_;
  wire _0283_;
  wire _0284_;
  wire _0285_;
  wire _0286_;
  wire _0287_;
  wire _0288_;
  wire _0289_;
  wire _0290_;
  wire _0291_;
  wire _0292_;
  wire _0293_;
  wire _0294_;
  wire _0295_;
  wire _0296_;
  wire _0297_;
  wire _0298_;
  wire _0299_;
  wire _0300_;
  wire _0301_;
  wire _0302_;
  wire _0303_;
  wire _0304_;
  wire _0305_;
  wire _0306_;
  wire _0307_;
  wire _0308_;
  wire _0309_;
  wire _0310_;
  wire _0311_;
  wire _0312_;
  wire _0313_;
  wire _0314_;
  wire _0315_;
  wire _0316_;
  wire _0317_;
  wire _0318_;
  wire _0319_;
  wire _0320_;
  wire _0321_;
  wire _0322_;
  wire _0323_;
  wire _0324_;
  wire _0325_;
  wire _0326_;
  wire _0327_;
  wire _0328_;
  wire _0329_;
  wire _0330_;
  wire _0331_;
  wire _0332_;
  wire _0333_;
  wire _0334_;
  wire _0335_;
  wire _0336_;
  wire _0337_;
  wire _0338_;
  wire _0339_;
  wire _0340_;
  wire _0341_;
  wire _0342_;
  wire _0343_;
  wire _0344_;
  wire _0345_;
  wire _0346_;
  wire _0347_;
  wire _0348_;
  wire _0349_;
  wire _0350_;
  wire _0351_;
  wire _0352_;
  wire _0353_;
  wire _0354_;
  wire _0355_;
  wire _0356_;
  wire _0357_;
  wire _0358_;
  wire _0359_;
  wire _0360_;
  wire _0361_;
  wire _0362_;
  wire _0363_;
  wire _0364_;
  wire _0365_;
  wire _0366_;
  wire _0367_;
  wire _0368_;
  wire _0369_;
  wire _0370_;
  wire _0371_;
  wire _0372_;
  wire _0373_;
  wire _0374_;
  wire _0375_;
  wire _0376_;
  wire _0377_;
  wire _0378_;
  wire _0379_;
  wire _0380_;
  wire _0381_;
  wire _0382_;
  wire _0383_;
  wire _0384_;
  wire _0385_;
  wire _0386_;
  wire _0387_;
  wire _0388_;
  wire _0389_;
  wire _0390_;
  wire _0391_;
  wire _0392_;
  wire _0393_;
  wire _0394_;
  wire _0395_;
  wire _0396_;
  wire _0397_;
  wire _0398_;
  wire _0399_;
  wire _0400_;
  wire _0401_;
  wire _0402_;
  wire _0403_;
  wire _0404_;
  wire _0405_;
  wire _0406_;
  wire _0407_;
  wire _0408_;
  wire _0409_;
  wire _0410_;
  wire _0411_;
  wire _0412_;
  wire _0413_;
  wire _0414_;
  wire _0415_;
  wire _0416_;
  wire _0417_;
  wire _0418_;
  wire _0419_;
  wire _0420_;
  wire _0421_;
  wire _0422_;
  wire _0423_;
  wire _0424_;
  wire _0425_;
  wire _0426_;
  wire _0427_;
  wire _0428_;
  wire _0429_;
  wire _0430_;
  wire _0431_;
  wire _0432_;
  wire _0433_;
  wire _0434_;
  wire _0435_;
  wire _0436_;
  wire _0437_;
  wire _0438_;
  wire _0439_;
  wire _0440_;
  wire _0441_;
  wire _0442_;
  wire _0443_;
  wire _0444_;
  wire _0445_;
  wire _0446_;
  wire _0447_;
  wire _0448_;
  wire _0449_;
  wire _0450_;
  wire _0451_;
  wire _0452_;
  wire _0453_;
  wire _0454_;
  wire _0455_;
  wire _0456_;
  wire _0457_;
  wire _0458_;
  wire _0459_;
  wire _0460_;
  wire _0461_;
  wire _0462_;
  wire _0463_;
  wire _0464_;
  wire _0465_;
  wire _0466_;
  wire _0467_;
  wire _0468_;
  wire _0469_;
  wire _0470_;
  wire _0471_;
  wire _0472_;
  wire _0473_;
  wire _0474_;
  wire _0475_;
  wire _0476_;
  wire _0477_;
  wire _0478_;
  wire _0479_;
  wire _0480_;
  wire _0481_;
  wire _0482_;
  wire _0483_;
  wire _0484_;
  wire _0485_;
  wire _0486_;
  wire _0487_;
  wire _0488_;
  wire _0489_;
  wire _0490_;
  wire _0491_;
  wire _0492_;
  wire _0493_;
  wire _0494_;
  wire _0495_;
  wire _0496_;
  wire _0497_;
  wire _0498_;
  wire _0499_;
  wire _0500_;
  wire _0501_;
  wire _0502_;
  wire _0503_;
  wire _0504_;
  wire _0505_;
  wire _0506_;
  wire _0507_;
  wire _0508_;
  wire _0509_;
  wire _0510_;
  wire _0511_;
  wire _0512_;
  wire _0513_;
  wire _0514_;
  wire _0515_;
  wire _0516_;
  wire _0517_;
  wire _0518_;
  wire _0519_;
  wire _0520_;
  wire _0521_;
  wire _0522_;
  wire _0523_;
  wire _0524_;
  wire _0525_;
  wire _0526_;
  wire _0527_;
  wire _0528_;
  wire _0529_;
  wire _0530_;
  wire _0531_;
  wire _0532_;
  wire _0533_;
  wire _0534_;
  wire _0535_;
  wire _0536_;
  wire _0537_;
  wire _0538_;
  wire _0539_;
  wire _0540_;
  wire _0541_;
  wire _0542_;
  wire _0543_;
  wire _0544_;
  wire _0545_;
  wire _0546_;
  wire _0547_;
  wire _0548_;
  wire _0549_;
  wire _0550_;
  wire _0551_;
  wire _0552_;
  wire _0553_;
  wire _0554_;
  wire _0555_;
  wire _0556_;
  wire _0557_;
  wire _0558_;
  wire _0559_;
  wire _0560_;
  wire _0561_;
  wire _0562_;
  wire _0563_;
  wire _0564_;
  wire _0565_;
  wire _0566_;
  wire _0567_;
  wire _0568_;
  wire _0569_;
  wire _0570_;
  wire _0571_;
  wire _0572_;
  wire _0573_;
  wire _0574_;
  wire _0575_;
  wire _0576_;
  wire _0577_;
  wire _0578_;
  wire _0579_;
  wire _0580_;
  wire _0581_;
  wire _0582_;
  wire _0583_;
  wire _0584_;
  wire _0585_;
  wire _0586_;
  wire _0587_;
  wire _0588_;
  wire _0589_;
  wire _0590_;
  wire _0591_;
  wire _0592_;
  wire _0593_;
  wire _0594_;
  wire _0595_;
  wire _0596_;
  wire _0597_;
  wire _0598_;
  wire _0599_;
  wire _0600_;
  wire _0601_;
  wire _0602_;
  wire _0603_;
  wire _0604_;
  wire _0605_;
  wire _0606_;
  wire _0607_;
  wire _0608_;
  wire _0609_;
  wire _0610_;
  wire _0611_;
  wire _0612_;
  wire _0613_;
  wire _0614_;
  wire _0615_;
  wire _0616_;
  wire _0617_;
  wire _0618_;
  wire _0619_;
  wire _0620_;
  wire _0621_;
  wire _0622_;
  wire _0623_;
  wire _0624_;
  wire _0625_;
  wire _0626_;
  wire _0627_;
  wire _0628_;
  wire _0629_;
  wire _0630_;
  wire _0631_;
  wire _0632_;
  wire _0633_;
  wire _0634_;
  wire _0635_;
  wire _0636_;
  wire _0637_;
  wire _0638_;
  wire _0639_;
  wire _0640_;
  wire _0641_;
  wire _0642_;
  wire _0643_;
  wire _0644_;
  wire _0645_;
  wire _0646_;
  wire _0647_;
  wire _0648_;
  wire _0649_;
  wire _0650_;
  wire _0651_;
  wire _0652_;
  wire _0653_;
  wire _0654_;
  wire _0655_;
  wire _0656_;
  wire _0657_;
  wire _0658_;
  wire _0659_;
  wire _0660_;
  wire _0661_;
  wire _0662_;
  wire _0663_;
  wire _0664_;
  wire _0665_;
  wire _0666_;
  wire _0667_;
  wire _0668_;
  wire _0669_;
  wire _0670_;
  wire _0671_;
  wire _0672_;
  wire _0673_;
  wire _0674_;
  wire _0675_;
  wire _0676_;
  wire _0677_;
  wire _0678_;
  wire _0679_;
  wire _0680_;
  wire _0681_;
  wire _0682_;
  wire _0683_;
  wire _0684_;
  wire _0685_;
  wire _0686_;
  wire _0687_;
  wire _0688_;
  wire _0689_;
  wire _0690_;
  wire _0691_;
  wire _0692_;
  wire _0693_;
  wire _0694_;
  wire _0695_;
  wire _0696_;
  wire _0697_;
  wire _0698_;
  wire _0699_;
  wire _0700_;
  wire _0701_;
  wire _0702_;
  wire _0703_;
  wire _0704_;
  wire _0705_;
  wire _0706_;
  wire _0707_;
  wire _0708_;
  wire _0709_;
  wire _0710_;
  wire _0711_;
  wire _0712_;
  wire _0713_;
  wire _0714_;
  wire _0715_;
  wire _0716_;
  wire _0717_;
  wire _0718_;
  wire _0719_;
  wire _0720_;
  wire _0721_;
  wire _0722_;
  wire _0723_;
  wire _0724_;
  wire _0725_;
  wire _0726_;
  wire _0727_;
  wire _0728_;
  wire _0729_;
  wire _0730_;
  wire _0731_;
  wire _0732_;
  wire _0733_;
  wire _0734_;
  wire _0735_;
  wire _0736_;
  wire _0737_;
  wire _0738_;
  wire _0739_;
  wire _0740_;
  wire _0741_;
  wire _0742_;
  wire _0743_;
  wire _0744_;
  wire _0745_;
  wire _0746_;
  wire _0747_;
  wire _0748_;
  wire _0749_;
  wire _0750_;
  wire _0751_;
  wire _0752_;
  wire _0753_;
  wire _0754_;
  wire _0755_;
  wire _0756_;
  wire _0757_;
  wire _0758_;
  wire _0759_;
  wire _0760_;
  wire _0761_;
  wire _0762_;
  wire _0763_;
  wire _0764_;
  wire _0765_;
  wire _0766_;
  wire _0767_;
  wire _0768_;
  wire _0769_;
  wire _0770_;
  wire _0771_;
  wire _0772_;
  wire _0773_;
  wire _0774_;
  wire _0775_;
  wire _0776_;
  wire _0777_;
  wire _0778_;
  wire _0779_;
  wire _0780_;
  wire _0781_;
  wire _0782_;
  wire _0783_;
  wire _0784_;
  wire _0785_;
  wire _0786_;
  wire _0787_;
  wire _0788_;
  wire _0789_;
  wire _0790_;
  wire _0791_;
  wire _0792_;
  wire _0793_;
  (* src = "cajeroAutomatico.v:39" *)
  wire _0794_;
  (* src = "cajeroAutomatico.v:39" *)
  wire _0795_;
  (* src = "cajeroAutomatico.v:39" *)
  wire _0796_;
  (* src = "cajeroAutomatico.v:39" *)
  wire _0797_;
  (* src = "cajeroAutomatico.v:39" *)
  wire _0798_;
  (* src = "cajeroAutomatico.v:39" *)
  wire _0799_;
  (* src = "cajeroAutomatico.v:39" *)
  wire _0800_;
  (* src = "cajeroAutomatico.v:39" *)
  wire _0801_;
  (* src = "cajeroAutomatico.v:39" *)
  wire _0802_;
  (* src = "cajeroAutomatico.v:39" *)
  wire _0803_;
  (* src = "cajeroAutomatico.v:39" *)
  wire _0804_;
  (* src = "cajeroAutomatico.v:39" *)
  wire _0805_;
  (* src = "cajeroAutomatico.v:39" *)
  wire _0806_;
  (* src = "cajeroAutomatico.v:39" *)
  wire _0807_;
  (* src = "cajeroAutomatico.v:39" *)
  wire _0808_;
  (* src = "cajeroAutomatico.v:39" *)
  wire _0809_;
  (* src = "cajeroAutomatico.v:4" *)
  wire _0810_;
  wire _0811_;
  wire _0812_;
  wire _0813_;
  wire _0814_;
  wire _0815_;
  wire _0816_;
  wire _0817_;
  (* src = "cajeroAutomatico.v:171" *)
  (* unused_bits = "2" *)
  wire [31:0] _0818_;
  (* src = "cajeroAutomatico.v:228" *)
  (* unused_bits = "2" *)
  wire [31:0] _0819_;
  wire _0820_;
  wire _0821_;
  wire _0822_;
  wire _0823_;
  wire _0824_;
  wire _0825_;
  wire _0826_;
  wire _0827_;
  wire _0828_;
  wire _0829_;
  (* unused_bits = "7" *)
  wire [7:0] _0830_;
  wire _0831_;
  wire _0832_;
  wire _0833_;
  wire _0834_;
  wire _0835_;
  wire _0836_;
  wire _0837_;
  wire _0838_;
  wire _0839_;
  wire [7:0] _0840_;
  wire [3:0] _0841_;
  wire [1:0] _0842_;
  wire _0843_;
  wire _0844_;
  wire _0845_;
  wire [31:0] _0846_;
  wire [15:0] _0847_;
  wire [7:0] _0848_;
  wire [3:0] _0849_;
  wire [1:0] _0850_;
  wire [15:0] _0851_;
  wire _0852_;
  wire _0853_;
  wire _0854_;
  wire _0855_;
  wire [1:0] _0856_;
  wire [15:0] _0857_;
  wire [1:0] _0858_;
  wire [2:0] _0859_;
  wire [1:0] _0860_;
  wire [1:0] _0861_;
  wire [2:0] _0862_;
  wire _0863_;
  wire _0864_;
  wire _0865_;
  wire _0866_;
  wire _0867_;
  wire _0868_;
  wire _0869_;
  (* src = "cajeroAutomatico.v:189" *)
  wire _0870_;
  (* src = "cajeroAutomatico.v:79" *)
  wire _0871_;
  (* src = "cajeroAutomatico.v:113" *)
  wire _0872_;
  (* src = "cajeroAutomatico.v:195" *)
  wire _0873_;
  (* src = "cajeroAutomatico.v:189" *)
  wire _0874_;
  (* src = "cajeroAutomatico.v:193" *)
  wire _0875_;
  wire _0876_;
  (* src = "cajeroAutomatico.v:187|cajeroAutomatico.v:148|<techmap.v>:432" *)
  wire [1:0] _0877_;
  wire _0878_;
  wire _0879_;
  wire _0880_;
  wire _0881_;
  (* src = "cajeroAutomatico.v:187|cajeroAutomatico.v:148|<techmap.v>:432" *)
  wire [1:0] _0882_;
  wire _0883_;
  wire [1:0] _0884_;
  (* src = "cajeroAutomatico.v:167|cajeroAutomatico.v:148|<techmap.v>:432" *)
  wire [3:0] _0885_;
  wire [1:0] _0886_;
  wire [15:0] _0887_;
  (* src = "cajeroAutomatico.v:167|cajeroAutomatico.v:148|<techmap.v>:432" *)
  wire [31:0] _0888_;
  wire [15:0] _0889_;
  (* src = "cajeroAutomatico.v:226|cajeroAutomatico.v:148|<techmap.v>:432" *)
  wire [3:0] _0890_;
  wire [1:0] _0891_;
  wire _0892_;
  wire _0893_;
  (* src = "cajeroAutomatico.v:187|cajeroAutomatico.v:148|<techmap.v>:432" *)
  wire [1:0] _0894_;
  wire _0895_;
  wire _0896_;
  wire _0897_;
  (* src = "cajeroAutomatico.v:226|cajeroAutomatico.v:148|<techmap.v>:432" *)
  wire [1:0] _0898_;
  wire _0899_;
  wire _0900_;
  (* src = "cajeroAutomatico.v:226|cajeroAutomatico.v:148|<techmap.v>:432" *)
  wire [1:0] _0901_;
  wire _0902_;
  wire _0903_;
  wire _0904_;
  (* src = "cajeroAutomatico.v:231|<techmap.v>:260|<techmap.v>:203" *)
  wire [31:0] _0905_;
  wire _0906_;
  wire _0907_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:258" *)
  wire [63:0] _0908_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:203" *)
  (* unused_bits = "2 4 5 6 8 9 10 11 12 13 14 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62" *)
  wire [63:0] _0909_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:203" *)
  (* unused_bits = "1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63" *)
  wire [63:0] _0910_;
  wire [63:0] _0911_;
  wire _0912_;
  wire _0913_;
  (* src = "cajeroAutomatico.v:187|cajeroAutomatico.v:148|<techmap.v>:445" *)
  wire _0914_;
  (* src = "cajeroAutomatico.v:167|cajeroAutomatico.v:148|<techmap.v>:445" *)
  wire _0915_;
  (* src = "cajeroAutomatico.v:226|cajeroAutomatico.v:148|<techmap.v>:445" *)
  wire _0916_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260" *)
  wire [63:0] _0917_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)
  wire _0918_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)
  wire _0919_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)
  wire _0920_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)
  wire _0921_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)
  wire _0922_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)
  wire _0923_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)
  wire _0924_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)
  wire _0925_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)
  wire _0926_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)
  wire _0927_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)
  wire _0928_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)
  wire _0929_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)
  wire _0930_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)
  wire _0931_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)
  wire _0932_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)
  wire _0933_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)
  wire _0934_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)
  wire _0935_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)
  wire _0936_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)
  wire _0937_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)
  wire _0938_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)
  wire _0939_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)
  wire _0940_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)
  wire _0941_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)
  wire _0942_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)
  wire _0943_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)
  wire _0944_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)
  wire _0945_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)
  wire _0946_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)
  wire _0947_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)
  wire _0948_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)
  wire _0949_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)
  wire _0950_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)
  wire _0951_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)
  wire _0952_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)
  wire _0953_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)
  wire _0954_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)
  wire _0955_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)
  wire _0956_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)
  wire _0957_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)
  wire _0958_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)
  wire _0959_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)
  wire _0960_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)
  wire _0961_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)
  wire _0962_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)
  wire _0963_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)
  wire _0964_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)
  wire _0965_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)
  wire _0966_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)
  wire _0967_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)
  wire _0968_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)
  wire _0969_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)
  wire _0970_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)
  wire _0971_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)
  wire _0972_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)
  wire _0973_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)
  wire _0974_;
  (* src = "cajeroAutomatico.v:17" *)
  output ADVERTENCIA;
  (* src = "cajeroAutomatico.v:14" *)
  output BALANCE_ACTUALIZADO;
  (* src = "cajeroAutomatico.v:12" *)
  input [63:0] BALANCE_INICIAL;
  (* src = "cajeroAutomatico.v:18" *)
  output BLOQUEO;
  (* src = "cajeroAutomatico.v:9" *)
  input [3:0] DIGITO;
  (* src = "cajeroAutomatico.v:8" *)
  input DIGITO_STB;
  (* src = "cajeroAutomatico.v:15" *)
  output ENTREGAR_DINERO;
  (* src = "cajeroAutomatico.v:19" *)
  output FONDOS_INSUFICIENTES;
  (* src = "cajeroAutomatico.v:11" *)
  input [31:0] MONTO;
  (* src = "cajeroAutomatico.v:7" *)
  input MONTO_STB;
  (* src = "cajeroAutomatico.v:10" *)
  input [15:0] PIN;
  (* src = "cajeroAutomatico.v:16" *)
  output PIN_INCORRECTO;
  (* src = "cajeroAutomatico.v:5" *)
  input TARJETA_RECIBIDA;
  (* src = "cajeroAutomatico.v:6" *)
  input TIPO_TRANS;
  (* src = "cajeroAutomatico.v:3" *)
  input clk;
  (* src = "cajeroAutomatico.v:40" *)
  wire [1:0] digitos_ingresados;
  (* src = "cajeroAutomatico.v:37" *)
  wire [1:0] intentos;
  (* src = "cajeroAutomatico.v:39" *)
  wire [15:0] pin_tecleado;
  (* src = "cajeroAutomatico.v:4" *)
  input rst;
  (* onehot = 32'd1 *)
  (* unused_bits = "7" *)
  wire [7:0] state;
  NOT _0975_ (
    .A(_0170_),
    .Y(_0172_)
  );
  NOT _0976_ (
    .A(_0810_),
    .Y(_0173_)
  );
  NOT _0977_ (
    .A(_0171_),
    .Y(_0174_)
  );
  NOT _0978_ (
    .A(_0813_),
    .Y(_0175_)
  );
  NOT _0979_ (
    .A(_0811_),
    .Y(_0176_)
  );
  NOT _0980_ (
    .A(_0106_),
    .Y(_0177_)
  );
  NOT _0981_ (
    .A(_0159_),
    .Y(_0178_)
  );
  NOT _0982_ (
    .A(_0141_),
    .Y(_0179_)
  );
  NOT _0983_ (
    .A(_0160_),
    .Y(_0180_)
  );
  NOT _0984_ (
    .A(_0169_),
    .Y(_0181_)
  );
  NOT _0985_ (
    .A(_0794_),
    .Y(_0182_)
  );
  NOT _0986_ (
    .A(_0802_),
    .Y(_0183_)
  );
  NOT _0987_ (
    .A(_0803_),
    .Y(_0184_)
  );
  NOT _0988_ (
    .A(_0805_),
    .Y(_0185_)
  );
  NOT _0989_ (
    .A(_0809_),
    .Y(_0186_)
  );
  NOT _0990_ (
    .A(_0800_),
    .Y(_0187_)
  );
  NOT _0991_ (
    .A(_0108_),
    .Y(_0188_)
  );
  NOT _0992_ (
    .A(_0107_),
    .Y(_0189_)
  );
  NOT _0993_ (
    .A(_0036_),
    .Y(_0190_)
  );
  NOT _0994_ (
    .A(_0037_),
    .Y(_0191_)
  );
  NOT _0995_ (
    .A(_0048_),
    .Y(_0192_)
  );
  NOT _0996_ (
    .A(_0059_),
    .Y(_0193_)
  );
  NOT _0997_ (
    .A(_0070_),
    .Y(_0194_)
  );
  NOT _0998_ (
    .A(_0081_),
    .Y(_0195_)
  );
  NOT _0999_ (
    .A(_0092_),
    .Y(_0196_)
  );
  NOT _1000_ (
    .A(_0097_),
    .Y(_0197_)
  );
  NOT _1001_ (
    .A(_0098_),
    .Y(_0198_)
  );
  NOT _1002_ (
    .A(_0099_),
    .Y(_0199_)
  );
  NOT _1003_ (
    .A(_0100_),
    .Y(_0200_)
  );
  NOT _1004_ (
    .A(_0038_),
    .Y(_0201_)
  );
  NOT _1005_ (
    .A(_0039_),
    .Y(_0202_)
  );
  NOT _1006_ (
    .A(_0040_),
    .Y(_0203_)
  );
  NOT _1007_ (
    .A(_0041_),
    .Y(_0204_)
  );
  NOT _1008_ (
    .A(_0042_),
    .Y(_0205_)
  );
  NOT _1009_ (
    .A(_0043_),
    .Y(_0206_)
  );
  NOT _1010_ (
    .A(_0044_),
    .Y(_0207_)
  );
  NOT _1011_ (
    .A(_0045_),
    .Y(_0208_)
  );
  NOT _1012_ (
    .A(_0046_),
    .Y(_0209_)
  );
  NOT _1013_ (
    .A(_0047_),
    .Y(_0210_)
  );
  NOT _1014_ (
    .A(_0049_),
    .Y(_0211_)
  );
  NOT _1015_ (
    .A(_0050_),
    .Y(_0212_)
  );
  NOT _1016_ (
    .A(_0051_),
    .Y(_0213_)
  );
  NOT _1017_ (
    .A(_0052_),
    .Y(_0214_)
  );
  NOT _1018_ (
    .A(_0053_),
    .Y(_0215_)
  );
  NOT _1019_ (
    .A(_0055_),
    .Y(_0216_)
  );
  NOT _1020_ (
    .A(_0056_),
    .Y(_0217_)
  );
  NOT _1021_ (
    .A(_0057_),
    .Y(_0218_)
  );
  NOT _1022_ (
    .A(_0060_),
    .Y(_0219_)
  );
  NOT _1023_ (
    .A(_0061_),
    .Y(_0220_)
  );
  NOT _1024_ (
    .A(_0089_),
    .Y(_0221_)
  );
  NOT _1025_ (
    .A(_0091_),
    .Y(_0222_)
  );
  NOT _1026_ (
    .A(_0120_),
    .Y(_0223_)
  );
  NOT _1027_ (
    .A(_0131_),
    .Y(_0224_)
  );
  NOT _1028_ (
    .A(_0134_),
    .Y(_0225_)
  );
  NOT _1029_ (
    .A(_0135_),
    .Y(_0226_)
  );
  NOT _1030_ (
    .A(_0136_),
    .Y(_0227_)
  );
  NOT _1031_ (
    .A(_0137_),
    .Y(_0228_)
  );
  NOT _1032_ (
    .A(_0138_),
    .Y(_0229_)
  );
  NOT _1033_ (
    .A(_0139_),
    .Y(_0230_)
  );
  NOT _1034_ (
    .A(_0140_),
    .Y(_0231_)
  );
  NOT _1035_ (
    .A(_0110_),
    .Y(_0232_)
  );
  NOT _1036_ (
    .A(_0111_),
    .Y(_0233_)
  );
  NOT _1037_ (
    .A(_0113_),
    .Y(_0234_)
  );
  NOT _1038_ (
    .A(_0114_),
    .Y(_0235_)
  );
  NOT _1039_ (
    .A(_0115_),
    .Y(_0236_)
  );
  NOT _1040_ (
    .A(_0116_),
    .Y(_0237_)
  );
  NOT _1041_ (
    .A(_0118_),
    .Y(_0238_)
  );
  NOT _1042_ (
    .A(_0119_),
    .Y(_0239_)
  );
  NOT _1043_ (
    .A(_0121_),
    .Y(_0240_)
  );
  NOT _1044_ (
    .A(_0122_),
    .Y(_0241_)
  );
  NOT _1045_ (
    .A(_0123_),
    .Y(_0242_)
  );
  NOT _1046_ (
    .A(_0124_),
    .Y(_0243_)
  );
  NOT _1047_ (
    .A(_0125_),
    .Y(_0244_)
  );
  NOT _1048_ (
    .A(_0126_),
    .Y(_0245_)
  );
  NOT _1049_ (
    .A(_0127_),
    .Y(_0246_)
  );
  NOT _1050_ (
    .A(_0128_),
    .Y(_0247_)
  );
  NOT _1051_ (
    .A(_0129_),
    .Y(_0248_)
  );
  NOT _1052_ (
    .A(_0130_),
    .Y(_0249_)
  );
  NOT _1053_ (
    .A(_0132_),
    .Y(_0250_)
  );
  NOT _1054_ (
    .A(_0133_),
    .Y(_0251_)
  );
  NOT _1055_ (
    .A(_0142_),
    .Y(_0252_)
  );
  NOT _1056_ (
    .A(_0150_),
    .Y(_0253_)
  );
  NOT _1057_ (
    .A(_0151_),
    .Y(_0254_)
  );
  NOT _1058_ (
    .A(_0153_),
    .Y(_0255_)
  );
  NOT _1059_ (
    .A(_0157_),
    .Y(_0256_)
  );
  NOT _1060_ (
    .A(_0148_),
    .Y(_0257_)
  );
  NOT _1061_ (
    .A(_0812_),
    .Y(_0258_)
  );
  NAND _1062_ (
    .A(_0170_),
    .B(_0171_),
    .Y(_0259_)
  );
  NAND _1063_ (
    .A(_0814_),
    .B(_0259_),
    .Y(_0260_)
  );
  NAND _1064_ (
    .A(_0106_),
    .B(_0168_),
    .Y(_0261_)
  );
  NOR _1065_ (
    .A(_0181_),
    .B(_0261_),
    .Y(_0262_)
  );
  NAND _1066_ (
    .A(_0813_),
    .B(_0262_),
    .Y(_0263_)
  );
  NAND _1067_ (
    .A(_0260_),
    .B(_0263_),
    .Y(_0264_)
  );
  NOT _1068_ (
    .A(_0264_),
    .Y(_0265_)
  );
  NOR _1069_ (
    .A(_0810_),
    .B(_0265_),
    .Y(_0167_)
  );
  NAND _1070_ (
    .A(_0811_),
    .B(_0178_),
    .Y(_0266_)
  );
  NOR _1071_ (
    .A(_0810_),
    .B(_0816_),
    .Y(_0267_)
  );
  NAND _1072_ (
    .A(_0266_),
    .B(_0267_),
    .Y(_0165_)
  );
  NOR _1073_ (
    .A(_0175_),
    .B(_0262_),
    .Y(_0268_)
  );
  NOR _1074_ (
    .A(_0815_),
    .B(_0268_),
    .Y(_0269_)
  );
  NOR _1075_ (
    .A(_0810_),
    .B(_0269_),
    .Y(_0166_)
  );
  NOR _1076_ (
    .A(_0813_),
    .B(_0811_),
    .Y(_0270_)
  );
  NAND _1077_ (
    .A(_0175_),
    .B(_0176_),
    .Y(_0271_)
  );
  NAND _1078_ (
    .A(_0168_),
    .B(_0270_),
    .Y(_0272_)
  );
  NAND _1079_ (
    .A(_0813_),
    .B(_0261_),
    .Y(_0273_)
  );
  NAND _1080_ (
    .A(_0272_),
    .B(_0273_),
    .Y(_0274_)
  );
  NOR _1081_ (
    .A(_0106_),
    .B(_0168_),
    .Y(_0275_)
  );
  NAND _1082_ (
    .A(_0173_),
    .B(_0274_),
    .Y(_0276_)
  );
  NOR _1083_ (
    .A(_0275_),
    .B(_0276_),
    .Y(_0015_)
  );
  NAND _1084_ (
    .A(_0181_),
    .B(_0261_),
    .Y(_0277_)
  );
  NOR _1085_ (
    .A(_0181_),
    .B(_0271_),
    .Y(_0278_)
  );
  NOR _1086_ (
    .A(_0268_),
    .B(_0278_),
    .Y(_0279_)
  );
  NAND _1087_ (
    .A(_0173_),
    .B(_0277_),
    .Y(_0280_)
  );
  NOR _1088_ (
    .A(_0279_),
    .B(_0280_),
    .Y(_0016_)
  );
  NOR _1089_ (
    .A(_0175_),
    .B(_0177_),
    .Y(_0281_)
  );
  NOR _1090_ (
    .A(_0813_),
    .B(_0176_),
    .Y(_0282_)
  );
  NOR _1091_ (
    .A(_0281_),
    .B(_0282_),
    .Y(_0283_)
  );
  NAND _1092_ (
    .A(_0794_),
    .B(_0283_),
    .Y(_0284_)
  );
  NAND _1093_ (
    .A(_0102_),
    .B(_0281_),
    .Y(_0285_)
  );
  NAND _1094_ (
    .A(_0284_),
    .B(_0285_),
    .Y(_0286_)
  );
  NOT _1095_ (
    .A(_0286_),
    .Y(_0287_)
  );
  NOR _1096_ (
    .A(_0810_),
    .B(_0287_),
    .Y(_0019_)
  );
  NAND _1097_ (
    .A(_0801_),
    .B(_0283_),
    .Y(_0288_)
  );
  NAND _1098_ (
    .A(_0103_),
    .B(_0281_),
    .Y(_0289_)
  );
  NAND _1099_ (
    .A(_0288_),
    .B(_0289_),
    .Y(_0290_)
  );
  NOT _1100_ (
    .A(_0290_),
    .Y(_0291_)
  );
  NOR _1101_ (
    .A(_0810_),
    .B(_0291_),
    .Y(_0026_)
  );
  NAND _1102_ (
    .A(_0802_),
    .B(_0283_),
    .Y(_0292_)
  );
  NAND _1103_ (
    .A(_0104_),
    .B(_0281_),
    .Y(_0293_)
  );
  NAND _1104_ (
    .A(_0292_),
    .B(_0293_),
    .Y(_0294_)
  );
  NOT _1105_ (
    .A(_0294_),
    .Y(_0295_)
  );
  NOR _1106_ (
    .A(_0810_),
    .B(_0295_),
    .Y(_0027_)
  );
  NAND _1107_ (
    .A(_0803_),
    .B(_0283_),
    .Y(_0296_)
  );
  NAND _1108_ (
    .A(_0105_),
    .B(_0281_),
    .Y(_0297_)
  );
  NAND _1109_ (
    .A(_0296_),
    .B(_0297_),
    .Y(_0298_)
  );
  NOT _1110_ (
    .A(_0298_),
    .Y(_0299_)
  );
  NOR _1111_ (
    .A(_0810_),
    .B(_0299_),
    .Y(_0028_)
  );
  NAND _1112_ (
    .A(_0804_),
    .B(_0283_),
    .Y(_0300_)
  );
  NAND _1113_ (
    .A(_0794_),
    .B(_0281_),
    .Y(_0301_)
  );
  NAND _1114_ (
    .A(_0300_),
    .B(_0301_),
    .Y(_0302_)
  );
  NOT _1115_ (
    .A(_0302_),
    .Y(_0303_)
  );
  NOR _1116_ (
    .A(_0810_),
    .B(_0303_),
    .Y(_0029_)
  );
  NAND _1117_ (
    .A(_0805_),
    .B(_0283_),
    .Y(_0304_)
  );
  NAND _1118_ (
    .A(_0801_),
    .B(_0281_),
    .Y(_0305_)
  );
  NAND _1119_ (
    .A(_0304_),
    .B(_0305_),
    .Y(_0306_)
  );
  NOT _1120_ (
    .A(_0306_),
    .Y(_0307_)
  );
  NOR _1121_ (
    .A(_0810_),
    .B(_0307_),
    .Y(_0030_)
  );
  NAND _1122_ (
    .A(_0806_),
    .B(_0283_),
    .Y(_0308_)
  );
  NAND _1123_ (
    .A(_0802_),
    .B(_0281_),
    .Y(_0309_)
  );
  NAND _1124_ (
    .A(_0308_),
    .B(_0309_),
    .Y(_0310_)
  );
  NOT _1125_ (
    .A(_0310_),
    .Y(_0311_)
  );
  NOR _1126_ (
    .A(_0810_),
    .B(_0311_),
    .Y(_0031_)
  );
  NAND _1127_ (
    .A(_0807_),
    .B(_0283_),
    .Y(_0312_)
  );
  NAND _1128_ (
    .A(_0803_),
    .B(_0281_),
    .Y(_0313_)
  );
  NAND _1129_ (
    .A(_0312_),
    .B(_0313_),
    .Y(_0314_)
  );
  NOT _1130_ (
    .A(_0314_),
    .Y(_0315_)
  );
  NOR _1131_ (
    .A(_0810_),
    .B(_0315_),
    .Y(_0032_)
  );
  NAND _1132_ (
    .A(_0808_),
    .B(_0283_),
    .Y(_0316_)
  );
  NAND _1133_ (
    .A(_0804_),
    .B(_0281_),
    .Y(_0317_)
  );
  NAND _1134_ (
    .A(_0316_),
    .B(_0317_),
    .Y(_0318_)
  );
  NOT _1135_ (
    .A(_0318_),
    .Y(_0319_)
  );
  NOR _1136_ (
    .A(_0810_),
    .B(_0319_),
    .Y(_0033_)
  );
  NAND _1137_ (
    .A(_0809_),
    .B(_0283_),
    .Y(_0320_)
  );
  NAND _1138_ (
    .A(_0805_),
    .B(_0281_),
    .Y(_0321_)
  );
  NAND _1139_ (
    .A(_0320_),
    .B(_0321_),
    .Y(_0322_)
  );
  NOT _1140_ (
    .A(_0322_),
    .Y(_0323_)
  );
  NOR _1141_ (
    .A(_0810_),
    .B(_0323_),
    .Y(_0034_)
  );
  NAND _1142_ (
    .A(_0795_),
    .B(_0283_),
    .Y(_0324_)
  );
  NAND _1143_ (
    .A(_0806_),
    .B(_0281_),
    .Y(_0325_)
  );
  NAND _1144_ (
    .A(_0324_),
    .B(_0325_),
    .Y(_0326_)
  );
  NOT _1145_ (
    .A(_0326_),
    .Y(_0327_)
  );
  NOR _1146_ (
    .A(_0810_),
    .B(_0327_),
    .Y(_0020_)
  );
  NAND _1147_ (
    .A(_0796_),
    .B(_0283_),
    .Y(_0328_)
  );
  NAND _1148_ (
    .A(_0807_),
    .B(_0281_),
    .Y(_0329_)
  );
  NAND _1149_ (
    .A(_0328_),
    .B(_0329_),
    .Y(_0330_)
  );
  NOT _1150_ (
    .A(_0330_),
    .Y(_0331_)
  );
  NOR _1151_ (
    .A(_0810_),
    .B(_0331_),
    .Y(_0021_)
  );
  NAND _1152_ (
    .A(_0797_),
    .B(_0283_),
    .Y(_0332_)
  );
  NAND _1153_ (
    .A(_0808_),
    .B(_0281_),
    .Y(_0333_)
  );
  NAND _1154_ (
    .A(_0332_),
    .B(_0333_),
    .Y(_0334_)
  );
  NOT _1155_ (
    .A(_0334_),
    .Y(_0335_)
  );
  NOR _1156_ (
    .A(_0810_),
    .B(_0335_),
    .Y(_0022_)
  );
  NAND _1157_ (
    .A(_0798_),
    .B(_0283_),
    .Y(_0336_)
  );
  NAND _1158_ (
    .A(_0809_),
    .B(_0281_),
    .Y(_0337_)
  );
  NAND _1159_ (
    .A(_0336_),
    .B(_0337_),
    .Y(_0338_)
  );
  NOT _1160_ (
    .A(_0338_),
    .Y(_0339_)
  );
  NOR _1161_ (
    .A(_0810_),
    .B(_0339_),
    .Y(_0023_)
  );
  NAND _1162_ (
    .A(_0799_),
    .B(_0283_),
    .Y(_0340_)
  );
  NAND _1163_ (
    .A(_0795_),
    .B(_0281_),
    .Y(_0341_)
  );
  NAND _1164_ (
    .A(_0340_),
    .B(_0341_),
    .Y(_0342_)
  );
  NOT _1165_ (
    .A(_0342_),
    .Y(_0343_)
  );
  NOR _1166_ (
    .A(_0810_),
    .B(_0343_),
    .Y(_0024_)
  );
  NAND _1167_ (
    .A(_0800_),
    .B(_0283_),
    .Y(_0344_)
  );
  NAND _1168_ (
    .A(_0796_),
    .B(_0281_),
    .Y(_0345_)
  );
  NAND _1169_ (
    .A(_0344_),
    .B(_0345_),
    .Y(_0346_)
  );
  NOT _1170_ (
    .A(_0346_),
    .Y(_0347_)
  );
  NOR _1171_ (
    .A(_0810_),
    .B(_0347_),
    .Y(_0025_)
  );
  NOR _1172_ (
    .A(_0176_),
    .B(_0814_),
    .Y(_0348_)
  );
  NOR _1173_ (
    .A(_0810_),
    .B(_0348_),
    .Y(_0349_)
  );
  NOT _1174_ (
    .A(_0349_),
    .Y(_0350_)
  );
  NOR _1175_ (
    .A(_0170_),
    .B(_0814_),
    .Y(_0351_)
  );
  NAND _1176_ (
    .A(_0170_),
    .B(_0814_),
    .Y(_0352_)
  );
  NAND _1177_ (
    .A(_0349_),
    .B(_0352_),
    .Y(_0353_)
  );
  NOR _1178_ (
    .A(_0351_),
    .B(_0353_),
    .Y(_0017_)
  );
  NOR _1179_ (
    .A(_0174_),
    .B(_0352_),
    .Y(_0354_)
  );
  NAND _1180_ (
    .A(_0174_),
    .B(_0352_),
    .Y(_0355_)
  );
  NAND _1181_ (
    .A(_0349_),
    .B(_0355_),
    .Y(_0356_)
  );
  NOR _1182_ (
    .A(_0354_),
    .B(_0356_),
    .Y(_0018_)
  );
  NOR _1183_ (
    .A(_0179_),
    .B(_0180_),
    .Y(_0357_)
  );
  NAND _1184_ (
    .A(_0219_),
    .B(_0132_),
    .Y(_0358_)
  );
  NAND _1185_ (
    .A(_0220_),
    .B(_0133_),
    .Y(_0359_)
  );
  NAND _1186_ (
    .A(_0358_),
    .B(_0359_),
    .Y(_0360_)
  );
  NOR _1187_ (
    .A(_0220_),
    .B(_0133_),
    .Y(_0361_)
  );
  NAND _1188_ (
    .A(_0061_),
    .B(_0251_),
    .Y(_0362_)
  );
  NAND _1189_ (
    .A(_0060_),
    .B(_0250_),
    .Y(_0363_)
  );
  NAND _1190_ (
    .A(_0058_),
    .B(_0249_),
    .Y(_0364_)
  );
  NAND _1191_ (
    .A(_0362_),
    .B(_0363_),
    .Y(_0365_)
  );
  NOR _1192_ (
    .A(_0360_),
    .B(_0365_),
    .Y(_0366_)
  );
  NAND _1193_ (
    .A(_0364_),
    .B(_0366_),
    .Y(_0367_)
  );
  NOR _1194_ (
    .A(_0057_),
    .B(_0248_),
    .Y(_0368_)
  );
  NOR _1195_ (
    .A(_0058_),
    .B(_0249_),
    .Y(_0369_)
  );
  NOR _1196_ (
    .A(_0368_),
    .B(_0369_),
    .Y(_0370_)
  );
  NOR _1197_ (
    .A(_0218_),
    .B(_0129_),
    .Y(_0371_)
  );
  NOR _1198_ (
    .A(_0367_),
    .B(_0371_),
    .Y(_0372_)
  );
  NAND _1199_ (
    .A(_0370_),
    .B(_0372_),
    .Y(_0373_)
  );
  NAND _1200_ (
    .A(_0217_),
    .B(_0128_),
    .Y(_0374_)
  );
  NAND _1201_ (
    .A(_0056_),
    .B(_0247_),
    .Y(_0375_)
  );
  NAND _1202_ (
    .A(_0374_),
    .B(_0375_),
    .Y(_0376_)
  );
  NOR _1203_ (
    .A(_0055_),
    .B(_0246_),
    .Y(_0377_)
  );
  NAND _1204_ (
    .A(_0216_),
    .B(_0127_),
    .Y(_0378_)
  );
  NAND _1205_ (
    .A(_0055_),
    .B(_0246_),
    .Y(_0379_)
  );
  NAND _1206_ (
    .A(_0378_),
    .B(_0379_),
    .Y(_0380_)
  );
  NOR _1207_ (
    .A(_0376_),
    .B(_0380_),
    .Y(_0381_)
  );
  NOR _1208_ (
    .A(_0053_),
    .B(_0244_),
    .Y(_0382_)
  );
  NOR _1209_ (
    .A(_0054_),
    .B(_0245_),
    .Y(_0383_)
  );
  NOR _1210_ (
    .A(_0382_),
    .B(_0383_),
    .Y(_0384_)
  );
  NAND _1211_ (
    .A(_0054_),
    .B(_0245_),
    .Y(_0385_)
  );
  NOR _1212_ (
    .A(_0215_),
    .B(_0125_),
    .Y(_0386_)
  );
  NAND _1213_ (
    .A(_0384_),
    .B(_0385_),
    .Y(_0387_)
  );
  NOR _1214_ (
    .A(_0386_),
    .B(_0387_),
    .Y(_0388_)
  );
  NAND _1215_ (
    .A(_0381_),
    .B(_0388_),
    .Y(_0389_)
  );
  NOR _1216_ (
    .A(_0373_),
    .B(_0389_),
    .Y(_0390_)
  );
  NOR _1217_ (
    .A(_0212_),
    .B(_0122_),
    .Y(_0391_)
  );
  NAND _1218_ (
    .A(_0214_),
    .B(_0124_),
    .Y(_0392_)
  );
  NOR _1219_ (
    .A(_0051_),
    .B(_0242_),
    .Y(_0393_)
  );
  NOR _1220_ (
    .A(_0213_),
    .B(_0123_),
    .Y(_0394_)
  );
  NOR _1221_ (
    .A(_0393_),
    .B(_0394_),
    .Y(_0395_)
  );
  NAND _1222_ (
    .A(_0052_),
    .B(_0243_),
    .Y(_0396_)
  );
  NAND _1223_ (
    .A(_0392_),
    .B(_0396_),
    .Y(_0397_)
  );
  NOR _1224_ (
    .A(_0391_),
    .B(_0397_),
    .Y(_0398_)
  );
  NAND _1225_ (
    .A(_0395_),
    .B(_0398_),
    .Y(_0399_)
  );
  NOR _1226_ (
    .A(_0049_),
    .B(_0240_),
    .Y(_0400_)
  );
  NOR _1227_ (
    .A(_0050_),
    .B(_0241_),
    .Y(_0401_)
  );
  NOR _1228_ (
    .A(_0400_),
    .B(_0401_),
    .Y(_0402_)
  );
  NOR _1229_ (
    .A(_0211_),
    .B(_0121_),
    .Y(_0403_)
  );
  NOR _1230_ (
    .A(_0399_),
    .B(_0403_),
    .Y(_0404_)
  );
  NAND _1231_ (
    .A(_0402_),
    .B(_0404_),
    .Y(_0405_)
  );
  NOT _1232_ (
    .A(_0405_),
    .Y(_0406_)
  );
  NOR _1233_ (
    .A(_0208_),
    .B(_0117_),
    .Y(_0407_)
  );
  NOR _1234_ (
    .A(_0209_),
    .B(_0118_),
    .Y(_0408_)
  );
  NOR _1235_ (
    .A(_0210_),
    .B(_0119_),
    .Y(_0409_)
  );
  NOR _1236_ (
    .A(_0047_),
    .B(_0239_),
    .Y(_0410_)
  );
  NOR _1237_ (
    .A(_0046_),
    .B(_0238_),
    .Y(_0411_)
  );
  NAND _1238_ (
    .A(_0209_),
    .B(_0118_),
    .Y(_0412_)
  );
  NOR _1239_ (
    .A(_0409_),
    .B(_0410_),
    .Y(_0413_)
  );
  NOR _1240_ (
    .A(_0408_),
    .B(_0411_),
    .Y(_0414_)
  );
  NAND _1241_ (
    .A(_0413_),
    .B(_0414_),
    .Y(_0415_)
  );
  NOR _1242_ (
    .A(_0407_),
    .B(_0415_),
    .Y(_0416_)
  );
  NAND _1243_ (
    .A(_0207_),
    .B(_0116_),
    .Y(_0417_)
  );
  NAND _1244_ (
    .A(_0208_),
    .B(_0117_),
    .Y(_0418_)
  );
  NAND _1245_ (
    .A(_0417_),
    .B(_0418_),
    .Y(_0419_)
  );
  NAND _1246_ (
    .A(_0044_),
    .B(_0237_),
    .Y(_0420_)
  );
  NAND _1247_ (
    .A(_0416_),
    .B(_0420_),
    .Y(_0421_)
  );
  NOR _1248_ (
    .A(_0405_),
    .B(_0421_),
    .Y(_0422_)
  );
  NAND _1249_ (
    .A(_0390_),
    .B(_0422_),
    .Y(_0423_)
  );
  NOR _1250_ (
    .A(_0419_),
    .B(_0423_),
    .Y(_0424_)
  );
  NOT _1251_ (
    .A(_0424_),
    .Y(_0425_)
  );
  NOR _1252_ (
    .A(_0042_),
    .B(_0235_),
    .Y(_0426_)
  );
  NAND _1253_ (
    .A(_0205_),
    .B(_0114_),
    .Y(_0427_)
  );
  NOR _1254_ (
    .A(_0043_),
    .B(_0236_),
    .Y(_0428_)
  );
  NAND _1255_ (
    .A(_0206_),
    .B(_0115_),
    .Y(_0429_)
  );
  NOR _1256_ (
    .A(_0426_),
    .B(_0428_),
    .Y(_0430_)
  );
  NAND _1257_ (
    .A(_0427_),
    .B(_0429_),
    .Y(_0431_)
  );
  NOR _1258_ (
    .A(_0206_),
    .B(_0115_),
    .Y(_0432_)
  );
  NAND _1259_ (
    .A(_0043_),
    .B(_0236_),
    .Y(_0433_)
  );
  NAND _1260_ (
    .A(_0042_),
    .B(_0235_),
    .Y(_0434_)
  );
  NAND _1261_ (
    .A(_0041_),
    .B(_0234_),
    .Y(_0435_)
  );
  NAND _1262_ (
    .A(_0433_),
    .B(_0434_),
    .Y(_0436_)
  );
  NOR _1263_ (
    .A(_0431_),
    .B(_0436_),
    .Y(_0437_)
  );
  NAND _1264_ (
    .A(_0435_),
    .B(_0437_),
    .Y(_0438_)
  );
  NOT _1265_ (
    .A(_0438_),
    .Y(_0439_)
  );
  NAND _1266_ (
    .A(_0203_),
    .B(_0112_),
    .Y(_0440_)
  );
  NAND _1267_ (
    .A(_0204_),
    .B(_0113_),
    .Y(_0441_)
  );
  NAND _1268_ (
    .A(_0440_),
    .B(_0441_),
    .Y(_0442_)
  );
  NOT _1269_ (
    .A(_0442_),
    .Y(_0443_)
  );
  NOR _1270_ (
    .A(_0203_),
    .B(_0112_),
    .Y(_0444_)
  );
  NOR _1271_ (
    .A(_0442_),
    .B(_0444_),
    .Y(_0445_)
  );
  NAND _1272_ (
    .A(_0439_),
    .B(_0445_),
    .Y(_0446_)
  );
  NOT _1273_ (
    .A(_0446_),
    .Y(_0447_)
  );
  NOR _1274_ (
    .A(_0039_),
    .B(_0233_),
    .Y(_0448_)
  );
  NAND _1275_ (
    .A(_0202_),
    .B(_0111_),
    .Y(_0449_)
  );
  NAND _1276_ (
    .A(_0038_),
    .B(_0232_),
    .Y(_0450_)
  );
  NAND _1277_ (
    .A(_0449_),
    .B(_0450_),
    .Y(_0451_)
  );
  NAND _1278_ (
    .A(_0100_),
    .B(_0231_),
    .Y(_0452_)
  );
  NOR _1279_ (
    .A(_0202_),
    .B(_0111_),
    .Y(_0453_)
  );
  NAND _1280_ (
    .A(_0039_),
    .B(_0233_),
    .Y(_0454_)
  );
  NOR _1281_ (
    .A(_0038_),
    .B(_0232_),
    .Y(_0455_)
  );
  NAND _1282_ (
    .A(_0201_),
    .B(_0110_),
    .Y(_0456_)
  );
  NOR _1283_ (
    .A(_0453_),
    .B(_0455_),
    .Y(_0457_)
  );
  NAND _1284_ (
    .A(_0452_),
    .B(_0457_),
    .Y(_0458_)
  );
  NAND _1285_ (
    .A(_0449_),
    .B(_0454_),
    .Y(_0459_)
  );
  NAND _1286_ (
    .A(_0450_),
    .B(_0456_),
    .Y(_0460_)
  );
  NOR _1287_ (
    .A(_0459_),
    .B(_0460_),
    .Y(_0461_)
  );
  NOR _1288_ (
    .A(_0451_),
    .B(_0458_),
    .Y(_0462_)
  );
  NAND _1289_ (
    .A(_0452_),
    .B(_0461_),
    .Y(_0463_)
  );
  NOR _1290_ (
    .A(_0099_),
    .B(_0230_),
    .Y(_0464_)
  );
  NAND _1291_ (
    .A(_0199_),
    .B(_0139_),
    .Y(_0465_)
  );
  NOR _1292_ (
    .A(_0100_),
    .B(_0231_),
    .Y(_0466_)
  );
  NAND _1293_ (
    .A(_0200_),
    .B(_0140_),
    .Y(_0467_)
  );
  NOR _1294_ (
    .A(_0464_),
    .B(_0466_),
    .Y(_0468_)
  );
  NAND _1295_ (
    .A(_0465_),
    .B(_0467_),
    .Y(_0469_)
  );
  NOR _1296_ (
    .A(_0199_),
    .B(_0139_),
    .Y(_0470_)
  );
  NAND _1297_ (
    .A(_0099_),
    .B(_0230_),
    .Y(_0471_)
  );
  NOR _1298_ (
    .A(_0469_),
    .B(_0470_),
    .Y(_0472_)
  );
  NAND _1299_ (
    .A(_0468_),
    .B(_0471_),
    .Y(_0473_)
  );
  NOR _1300_ (
    .A(_0463_),
    .B(_0473_),
    .Y(_0474_)
  );
  NAND _1301_ (
    .A(_0462_),
    .B(_0472_),
    .Y(_0475_)
  );
  NOR _1302_ (
    .A(_0097_),
    .B(_0228_),
    .Y(_0476_)
  );
  NAND _1303_ (
    .A(_0197_),
    .B(_0137_),
    .Y(_0477_)
  );
  NOR _1304_ (
    .A(_0098_),
    .B(_0229_),
    .Y(_0478_)
  );
  NAND _1305_ (
    .A(_0198_),
    .B(_0138_),
    .Y(_0479_)
  );
  NOR _1306_ (
    .A(_0476_),
    .B(_0478_),
    .Y(_0480_)
  );
  NAND _1307_ (
    .A(_0477_),
    .B(_0479_),
    .Y(_0481_)
  );
  NOR _1308_ (
    .A(_0198_),
    .B(_0138_),
    .Y(_0482_)
  );
  NAND _1309_ (
    .A(_0098_),
    .B(_0229_),
    .Y(_0483_)
  );
  NAND _1310_ (
    .A(_0097_),
    .B(_0228_),
    .Y(_0484_)
  );
  NAND _1311_ (
    .A(_0092_),
    .B(_0227_),
    .Y(_0485_)
  );
  NAND _1312_ (
    .A(_0483_),
    .B(_0484_),
    .Y(_0486_)
  );
  NOR _1313_ (
    .A(_0481_),
    .B(_0486_),
    .Y(_0487_)
  );
  NAND _1314_ (
    .A(_0477_),
    .B(_0484_),
    .Y(_0488_)
  );
  NOR _1315_ (
    .A(_0478_),
    .B(_0482_),
    .Y(_0489_)
  );
  NAND _1316_ (
    .A(_0485_),
    .B(_0489_),
    .Y(_0490_)
  );
  NOR _1317_ (
    .A(_0488_),
    .B(_0490_),
    .Y(_0491_)
  );
  NAND _1318_ (
    .A(_0485_),
    .B(_0487_),
    .Y(_0492_)
  );
  NOR _1319_ (
    .A(_0081_),
    .B(_0226_),
    .Y(_0493_)
  );
  NAND _1320_ (
    .A(_0195_),
    .B(_0135_),
    .Y(_0494_)
  );
  NOR _1321_ (
    .A(_0092_),
    .B(_0227_),
    .Y(_0495_)
  );
  NAND _1322_ (
    .A(_0196_),
    .B(_0136_),
    .Y(_0496_)
  );
  NOR _1323_ (
    .A(_0493_),
    .B(_0495_),
    .Y(_0497_)
  );
  NAND _1324_ (
    .A(_0494_),
    .B(_0496_),
    .Y(_0498_)
  );
  NOR _1325_ (
    .A(_0492_),
    .B(_0497_),
    .Y(_0499_)
  );
  NAND _1326_ (
    .A(_0491_),
    .B(_0498_),
    .Y(_0500_)
  );
  NOR _1327_ (
    .A(_0480_),
    .B(_0482_),
    .Y(_0501_)
  );
  NAND _1328_ (
    .A(_0481_),
    .B(_0483_),
    .Y(_0502_)
  );
  NOR _1329_ (
    .A(_0499_),
    .B(_0501_),
    .Y(_0503_)
  );
  NAND _1330_ (
    .A(_0500_),
    .B(_0502_),
    .Y(_0504_)
  );
  NOR _1331_ (
    .A(_0475_),
    .B(_0503_),
    .Y(_0505_)
  );
  NAND _1332_ (
    .A(_0474_),
    .B(_0504_),
    .Y(_0506_)
  );
  NOR _1333_ (
    .A(_0463_),
    .B(_0468_),
    .Y(_0507_)
  );
  NAND _1334_ (
    .A(_0462_),
    .B(_0469_),
    .Y(_0508_)
  );
  NOR _1335_ (
    .A(_0453_),
    .B(_0456_),
    .Y(_0509_)
  );
  NAND _1336_ (
    .A(_0454_),
    .B(_0455_),
    .Y(_0510_)
  );
  NOR _1337_ (
    .A(_0448_),
    .B(_0509_),
    .Y(_0511_)
  );
  NAND _1338_ (
    .A(_0449_),
    .B(_0510_),
    .Y(_0512_)
  );
  NOR _1339_ (
    .A(_0507_),
    .B(_0512_),
    .Y(_0513_)
  );
  NAND _1340_ (
    .A(_0508_),
    .B(_0511_),
    .Y(_0514_)
  );
  NOR _1341_ (
    .A(_0194_),
    .B(_0134_),
    .Y(_0515_)
  );
  NAND _1342_ (
    .A(_0070_),
    .B(_0225_),
    .Y(_0516_)
  );
  NOR _1343_ (
    .A(_0070_),
    .B(_0225_),
    .Y(_0517_)
  );
  NAND _1344_ (
    .A(_0194_),
    .B(_0134_),
    .Y(_0518_)
  );
  NAND _1345_ (
    .A(_0516_),
    .B(_0518_),
    .Y(_0519_)
  );
  NOR _1346_ (
    .A(_0059_),
    .B(_0224_),
    .Y(_0520_)
  );
  NAND _1347_ (
    .A(_0193_),
    .B(_0131_),
    .Y(_0521_)
  );
  NAND _1348_ (
    .A(_0059_),
    .B(_0224_),
    .Y(_0522_)
  );
  NAND _1349_ (
    .A(_0521_),
    .B(_0522_),
    .Y(_0523_)
  );
  NOR _1350_ (
    .A(_0519_),
    .B(_0523_),
    .Y(_0524_)
  );
  NOT _1351_ (
    .A(_0524_),
    .Y(_0525_)
  );
  NOR _1352_ (
    .A(_0048_),
    .B(_0223_),
    .Y(_0526_)
  );
  NAND _1353_ (
    .A(_0192_),
    .B(_0120_),
    .Y(_0527_)
  );
  NAND _1354_ (
    .A(_0048_),
    .B(_0223_),
    .Y(_0528_)
  );
  NOR _1355_ (
    .A(_0191_),
    .B(_0109_),
    .Y(_0529_)
  );
  NOR _1356_ (
    .A(_0526_),
    .B(_0529_),
    .Y(_0530_)
  );
  NAND _1357_ (
    .A(_0527_),
    .B(_0528_),
    .Y(_0531_)
  );
  NOR _1358_ (
    .A(_0529_),
    .B(_0531_),
    .Y(_0532_)
  );
  NAND _1359_ (
    .A(_0528_),
    .B(_0530_),
    .Y(_0533_)
  );
  NOR _1360_ (
    .A(_0526_),
    .B(_0532_),
    .Y(_0534_)
  );
  NAND _1361_ (
    .A(_0527_),
    .B(_0533_),
    .Y(_0535_)
  );
  NOR _1362_ (
    .A(_0525_),
    .B(_0534_),
    .Y(_0536_)
  );
  NAND _1363_ (
    .A(_0524_),
    .B(_0535_),
    .Y(_0537_)
  );
  NOR _1364_ (
    .A(_0515_),
    .B(_0521_),
    .Y(_0538_)
  );
  NAND _1365_ (
    .A(_0516_),
    .B(_0520_),
    .Y(_0539_)
  );
  NOR _1366_ (
    .A(_0517_),
    .B(_0538_),
    .Y(_0540_)
  );
  NAND _1367_ (
    .A(_0518_),
    .B(_0539_),
    .Y(_0541_)
  );
  NOR _1368_ (
    .A(_0536_),
    .B(_0541_),
    .Y(_0542_)
  );
  NAND _1369_ (
    .A(_0537_),
    .B(_0540_),
    .Y(_0543_)
  );
  NOR _1370_ (
    .A(_0195_),
    .B(_0135_),
    .Y(_0544_)
  );
  NAND _1371_ (
    .A(_0081_),
    .B(_0226_),
    .Y(_0545_)
  );
  NOR _1372_ (
    .A(_0498_),
    .B(_0544_),
    .Y(_0546_)
  );
  NAND _1373_ (
    .A(_0497_),
    .B(_0545_),
    .Y(_0547_)
  );
  NOR _1374_ (
    .A(_0492_),
    .B(_0547_),
    .Y(_0548_)
  );
  NAND _1375_ (
    .A(_0491_),
    .B(_0546_),
    .Y(_0549_)
  );
  NOR _1376_ (
    .A(_0475_),
    .B(_0549_),
    .Y(_0550_)
  );
  NAND _1377_ (
    .A(_0474_),
    .B(_0548_),
    .Y(_0551_)
  );
  NOR _1378_ (
    .A(_0542_),
    .B(_0551_),
    .Y(_0552_)
  );
  NAND _1379_ (
    .A(_0543_),
    .B(_0550_),
    .Y(_0553_)
  );
  NOR _1380_ (
    .A(_0514_),
    .B(_0552_),
    .Y(_0554_)
  );
  NAND _1381_ (
    .A(_0513_),
    .B(_0553_),
    .Y(_0555_)
  );
  NOR _1382_ (
    .A(_0505_),
    .B(_0555_),
    .Y(_0556_)
  );
  NAND _1383_ (
    .A(_0506_),
    .B(_0554_),
    .Y(_0557_)
  );
  NOR _1384_ (
    .A(_0446_),
    .B(_0556_),
    .Y(_0558_)
  );
  NAND _1385_ (
    .A(_0447_),
    .B(_0557_),
    .Y(_0559_)
  );
  NOR _1386_ (
    .A(_0438_),
    .B(_0443_),
    .Y(_0560_)
  );
  NAND _1387_ (
    .A(_0439_),
    .B(_0442_),
    .Y(_0561_)
  );
  NOR _1388_ (
    .A(_0430_),
    .B(_0432_),
    .Y(_0562_)
  );
  NAND _1389_ (
    .A(_0431_),
    .B(_0433_),
    .Y(_0563_)
  );
  NOR _1390_ (
    .A(_0560_),
    .B(_0562_),
    .Y(_0564_)
  );
  NAND _1391_ (
    .A(_0561_),
    .B(_0563_),
    .Y(_0565_)
  );
  NOR _1392_ (
    .A(_0558_),
    .B(_0565_),
    .Y(_0566_)
  );
  NAND _1393_ (
    .A(_0559_),
    .B(_0564_),
    .Y(_0567_)
  );
  NOR _1394_ (
    .A(_0425_),
    .B(_0566_),
    .Y(_0568_)
  );
  NAND _1395_ (
    .A(_0424_),
    .B(_0567_),
    .Y(_0569_)
  );
  NAND _1396_ (
    .A(_0416_),
    .B(_0419_),
    .Y(_0570_)
  );
  NOR _1397_ (
    .A(_0409_),
    .B(_0412_),
    .Y(_0571_)
  );
  NOR _1398_ (
    .A(_0410_),
    .B(_0571_),
    .Y(_0572_)
  );
  NAND _1399_ (
    .A(_0570_),
    .B(_0572_),
    .Y(_0573_)
  );
  NAND _1400_ (
    .A(_0406_),
    .B(_0573_),
    .Y(_0574_)
  );
  NOR _1401_ (
    .A(_0399_),
    .B(_0402_),
    .Y(_0575_)
  );
  NAND _1402_ (
    .A(_0393_),
    .B(_0396_),
    .Y(_0576_)
  );
  NAND _1403_ (
    .A(_0392_),
    .B(_0576_),
    .Y(_0577_)
  );
  NOR _1404_ (
    .A(_0575_),
    .B(_0577_),
    .Y(_0578_)
  );
  NAND _1405_ (
    .A(_0574_),
    .B(_0578_),
    .Y(_0579_)
  );
  NAND _1406_ (
    .A(_0390_),
    .B(_0579_),
    .Y(_0580_)
  );
  NAND _1407_ (
    .A(_0375_),
    .B(_0377_),
    .Y(_0581_)
  );
  NAND _1408_ (
    .A(_0374_),
    .B(_0581_),
    .Y(_0582_)
  );
  NAND _1409_ (
    .A(_0381_),
    .B(_0385_),
    .Y(_0583_)
  );
  NOR _1410_ (
    .A(_0384_),
    .B(_0583_),
    .Y(_0584_)
  );
  NOR _1411_ (
    .A(_0582_),
    .B(_0584_),
    .Y(_0585_)
  );
  NOR _1412_ (
    .A(_0373_),
    .B(_0585_),
    .Y(_0586_)
  );
  NOR _1413_ (
    .A(_0367_),
    .B(_0370_),
    .Y(_0587_)
  );
  NOR _1414_ (
    .A(_0358_),
    .B(_0361_),
    .Y(_0588_)
  );
  NOR _1415_ (
    .A(_0587_),
    .B(_0588_),
    .Y(_0589_)
  );
  NAND _1416_ (
    .A(_0359_),
    .B(_0589_),
    .Y(_0590_)
  );
  NOR _1417_ (
    .A(_0586_),
    .B(_0590_),
    .Y(_0591_)
  );
  NAND _1418_ (
    .A(_0580_),
    .B(_0591_),
    .Y(_0592_)
  );
  NOT _1419_ (
    .A(_0592_),
    .Y(_0593_)
  );
  NOR _1420_ (
    .A(_0568_),
    .B(_0592_),
    .Y(_0594_)
  );
  NAND _1421_ (
    .A(_0569_),
    .B(_0593_),
    .Y(_0595_)
  );
  NAND _1422_ (
    .A(_0191_),
    .B(_0109_),
    .Y(_0596_)
  );
  NAND _1423_ (
    .A(_0524_),
    .B(_0596_),
    .Y(_0597_)
  );
  NOR _1424_ (
    .A(_0533_),
    .B(_0597_),
    .Y(_0598_)
  );
  NAND _1425_ (
    .A(_0550_),
    .B(_0598_),
    .Y(_0599_)
  );
  NOR _1426_ (
    .A(_0446_),
    .B(_0599_),
    .Y(_0600_)
  );
  NAND _1427_ (
    .A(_0424_),
    .B(_0600_),
    .Y(_0601_)
  );
  NOR _1428_ (
    .A(_0084_),
    .B(_0085_),
    .Y(_0602_)
  );
  NOR _1429_ (
    .A(_0086_),
    .B(_0087_),
    .Y(_0603_)
  );
  NAND _1430_ (
    .A(_0602_),
    .B(_0603_),
    .Y(_0604_)
  );
  NOR _1431_ (
    .A(_0079_),
    .B(_0080_),
    .Y(_0605_)
  );
  NOR _1432_ (
    .A(_0082_),
    .B(_0083_),
    .Y(_0606_)
  );
  NAND _1433_ (
    .A(_0605_),
    .B(_0606_),
    .Y(_0607_)
  );
  NOR _1434_ (
    .A(_0604_),
    .B(_0607_),
    .Y(_0608_)
  );
  NOR _1435_ (
    .A(_0093_),
    .B(_0094_),
    .Y(_0609_)
  );
  NOR _1436_ (
    .A(_0095_),
    .B(_0096_),
    .Y(_0610_)
  );
  NAND _1437_ (
    .A(_0609_),
    .B(_0610_),
    .Y(_0611_)
  );
  NOR _1438_ (
    .A(_0088_),
    .B(_0089_),
    .Y(_0612_)
  );
  NOR _1439_ (
    .A(_0090_),
    .B(_0091_),
    .Y(_0613_)
  );
  NAND _1440_ (
    .A(_0612_),
    .B(_0613_),
    .Y(_0614_)
  );
  NOR _1441_ (
    .A(_0611_),
    .B(_0614_),
    .Y(_0615_)
  );
  NAND _1442_ (
    .A(_0608_),
    .B(_0615_),
    .Y(_0616_)
  );
  NOR _1443_ (
    .A(_0066_),
    .B(_0067_),
    .Y(_0617_)
  );
  NOR _1444_ (
    .A(_0068_),
    .B(_0069_),
    .Y(_0618_)
  );
  NAND _1445_ (
    .A(_0617_),
    .B(_0618_),
    .Y(_0619_)
  );
  NOR _1446_ (
    .A(_0062_),
    .B(_0063_),
    .Y(_0620_)
  );
  NOR _1447_ (
    .A(_0064_),
    .B(_0065_),
    .Y(_0621_)
  );
  NAND _1448_ (
    .A(_0620_),
    .B(_0621_),
    .Y(_0622_)
  );
  NOR _1449_ (
    .A(_0619_),
    .B(_0622_),
    .Y(_0623_)
  );
  NOR _1450_ (
    .A(_0075_),
    .B(_0076_),
    .Y(_0624_)
  );
  NOR _1451_ (
    .A(_0077_),
    .B(_0078_),
    .Y(_0625_)
  );
  NAND _1452_ (
    .A(_0624_),
    .B(_0625_),
    .Y(_0626_)
  );
  NOR _1453_ (
    .A(_0071_),
    .B(_0072_),
    .Y(_0627_)
  );
  NOR _1454_ (
    .A(_0073_),
    .B(_0074_),
    .Y(_0628_)
  );
  NAND _1455_ (
    .A(_0627_),
    .B(_0628_),
    .Y(_0629_)
  );
  NOR _1456_ (
    .A(_0626_),
    .B(_0629_),
    .Y(_0630_)
  );
  NAND _1457_ (
    .A(_0623_),
    .B(_0630_),
    .Y(_0631_)
  );
  NOR _1458_ (
    .A(_0616_),
    .B(_0631_),
    .Y(_0632_)
  );
  NAND _1459_ (
    .A(_0601_),
    .B(_0632_),
    .Y(_0633_)
  );
  NOR _1460_ (
    .A(_0594_),
    .B(_0633_),
    .Y(_0634_)
  );
  NAND _1461_ (
    .A(_0357_),
    .B(_0634_),
    .Y(_0635_)
  );
  NOR _1462_ (
    .A(_0093_),
    .B(_0096_),
    .Y(_0636_)
  );
  NOR _1463_ (
    .A(_0084_),
    .B(_0087_),
    .Y(_0637_)
  );
  NOR _1464_ (
    .A(_0067_),
    .B(_0068_),
    .Y(_0638_)
  );
  NOT _1465_ (
    .A(_0638_),
    .Y(_0639_)
  );
  NOR _1466_ (
    .A(_0072_),
    .B(_0073_),
    .Y(_0640_)
  );
  NOR _1467_ (
    .A(_0082_),
    .B(_0094_),
    .Y(_0641_)
  );
  NOR _1468_ (
    .A(_0088_),
    .B(_0095_),
    .Y(_0642_)
  );
  NAND _1469_ (
    .A(_0641_),
    .B(_0642_),
    .Y(_0643_)
  );
  NOR _1470_ (
    .A(_0063_),
    .B(_0069_),
    .Y(_0644_)
  );
  NOR _1471_ (
    .A(_0065_),
    .B(_0075_),
    .Y(_0645_)
  );
  NAND _1472_ (
    .A(_0644_),
    .B(_0645_),
    .Y(_0646_)
  );
  NOR _1473_ (
    .A(_0643_),
    .B(_0646_),
    .Y(_0647_)
  );
  NAND _1474_ (
    .A(_0222_),
    .B(_0637_),
    .Y(_0648_)
  );
  NOR _1475_ (
    .A(_0064_),
    .B(_0066_),
    .Y(_0649_)
  );
  NOR _1476_ (
    .A(_0062_),
    .B(_0078_),
    .Y(_0650_)
  );
  NAND _1477_ (
    .A(_0649_),
    .B(_0650_),
    .Y(_0651_)
  );
  NOR _1478_ (
    .A(_0648_),
    .B(_0651_),
    .Y(_0652_)
  );
  NAND _1479_ (
    .A(_0647_),
    .B(_0652_),
    .Y(_0653_)
  );
  NOR _1480_ (
    .A(_0071_),
    .B(_0077_),
    .Y(_0654_)
  );
  NOR _1481_ (
    .A(_0083_),
    .B(_0085_),
    .Y(_0655_)
  );
  NAND _1482_ (
    .A(_0654_),
    .B(_0655_),
    .Y(_0656_)
  );
  NAND _1483_ (
    .A(_0221_),
    .B(_0636_),
    .Y(_0657_)
  );
  NOR _1484_ (
    .A(_0080_),
    .B(_0090_),
    .Y(_0658_)
  );
  NAND _1485_ (
    .A(_0640_),
    .B(_0658_),
    .Y(_0659_)
  );
  NOR _1486_ (
    .A(_0657_),
    .B(_0659_),
    .Y(_0660_)
  );
  NOR _1487_ (
    .A(_0074_),
    .B(_0076_),
    .Y(_0661_)
  );
  NOR _1488_ (
    .A(_0079_),
    .B(_0086_),
    .Y(_0662_)
  );
  NAND _1489_ (
    .A(_0661_),
    .B(_0662_),
    .Y(_0663_)
  );
  NOR _1490_ (
    .A(_0639_),
    .B(_0663_),
    .Y(_0664_)
  );
  NAND _1491_ (
    .A(_0660_),
    .B(_0664_),
    .Y(_0665_)
  );
  NOR _1492_ (
    .A(_0656_),
    .B(_0665_),
    .Y(_0666_)
  );
  NAND _1493_ (
    .A(_0601_),
    .B(_0666_),
    .Y(_0667_)
  );
  NOR _1494_ (
    .A(_0653_),
    .B(_0667_),
    .Y(_0668_)
  );
  NAND _1495_ (
    .A(_0595_),
    .B(_0668_),
    .Y(_0669_)
  );
  NAND _1496_ (
    .A(_0188_),
    .B(_0635_),
    .Y(_0670_)
  );
  NOR _1497_ (
    .A(_0811_),
    .B(_0188_),
    .Y(_0671_)
  );
  NOR _1498_ (
    .A(_0816_),
    .B(_0671_),
    .Y(_0672_)
  );
  NAND _1499_ (
    .A(_0173_),
    .B(_0670_),
    .Y(_0673_)
  );
  NOR _1500_ (
    .A(_0672_),
    .B(_0673_),
    .Y(_0013_)
  );
  NAND _1501_ (
    .A(_0173_),
    .B(_0354_),
    .Y(_0674_)
  );
  NAND _1502_ (
    .A(_0101_),
    .B(_0349_),
    .Y(_0675_)
  );
  NAND _1503_ (
    .A(_0674_),
    .B(_0675_),
    .Y(_0011_)
  );
  NAND _1504_ (
    .A(_0172_),
    .B(_0814_),
    .Y(_0676_)
  );
  NOR _1505_ (
    .A(_0174_),
    .B(_0676_),
    .Y(_0677_)
  );
  NOR _1506_ (
    .A(_0035_),
    .B(_0677_),
    .Y(_0678_)
  );
  NOR _1507_ (
    .A(_0350_),
    .B(_0678_),
    .Y(_0009_)
  );
  NOR _1508_ (
    .A(_0814_),
    .B(_0158_),
    .Y(_0679_)
  );
  NOR _1509_ (
    .A(_0350_),
    .B(_0679_),
    .Y(_0014_)
  );
  NAND _1510_ (
    .A(_0357_),
    .B(_0669_),
    .Y(_0680_)
  );
  NAND _1511_ (
    .A(_0189_),
    .B(_0680_),
    .Y(_0681_)
  );
  NOR _1512_ (
    .A(_0811_),
    .B(_0189_),
    .Y(_0682_)
  );
  NOR _1513_ (
    .A(_0816_),
    .B(_0682_),
    .Y(_0683_)
  );
  NAND _1514_ (
    .A(_0173_),
    .B(_0681_),
    .Y(_0684_)
  );
  NOR _1515_ (
    .A(_0683_),
    .B(_0684_),
    .Y(_0012_)
  );
  NOR _1516_ (
    .A(_0180_),
    .B(_0669_),
    .Y(_0685_)
  );
  NOR _1517_ (
    .A(_0179_),
    .B(_0685_),
    .Y(_0686_)
  );
  NOR _1518_ (
    .A(_0036_),
    .B(_0686_),
    .Y(_0687_)
  );
  NOR _1519_ (
    .A(_0811_),
    .B(_0190_),
    .Y(_0688_)
  );
  NOR _1520_ (
    .A(_0816_),
    .B(_0688_),
    .Y(_0689_)
  );
  NOR _1521_ (
    .A(_0810_),
    .B(_0689_),
    .Y(_0690_)
  );
  NOT _1522_ (
    .A(_0690_),
    .Y(_0691_)
  );
  NOR _1523_ (
    .A(_0687_),
    .B(_0691_),
    .Y(_0010_)
  );
  NOR _1524_ (
    .A(_0187_),
    .B(_0148_),
    .Y(_0692_)
  );
  NOR _1525_ (
    .A(_0800_),
    .B(_0257_),
    .Y(_0693_)
  );
  NOR _1526_ (
    .A(_0692_),
    .B(_0693_),
    .Y(_0694_)
  );
  NOR _1527_ (
    .A(_0805_),
    .B(_0255_),
    .Y(_0695_)
  );
  NAND _1528_ (
    .A(_0185_),
    .B(_0153_),
    .Y(_0696_)
  );
  NOR _1529_ (
    .A(_0185_),
    .B(_0153_),
    .Y(_0697_)
  );
  NAND _1530_ (
    .A(_0805_),
    .B(_0255_),
    .Y(_0698_)
  );
  NOR _1531_ (
    .A(_0184_),
    .B(_0151_),
    .Y(_0699_)
  );
  NOR _1532_ (
    .A(_0803_),
    .B(_0254_),
    .Y(_0700_)
  );
  NOR _1533_ (
    .A(_0699_),
    .B(_0700_),
    .Y(_0701_)
  );
  NAND _1534_ (
    .A(_0798_),
    .B(_0146_),
    .Y(_0702_)
  );
  NOR _1535_ (
    .A(_0798_),
    .B(_0146_),
    .Y(_0703_)
  );
  NOT _1536_ (
    .A(_0703_),
    .Y(_0704_)
  );
  NAND _1537_ (
    .A(_0702_),
    .B(_0704_),
    .Y(_0705_)
  );
  NOR _1538_ (
    .A(_0809_),
    .B(_0256_),
    .Y(_0706_)
  );
  NOR _1539_ (
    .A(_0806_),
    .B(_0154_),
    .Y(_0707_)
  );
  NOT _1540_ (
    .A(_0707_),
    .Y(_0708_)
  );
  NAND _1541_ (
    .A(_0806_),
    .B(_0154_),
    .Y(_0709_)
  );
  NAND _1542_ (
    .A(_0708_),
    .B(_0709_),
    .Y(_0710_)
  );
  NOR _1543_ (
    .A(_0807_),
    .B(_0155_),
    .Y(_0711_)
  );
  NOT _1544_ (
    .A(_0711_),
    .Y(_0712_)
  );
  NAND _1545_ (
    .A(_0807_),
    .B(_0155_),
    .Y(_0713_)
  );
  NAND _1546_ (
    .A(_0712_),
    .B(_0713_),
    .Y(_0714_)
  );
  NOR _1547_ (
    .A(_0797_),
    .B(_0145_),
    .Y(_0715_)
  );
  NOT _1548_ (
    .A(_0715_),
    .Y(_0716_)
  );
  NAND _1549_ (
    .A(_0797_),
    .B(_0145_),
    .Y(_0717_)
  );
  NAND _1550_ (
    .A(_0716_),
    .B(_0717_),
    .Y(_0718_)
  );
  NOR _1551_ (
    .A(_0801_),
    .B(_0149_),
    .Y(_0719_)
  );
  NOT _1552_ (
    .A(_0719_),
    .Y(_0720_)
  );
  NAND _1553_ (
    .A(_0801_),
    .B(_0149_),
    .Y(_0721_)
  );
  NOT _1554_ (
    .A(_0721_),
    .Y(_0722_)
  );
  NOR _1555_ (
    .A(_0719_),
    .B(_0722_),
    .Y(_0723_)
  );
  NAND _1556_ (
    .A(_0720_),
    .B(_0721_),
    .Y(_0724_)
  );
  NOR _1557_ (
    .A(_0794_),
    .B(_0252_),
    .Y(_0725_)
  );
  NAND _1558_ (
    .A(_0182_),
    .B(_0142_),
    .Y(_0726_)
  );
  NOR _1559_ (
    .A(_0183_),
    .B(_0150_),
    .Y(_0727_)
  );
  NOR _1560_ (
    .A(_0802_),
    .B(_0253_),
    .Y(_0728_)
  );
  NOR _1561_ (
    .A(_0727_),
    .B(_0728_),
    .Y(_0729_)
  );
  NOR _1562_ (
    .A(_0182_),
    .B(_0142_),
    .Y(_0730_)
  );
  NAND _1563_ (
    .A(_0794_),
    .B(_0252_),
    .Y(_0731_)
  );
  NOR _1564_ (
    .A(_0186_),
    .B(_0157_),
    .Y(_0732_)
  );
  NAND _1565_ (
    .A(_0808_),
    .B(_0156_),
    .Y(_0733_)
  );
  NOR _1566_ (
    .A(_0808_),
    .B(_0156_),
    .Y(_0734_)
  );
  NOT _1567_ (
    .A(_0734_),
    .Y(_0735_)
  );
  NAND _1568_ (
    .A(_0733_),
    .B(_0735_),
    .Y(_0736_)
  );
  NOR _1569_ (
    .A(_0706_),
    .B(_0727_),
    .Y(_0737_)
  );
  NAND _1570_ (
    .A(_0736_),
    .B(_0737_),
    .Y(_0738_)
  );
  NOR _1571_ (
    .A(_0695_),
    .B(_0728_),
    .Y(_0739_)
  );
  NAND _1572_ (
    .A(_0705_),
    .B(_0739_),
    .Y(_0740_)
  );
  NOR _1573_ (
    .A(_0738_),
    .B(_0740_),
    .Y(_0741_)
  );
  NAND _1574_ (
    .A(_0804_),
    .B(_0152_),
    .Y(_0742_)
  );
  NOR _1575_ (
    .A(_0804_),
    .B(_0152_),
    .Y(_0743_)
  );
  NOT _1576_ (
    .A(_0743_),
    .Y(_0744_)
  );
  NAND _1577_ (
    .A(_0742_),
    .B(_0744_),
    .Y(_0745_)
  );
  NOR _1578_ (
    .A(_0799_),
    .B(_0147_),
    .Y(_0746_)
  );
  NOT _1579_ (
    .A(_0746_),
    .Y(_0747_)
  );
  NAND _1580_ (
    .A(_0799_),
    .B(_0147_),
    .Y(_0748_)
  );
  NAND _1581_ (
    .A(_0747_),
    .B(_0748_),
    .Y(_0749_)
  );
  NAND _1582_ (
    .A(_0745_),
    .B(_0749_),
    .Y(_0750_)
  );
  NAND _1583_ (
    .A(_0796_),
    .B(_0144_),
    .Y(_0751_)
  );
  NOR _1584_ (
    .A(_0796_),
    .B(_0144_),
    .Y(_0752_)
  );
  NOT _1585_ (
    .A(_0752_),
    .Y(_0753_)
  );
  NAND _1586_ (
    .A(_0751_),
    .B(_0753_),
    .Y(_0754_)
  );
  NAND _1587_ (
    .A(_0724_),
    .B(_0754_),
    .Y(_0755_)
  );
  NOR _1588_ (
    .A(_0750_),
    .B(_0755_),
    .Y(_0756_)
  );
  NAND _1589_ (
    .A(_0741_),
    .B(_0756_),
    .Y(_0757_)
  );
  NOR _1590_ (
    .A(_0795_),
    .B(_0143_),
    .Y(_0758_)
  );
  NOT _1591_ (
    .A(_0758_),
    .Y(_0759_)
  );
  NAND _1592_ (
    .A(_0795_),
    .B(_0143_),
    .Y(_0760_)
  );
  NOT _1593_ (
    .A(_0760_),
    .Y(_0761_)
  );
  NOR _1594_ (
    .A(_0758_),
    .B(_0761_),
    .Y(_0762_)
  );
  NAND _1595_ (
    .A(_0759_),
    .B(_0760_),
    .Y(_0763_)
  );
  NAND _1596_ (
    .A(_0710_),
    .B(_0763_),
    .Y(_0764_)
  );
  NOR _1597_ (
    .A(_0725_),
    .B(_0730_),
    .Y(_0765_)
  );
  NAND _1598_ (
    .A(_0726_),
    .B(_0731_),
    .Y(_0766_)
  );
  NAND _1599_ (
    .A(_0701_),
    .B(_0765_),
    .Y(_0767_)
  );
  NOR _1600_ (
    .A(_0764_),
    .B(_0767_),
    .Y(_0768_)
  );
  NAND _1601_ (
    .A(_0714_),
    .B(_0718_),
    .Y(_0769_)
  );
  NOR _1602_ (
    .A(_0697_),
    .B(_0732_),
    .Y(_0770_)
  );
  NAND _1603_ (
    .A(_0694_),
    .B(_0770_),
    .Y(_0771_)
  );
  NOR _1604_ (
    .A(_0769_),
    .B(_0771_),
    .Y(_0772_)
  );
  NAND _1605_ (
    .A(_0768_),
    .B(_0772_),
    .Y(_0773_)
  );
  NOR _1606_ (
    .A(_0762_),
    .B(_0766_),
    .Y(_0774_)
  );
  NAND _1607_ (
    .A(_0701_),
    .B(_0710_),
    .Y(_0775_)
  );
  NAND _1608_ (
    .A(_0718_),
    .B(_0745_),
    .Y(_0776_)
  );
  NOR _1609_ (
    .A(_0775_),
    .B(_0776_),
    .Y(_0777_)
  );
  NAND _1610_ (
    .A(_0705_),
    .B(_0714_),
    .Y(_0778_)
  );
  NAND _1611_ (
    .A(_0749_),
    .B(_0754_),
    .Y(_0779_)
  );
  NOR _1612_ (
    .A(_0778_),
    .B(_0779_),
    .Y(_0780_)
  );
  NAND _1613_ (
    .A(_0777_),
    .B(_0780_),
    .Y(_0781_)
  );
  NAND _1614_ (
    .A(_0696_),
    .B(_0729_),
    .Y(_0782_)
  );
  NOR _1615_ (
    .A(_0706_),
    .B(_0732_),
    .Y(_0783_)
  );
  NAND _1616_ (
    .A(_0736_),
    .B(_0783_),
    .Y(_0784_)
  );
  NOR _1617_ (
    .A(_0782_),
    .B(_0784_),
    .Y(_0785_)
  );
  NAND _1618_ (
    .A(_0694_),
    .B(_0698_),
    .Y(_0786_)
  );
  NOR _1619_ (
    .A(_0723_),
    .B(_0786_),
    .Y(_0787_)
  );
  NAND _1620_ (
    .A(_0785_),
    .B(_0787_),
    .Y(_0788_)
  );
  NOR _1621_ (
    .A(_0781_),
    .B(_0788_),
    .Y(_0789_)
  );
  NOR _1622_ (
    .A(_0757_),
    .B(_0773_),
    .Y(_0790_)
  );
  NAND _1623_ (
    .A(_0774_),
    .B(_0789_),
    .Y(_0791_)
  );
  NAND _1624_ (
    .A(_0173_),
    .B(_0817_),
    .Y(_0792_)
  );
  NOR _1625_ (
    .A(_0791_),
    .B(_0792_),
    .Y(_0161_)
  );
  NOR _1626_ (
    .A(_0810_),
    .B(_0258_),
    .Y(_0164_)
  );
  NAND _1627_ (
    .A(_0811_),
    .B(_0159_),
    .Y(_0793_)
  );
  NOR _1628_ (
    .A(_0810_),
    .B(_0793_),
    .Y(_0163_)
  );
  NOR _1629_ (
    .A(_0790_),
    .B(_0792_),
    .Y(_0162_)
  );
  DFF _1630_ (
    .C(clk),
    .D(_0830_[0]),
    .Q(state[0])
  );
  DFF _1631_ (
    .C(clk),
    .D(_0821_),
    .Q(state[1])
  );
  DFF _1632_ (
    .C(clk),
    .D(_0830_[2]),
    .Q(state[2])
  );
  DFF _1633_ (
    .C(clk),
    .D(_0825_),
    .Q(state[3])
  );
  DFF _1634_ (
    .C(clk),
    .D(_0826_),
    .Q(state[4])
  );
  DFF _1635_ (
    .C(clk),
    .D(_0827_),
    .Q(state[5])
  );
  DFF _1636_ (
    .C(clk),
    .D(_0830_[6]),
    .Q(state[6])
  );
  (* src = "cajeroAutomatico.v:133" *)
  DFF _1637_ (
    .C(clk),
    .D(_0001_),
    .Q(BALANCE_ACTUALIZADO)
  );
  (* src = "cajeroAutomatico.v:133" *)
  DFF _1638_ (
    .C(clk),
    .D(_0003_),
    .Q(ENTREGAR_DINERO)
  );
  (* src = "cajeroAutomatico.v:133" *)
  DFF _1639_ (
    .C(clk),
    .D(_0005_),
    .Q(PIN_INCORRECTO)
  );
  (* src = "cajeroAutomatico.v:133" *)
  DFF _1640_ (
    .C(clk),
    .D(_0000_),
    .Q(ADVERTENCIA)
  );
  (* src = "cajeroAutomatico.v:133" *)
  DFF _1641_ (
    .C(clk),
    .D(_0002_),
    .Q(BLOQUEO)
  );
  (* src = "cajeroAutomatico.v:133" *)
  DFF _1642_ (
    .C(clk),
    .D(_0004_),
    .Q(FONDOS_INSUFICIENTES)
  );
  (* src = "cajeroAutomatico.v:133" *)
  DFF _1643_ (
    .C(clk),
    .D(_0007_[0]),
    .Q(intentos[0])
  );
  (* src = "cajeroAutomatico.v:133" *)
  DFF _1644_ (
    .C(clk),
    .D(_0007_[1]),
    .Q(intentos[1])
  );
  (* src = "cajeroAutomatico.v:133" *)
  DFF _1645_ (
    .C(clk),
    .D(_0008_[0]),
    .Q(pin_tecleado[0])
  );
  (* src = "cajeroAutomatico.v:133" *)
  DFF _1646_ (
    .C(clk),
    .D(_0008_[1]),
    .Q(pin_tecleado[1])
  );
  (* src = "cajeroAutomatico.v:133" *)
  DFF _1647_ (
    .C(clk),
    .D(_0008_[2]),
    .Q(pin_tecleado[2])
  );
  (* src = "cajeroAutomatico.v:133" *)
  DFF _1648_ (
    .C(clk),
    .D(_0008_[3]),
    .Q(pin_tecleado[3])
  );
  (* src = "cajeroAutomatico.v:133" *)
  DFF _1649_ (
    .C(clk),
    .D(_0008_[4]),
    .Q(pin_tecleado[4])
  );
  (* src = "cajeroAutomatico.v:133" *)
  DFF _1650_ (
    .C(clk),
    .D(_0008_[5]),
    .Q(pin_tecleado[5])
  );
  (* src = "cajeroAutomatico.v:133" *)
  DFF _1651_ (
    .C(clk),
    .D(_0008_[6]),
    .Q(pin_tecleado[6])
  );
  (* src = "cajeroAutomatico.v:133" *)
  DFF _1652_ (
    .C(clk),
    .D(_0008_[7]),
    .Q(pin_tecleado[7])
  );
  (* src = "cajeroAutomatico.v:133" *)
  DFF _1653_ (
    .C(clk),
    .D(_0008_[8]),
    .Q(pin_tecleado[8])
  );
  (* src = "cajeroAutomatico.v:133" *)
  DFF _1654_ (
    .C(clk),
    .D(_0008_[9]),
    .Q(pin_tecleado[9])
  );
  (* src = "cajeroAutomatico.v:133" *)
  DFF _1655_ (
    .C(clk),
    .D(_0008_[10]),
    .Q(pin_tecleado[10])
  );
  (* src = "cajeroAutomatico.v:133" *)
  DFF _1656_ (
    .C(clk),
    .D(_0008_[11]),
    .Q(pin_tecleado[11])
  );
  (* src = "cajeroAutomatico.v:133" *)
  DFF _1657_ (
    .C(clk),
    .D(_0008_[12]),
    .Q(pin_tecleado[12])
  );
  (* src = "cajeroAutomatico.v:133" *)
  DFF _1658_ (
    .C(clk),
    .D(_0008_[13]),
    .Q(pin_tecleado[13])
  );
  (* src = "cajeroAutomatico.v:133" *)
  DFF _1659_ (
    .C(clk),
    .D(_0008_[14]),
    .Q(pin_tecleado[14])
  );
  (* src = "cajeroAutomatico.v:133" *)
  DFF _1660_ (
    .C(clk),
    .D(_0008_[15]),
    .Q(pin_tecleado[15])
  );
  (* src = "cajeroAutomatico.v:133" *)
  DFF _1661_ (
    .C(clk),
    .D(_0006_[0]),
    .Q(digitos_ingresados[0])
  );
  (* src = "cajeroAutomatico.v:133" *)
  DFF _1662_ (
    .C(clk),
    .D(_0006_[1]),
    .Q(digitos_ingresados[1])
  );
  assign _0818_[31:3] = 29'h00000000;
  assign _0819_[31:3] = 29'h00000000;
  assign { _0830_[5:3], _0830_[1] } = { _0827_, _0826_, _0825_, _0821_ };
  assign _0851_[15:1] = 15'h7fff;
  assign _0856_[0] = _0818_[0];
  assign _0858_[0] = intentos[0];
  assign _0859_[1] = rst;
  assign _0860_[0] = rst;
  assign _0861_[0] = rst;
  assign _0862_[1:0] = { rst, _0859_[0] };
  assign _0877_[1] = 1'h0;
  assign _0882_[1] = 1'h0;
  assign _0885_[3:2] = 2'h0;
  assign _0888_[31:16] = 16'h0000;
  assign _0890_[3:2] = 2'h0;
  assign _0894_[1] = 1'h0;
  assign _0898_[1] = 1'h0;
  assign _0901_[1] = 1'h0;
  assign _0905_[30:1] = { _0905_[31], _0905_[31], _0905_[31], _0905_[31], _0905_[31], _0905_[31], _0905_[31], _0905_[31], _0905_[31], _0905_[31], _0905_[31], _0905_[31], _0905_[31], _0905_[31], _0905_[31], _0905_[31], _0905_[31], _0905_[31], _0905_[31], _0905_[31], _0905_[31], _0905_[31], _0905_[31], _0905_[31], _0905_[31], _0905_[31], _0905_[31], _0905_[31], _0905_[31], _0905_[31] };
  assign { _0911_[63:32], _0911_[0] } = { _0908_[63:32], _0910_[0] };
  assign _0917_[63:32] = 32'd0;
  assign _0170_ = intentos[0];
  assign _0830_[6] = _0167_;
  assign _0810_ = rst;
  assign _0816_ = state[5];
  assign _0830_[0] = _0165_;
  assign _0830_[2] = _0166_;
  assign _0171_ = intentos[1];
  assign _0813_ = state[2];
  assign _0811_ = state[0];
  assign _0814_ = state[3];
  assign _0106_ = DIGITO_STB;
  assign _0159_ = TARJETA_RECIBIDA;
  assign _0141_ = MONTO_STB;
  assign _0160_ = TIPO_TRANS;
  assign _0168_ = digitos_ingresados[0];
  assign _0169_ = digitos_ingresados[1];
  assign _0006_[0] = _0015_;
  assign _0006_[1] = _0016_;
  assign _0794_ = pin_tecleado[0];
  assign _0102_ = DIGITO[0];
  assign _0801_ = pin_tecleado[1];
  assign _0103_ = DIGITO[1];
  assign _0802_ = pin_tecleado[2];
  assign _0104_ = DIGITO[2];
  assign _0803_ = pin_tecleado[3];
  assign _0105_ = DIGITO[3];
  assign _0804_ = pin_tecleado[4];
  assign _0805_ = pin_tecleado[5];
  assign _0806_ = pin_tecleado[6];
  assign _0807_ = pin_tecleado[7];
  assign _0808_ = pin_tecleado[8];
  assign _0809_ = pin_tecleado[9];
  assign _0795_ = pin_tecleado[10];
  assign _0796_ = pin_tecleado[11];
  assign _0797_ = pin_tecleado[12];
  assign _0798_ = pin_tecleado[13];
  assign _0799_ = pin_tecleado[14];
  assign _0800_ = pin_tecleado[15];
  assign _0008_[0] = _0019_;
  assign _0008_[1] = _0026_;
  assign _0008_[2] = _0027_;
  assign _0008_[3] = _0028_;
  assign _0008_[4] = _0029_;
  assign _0008_[5] = _0030_;
  assign _0008_[6] = _0031_;
  assign _0008_[7] = _0032_;
  assign _0008_[8] = _0033_;
  assign _0008_[9] = _0034_;
  assign _0008_[10] = _0020_;
  assign _0008_[11] = _0021_;
  assign _0008_[12] = _0022_;
  assign _0008_[13] = _0023_;
  assign _0008_[14] = _0024_;
  assign _0008_[15] = _0025_;
  assign _0007_[0] = _0017_;
  assign _0007_[1] = _0018_;
  assign _0108_ = FONDOS_INSUFICIENTES;
  assign _0004_ = _0013_;
  assign _0101_ = BLOQUEO;
  assign _0002_ = _0011_;
  assign _0035_ = ADVERTENCIA;
  assign _0000_ = _0009_;
  assign _0005_ = _0014_;
  assign _0107_ = ENTREGAR_DINERO;
  assign _0003_ = _0012_;
  assign _0036_ = BALANCE_ACTUALIZADO;
  assign _0001_ = _0010_;
  assign _0158_ = PIN_INCORRECTO;
  assign _0037_ = BALANCE_INICIAL[0];
  assign _0048_ = BALANCE_INICIAL[1];
  assign _0059_ = BALANCE_INICIAL[2];
  assign _0070_ = BALANCE_INICIAL[3];
  assign _0081_ = BALANCE_INICIAL[4];
  assign _0092_ = BALANCE_INICIAL[5];
  assign _0097_ = BALANCE_INICIAL[6];
  assign _0098_ = BALANCE_INICIAL[7];
  assign _0099_ = BALANCE_INICIAL[8];
  assign _0100_ = BALANCE_INICIAL[9];
  assign _0038_ = BALANCE_INICIAL[10];
  assign _0039_ = BALANCE_INICIAL[11];
  assign _0040_ = BALANCE_INICIAL[12];
  assign _0041_ = BALANCE_INICIAL[13];
  assign _0042_ = BALANCE_INICIAL[14];
  assign _0043_ = BALANCE_INICIAL[15];
  assign _0044_ = BALANCE_INICIAL[16];
  assign _0045_ = BALANCE_INICIAL[17];
  assign _0046_ = BALANCE_INICIAL[18];
  assign _0047_ = BALANCE_INICIAL[19];
  assign _0049_ = BALANCE_INICIAL[20];
  assign _0050_ = BALANCE_INICIAL[21];
  assign _0051_ = BALANCE_INICIAL[22];
  assign _0052_ = BALANCE_INICIAL[23];
  assign _0053_ = BALANCE_INICIAL[24];
  assign _0054_ = BALANCE_INICIAL[25];
  assign _0055_ = BALANCE_INICIAL[26];
  assign _0056_ = BALANCE_INICIAL[27];
  assign _0057_ = BALANCE_INICIAL[28];
  assign _0058_ = BALANCE_INICIAL[29];
  assign _0060_ = BALANCE_INICIAL[30];
  assign _0061_ = BALANCE_INICIAL[31];
  assign _0062_ = BALANCE_INICIAL[32];
  assign _0063_ = BALANCE_INICIAL[33];
  assign _0064_ = BALANCE_INICIAL[34];
  assign _0065_ = BALANCE_INICIAL[35];
  assign _0066_ = BALANCE_INICIAL[36];
  assign _0067_ = BALANCE_INICIAL[37];
  assign _0068_ = BALANCE_INICIAL[38];
  assign _0069_ = BALANCE_INICIAL[39];
  assign _0071_ = BALANCE_INICIAL[40];
  assign _0072_ = BALANCE_INICIAL[41];
  assign _0073_ = BALANCE_INICIAL[42];
  assign _0074_ = BALANCE_INICIAL[43];
  assign _0075_ = BALANCE_INICIAL[44];
  assign _0076_ = BALANCE_INICIAL[45];
  assign _0077_ = BALANCE_INICIAL[46];
  assign _0078_ = BALANCE_INICIAL[47];
  assign _0079_ = BALANCE_INICIAL[48];
  assign _0080_ = BALANCE_INICIAL[49];
  assign _0082_ = BALANCE_INICIAL[50];
  assign _0083_ = BALANCE_INICIAL[51];
  assign _0084_ = BALANCE_INICIAL[52];
  assign _0085_ = BALANCE_INICIAL[53];
  assign _0086_ = BALANCE_INICIAL[54];
  assign _0087_ = BALANCE_INICIAL[55];
  assign _0088_ = BALANCE_INICIAL[56];
  assign _0089_ = BALANCE_INICIAL[57];
  assign _0090_ = BALANCE_INICIAL[58];
  assign _0091_ = BALANCE_INICIAL[59];
  assign _0093_ = BALANCE_INICIAL[60];
  assign _0094_ = BALANCE_INICIAL[61];
  assign _0095_ = BALANCE_INICIAL[62];
  assign _0096_ = BALANCE_INICIAL[63];
  assign _0109_ = MONTO[0];
  assign _0120_ = MONTO[1];
  assign _0131_ = MONTO[2];
  assign _0134_ = MONTO[3];
  assign _0135_ = MONTO[4];
  assign _0136_ = MONTO[5];
  assign _0137_ = MONTO[6];
  assign _0138_ = MONTO[7];
  assign _0139_ = MONTO[8];
  assign _0140_ = MONTO[9];
  assign _0110_ = MONTO[10];
  assign _0111_ = MONTO[11];
  assign _0112_ = MONTO[12];
  assign _0113_ = MONTO[13];
  assign _0114_ = MONTO[14];
  assign _0115_ = MONTO[15];
  assign _0116_ = MONTO[16];
  assign _0117_ = MONTO[17];
  assign _0118_ = MONTO[18];
  assign _0119_ = MONTO[19];
  assign _0121_ = MONTO[20];
  assign _0122_ = MONTO[21];
  assign _0123_ = MONTO[22];
  assign _0124_ = MONTO[23];
  assign _0125_ = MONTO[24];
  assign _0126_ = MONTO[25];
  assign _0127_ = MONTO[26];
  assign _0128_ = MONTO[27];
  assign _0129_ = MONTO[28];
  assign _0130_ = MONTO[29];
  assign _0132_ = MONTO[30];
  assign _0133_ = MONTO[31];
  assign _0817_ = state[6];
  assign _0821_ = _0161_;
  assign _0142_ = PIN[0];
  assign _0149_ = PIN[1];
  assign _0150_ = PIN[2];
  assign _0151_ = PIN[3];
  assign _0152_ = PIN[4];
  assign _0153_ = PIN[5];
  assign _0154_ = PIN[6];
  assign _0155_ = PIN[7];
  assign _0156_ = PIN[8];
  assign _0157_ = PIN[9];
  assign _0143_ = PIN[10];
  assign _0144_ = PIN[11];
  assign _0145_ = PIN[12];
  assign _0146_ = PIN[13];
  assign _0147_ = PIN[14];
  assign _0148_ = PIN[15];
  assign _0812_ = state[1];
  assign _0827_ = _0164_;
  assign _0826_ = _0163_;
  assign _0825_ = _0162_;
  assign _0815_ = state[4];
endmodule
