/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "cajeroAutomatico.v:1" *)
module cajero_automatico(clk, rst, TARJETA_RECIBIDA, TIPO_TRANS, MONTO_STB, DIGITO_STB, DIGITO, PIN, MONTO, BALANCE_INICIAL, BALANCE_ACTUALIZADO, ENTREGAR_DINERO, PIN_INCORRECTO, ADVERTENCIA, BLOQUEO, FONDOS_INSUFICIENTES);
  (* src = "cajeroAutomatico.v:133" *)
  wire _000_;
  (* src = "cajeroAutomatico.v:133" *)
  wire _001_;
  (* src = "cajeroAutomatico.v:133" *)
  wire _002_;
  (* src = "cajeroAutomatico.v:133" *)
  wire _003_;
  (* src = "cajeroAutomatico.v:133" *)
  wire _004_;
  (* src = "cajeroAutomatico.v:133" *)
  wire _005_;
  (* src = "cajeroAutomatico.v:133" *)
  wire [1:0] _006_;
  (* src = "cajeroAutomatico.v:133" *)
  wire [1:0] _007_;
  (* src = "cajeroAutomatico.v:133" *)
  wire [15:0] _008_;
  (* src = "cajeroAutomatico.v:171" *)
  (* unused_bits = "2" *)
  wire [31:0] _009_;
  (* src = "cajeroAutomatico.v:228" *)
  (* unused_bits = "2" *)
  wire [31:0] _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  (* unused_bits = "7" *)
  wire [7:0] _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire [7:0] _031_;
  wire [3:0] _032_;
  wire [1:0] _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire [31:0] _037_;
  wire [15:0] _038_;
  wire [7:0] _039_;
  wire [3:0] _040_;
  wire [1:0] _041_;
  wire [15:0] _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire [1:0] _047_;
  wire [15:0] _048_;
  wire [1:0] _049_;
  wire [2:0] _050_;
  wire [1:0] _051_;
  wire [1:0] _052_;
  wire [2:0] _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  (* src = "cajeroAutomatico.v:189" *)
  wire _061_;
  (* src = "cajeroAutomatico.v:79" *)
  wire _062_;
  (* src = "cajeroAutomatico.v:113" *)
  wire _063_;
  (* src = "cajeroAutomatico.v:195" *)
  wire _064_;
  (* src = "cajeroAutomatico.v:189" *)
  wire _065_;
  (* src = "cajeroAutomatico.v:193" *)
  wire _066_;
  wire _067_;
  (* src = "cajeroAutomatico.v:187|cajeroAutomatico.v:148|<techmap.v>:432" *)
  wire [1:0] _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  (* src = "cajeroAutomatico.v:187|cajeroAutomatico.v:148|<techmap.v>:432" *)
  wire [1:0] _073_;
  wire _074_;
  wire [1:0] _075_;
  (* src = "cajeroAutomatico.v:167|cajeroAutomatico.v:148|<techmap.v>:432" *)
  wire [3:0] _076_;
  wire [1:0] _077_;
  wire [15:0] _078_;
  (* src = "cajeroAutomatico.v:167|cajeroAutomatico.v:148|<techmap.v>:432" *)
  wire [31:0] _079_;
  wire [15:0] _080_;
  (* src = "cajeroAutomatico.v:226|cajeroAutomatico.v:148|<techmap.v>:432" *)
  wire [3:0] _081_;
  wire [1:0] _082_;
  wire _083_;
  wire _084_;
  (* src = "cajeroAutomatico.v:187|cajeroAutomatico.v:148|<techmap.v>:432" *)
  wire [1:0] _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  (* src = "cajeroAutomatico.v:226|cajeroAutomatico.v:148|<techmap.v>:432" *)
  wire [1:0] _089_;
  wire _090_;
  wire _091_;
  (* src = "cajeroAutomatico.v:226|cajeroAutomatico.v:148|<techmap.v>:432" *)
  wire [1:0] _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  (* src = "cajeroAutomatico.v:231|<techmap.v>:260|<techmap.v>:203" *)
  wire [31:0] _096_;
  wire _097_;
  wire _098_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:258" *)
  wire [63:0] _099_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:203" *)
  (* unused_bits = "2 4 5 6 8 9 10 11 12 13 14 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62" *)
  wire [63:0] _100_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:203" *)
  (* unused_bits = "1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63" *)
  wire [63:0] _101_;
  wire [63:0] _102_;
  wire _103_;
  wire _104_;
  (* src = "cajeroAutomatico.v:187|cajeroAutomatico.v:148|<techmap.v>:445" *)
  wire _105_;
  (* src = "cajeroAutomatico.v:167|cajeroAutomatico.v:148|<techmap.v>:445" *)
  wire _106_;
  (* src = "cajeroAutomatico.v:226|cajeroAutomatico.v:148|<techmap.v>:445" *)
  wire _107_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260" *)
  wire [63:0] _108_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)
  wire _109_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)
  wire _110_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)
  wire _111_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)
  wire _112_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)
  wire _113_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)
  wire _114_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)
  wire _115_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)
  wire _116_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)
  wire _117_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)
  wire _118_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)
  wire _119_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)
  wire _120_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)
  wire _121_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)
  wire _122_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)
  wire _123_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)
  wire _124_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)
  wire _125_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)
  wire _126_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)
  wire _127_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)
  wire _128_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)
  wire _129_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)
  wire _130_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)
  wire _131_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)
  wire _132_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)
  wire _133_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)
  wire _134_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)
  wire _135_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)
  wire _136_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)
  wire _137_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)
  wire _138_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)
  wire _139_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)
  wire _140_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)
  wire _141_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)
  wire _142_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)
  wire _143_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)
  wire _144_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)
  wire _145_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)
  wire _146_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)
  wire _147_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)
  wire _148_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)
  wire _149_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)
  wire _150_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)
  wire _151_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)
  wire _152_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)
  wire _153_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)
  wire _154_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)
  wire _155_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)
  wire _156_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)
  wire _157_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)
  wire _158_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)
  wire _159_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)
  wire _160_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)
  wire _161_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)
  wire _162_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)
  wire _163_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)
  wire _164_;
  (* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)
  wire _165_;
  (* src = "cajeroAutomatico.v:17" *)
  output ADVERTENCIA;
  reg ADVERTENCIA;
  (* src = "cajeroAutomatico.v:14" *)
  output BALANCE_ACTUALIZADO;
  reg BALANCE_ACTUALIZADO;
  (* src = "cajeroAutomatico.v:12" *)
  input [63:0] BALANCE_INICIAL;
  (* src = "cajeroAutomatico.v:18" *)
  output BLOQUEO;
  reg BLOQUEO;
  (* src = "cajeroAutomatico.v:9" *)
  input [3:0] DIGITO;
  (* src = "cajeroAutomatico.v:8" *)
  input DIGITO_STB;
  (* src = "cajeroAutomatico.v:15" *)
  output ENTREGAR_DINERO;
  reg ENTREGAR_DINERO;
  (* src = "cajeroAutomatico.v:19" *)
  output FONDOS_INSUFICIENTES;
  reg FONDOS_INSUFICIENTES;
  (* src = "cajeroAutomatico.v:11" *)
  input [31:0] MONTO;
  (* src = "cajeroAutomatico.v:7" *)
  input MONTO_STB;
  (* src = "cajeroAutomatico.v:10" *)
  input [15:0] PIN;
  (* src = "cajeroAutomatico.v:16" *)
  output PIN_INCORRECTO;
  reg PIN_INCORRECTO;
  (* src = "cajeroAutomatico.v:5" *)
  input TARJETA_RECIBIDA;
  (* src = "cajeroAutomatico.v:6" *)
  input TIPO_TRANS;
  (* src = "cajeroAutomatico.v:3" *)
  input clk;
  (* src = "cajeroAutomatico.v:40" *)
  reg [1:0] digitos_ingresados;
  (* src = "cajeroAutomatico.v:37" *)
  reg [1:0] intentos;
  (* src = "cajeroAutomatico.v:39" *)
  reg [15:0] pin_tecleado;
  (* src = "cajeroAutomatico.v:4" *)
  input rst;
  (* onehot = 32'd1 *)
  (* unused_bits = "7" *)
  wire [7:0] state;
  assign _054_ = _009_[0] |(* src = "cajeroAutomatico.v:67" *)  _047_[1];
  assign _031_[0] = _048_[0] |(* src = "cajeroAutomatico.v:79" *)  _048_[1];
  assign _031_[1] = _048_[2] |(* src = "cajeroAutomatico.v:79" *)  _048_[3];
  assign _031_[2] = _048_[4] |(* src = "cajeroAutomatico.v:79" *)  _048_[5];
  assign _031_[3] = _048_[6] |(* src = "cajeroAutomatico.v:79" *)  _048_[7];
  assign _031_[4] = _048_[8] |(* src = "cajeroAutomatico.v:79" *)  _048_[9];
  assign _031_[5] = _048_[10] |(* src = "cajeroAutomatico.v:79" *)  _048_[11];
  assign _031_[6] = _048_[12] |(* src = "cajeroAutomatico.v:79" *)  _048_[13];
  assign _031_[7] = _048_[14] |(* src = "cajeroAutomatico.v:79" *)  _048_[15];
  assign _032_[0] = _031_[0] |(* src = "cajeroAutomatico.v:79" *)  _031_[1];
  assign _032_[1] = _031_[2] |(* src = "cajeroAutomatico.v:79" *)  _031_[3];
  assign _032_[2] = _031_[4] |(* src = "cajeroAutomatico.v:79" *)  _031_[5];
  assign _032_[3] = _031_[6] |(* src = "cajeroAutomatico.v:79" *)  _031_[7];
  assign _033_[0] = _032_[0] |(* src = "cajeroAutomatico.v:79" *)  _032_[1];
  assign _033_[1] = _032_[2] |(* src = "cajeroAutomatico.v:79" *)  _032_[3];
  assign _055_ = _033_[0] |(* src = "cajeroAutomatico.v:79" *)  _033_[1];
  assign _056_ = intentos[0] |(* src = "cajeroAutomatico.v:229" *)  _049_[1];
  assign _021_[6] = _019_ | _020_;
  assign _057_ = _034_ | _050_[2];
  assign _058_ = rst | _051_[1];
  assign _035_ = state[5] | _011_;
  assign _021_[0] = _035_ | rst;
  assign _059_ = rst | _052_[1];
  assign _036_ = _014_ | _015_;
  assign _021_[2] = _036_ | _013_;
  assign _034_ = _050_[0] | rst;
  assign _060_ = _034_ | _053_[2];
  assign _037_[0] = _101_[0] &(* src = "cajeroAutomatico.v:195" *)  _102_[1];
  assign _037_[5] = _102_[10] &(* src = "cajeroAutomatico.v:195" *)  _102_[11];
  assign _037_[6] = _102_[12] &(* src = "cajeroAutomatico.v:195" *)  _102_[13];
  assign _037_[14] = _102_[28] &(* src = "cajeroAutomatico.v:195" *)  _102_[29];
  assign _037_[16] = _099_[32] &(* src = "cajeroAutomatico.v:195" *)  _099_[33];
  assign _037_[30] = _099_[60] &(* src = "cajeroAutomatico.v:195" *)  _099_[61];
  assign _038_[0] = _037_[0] &(* src = "cajeroAutomatico.v:195" *)  _037_[1];
  assign _038_[2] = _037_[4] &(* src = "cajeroAutomatico.v:195" *)  _037_[5];
  assign _038_[7] = _037_[14] &(* src = "cajeroAutomatico.v:195" *)  _037_[15];
  assign _038_[11] = _037_[22] &(* src = "cajeroAutomatico.v:195" *)  _037_[23];
  assign _039_[0] = _038_[0] &(* src = "cajeroAutomatico.v:195" *)  _038_[1];
  assign _039_[2] = _038_[4] &(* src = "cajeroAutomatico.v:195" *)  _038_[5];
  assign _039_[7] = _038_[14] &(* src = "cajeroAutomatico.v:195" *)  _038_[15];
  assign _040_[0] = _039_[0] &(* src = "cajeroAutomatico.v:195" *)  _039_[1];
  assign _041_[0] = _040_[0] &(* src = "cajeroAutomatico.v:195" *)  _040_[1];
  assign _104_ = _041_[0] &(* src = "cajeroAutomatico.v:195" *)  _041_[1];
  assign _064_ = _103_ | _104_;
  assign _042_[0] = _010_[0] &(* src = "cajeroAutomatico.v:231" *)  intentos[1];
  assign _106_ = state[2] |(* src = "cajeroAutomatico.v:167|cajeroAutomatico.v:148|<techmap.v>:445" *)  state[0];
  assign _107_ = state[3] |(* src = "cajeroAutomatico.v:226|cajeroAutomatico.v:148|<techmap.v>:445" *)  state[0];
  assign _105_ = state[5] |(* src = "cajeroAutomatico.v:187|cajeroAutomatico.v:148|<techmap.v>:445" *)  state[0];
  assign _043_ = DIGITO_STB | rst;
  assign _044_ = rst | _063_;
  assign _045_ = rst | TARJETA_RECIBIDA;
  assign _046_ = rst | _062_;
  assign _053_[2] = ~(* src = "cajeroAutomatico.v:67" *) _054_;
  assign _062_ = ~(* src = "cajeroAutomatico.v:79" *) _055_;
  assign _024_ = ~_043_;
  assign _030_ = ~_044_;
  assign _029_ = ~_057_;
  assign _028_ = ~_058_;
  assign _022_ = ~_045_;
  assign _027_ = ~_046_;
  assign _023_ = ~_059_;
  assign _025_ = ~_060_;
  assign _065_ = MONTO_STB &(* src = "cajeroAutomatico.v:189" *)  _061_;
  assign _066_ = MONTO_STB &(* src = "cajeroAutomatico.v:193" *)  TIPO_TRANS;
  assign _075_[0] = DIGITO_STB ? (* src = "cajeroAutomatico.v:169" *) _009_[0] : digitos_ingresados[0];
  assign _075_[1] = DIGITO_STB ? (* src = "cajeroAutomatico.v:169" *) _009_[1] : digitos_ingresados[1];
  assign _006_[0] = rst ? (* src = "cajeroAutomatico.v:134" *) 1'h0 : _077_[0];
  assign _006_[1] = rst ? (* src = "cajeroAutomatico.v:134" *) 1'h0 : _077_[1];
  assign _078_[0] = DIGITO_STB ? (* src = "cajeroAutomatico.v:169" *) DIGITO[0] : pin_tecleado[0];
  assign _078_[1] = DIGITO_STB ? (* src = "cajeroAutomatico.v:169" *) DIGITO[1] : pin_tecleado[1];
  assign _078_[2] = DIGITO_STB ? (* src = "cajeroAutomatico.v:169" *) DIGITO[2] : pin_tecleado[2];
  assign _078_[3] = DIGITO_STB ? (* src = "cajeroAutomatico.v:169" *) DIGITO[3] : pin_tecleado[3];
  assign _078_[4] = DIGITO_STB ? (* src = "cajeroAutomatico.v:169" *) pin_tecleado[0] : pin_tecleado[4];
  assign _078_[5] = DIGITO_STB ? (* src = "cajeroAutomatico.v:169" *) pin_tecleado[1] : pin_tecleado[5];
  assign _078_[6] = DIGITO_STB ? (* src = "cajeroAutomatico.v:169" *) pin_tecleado[2] : pin_tecleado[6];
  assign _078_[7] = DIGITO_STB ? (* src = "cajeroAutomatico.v:169" *) pin_tecleado[3] : pin_tecleado[7];
  assign _078_[8] = DIGITO_STB ? (* src = "cajeroAutomatico.v:169" *) pin_tecleado[4] : pin_tecleado[8];
  assign _078_[9] = DIGITO_STB ? (* src = "cajeroAutomatico.v:169" *) pin_tecleado[5] : pin_tecleado[9];
  assign _078_[10] = DIGITO_STB ? (* src = "cajeroAutomatico.v:169" *) pin_tecleado[6] : pin_tecleado[10];
  assign _078_[11] = DIGITO_STB ? (* src = "cajeroAutomatico.v:169" *) pin_tecleado[7] : pin_tecleado[11];
  assign _078_[12] = DIGITO_STB ? (* src = "cajeroAutomatico.v:169" *) pin_tecleado[8] : pin_tecleado[12];
  assign _078_[13] = DIGITO_STB ? (* src = "cajeroAutomatico.v:169" *) pin_tecleado[9] : pin_tecleado[13];
  assign _078_[14] = DIGITO_STB ? (* src = "cajeroAutomatico.v:169" *) pin_tecleado[10] : pin_tecleado[14];
  assign _078_[15] = DIGITO_STB ? (* src = "cajeroAutomatico.v:169" *) pin_tecleado[11] : pin_tecleado[15];
  assign _008_[0] = rst ? (* src = "cajeroAutomatico.v:134" *) 1'h0 : _080_[0];
  assign _008_[1] = rst ? (* src = "cajeroAutomatico.v:134" *) 1'h0 : _080_[1];
  assign _008_[2] = rst ? (* src = "cajeroAutomatico.v:134" *) 1'h0 : _080_[2];
  assign _008_[3] = rst ? (* src = "cajeroAutomatico.v:134" *) 1'h0 : _080_[3];
  assign _008_[4] = rst ? (* src = "cajeroAutomatico.v:134" *) 1'h0 : _080_[4];
  assign _008_[5] = rst ? (* src = "cajeroAutomatico.v:134" *) 1'h0 : _080_[5];
  assign _008_[6] = rst ? (* src = "cajeroAutomatico.v:134" *) 1'h0 : _080_[6];
  assign _008_[7] = rst ? (* src = "cajeroAutomatico.v:134" *) 1'h0 : _080_[7];
  assign _008_[8] = rst ? (* src = "cajeroAutomatico.v:134" *) 1'h0 : _080_[8];
  assign _008_[9] = rst ? (* src = "cajeroAutomatico.v:134" *) 1'h0 : _080_[9];
  assign _008_[10] = rst ? (* src = "cajeroAutomatico.v:134" *) 1'h0 : _080_[10];
  assign _008_[11] = rst ? (* src = "cajeroAutomatico.v:134" *) 1'h0 : _080_[11];
  assign _008_[12] = rst ? (* src = "cajeroAutomatico.v:134" *) 1'h0 : _080_[12];
  assign _008_[13] = rst ? (* src = "cajeroAutomatico.v:134" *) 1'h0 : _080_[13];
  assign _008_[14] = rst ? (* src = "cajeroAutomatico.v:134" *) 1'h0 : _080_[14];
  assign _008_[15] = rst ? (* src = "cajeroAutomatico.v:134" *) 1'h0 : _080_[15];
  assign _007_[0] = rst ? (* src = "cajeroAutomatico.v:134" *) 1'h0 : _082_[0];
  assign _007_[1] = rst ? (* src = "cajeroAutomatico.v:134" *) 1'h0 : _082_[1];
  assign _083_ = _064_ ? (* src = "cajeroAutomatico.v:195" *) FONDOS_INSUFICIENTES : 1'h1;
  assign _084_ = _066_ ? (* src = "cajeroAutomatico.v:193" *) _083_ : FONDOS_INSUFICIENTES;
  assign _004_ = rst ? (* src = "cajeroAutomatico.v:134" *) 1'h0 : _086_;
  assign _087_ = _098_ ? (* src = "cajeroAutomatico.v:231" *) BLOQUEO : 1'h1;
  assign _088_ = _056_ ? (* src = "cajeroAutomatico.v:229" *) _087_ : BLOQUEO;
  assign _002_ = rst ? (* src = "cajeroAutomatico.v:134" *) 1'h0 : _090_;
  assign _091_ = _056_ ? (* src = "cajeroAutomatico.v:229" *) ADVERTENCIA : 1'h1;
  assign _000_ = rst ? (* src = "cajeroAutomatico.v:134" *) 1'h0 : _093_;
  assign _005_ = rst ? (* src = "cajeroAutomatico.v:134" *) 1'h0 : _094_;
  assign _095_ = _064_ ? (* src = "cajeroAutomatico.v:195" *) 1'h1 : ENTREGAR_DINERO;
  assign _067_ = _066_ ? (* src = "cajeroAutomatico.v:193" *) _095_ : ENTREGAR_DINERO;
  assign _003_ = rst ? (* src = "cajeroAutomatico.v:134" *) 1'h0 : _069_;
  assign _072_ = _066_ ? (* src = "cajeroAutomatico.v:193" *) _071_ : _070_;
  assign _070_ = _065_ ? (* src = "cajeroAutomatico.v:189" *) 1'h1 : BALANCE_ACTUALIZADO;
  assign _071_ = _064_ ? (* src = "cajeroAutomatico.v:195" *) 1'h1 : _070_;
  assign _001_ = rst ? (* src = "cajeroAutomatico.v:134" *) 1'h0 : _074_;
  assign _077_[0] = _106_ ? (* src = "cajeroAutomatico.v:167|cajeroAutomatico.v:148|<techmap.v>:445" *) _076_[0] : digitos_ingresados[0];
  assign _077_[1] = _106_ ? (* src = "cajeroAutomatico.v:167|cajeroAutomatico.v:148|<techmap.v>:445" *) _076_[1] : digitos_ingresados[1];
  assign _080_[0] = _106_ ? (* src = "cajeroAutomatico.v:167|cajeroAutomatico.v:148|<techmap.v>:445" *) _079_[0] : pin_tecleado[0];
  assign _080_[1] = _106_ ? (* src = "cajeroAutomatico.v:167|cajeroAutomatico.v:148|<techmap.v>:445" *) _079_[1] : pin_tecleado[1];
  assign _080_[2] = _106_ ? (* src = "cajeroAutomatico.v:167|cajeroAutomatico.v:148|<techmap.v>:445" *) _079_[2] : pin_tecleado[2];
  assign _080_[3] = _106_ ? (* src = "cajeroAutomatico.v:167|cajeroAutomatico.v:148|<techmap.v>:445" *) _079_[3] : pin_tecleado[3];
  assign _080_[4] = _106_ ? (* src = "cajeroAutomatico.v:167|cajeroAutomatico.v:148|<techmap.v>:445" *) _079_[4] : pin_tecleado[4];
  assign _080_[5] = _106_ ? (* src = "cajeroAutomatico.v:167|cajeroAutomatico.v:148|<techmap.v>:445" *) _079_[5] : pin_tecleado[5];
  assign _080_[6] = _106_ ? (* src = "cajeroAutomatico.v:167|cajeroAutomatico.v:148|<techmap.v>:445" *) _079_[6] : pin_tecleado[6];
  assign _080_[7] = _106_ ? (* src = "cajeroAutomatico.v:167|cajeroAutomatico.v:148|<techmap.v>:445" *) _079_[7] : pin_tecleado[7];
  assign _080_[8] = _106_ ? (* src = "cajeroAutomatico.v:167|cajeroAutomatico.v:148|<techmap.v>:445" *) _079_[8] : pin_tecleado[8];
  assign _080_[9] = _106_ ? (* src = "cajeroAutomatico.v:167|cajeroAutomatico.v:148|<techmap.v>:445" *) _079_[9] : pin_tecleado[9];
  assign _080_[10] = _106_ ? (* src = "cajeroAutomatico.v:167|cajeroAutomatico.v:148|<techmap.v>:445" *) _079_[10] : pin_tecleado[10];
  assign _080_[11] = _106_ ? (* src = "cajeroAutomatico.v:167|cajeroAutomatico.v:148|<techmap.v>:445" *) _079_[11] : pin_tecleado[11];
  assign _080_[12] = _106_ ? (* src = "cajeroAutomatico.v:167|cajeroAutomatico.v:148|<techmap.v>:445" *) _079_[12] : pin_tecleado[12];
  assign _080_[13] = _106_ ? (* src = "cajeroAutomatico.v:167|cajeroAutomatico.v:148|<techmap.v>:445" *) _079_[13] : pin_tecleado[13];
  assign _080_[14] = _106_ ? (* src = "cajeroAutomatico.v:167|cajeroAutomatico.v:148|<techmap.v>:445" *) _079_[14] : pin_tecleado[14];
  assign _080_[15] = _106_ ? (* src = "cajeroAutomatico.v:167|cajeroAutomatico.v:148|<techmap.v>:445" *) _079_[15] : pin_tecleado[15];
  assign _082_[0] = _107_ ? (* src = "cajeroAutomatico.v:226|cajeroAutomatico.v:148|<techmap.v>:445" *) _081_[0] : intentos[0];
  assign _082_[1] = _107_ ? (* src = "cajeroAutomatico.v:226|cajeroAutomatico.v:148|<techmap.v>:445" *) _081_[1] : intentos[1];
  assign _086_ = _105_ ? (* src = "cajeroAutomatico.v:187|cajeroAutomatico.v:148|<techmap.v>:445" *) _085_[0] : FONDOS_INSUFICIENTES;
  assign _090_ = _107_ ? (* src = "cajeroAutomatico.v:226|cajeroAutomatico.v:148|<techmap.v>:445" *) _089_[0] : BLOQUEO;
  assign _093_ = _107_ ? (* src = "cajeroAutomatico.v:226|cajeroAutomatico.v:148|<techmap.v>:445" *) _092_[0] : ADVERTENCIA;
  assign _094_ = _107_ ? (* src = "cajeroAutomatico.v:226|cajeroAutomatico.v:148|<techmap.v>:445" *) state[3] : PIN_INCORRECTO;
  assign _069_ = _105_ ? (* src = "cajeroAutomatico.v:187|cajeroAutomatico.v:148|<techmap.v>:445" *) _068_[0] : ENTREGAR_DINERO;
  assign _074_ = _105_ ? (* src = "cajeroAutomatico.v:187|cajeroAutomatico.v:148|<techmap.v>:445" *) _073_[0] : BALANCE_ACTUALIZADO;
  assign _099_[0] = ~(* src = "cajeroAutomatico.v:195|<techmap.v>:258" *) BALANCE_INICIAL[0];
  assign _099_[1] = ~(* src = "cajeroAutomatico.v:195|<techmap.v>:258" *) BALANCE_INICIAL[1];
  assign _099_[2] = ~(* src = "cajeroAutomatico.v:195|<techmap.v>:258" *) BALANCE_INICIAL[2];
  assign _099_[3] = ~(* src = "cajeroAutomatico.v:195|<techmap.v>:258" *) BALANCE_INICIAL[3];
  assign _099_[4] = ~(* src = "cajeroAutomatico.v:195|<techmap.v>:258" *) BALANCE_INICIAL[4];
  assign _099_[5] = ~(* src = "cajeroAutomatico.v:195|<techmap.v>:258" *) BALANCE_INICIAL[5];
  assign _099_[6] = ~(* src = "cajeroAutomatico.v:195|<techmap.v>:258" *) BALANCE_INICIAL[6];
  assign _099_[7] = ~(* src = "cajeroAutomatico.v:195|<techmap.v>:258" *) BALANCE_INICIAL[7];
  assign _099_[8] = ~(* src = "cajeroAutomatico.v:195|<techmap.v>:258" *) BALANCE_INICIAL[8];
  assign _099_[9] = ~(* src = "cajeroAutomatico.v:195|<techmap.v>:258" *) BALANCE_INICIAL[9];
  assign _099_[10] = ~(* src = "cajeroAutomatico.v:195|<techmap.v>:258" *) BALANCE_INICIAL[10];
  assign _099_[11] = ~(* src = "cajeroAutomatico.v:195|<techmap.v>:258" *) BALANCE_INICIAL[11];
  assign _099_[12] = ~(* src = "cajeroAutomatico.v:195|<techmap.v>:258" *) BALANCE_INICIAL[12];
  assign _099_[13] = ~(* src = "cajeroAutomatico.v:195|<techmap.v>:258" *) BALANCE_INICIAL[13];
  assign _099_[14] = ~(* src = "cajeroAutomatico.v:195|<techmap.v>:258" *) BALANCE_INICIAL[14];
  assign _099_[15] = ~(* src = "cajeroAutomatico.v:195|<techmap.v>:258" *) BALANCE_INICIAL[15];
  assign _099_[16] = ~(* src = "cajeroAutomatico.v:195|<techmap.v>:258" *) BALANCE_INICIAL[16];
  assign _099_[17] = ~(* src = "cajeroAutomatico.v:195|<techmap.v>:258" *) BALANCE_INICIAL[17];
  assign _099_[18] = ~(* src = "cajeroAutomatico.v:195|<techmap.v>:258" *) BALANCE_INICIAL[18];
  assign _099_[19] = ~(* src = "cajeroAutomatico.v:195|<techmap.v>:258" *) BALANCE_INICIAL[19];
  assign _099_[20] = ~(* src = "cajeroAutomatico.v:195|<techmap.v>:258" *) BALANCE_INICIAL[20];
  assign _099_[21] = ~(* src = "cajeroAutomatico.v:195|<techmap.v>:258" *) BALANCE_INICIAL[21];
  assign _099_[22] = ~(* src = "cajeroAutomatico.v:195|<techmap.v>:258" *) BALANCE_INICIAL[22];
  assign _099_[23] = ~(* src = "cajeroAutomatico.v:195|<techmap.v>:258" *) BALANCE_INICIAL[23];
  assign _099_[24] = ~(* src = "cajeroAutomatico.v:195|<techmap.v>:258" *) BALANCE_INICIAL[24];
  assign _099_[25] = ~(* src = "cajeroAutomatico.v:195|<techmap.v>:258" *) BALANCE_INICIAL[25];
  assign _099_[26] = ~(* src = "cajeroAutomatico.v:195|<techmap.v>:258" *) BALANCE_INICIAL[26];
  assign _099_[27] = ~(* src = "cajeroAutomatico.v:195|<techmap.v>:258" *) BALANCE_INICIAL[27];
  assign _099_[28] = ~(* src = "cajeroAutomatico.v:195|<techmap.v>:258" *) BALANCE_INICIAL[28];
  assign _099_[29] = ~(* src = "cajeroAutomatico.v:195|<techmap.v>:258" *) BALANCE_INICIAL[29];
  assign _099_[30] = ~(* src = "cajeroAutomatico.v:195|<techmap.v>:258" *) BALANCE_INICIAL[30];
  assign _099_[31] = ~(* src = "cajeroAutomatico.v:195|<techmap.v>:258" *) BALANCE_INICIAL[31];
  assign _099_[32] = ~(* src = "cajeroAutomatico.v:195|<techmap.v>:258" *) BALANCE_INICIAL[32];
  assign _099_[33] = ~(* src = "cajeroAutomatico.v:195|<techmap.v>:258" *) BALANCE_INICIAL[33];
  assign _099_[34] = ~(* src = "cajeroAutomatico.v:195|<techmap.v>:258" *) BALANCE_INICIAL[34];
  assign _099_[35] = ~(* src = "cajeroAutomatico.v:195|<techmap.v>:258" *) BALANCE_INICIAL[35];
  assign _099_[36] = ~(* src = "cajeroAutomatico.v:195|<techmap.v>:258" *) BALANCE_INICIAL[36];
  assign _099_[37] = ~(* src = "cajeroAutomatico.v:195|<techmap.v>:258" *) BALANCE_INICIAL[37];
  assign _099_[38] = ~(* src = "cajeroAutomatico.v:195|<techmap.v>:258" *) BALANCE_INICIAL[38];
  assign _099_[39] = ~(* src = "cajeroAutomatico.v:195|<techmap.v>:258" *) BALANCE_INICIAL[39];
  assign _099_[40] = ~(* src = "cajeroAutomatico.v:195|<techmap.v>:258" *) BALANCE_INICIAL[40];
  assign _099_[41] = ~(* src = "cajeroAutomatico.v:195|<techmap.v>:258" *) BALANCE_INICIAL[41];
  assign _099_[42] = ~(* src = "cajeroAutomatico.v:195|<techmap.v>:258" *) BALANCE_INICIAL[42];
  assign _099_[43] = ~(* src = "cajeroAutomatico.v:195|<techmap.v>:258" *) BALANCE_INICIAL[43];
  assign _099_[44] = ~(* src = "cajeroAutomatico.v:195|<techmap.v>:258" *) BALANCE_INICIAL[44];
  assign _099_[45] = ~(* src = "cajeroAutomatico.v:195|<techmap.v>:258" *) BALANCE_INICIAL[45];
  assign _099_[46] = ~(* src = "cajeroAutomatico.v:195|<techmap.v>:258" *) BALANCE_INICIAL[46];
  assign _099_[47] = ~(* src = "cajeroAutomatico.v:195|<techmap.v>:258" *) BALANCE_INICIAL[47];
  assign _099_[48] = ~(* src = "cajeroAutomatico.v:195|<techmap.v>:258" *) BALANCE_INICIAL[48];
  assign _099_[49] = ~(* src = "cajeroAutomatico.v:195|<techmap.v>:258" *) BALANCE_INICIAL[49];
  assign _099_[50] = ~(* src = "cajeroAutomatico.v:195|<techmap.v>:258" *) BALANCE_INICIAL[50];
  assign _099_[51] = ~(* src = "cajeroAutomatico.v:195|<techmap.v>:258" *) BALANCE_INICIAL[51];
  assign _099_[52] = ~(* src = "cajeroAutomatico.v:195|<techmap.v>:258" *) BALANCE_INICIAL[52];
  assign _099_[53] = ~(* src = "cajeroAutomatico.v:195|<techmap.v>:258" *) BALANCE_INICIAL[53];
  assign _099_[54] = ~(* src = "cajeroAutomatico.v:195|<techmap.v>:258" *) BALANCE_INICIAL[54];
  assign _099_[55] = ~(* src = "cajeroAutomatico.v:195|<techmap.v>:258" *) BALANCE_INICIAL[55];
  assign _099_[56] = ~(* src = "cajeroAutomatico.v:195|<techmap.v>:258" *) BALANCE_INICIAL[56];
  assign _099_[57] = ~(* src = "cajeroAutomatico.v:195|<techmap.v>:258" *) BALANCE_INICIAL[57];
  assign _099_[58] = ~(* src = "cajeroAutomatico.v:195|<techmap.v>:258" *) BALANCE_INICIAL[58];
  assign _099_[59] = ~(* src = "cajeroAutomatico.v:195|<techmap.v>:258" *) BALANCE_INICIAL[59];
  assign _099_[60] = ~(* src = "cajeroAutomatico.v:195|<techmap.v>:258" *) BALANCE_INICIAL[60];
  assign _099_[61] = ~(* src = "cajeroAutomatico.v:195|<techmap.v>:258" *) BALANCE_INICIAL[61];
  assign _099_[62] = ~(* src = "cajeroAutomatico.v:195|<techmap.v>:258" *) BALANCE_INICIAL[62];
  assign _099_[63] = ~(* src = "cajeroAutomatico.v:195|<techmap.v>:258" *) BALANCE_INICIAL[63];
  assign _061_ = ~(* src = "cajeroAutomatico.v:189" *) TIPO_TRANS;
  assign _026_ = ~rst;
  assign _103_ = ~(* src = "cajeroAutomatico.v:195" *) _100_[63];
  assign _063_ = ~(* src = "cajeroAutomatico.v:231" *) _098_;
  assign _097_ = ~(* src = "cajeroAutomatico.v:231" *) _096_[31];
  reg \state_reg[0] ;
  always @(posedge clk)
      \state_reg[0]  <= _021_[0];
  assign state[0] = \state_reg[0] ;
  reg \state_reg[1] ;
  always @(posedge clk)
      \state_reg[1]  <= _012_;
  assign state[1] = \state_reg[1] ;
  reg \state_reg[2] ;
  always @(posedge clk)
      \state_reg[2]  <= _021_[2];
  assign state[2] = \state_reg[2] ;
  reg \state_reg[3] ;
  always @(posedge clk)
      \state_reg[3]  <= _016_;
  assign state[3] = \state_reg[3] ;
  reg \state_reg[4] ;
  always @(posedge clk)
      \state_reg[4]  <= _017_;
  assign state[4] = \state_reg[4] ;
  reg \state_reg[5] ;
  always @(posedge clk)
      \state_reg[5]  <= _018_;
  assign state[5] = \state_reg[5] ;
  reg \state_reg[6] ;
  always @(posedge clk)
      \state_reg[6]  <= _021_[6];
  assign state[6] = \state_reg[6] ;
  (* src = "cajeroAutomatico.v:133" *)
  always @(posedge clk)
      BALANCE_ACTUALIZADO <= _001_;
  (* src = "cajeroAutomatico.v:133" *)
  always @(posedge clk)
      ENTREGAR_DINERO <= _003_;
  (* src = "cajeroAutomatico.v:133" *)
  always @(posedge clk)
      PIN_INCORRECTO <= _005_;
  (* src = "cajeroAutomatico.v:133" *)
  always @(posedge clk)
      ADVERTENCIA <= _000_;
  (* src = "cajeroAutomatico.v:133" *)
  always @(posedge clk)
      BLOQUEO <= _002_;
  (* src = "cajeroAutomatico.v:133" *)
  always @(posedge clk)
      FONDOS_INSUFICIENTES <= _004_;
  (* src = "cajeroAutomatico.v:133" *)
  always @(posedge clk)
      intentos[0] <= _007_[0];
  (* src = "cajeroAutomatico.v:133" *)
  always @(posedge clk)
      intentos[1] <= _007_[1];
  (* src = "cajeroAutomatico.v:133" *)
  always @(posedge clk)
      pin_tecleado[0] <= _008_[0];
  (* src = "cajeroAutomatico.v:133" *)
  always @(posedge clk)
      pin_tecleado[1] <= _008_[1];
  (* src = "cajeroAutomatico.v:133" *)
  always @(posedge clk)
      pin_tecleado[2] <= _008_[2];
  (* src = "cajeroAutomatico.v:133" *)
  always @(posedge clk)
      pin_tecleado[3] <= _008_[3];
  (* src = "cajeroAutomatico.v:133" *)
  always @(posedge clk)
      pin_tecleado[4] <= _008_[4];
  (* src = "cajeroAutomatico.v:133" *)
  always @(posedge clk)
      pin_tecleado[5] <= _008_[5];
  (* src = "cajeroAutomatico.v:133" *)
  always @(posedge clk)
      pin_tecleado[6] <= _008_[6];
  (* src = "cajeroAutomatico.v:133" *)
  always @(posedge clk)
      pin_tecleado[7] <= _008_[7];
  (* src = "cajeroAutomatico.v:133" *)
  always @(posedge clk)
      pin_tecleado[8] <= _008_[8];
  (* src = "cajeroAutomatico.v:133" *)
  always @(posedge clk)
      pin_tecleado[9] <= _008_[9];
  (* src = "cajeroAutomatico.v:133" *)
  always @(posedge clk)
      pin_tecleado[10] <= _008_[10];
  (* src = "cajeroAutomatico.v:133" *)
  always @(posedge clk)
      pin_tecleado[11] <= _008_[11];
  (* src = "cajeroAutomatico.v:133" *)
  always @(posedge clk)
      pin_tecleado[12] <= _008_[12];
  (* src = "cajeroAutomatico.v:133" *)
  always @(posedge clk)
      pin_tecleado[13] <= _008_[13];
  (* src = "cajeroAutomatico.v:133" *)
  always @(posedge clk)
      pin_tecleado[14] <= _008_[14];
  (* src = "cajeroAutomatico.v:133" *)
  always @(posedge clk)
      pin_tecleado[15] <= _008_[15];
  (* src = "cajeroAutomatico.v:133" *)
  always @(posedge clk)
      digitos_ingresados[0] <= _006_[0];
  (* src = "cajeroAutomatico.v:133" *)
  always @(posedge clk)
      digitos_ingresados[1] <= _006_[1];
  assign _108_[0] = MONTO[0] &(* src = "cajeroAutomatico.v:195|<techmap.v>:260" *)  _099_[0];
  assign _108_[1] = MONTO[1] &(* src = "cajeroAutomatico.v:195|<techmap.v>:260" *)  _099_[1];
  assign _108_[2] = MONTO[2] &(* src = "cajeroAutomatico.v:195|<techmap.v>:260" *)  _099_[2];
  assign _108_[3] = MONTO[3] &(* src = "cajeroAutomatico.v:195|<techmap.v>:260" *)  _099_[3];
  assign _108_[4] = MONTO[4] &(* src = "cajeroAutomatico.v:195|<techmap.v>:260" *)  _099_[4];
  assign _108_[5] = MONTO[5] &(* src = "cajeroAutomatico.v:195|<techmap.v>:260" *)  _099_[5];
  assign _108_[6] = MONTO[6] &(* src = "cajeroAutomatico.v:195|<techmap.v>:260" *)  _099_[6];
  assign _108_[7] = MONTO[7] &(* src = "cajeroAutomatico.v:195|<techmap.v>:260" *)  _099_[7];
  assign _108_[8] = MONTO[8] &(* src = "cajeroAutomatico.v:195|<techmap.v>:260" *)  _099_[8];
  assign _108_[9] = MONTO[9] &(* src = "cajeroAutomatico.v:195|<techmap.v>:260" *)  _099_[9];
  assign _108_[10] = MONTO[10] &(* src = "cajeroAutomatico.v:195|<techmap.v>:260" *)  _099_[10];
  assign _108_[11] = MONTO[11] &(* src = "cajeroAutomatico.v:195|<techmap.v>:260" *)  _099_[11];
  assign _108_[12] = MONTO[12] &(* src = "cajeroAutomatico.v:195|<techmap.v>:260" *)  _099_[12];
  assign _108_[13] = MONTO[13] &(* src = "cajeroAutomatico.v:195|<techmap.v>:260" *)  _099_[13];
  assign _108_[14] = MONTO[14] &(* src = "cajeroAutomatico.v:195|<techmap.v>:260" *)  _099_[14];
  assign _108_[15] = MONTO[15] &(* src = "cajeroAutomatico.v:195|<techmap.v>:260" *)  _099_[15];
  assign _108_[16] = MONTO[16] &(* src = "cajeroAutomatico.v:195|<techmap.v>:260" *)  _099_[16];
  assign _108_[17] = MONTO[17] &(* src = "cajeroAutomatico.v:195|<techmap.v>:260" *)  _099_[17];
  assign _108_[18] = MONTO[18] &(* src = "cajeroAutomatico.v:195|<techmap.v>:260" *)  _099_[18];
  assign _108_[19] = MONTO[19] &(* src = "cajeroAutomatico.v:195|<techmap.v>:260" *)  _099_[19];
  assign _108_[20] = MONTO[20] &(* src = "cajeroAutomatico.v:195|<techmap.v>:260" *)  _099_[20];
  assign _108_[21] = MONTO[21] &(* src = "cajeroAutomatico.v:195|<techmap.v>:260" *)  _099_[21];
  assign _108_[22] = MONTO[22] &(* src = "cajeroAutomatico.v:195|<techmap.v>:260" *)  _099_[22];
  assign _108_[23] = MONTO[23] &(* src = "cajeroAutomatico.v:195|<techmap.v>:260" *)  _099_[23];
  assign _108_[24] = MONTO[24] &(* src = "cajeroAutomatico.v:195|<techmap.v>:260" *)  _099_[24];
  assign _108_[25] = MONTO[25] &(* src = "cajeroAutomatico.v:195|<techmap.v>:260" *)  _099_[25];
  assign _108_[26] = MONTO[26] &(* src = "cajeroAutomatico.v:195|<techmap.v>:260" *)  _099_[26];
  assign _108_[27] = MONTO[27] &(* src = "cajeroAutomatico.v:195|<techmap.v>:260" *)  _099_[27];
  assign _108_[28] = MONTO[28] &(* src = "cajeroAutomatico.v:195|<techmap.v>:260" *)  _099_[28];
  assign _108_[29] = MONTO[29] &(* src = "cajeroAutomatico.v:195|<techmap.v>:260" *)  _099_[29];
  assign _108_[30] = MONTO[30] &(* src = "cajeroAutomatico.v:195|<techmap.v>:260" *)  _099_[30];
  assign _108_[31] = MONTO[31] &(* src = "cajeroAutomatico.v:195|<techmap.v>:260" *)  _099_[31];
  assign _101_[0] = MONTO[0] ^(* src = "cajeroAutomatico.v:195|<techmap.v>:262" *)  _099_[0];
  assign _102_[1] = MONTO[1] ^(* src = "cajeroAutomatico.v:195|<techmap.v>:262" *)  _099_[1];
  assign _102_[2] = MONTO[2] ^(* src = "cajeroAutomatico.v:195|<techmap.v>:262" *)  _099_[2];
  assign _102_[3] = MONTO[3] ^(* src = "cajeroAutomatico.v:195|<techmap.v>:262" *)  _099_[3];
  assign _102_[4] = MONTO[4] ^(* src = "cajeroAutomatico.v:195|<techmap.v>:262" *)  _099_[4];
  assign _102_[5] = MONTO[5] ^(* src = "cajeroAutomatico.v:195|<techmap.v>:262" *)  _099_[5];
  assign _102_[6] = MONTO[6] ^(* src = "cajeroAutomatico.v:195|<techmap.v>:262" *)  _099_[6];
  assign _102_[7] = MONTO[7] ^(* src = "cajeroAutomatico.v:195|<techmap.v>:262" *)  _099_[7];
  assign _102_[8] = MONTO[8] ^(* src = "cajeroAutomatico.v:195|<techmap.v>:262" *)  _099_[8];
  assign _102_[9] = MONTO[9] ^(* src = "cajeroAutomatico.v:195|<techmap.v>:262" *)  _099_[9];
  assign _102_[10] = MONTO[10] ^(* src = "cajeroAutomatico.v:195|<techmap.v>:262" *)  _099_[10];
  assign _102_[11] = MONTO[11] ^(* src = "cajeroAutomatico.v:195|<techmap.v>:262" *)  _099_[11];
  assign _102_[12] = MONTO[12] ^(* src = "cajeroAutomatico.v:195|<techmap.v>:262" *)  _099_[12];
  assign _102_[13] = MONTO[13] ^(* src = "cajeroAutomatico.v:195|<techmap.v>:262" *)  _099_[13];
  assign _102_[14] = MONTO[14] ^(* src = "cajeroAutomatico.v:195|<techmap.v>:262" *)  _099_[14];
  assign _102_[15] = MONTO[15] ^(* src = "cajeroAutomatico.v:195|<techmap.v>:262" *)  _099_[15];
  assign _102_[16] = MONTO[16] ^(* src = "cajeroAutomatico.v:195|<techmap.v>:262" *)  _099_[16];
  assign _102_[17] = MONTO[17] ^(* src = "cajeroAutomatico.v:195|<techmap.v>:262" *)  _099_[17];
  assign _102_[18] = MONTO[18] ^(* src = "cajeroAutomatico.v:195|<techmap.v>:262" *)  _099_[18];
  assign _102_[19] = MONTO[19] ^(* src = "cajeroAutomatico.v:195|<techmap.v>:262" *)  _099_[19];
  assign _102_[20] = MONTO[20] ^(* src = "cajeroAutomatico.v:195|<techmap.v>:262" *)  _099_[20];
  assign _102_[21] = MONTO[21] ^(* src = "cajeroAutomatico.v:195|<techmap.v>:262" *)  _099_[21];
  assign _102_[22] = MONTO[22] ^(* src = "cajeroAutomatico.v:195|<techmap.v>:262" *)  _099_[22];
  assign _102_[23] = MONTO[23] ^(* src = "cajeroAutomatico.v:195|<techmap.v>:262" *)  _099_[23];
  assign _102_[24] = MONTO[24] ^(* src = "cajeroAutomatico.v:195|<techmap.v>:262" *)  _099_[24];
  assign _102_[25] = MONTO[25] ^(* src = "cajeroAutomatico.v:195|<techmap.v>:262" *)  _099_[25];
  assign _102_[26] = MONTO[26] ^(* src = "cajeroAutomatico.v:195|<techmap.v>:262" *)  _099_[26];
  assign _102_[27] = MONTO[27] ^(* src = "cajeroAutomatico.v:195|<techmap.v>:262" *)  _099_[27];
  assign _102_[28] = MONTO[28] ^(* src = "cajeroAutomatico.v:195|<techmap.v>:262" *)  _099_[28];
  assign _102_[29] = MONTO[29] ^(* src = "cajeroAutomatico.v:195|<techmap.v>:262" *)  _099_[29];
  assign _102_[30] = MONTO[30] ^(* src = "cajeroAutomatico.v:195|<techmap.v>:262" *)  _099_[30];
  assign _102_[31] = MONTO[31] ^(* src = "cajeroAutomatico.v:195|<techmap.v>:262" *)  _099_[31];
  assign _010_[1] = intentos[1] ^(* src = "cajeroAutomatico.v:228|cajeroAutomatico.v:171|<techmap.v>:263" *)  intentos[0];
  assign _010_[0] = intentos[0] ^(* src = "cajeroAutomatico.v:228|cajeroAutomatico.v:171|<techmap.v>:262" *)  1'h1;
  assign _109_ = _102_[1] &(* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)  _100_[0];
  assign _110_ = _102_[3] &(* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)  _108_[2];
  assign _111_ = _102_[5] &(* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)  _108_[4];
  assign _112_ = _102_[7] &(* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)  _108_[6];
  assign _113_ = _102_[9] &(* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)  _108_[8];
  assign _114_ = _102_[11] &(* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)  _108_[10];
  assign _115_ = _102_[13] &(* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)  _108_[12];
  assign _116_ = _102_[15] &(* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)  _108_[14];
  assign _117_ = _102_[17] &(* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)  _108_[16];
  assign _118_ = _102_[19] &(* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)  _108_[18];
  assign _119_ = _102_[21] &(* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)  _108_[20];
  assign _120_ = _102_[23] &(* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)  _108_[22];
  assign _121_ = _102_[25] &(* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)  _108_[24];
  assign _122_ = _102_[27] &(* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)  _108_[26];
  assign _123_ = _102_[29] &(* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)  _108_[28];
  assign _124_ = _102_[31] &(* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)  _108_[30];
  assign _125_ = _037_[1] &(* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)  _100_[1];
  assign _126_ = _037_[3] &(* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)  _141_;
  assign _127_ = _037_[5] &(* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)  _143_;
  assign _128_ = _037_[7] &(* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)  _145_;
  assign _129_ = _037_[9] &(* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)  _147_;
  assign _130_ = _037_[11] &(* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)  _149_;
  assign _131_ = _037_[13] &(* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)  _151_;
  assign _132_ = _037_[15] &(* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)  _153_;
  assign _133_ = _038_[1] &(* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)  _100_[3];
  assign _134_ = _038_[3] &(* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)  _156_;
  assign _135_ = _038_[5] &(* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)  _158_;
  assign _136_ = _038_[7] &(* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)  _160_;
  assign _137_ = _039_[1] &(* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)  _100_[7];
  assign _138_ = _039_[3] &(* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)  _163_;
  assign _139_ = _040_[1] &(* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)  _100_[15];
  assign _100_[63] = _041_[1] &(* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)  _100_[31];
  assign _037_[1] = _102_[3] &(* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:222" *)  _102_[2];
  assign _037_[2] = _102_[5] &(* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:222" *)  _102_[4];
  assign _037_[3] = _102_[7] &(* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:222" *)  _102_[6];
  assign _037_[4] = _102_[9] &(* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:222" *)  _102_[8];
  assign _037_[7] = _102_[15] &(* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:222" *)  _102_[14];
  assign _037_[8] = _102_[17] &(* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:222" *)  _102_[16];
  assign _037_[9] = _102_[19] &(* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:222" *)  _102_[18];
  assign _037_[10] = _102_[21] &(* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:222" *)  _102_[20];
  assign _037_[11] = _102_[23] &(* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:222" *)  _102_[22];
  assign _037_[12] = _102_[25] &(* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:222" *)  _102_[24];
  assign _037_[13] = _102_[27] &(* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:222" *)  _102_[26];
  assign _037_[15] = _102_[31] &(* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:222" *)  _102_[30];
  assign _037_[17] = _099_[35] &(* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:222" *)  _099_[34];
  assign _037_[18] = _099_[37] &(* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:222" *)  _099_[36];
  assign _037_[19] = _099_[39] &(* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:222" *)  _099_[38];
  assign _037_[20] = _099_[41] &(* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:222" *)  _099_[40];
  assign _037_[21] = _099_[43] &(* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:222" *)  _099_[42];
  assign _037_[22] = _099_[45] &(* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:222" *)  _099_[44];
  assign _037_[23] = _099_[47] &(* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:222" *)  _099_[46];
  assign _037_[24] = _099_[49] &(* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:222" *)  _099_[48];
  assign _037_[25] = _099_[51] &(* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:222" *)  _099_[50];
  assign _037_[26] = _099_[53] &(* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:222" *)  _099_[52];
  assign _037_[27] = _099_[55] &(* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:222" *)  _099_[54];
  assign _037_[28] = _099_[57] &(* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:222" *)  _099_[56];
  assign _037_[29] = _099_[59] &(* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:222" *)  _099_[58];
  assign _037_[31] = _099_[63] &(* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:222" *)  _099_[62];
  assign _038_[1] = _037_[3] &(* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:222" *)  _037_[2];
  assign _038_[3] = _037_[7] &(* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:222" *)  _037_[6];
  assign _038_[4] = _037_[9] &(* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:222" *)  _037_[8];
  assign _038_[5] = _037_[11] &(* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:222" *)  _037_[10];
  assign _038_[6] = _037_[13] &(* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:222" *)  _037_[12];
  assign _038_[8] = _037_[17] &(* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:222" *)  _037_[16];
  assign _038_[9] = _037_[19] &(* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:222" *)  _037_[18];
  assign _038_[10] = _037_[21] &(* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:222" *)  _037_[20];
  assign _038_[12] = _037_[25] &(* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:222" *)  _037_[24];
  assign _038_[13] = _037_[27] &(* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:222" *)  _037_[26];
  assign _038_[14] = _037_[29] &(* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:222" *)  _037_[28];
  assign _038_[15] = _037_[31] &(* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:222" *)  _037_[30];
  assign _039_[1] = _038_[3] &(* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:222" *)  _038_[2];
  assign _039_[3] = _038_[7] &(* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:222" *)  _038_[6];
  assign _039_[4] = _038_[9] &(* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:222" *)  _038_[8];
  assign _039_[5] = _038_[11] &(* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:222" *)  _038_[10];
  assign _039_[6] = _038_[13] &(* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:222" *)  _038_[12];
  assign _040_[1] = _039_[3] &(* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:222" *)  _039_[2];
  assign _040_[2] = _039_[5] &(* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:222" *)  _039_[4];
  assign _040_[3] = _039_[7] &(* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:222" *)  _039_[6];
  assign _041_[1] = _040_[3] &(* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:222" *)  _040_[2];
  assign _100_[0] = _108_[0] |(* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:212" *)  _101_[0];
  assign _100_[1] = _108_[1] |(* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)  _109_;
  assign _140_ = _108_[3] |(* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)  _110_;
  assign _141_ = _108_[5] |(* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)  _111_;
  assign _142_ = _108_[7] |(* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)  _112_;
  assign _143_ = _108_[9] |(* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)  _113_;
  assign _144_ = _108_[11] |(* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)  _114_;
  assign _145_ = _108_[13] |(* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)  _115_;
  assign _146_ = _108_[15] |(* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)  _116_;
  assign _147_ = _108_[17] |(* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)  _117_;
  assign _148_ = _108_[19] |(* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)  _118_;
  assign _149_ = _108_[21] |(* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)  _119_;
  assign _150_ = _108_[23] |(* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)  _120_;
  assign _151_ = _108_[25] |(* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)  _121_;
  assign _152_ = _108_[27] |(* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)  _122_;
  assign _153_ = _108_[29] |(* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)  _123_;
  assign _154_ = _108_[31] |(* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)  _124_;
  assign _100_[3] = _140_ |(* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)  _125_;
  assign _155_ = _142_ |(* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)  _126_;
  assign _156_ = _144_ |(* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)  _127_;
  assign _157_ = _146_ |(* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)  _128_;
  assign _158_ = _148_ |(* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)  _129_;
  assign _159_ = _150_ |(* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)  _130_;
  assign _160_ = _152_ |(* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)  _131_;
  assign _161_ = _154_ |(* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)  _132_;
  assign _100_[7] = _155_ |(* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)  _133_;
  assign _162_ = _157_ |(* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)  _134_;
  assign _163_ = _159_ |(* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)  _135_;
  assign _164_ = _161_ |(* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)  _136_;
  assign _100_[15] = _162_ |(* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)  _137_;
  assign _165_ = _164_ |(* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)  _138_;
  assign _100_[31] = _165_ |(* src = "cajeroAutomatico.v:195|<techmap.v>:260|<techmap.v>:221" *)  _139_;
  assign _096_[31] = intentos[1] &(* src = "cajeroAutomatico.v:231|<techmap.v>:260|<techmap.v>:221" *)  _096_[0];
  assign _096_[0] = intentos[0] |(* src = "cajeroAutomatico.v:231|<techmap.v>:260|<techmap.v>:212" *)  _010_[0];
  assign _013_ = _024_ & state[2];
  assign _012_ = _023_ & state[6];
  assign _047_[1] = digitos_ingresados[1] ^(* src = "cajeroAutomatico.v:67" *)  1'h1;
  assign _048_[0] = PIN[0] ^(* src = "cajeroAutomatico.v:79" *)  pin_tecleado[0];
  assign _048_[1] = PIN[1] ^(* src = "cajeroAutomatico.v:79" *)  pin_tecleado[1];
  assign _048_[2] = PIN[2] ^(* src = "cajeroAutomatico.v:79" *)  pin_tecleado[2];
  assign _048_[3] = PIN[3] ^(* src = "cajeroAutomatico.v:79" *)  pin_tecleado[3];
  assign _048_[4] = PIN[4] ^(* src = "cajeroAutomatico.v:79" *)  pin_tecleado[4];
  assign _048_[5] = PIN[5] ^(* src = "cajeroAutomatico.v:79" *)  pin_tecleado[5];
  assign _048_[6] = PIN[6] ^(* src = "cajeroAutomatico.v:79" *)  pin_tecleado[6];
  assign _048_[7] = PIN[7] ^(* src = "cajeroAutomatico.v:79" *)  pin_tecleado[7];
  assign _048_[8] = PIN[8] ^(* src = "cajeroAutomatico.v:79" *)  pin_tecleado[8];
  assign _048_[9] = PIN[9] ^(* src = "cajeroAutomatico.v:79" *)  pin_tecleado[9];
  assign _048_[10] = PIN[10] ^(* src = "cajeroAutomatico.v:79" *)  pin_tecleado[10];
  assign _048_[11] = PIN[11] ^(* src = "cajeroAutomatico.v:79" *)  pin_tecleado[11];
  assign _048_[12] = PIN[12] ^(* src = "cajeroAutomatico.v:79" *)  pin_tecleado[12];
  assign _048_[13] = PIN[13] ^(* src = "cajeroAutomatico.v:79" *)  pin_tecleado[13];
  assign _048_[14] = PIN[14] ^(* src = "cajeroAutomatico.v:79" *)  pin_tecleado[14];
  assign _048_[15] = PIN[15] ^(* src = "cajeroAutomatico.v:79" *)  pin_tecleado[15];
  assign _049_[1] = intentos[1] ^(* src = "cajeroAutomatico.v:229" *)  1'h1;
  assign _020_ = _030_ & state[3];
  assign _019_ = _029_ & state[2];
  assign _050_[2] = _053_[2] ^ 1'h1;
  assign _018_ = _026_ & state[1];
  assign _051_[1] = TARJETA_RECIBIDA ^ 1'h1;
  assign _017_ = _028_ & state[0];
  assign _016_ = _027_ & state[6];
  assign _011_ = _022_ & state[0];
  assign _052_[1] = _062_ ^ 1'h1;
  assign _015_ = _026_ & state[4];
  assign _014_ = _025_ & state[2];
  assign _050_[0] = DIGITO_STB ^ 1'h1;
  assign _098_ = _097_ | _042_[0];
  assign _076_[0] = _075_[0] &(* src = "cajeroAutomatico.v:167|cajeroAutomatico.v:148|<techmap.v>:434" *)  state[2];
  assign _076_[1] = _075_[1] &(* src = "cajeroAutomatico.v:167|cajeroAutomatico.v:148|<techmap.v>:434" *)  state[2];
  assign _079_[0] = _078_[0] &(* src = "cajeroAutomatico.v:167|cajeroAutomatico.v:148|<techmap.v>:434" *)  state[2];
  assign _079_[1] = _078_[1] &(* src = "cajeroAutomatico.v:167|cajeroAutomatico.v:148|<techmap.v>:434" *)  state[2];
  assign _079_[2] = _078_[2] &(* src = "cajeroAutomatico.v:167|cajeroAutomatico.v:148|<techmap.v>:434" *)  state[2];
  assign _079_[3] = _078_[3] &(* src = "cajeroAutomatico.v:167|cajeroAutomatico.v:148|<techmap.v>:434" *)  state[2];
  assign _079_[4] = _078_[4] &(* src = "cajeroAutomatico.v:167|cajeroAutomatico.v:148|<techmap.v>:434" *)  state[2];
  assign _079_[5] = _078_[5] &(* src = "cajeroAutomatico.v:167|cajeroAutomatico.v:148|<techmap.v>:434" *)  state[2];
  assign _079_[6] = _078_[6] &(* src = "cajeroAutomatico.v:167|cajeroAutomatico.v:148|<techmap.v>:434" *)  state[2];
  assign _079_[7] = _078_[7] &(* src = "cajeroAutomatico.v:167|cajeroAutomatico.v:148|<techmap.v>:434" *)  state[2];
  assign _079_[8] = _078_[8] &(* src = "cajeroAutomatico.v:167|cajeroAutomatico.v:148|<techmap.v>:434" *)  state[2];
  assign _079_[9] = _078_[9] &(* src = "cajeroAutomatico.v:167|cajeroAutomatico.v:148|<techmap.v>:434" *)  state[2];
  assign _079_[10] = _078_[10] &(* src = "cajeroAutomatico.v:167|cajeroAutomatico.v:148|<techmap.v>:434" *)  state[2];
  assign _079_[11] = _078_[11] &(* src = "cajeroAutomatico.v:167|cajeroAutomatico.v:148|<techmap.v>:434" *)  state[2];
  assign _079_[12] = _078_[12] &(* src = "cajeroAutomatico.v:167|cajeroAutomatico.v:148|<techmap.v>:434" *)  state[2];
  assign _079_[13] = _078_[13] &(* src = "cajeroAutomatico.v:167|cajeroAutomatico.v:148|<techmap.v>:434" *)  state[2];
  assign _079_[14] = _078_[14] &(* src = "cajeroAutomatico.v:167|cajeroAutomatico.v:148|<techmap.v>:434" *)  state[2];
  assign _079_[15] = _078_[15] &(* src = "cajeroAutomatico.v:167|cajeroAutomatico.v:148|<techmap.v>:434" *)  state[2];
  assign _081_[0] = _010_[0] &(* src = "cajeroAutomatico.v:226|cajeroAutomatico.v:148|<techmap.v>:434" *)  state[3];
  assign _081_[1] = _010_[1] &(* src = "cajeroAutomatico.v:226|cajeroAutomatico.v:148|<techmap.v>:434" *)  state[3];
  assign _085_[0] = _084_ &(* src = "cajeroAutomatico.v:187|cajeroAutomatico.v:148|<techmap.v>:434" *)  state[5];
  assign _089_[0] = _088_ &(* src = "cajeroAutomatico.v:226|cajeroAutomatico.v:148|<techmap.v>:434" *)  state[3];
  assign _092_[0] = _091_ &(* src = "cajeroAutomatico.v:226|cajeroAutomatico.v:148|<techmap.v>:434" *)  state[3];
  assign _068_[0] = _067_ &(* src = "cajeroAutomatico.v:187|cajeroAutomatico.v:148|<techmap.v>:434" *)  state[5];
  assign _073_[0] = _072_ &(* src = "cajeroAutomatico.v:187|cajeroAutomatico.v:148|<techmap.v>:434" *)  state[5];
  assign _009_[1] = digitos_ingresados[1] ^(* src = "cajeroAutomatico.v:171|<techmap.v>:263" *)  digitos_ingresados[0];
  assign _009_[0] = digitos_ingresados[0] ^(* src = "cajeroAutomatico.v:171|<techmap.v>:262" *)  1'h1;
  assign _009_[31:3] = 29'h00000000;
  assign _010_[31:3] = 29'h00000000;
  assign { _021_[5:3], _021_[1] } = { _018_, _017_, _016_, _012_ };
  assign _042_[15:1] = 15'h7fff;
  assign _047_[0] = _009_[0];
  assign _049_[0] = intentos[0];
  assign _050_[1] = rst;
  assign _051_[0] = rst;
  assign _052_[0] = rst;
  assign _053_[1:0] = { rst, _050_[0] };
  assign _068_[1] = 1'h0;
  assign _073_[1] = 1'h0;
  assign _076_[3:2] = 2'h0;
  assign _079_[31:16] = 16'h0000;
  assign _081_[3:2] = 2'h0;
  assign _085_[1] = 1'h0;
  assign _089_[1] = 1'h0;
  assign _092_[1] = 1'h0;
  assign _096_[30:1] = { _096_[31], _096_[31], _096_[31], _096_[31], _096_[31], _096_[31], _096_[31], _096_[31], _096_[31], _096_[31], _096_[31], _096_[31], _096_[31], _096_[31], _096_[31], _096_[31], _096_[31], _096_[31], _096_[31], _096_[31], _096_[31], _096_[31], _096_[31], _096_[31], _096_[31], _096_[31], _096_[31], _096_[31], _096_[31], _096_[31] };
  assign { _102_[63:32], _102_[0] } = { _099_[63:32], _101_[0] };
  assign _108_[63:32] = 32'd0;
endmodule
