/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "cajeroAutomatico.v:1" *)
module cajero_automatico(clk, rst, TARJETA_RECIBIDA, TIPO_TRANS, MONTO_STB, DIGITO_STB, DIGITO, PIN, MONTO, BALANCE_INICIAL, BALANCE_ACTUALIZADO, ENTREGAR_DINERO, PIN_INCORRECTO, ADVERTENCIA, BLOQUEO, FONDOS_INSUFICIENTES);
  (* src = "cajeroAutomatico.v:133" *)
  wire _0000_;
  (* src = "cajeroAutomatico.v:133" *)
  wire _0001_;
  (* src = "cajeroAutomatico.v:133" *)
  wire _0002_;
  (* src = "cajeroAutomatico.v:133" *)
  wire _0003_;
  (* src = "cajeroAutomatico.v:133" *)
  wire _0004_;
  (* src = "cajeroAutomatico.v:133" *)
  wire _0005_;
  (* src = "cajeroAutomatico.v:133" *)
  wire [1:0] _0006_;
  (* src = "cajeroAutomatico.v:133" *)
  wire [1:0] _0007_;
  (* src = "cajeroAutomatico.v:133" *)
  wire [15:0] _0008_;
  wire _0009_;
  wire _0010_;
  wire _0011_;
  wire _0012_;
  wire _0013_;
  wire _0014_;
  wire _0015_;
  wire _0016_;
  wire _0017_;
  wire _0018_;
  wire _0019_;
  wire _0020_;
  wire _0021_;
  wire _0022_;
  wire _0023_;
  wire _0024_;
  wire _0025_;
  wire _0026_;
  wire _0027_;
  wire _0028_;
  wire _0029_;
  wire _0030_;
  wire _0031_;
  wire _0032_;
  wire _0033_;
  wire _0034_;
  wire _0035_;
  wire _0036_;
  wire _0037_;
  wire _0038_;
  wire _0039_;
  wire _0040_;
  wire _0041_;
  wire _0042_;
  wire _0043_;
  wire _0044_;
  wire _0045_;
  wire _0046_;
  wire _0047_;
  wire _0048_;
  wire _0049_;
  wire _0050_;
  wire _0051_;
  wire _0052_;
  wire _0053_;
  wire _0054_;
  wire _0055_;
  wire _0056_;
  wire _0057_;
  wire _0058_;
  wire _0059_;
  wire _0060_;
  wire _0061_;
  wire _0062_;
  wire _0063_;
  wire _0064_;
  wire _0065_;
  wire _0066_;
  wire _0067_;
  wire _0068_;
  wire _0069_;
  wire _0070_;
  wire _0071_;
  wire _0072_;
  wire _0073_;
  wire _0074_;
  wire _0075_;
  wire _0076_;
  wire _0077_;
  wire _0078_;
  wire _0079_;
  wire _0080_;
  wire _0081_;
  wire _0082_;
  wire _0083_;
  wire _0084_;
  wire _0085_;
  wire _0086_;
  wire _0087_;
  wire _0088_;
  wire _0089_;
  wire _0090_;
  wire _0091_;
  wire _0092_;
  wire _0093_;
  wire _0094_;
  wire _0095_;
  wire _0096_;
  wire _0097_;
  wire _0098_;
  wire _0099_;
  wire _0100_;
  wire _0101_;
  wire _0102_;
  wire _0103_;
  wire _0104_;
  wire _0105_;
  wire _0106_;
  wire _0107_;
  wire _0108_;
  wire _0109_;
  wire _0110_;
  wire _0111_;
  wire _0112_;
  wire _0113_;
  wire _0114_;
  wire _0115_;
  wire _0116_;
  wire _0117_;
  wire _0118_;
  wire _0119_;
  wire _0120_;
  wire _0121_;
  wire _0122_;
  wire _0123_;
  wire _0124_;
  wire _0125_;
  wire _0126_;
  wire _0127_;
  wire _0128_;
  wire _0129_;
  wire _0130_;
  wire _0131_;
  wire _0132_;
  wire _0133_;
  wire _0134_;
  wire _0135_;
  wire _0136_;
  wire _0137_;
  wire _0138_;
  wire _0139_;
  wire _0140_;
  wire _0141_;
  wire _0142_;
  wire _0143_;
  wire _0144_;
  wire _0145_;
  wire _0146_;
  wire _0147_;
  wire _0148_;
  wire _0149_;
  wire _0150_;
  wire _0151_;
  wire _0152_;
  wire _0153_;
  wire _0154_;
  wire _0155_;
  wire _0156_;
  wire _0157_;
  wire _0158_;
  wire _0159_;
  wire _0160_;
  wire _0161_;
  wire _0162_;
  wire _0163_;
  wire _0164_;
  wire _0165_;
  wire _0166_;
  wire _0167_;
  wire _0168_;
  wire _0169_;
  wire _0170_;
  wire _0171_;
  wire _0172_;
  wire _0173_;
  wire _0174_;
  wire _0175_;
  wire _0176_;
  wire _0177_;
  wire _0178_;
  wire _0179_;
  wire _0180_;
  wire _0181_;
  wire _0182_;
  wire _0183_;
  wire _0184_;
  wire _0185_;
  wire _0186_;
  wire _0187_;
  wire _0188_;
  wire _0189_;
  wire _0190_;
  wire _0191_;
  wire _0192_;
  wire _0193_;
  wire _0194_;
  wire _0195_;
  wire _0196_;
  wire _0197_;
  wire _0198_;
  wire _0199_;
  wire _0200_;
  wire _0201_;
  wire _0202_;
  wire _0203_;
  wire _0204_;
  wire _0205_;
  wire _0206_;
  wire _0207_;
  wire _0208_;
  wire _0209_;
  wire _0210_;
  wire _0211_;
  wire _0212_;
  wire _0213_;
  wire _0214_;
  wire _0215_;
  wire _0216_;
  wire _0217_;
  wire _0218_;
  wire _0219_;
  wire _0220_;
  wire _0221_;
  wire _0222_;
  wire _0223_;
  wire _0224_;
  wire _0225_;
  wire _0226_;
  wire _0227_;
  wire _0228_;
  wire _0229_;
  wire _0230_;
  wire _0231_;
  wire _0232_;
  wire _0233_;
  wire _0234_;
  wire _0235_;
  wire _0236_;
  wire _0237_;
  wire _0238_;
  wire _0239_;
  wire _0240_;
  wire _0241_;
  wire _0242_;
  wire _0243_;
  wire _0244_;
  wire _0245_;
  wire _0246_;
  wire _0247_;
  wire _0248_;
  wire _0249_;
  wire _0250_;
  wire _0251_;
  wire _0252_;
  wire _0253_;
  wire _0254_;
  wire _0255_;
  wire _0256_;
  wire _0257_;
  wire _0258_;
  wire _0259_;
  wire _0260_;
  wire _0261_;
  wire _0262_;
  wire _0263_;
  wire _0264_;
  wire _0265_;
  wire _0266_;
  wire _0267_;
  wire _0268_;
  wire _0269_;
  wire _0270_;
  wire _0271_;
  wire _0272_;
  wire _0273_;
  wire _0274_;
  wire _0275_;
  wire _0276_;
  wire _0277_;
  wire _0278_;
  wire _0279_;
  wire _0280_;
  wire _0281_;
  wire _0282_;
  wire _0283_;
  wire _0284_;
  wire _0285_;
  wire _0286_;
  wire _0287_;
  wire _0288_;
  wire _0289_;
  wire _0290_;
  wire _0291_;
  wire _0292_;
  wire _0293_;
  wire _0294_;
  wire _0295_;
  wire _0296_;
  wire _0297_;
  wire _0298_;
  wire _0299_;
  wire _0300_;
  wire _0301_;
  wire _0302_;
  wire _0303_;
  wire _0304_;
  wire _0305_;
  wire _0306_;
  wire _0307_;
  wire _0308_;
  wire _0309_;
  wire _0310_;
  wire _0311_;
  wire _0312_;
  wire _0313_;
  wire _0314_;
  wire _0315_;
  wire _0316_;
  wire _0317_;
  wire _0318_;
  wire _0319_;
  wire _0320_;
  wire _0321_;
  wire _0322_;
  wire _0323_;
  wire _0324_;
  wire _0325_;
  wire _0326_;
  wire _0327_;
  wire _0328_;
  wire _0329_;
  wire _0330_;
  wire _0331_;
  wire _0332_;
  wire _0333_;
  wire _0334_;
  wire _0335_;
  wire _0336_;
  wire _0337_;
  wire _0338_;
  wire _0339_;
  wire _0340_;
  wire _0341_;
  wire _0342_;
  wire _0343_;
  wire _0344_;
  wire _0345_;
  wire _0346_;
  wire _0347_;
  wire _0348_;
  wire _0349_;
  wire _0350_;
  wire _0351_;
  wire _0352_;
  wire _0353_;
  wire _0354_;
  wire _0355_;
  wire _0356_;
  wire _0357_;
  wire _0358_;
  wire _0359_;
  wire _0360_;
  wire _0361_;
  wire _0362_;
  wire _0363_;
  wire _0364_;
  wire _0365_;
  wire _0366_;
  wire _0367_;
  wire _0368_;
  wire _0369_;
  wire _0370_;
  wire _0371_;
  wire _0372_;
  wire _0373_;
  wire _0374_;
  wire _0375_;
  wire _0376_;
  wire _0377_;
  wire _0378_;
  wire _0379_;
  wire _0380_;
  wire _0381_;
  wire _0382_;
  wire _0383_;
  wire _0384_;
  wire _0385_;
  wire _0386_;
  wire _0387_;
  wire _0388_;
  wire _0389_;
  wire _0390_;
  wire _0391_;
  wire _0392_;
  wire _0393_;
  wire _0394_;
  wire _0395_;
  wire _0396_;
  wire _0397_;
  wire _0398_;
  wire _0399_;
  wire _0400_;
  wire _0401_;
  wire _0402_;
  wire _0403_;
  wire _0404_;
  wire _0405_;
  wire _0406_;
  wire _0407_;
  wire _0408_;
  wire _0409_;
  wire _0410_;
  wire _0411_;
  wire _0412_;
  wire _0413_;
  wire _0414_;
  wire _0415_;
  wire _0416_;
  wire _0417_;
  wire _0418_;
  wire _0419_;
  wire _0420_;
  wire _0421_;
  wire _0422_;
  wire _0423_;
  wire _0424_;
  wire _0425_;
  wire _0426_;
  wire _0427_;
  wire _0428_;
  wire _0429_;
  wire _0430_;
  wire _0431_;
  wire _0432_;
  wire _0433_;
  wire _0434_;
  wire _0435_;
  wire _0436_;
  wire _0437_;
  wire _0438_;
  wire _0439_;
  wire _0440_;
  wire _0441_;
  wire _0442_;
  wire _0443_;
  wire _0444_;
  wire _0445_;
  wire _0446_;
  wire _0447_;
  wire _0448_;
  wire _0449_;
  wire _0450_;
  wire _0451_;
  wire _0452_;
  wire _0453_;
  wire _0454_;
  wire _0455_;
  wire _0456_;
  wire _0457_;
  wire _0458_;
  wire _0459_;
  wire _0460_;
  wire _0461_;
  wire _0462_;
  wire _0463_;
  wire _0464_;
  wire _0465_;
  wire _0466_;
  wire _0467_;
  wire _0468_;
  wire _0469_;
  wire _0470_;
  wire _0471_;
  wire _0472_;
  wire _0473_;
  wire _0474_;
  wire _0475_;
  wire _0476_;
  wire _0477_;
  wire _0478_;
  wire _0479_;
  wire _0480_;
  wire _0481_;
  wire _0482_;
  wire _0483_;
  wire _0484_;
  wire _0485_;
  wire _0486_;
  wire _0487_;
  wire _0488_;
  wire _0489_;
  wire _0490_;
  wire _0491_;
  wire _0492_;
  wire _0493_;
  wire _0494_;
  wire _0495_;
  wire _0496_;
  wire _0497_;
  wire _0498_;
  wire _0499_;
  wire _0500_;
  wire _0501_;
  wire _0502_;
  wire _0503_;
  wire _0504_;
  wire _0505_;
  wire _0506_;
  wire _0507_;
  wire _0508_;
  wire _0509_;
  wire _0510_;
  wire _0511_;
  wire _0512_;
  wire _0513_;
  wire _0514_;
  wire _0515_;
  wire _0516_;
  wire _0517_;
  wire _0518_;
  wire _0519_;
  wire _0520_;
  wire _0521_;
  wire _0522_;
  wire _0523_;
  wire _0524_;
  wire _0525_;
  wire _0526_;
  wire _0527_;
  wire _0528_;
  wire _0529_;
  wire _0530_;
  wire _0531_;
  wire _0532_;
  wire _0533_;
  wire _0534_;
  wire _0535_;
  wire _0536_;
  wire _0537_;
  wire _0538_;
  wire _0539_;
  wire _0540_;
  wire _0541_;
  wire _0542_;
  wire _0543_;
  wire _0544_;
  wire _0545_;
  wire _0546_;
  wire _0547_;
  wire _0548_;
  wire _0549_;
  wire _0550_;
  wire _0551_;
  wire _0552_;
  wire _0553_;
  wire _0554_;
  wire _0555_;
  wire _0556_;
  wire _0557_;
  wire _0558_;
  wire _0559_;
  wire _0560_;
  wire _0561_;
  wire _0562_;
  wire _0563_;
  wire _0564_;
  wire _0565_;
  wire _0566_;
  wire _0567_;
  wire _0568_;
  wire _0569_;
  wire _0570_;
  wire _0571_;
  wire _0572_;
  wire _0573_;
  wire _0574_;
  wire _0575_;
  wire _0576_;
  wire _0577_;
  wire _0578_;
  wire _0579_;
  wire _0580_;
  wire _0581_;
  wire _0582_;
  wire _0583_;
  wire _0584_;
  wire _0585_;
  wire _0586_;
  wire _0587_;
  wire _0588_;
  wire _0589_;
  wire _0590_;
  wire _0591_;
  wire _0592_;
  wire _0593_;
  wire _0594_;
  wire _0595_;
  wire _0596_;
  wire _0597_;
  wire _0598_;
  wire _0599_;
  wire _0600_;
  wire _0601_;
  wire _0602_;
  wire _0603_;
  wire _0604_;
  wire _0605_;
  wire _0606_;
  wire _0607_;
  wire _0608_;
  wire _0609_;
  wire _0610_;
  wire _0611_;
  wire _0612_;
  wire _0613_;
  wire _0614_;
  wire _0615_;
  wire _0616_;
  wire _0617_;
  wire _0618_;
  wire _0619_;
  wire _0620_;
  wire _0621_;
  wire _0622_;
  wire _0623_;
  wire _0624_;
  wire _0625_;
  wire _0626_;
  wire _0627_;
  wire _0628_;
  wire _0629_;
  wire _0630_;
  wire _0631_;
  wire _0632_;
  wire _0633_;
  wire _0634_;
  wire _0635_;
  wire _0636_;
  wire _0637_;
  (* src = "cajeroAutomatico.v:17" *)
  output ADVERTENCIA;
  (* src = "cajeroAutomatico.v:14" *)
  output BALANCE_ACTUALIZADO;
  (* src = "cajeroAutomatico.v:12" *)
  input [63:0] BALANCE_INICIAL;
  (* src = "cajeroAutomatico.v:18" *)
  output BLOQUEO;
  (* src = "cajeroAutomatico.v:9" *)
  input [3:0] DIGITO;
  (* src = "cajeroAutomatico.v:8" *)
  input DIGITO_STB;
  (* src = "cajeroAutomatico.v:15" *)
  output ENTREGAR_DINERO;
  (* src = "cajeroAutomatico.v:19" *)
  output FONDOS_INSUFICIENTES;
  (* src = "cajeroAutomatico.v:11" *)
  input [31:0] MONTO;
  (* src = "cajeroAutomatico.v:7" *)
  input MONTO_STB;
  (* src = "cajeroAutomatico.v:10" *)
  input [15:0] PIN;
  (* src = "cajeroAutomatico.v:16" *)
  output PIN_INCORRECTO;
  (* src = "cajeroAutomatico.v:5" *)
  input TARJETA_RECIBIDA;
  (* src = "cajeroAutomatico.v:6" *)
  input TIPO_TRANS;
  (* src = "cajeroAutomatico.v:3" *)
  input clk;
  (* src = "cajeroAutomatico.v:40" *)
  wire [1:0] digitos_ingresados;
  (* src = "cajeroAutomatico.v:37" *)
  wire [1:0] intentos;
  (* src = "cajeroAutomatico.v:39" *)
  wire [15:0] pin_tecleado;
  (* src = "cajeroAutomatico.v:4" *)
  input rst;
  (* onehot = 32'd1 *)
  (* unused_bits = "7" *)
  wire [7:0] state;
  NOT _0638_ (
    .A(intentos[0]),
    .Y(_0016_)
  );
  NOT _0639_ (
    .A(rst),
    .Y(_0017_)
  );
  NOT _0640_ (
    .A(intentos[1]),
    .Y(_0018_)
  );
  NOT _0641_ (
    .A(state[2]),
    .Y(_0019_)
  );
  NOT _0642_ (
    .A(state[0]),
    .Y(_0020_)
  );
  NOT _0643_ (
    .A(DIGITO_STB),
    .Y(_0021_)
  );
  NOT _0644_ (
    .A(TARJETA_RECIBIDA),
    .Y(_0022_)
  );
  NOT _0645_ (
    .A(MONTO_STB),
    .Y(_0023_)
  );
  NOT _0646_ (
    .A(TIPO_TRANS),
    .Y(_0024_)
  );
  NOT _0647_ (
    .A(digitos_ingresados[1]),
    .Y(_0025_)
  );
  NOT _0648_ (
    .A(pin_tecleado[0]),
    .Y(_0026_)
  );
  NOT _0649_ (
    .A(pin_tecleado[2]),
    .Y(_0027_)
  );
  NOT _0650_ (
    .A(pin_tecleado[3]),
    .Y(_0028_)
  );
  NOT _0651_ (
    .A(pin_tecleado[5]),
    .Y(_0029_)
  );
  NOT _0652_ (
    .A(pin_tecleado[9]),
    .Y(_0030_)
  );
  NOT _0653_ (
    .A(pin_tecleado[15]),
    .Y(_0031_)
  );
  NOT _0654_ (
    .A(FONDOS_INSUFICIENTES),
    .Y(_0032_)
  );
  NOT _0655_ (
    .A(ENTREGAR_DINERO),
    .Y(_0033_)
  );
  NOT _0656_ (
    .A(BALANCE_ACTUALIZADO),
    .Y(_0034_)
  );
  NOT _0657_ (
    .A(BALANCE_INICIAL[0]),
    .Y(_0035_)
  );
  NOT _0658_ (
    .A(BALANCE_INICIAL[1]),
    .Y(_0036_)
  );
  NOT _0659_ (
    .A(BALANCE_INICIAL[2]),
    .Y(_0037_)
  );
  NOT _0660_ (
    .A(BALANCE_INICIAL[3]),
    .Y(_0038_)
  );
  NOT _0661_ (
    .A(BALANCE_INICIAL[4]),
    .Y(_0039_)
  );
  NOT _0662_ (
    .A(BALANCE_INICIAL[5]),
    .Y(_0040_)
  );
  NOT _0663_ (
    .A(BALANCE_INICIAL[6]),
    .Y(_0041_)
  );
  NOT _0664_ (
    .A(BALANCE_INICIAL[7]),
    .Y(_0042_)
  );
  NOT _0665_ (
    .A(BALANCE_INICIAL[8]),
    .Y(_0043_)
  );
  NOT _0666_ (
    .A(BALANCE_INICIAL[9]),
    .Y(_0044_)
  );
  NOT _0667_ (
    .A(BALANCE_INICIAL[10]),
    .Y(_0045_)
  );
  NOT _0668_ (
    .A(BALANCE_INICIAL[11]),
    .Y(_0046_)
  );
  NOT _0669_ (
    .A(BALANCE_INICIAL[12]),
    .Y(_0047_)
  );
  NOT _0670_ (
    .A(BALANCE_INICIAL[13]),
    .Y(_0048_)
  );
  NOT _0671_ (
    .A(BALANCE_INICIAL[14]),
    .Y(_0049_)
  );
  NOT _0672_ (
    .A(BALANCE_INICIAL[15]),
    .Y(_0050_)
  );
  NOT _0673_ (
    .A(BALANCE_INICIAL[16]),
    .Y(_0051_)
  );
  NOT _0674_ (
    .A(BALANCE_INICIAL[17]),
    .Y(_0052_)
  );
  NOT _0675_ (
    .A(BALANCE_INICIAL[18]),
    .Y(_0053_)
  );
  NOT _0676_ (
    .A(BALANCE_INICIAL[19]),
    .Y(_0054_)
  );
  NOT _0677_ (
    .A(BALANCE_INICIAL[20]),
    .Y(_0055_)
  );
  NOT _0678_ (
    .A(BALANCE_INICIAL[21]),
    .Y(_0056_)
  );
  NOT _0679_ (
    .A(BALANCE_INICIAL[22]),
    .Y(_0057_)
  );
  NOT _0680_ (
    .A(BALANCE_INICIAL[23]),
    .Y(_0058_)
  );
  NOT _0681_ (
    .A(BALANCE_INICIAL[24]),
    .Y(_0059_)
  );
  NOT _0682_ (
    .A(BALANCE_INICIAL[26]),
    .Y(_0060_)
  );
  NOT _0683_ (
    .A(BALANCE_INICIAL[27]),
    .Y(_0061_)
  );
  NOT _0684_ (
    .A(BALANCE_INICIAL[28]),
    .Y(_0062_)
  );
  NOT _0685_ (
    .A(BALANCE_INICIAL[30]),
    .Y(_0063_)
  );
  NOT _0686_ (
    .A(BALANCE_INICIAL[31]),
    .Y(_0064_)
  );
  NOT _0687_ (
    .A(BALANCE_INICIAL[57]),
    .Y(_0065_)
  );
  NOT _0688_ (
    .A(BALANCE_INICIAL[59]),
    .Y(_0066_)
  );
  NOT _0689_ (
    .A(MONTO[1]),
    .Y(_0067_)
  );
  NOT _0690_ (
    .A(MONTO[2]),
    .Y(_0068_)
  );
  NOT _0691_ (
    .A(MONTO[3]),
    .Y(_0069_)
  );
  NOT _0692_ (
    .A(MONTO[4]),
    .Y(_0070_)
  );
  NOT _0693_ (
    .A(MONTO[5]),
    .Y(_0071_)
  );
  NOT _0694_ (
    .A(MONTO[6]),
    .Y(_0072_)
  );
  NOT _0695_ (
    .A(MONTO[7]),
    .Y(_0073_)
  );
  NOT _0696_ (
    .A(MONTO[8]),
    .Y(_0074_)
  );
  NOT _0697_ (
    .A(MONTO[9]),
    .Y(_0075_)
  );
  NOT _0698_ (
    .A(MONTO[10]),
    .Y(_0076_)
  );
  NOT _0699_ (
    .A(MONTO[11]),
    .Y(_0077_)
  );
  NOT _0700_ (
    .A(MONTO[13]),
    .Y(_0078_)
  );
  NOT _0701_ (
    .A(MONTO[14]),
    .Y(_0079_)
  );
  NOT _0702_ (
    .A(MONTO[15]),
    .Y(_0080_)
  );
  NOT _0703_ (
    .A(MONTO[16]),
    .Y(_0081_)
  );
  NOT _0704_ (
    .A(MONTO[18]),
    .Y(_0082_)
  );
  NOT _0705_ (
    .A(MONTO[19]),
    .Y(_0083_)
  );
  NOT _0706_ (
    .A(MONTO[20]),
    .Y(_0084_)
  );
  NOT _0707_ (
    .A(MONTO[21]),
    .Y(_0085_)
  );
  NOT _0708_ (
    .A(MONTO[22]),
    .Y(_0086_)
  );
  NOT _0709_ (
    .A(MONTO[23]),
    .Y(_0087_)
  );
  NOT _0710_ (
    .A(MONTO[24]),
    .Y(_0088_)
  );
  NOT _0711_ (
    .A(MONTO[25]),
    .Y(_0089_)
  );
  NOT _0712_ (
    .A(MONTO[26]),
    .Y(_0090_)
  );
  NOT _0713_ (
    .A(MONTO[27]),
    .Y(_0091_)
  );
  NOT _0714_ (
    .A(MONTO[28]),
    .Y(_0092_)
  );
  NOT _0715_ (
    .A(MONTO[29]),
    .Y(_0093_)
  );
  NOT _0716_ (
    .A(MONTO[30]),
    .Y(_0094_)
  );
  NOT _0717_ (
    .A(MONTO[31]),
    .Y(_0095_)
  );
  NOT _0718_ (
    .A(PIN[0]),
    .Y(_0096_)
  );
  NOT _0719_ (
    .A(PIN[2]),
    .Y(_0097_)
  );
  NOT _0720_ (
    .A(PIN[3]),
    .Y(_0098_)
  );
  NOT _0721_ (
    .A(PIN[5]),
    .Y(_0099_)
  );
  NOT _0722_ (
    .A(PIN[9]),
    .Y(_0100_)
  );
  NOT _0723_ (
    .A(PIN[15]),
    .Y(_0101_)
  );
  NOT _0724_ (
    .A(state[1]),
    .Y(_0102_)
  );
  NAND _0725_ (
    .A(intentos[0]),
    .B(intentos[1]),
    .Y(_0103_)
  );
  NAND _0726_ (
    .A(state[3]),
    .B(_0103_),
    .Y(_0104_)
  );
  NAND _0727_ (
    .A(DIGITO_STB),
    .B(digitos_ingresados[0]),
    .Y(_0105_)
  );
  NOR _0728_ (
    .A(_0025_),
    .B(_0105_),
    .Y(_0106_)
  );
  NAND _0729_ (
    .A(state[2]),
    .B(_0106_),
    .Y(_0107_)
  );
  NAND _0730_ (
    .A(_0104_),
    .B(_0107_),
    .Y(_0108_)
  );
  NOT _0731_ (
    .A(_0108_),
    .Y(_0109_)
  );
  NOR _0732_ (
    .A(rst),
    .B(_0109_),
    .Y(_0015_)
  );
  NAND _0733_ (
    .A(state[0]),
    .B(_0022_),
    .Y(_0110_)
  );
  NOR _0734_ (
    .A(rst),
    .B(state[5]),
    .Y(_0111_)
  );
  NAND _0735_ (
    .A(_0110_),
    .B(_0111_),
    .Y(_0013_)
  );
  NOR _0736_ (
    .A(_0019_),
    .B(_0106_),
    .Y(_0112_)
  );
  NOR _0737_ (
    .A(state[4]),
    .B(_0112_),
    .Y(_0113_)
  );
  NOR _0738_ (
    .A(rst),
    .B(_0113_),
    .Y(_0014_)
  );
  NOR _0739_ (
    .A(state[2]),
    .B(state[0]),
    .Y(_0114_)
  );
  NAND _0740_ (
    .A(_0019_),
    .B(_0020_),
    .Y(_0115_)
  );
  NAND _0741_ (
    .A(digitos_ingresados[0]),
    .B(_0114_),
    .Y(_0116_)
  );
  NAND _0742_ (
    .A(state[2]),
    .B(_0105_),
    .Y(_0117_)
  );
  NAND _0743_ (
    .A(_0116_),
    .B(_0117_),
    .Y(_0118_)
  );
  NOR _0744_ (
    .A(DIGITO_STB),
    .B(digitos_ingresados[0]),
    .Y(_0119_)
  );
  NAND _0745_ (
    .A(_0017_),
    .B(_0118_),
    .Y(_0120_)
  );
  NOR _0746_ (
    .A(_0119_),
    .B(_0120_),
    .Y(_0006_[0])
  );
  NAND _0747_ (
    .A(_0025_),
    .B(_0105_),
    .Y(_0121_)
  );
  NOR _0748_ (
    .A(_0025_),
    .B(_0115_),
    .Y(_0122_)
  );
  NOR _0749_ (
    .A(_0112_),
    .B(_0122_),
    .Y(_0123_)
  );
  NAND _0750_ (
    .A(_0017_),
    .B(_0121_),
    .Y(_0124_)
  );
  NOR _0751_ (
    .A(_0123_),
    .B(_0124_),
    .Y(_0006_[1])
  );
  NOR _0752_ (
    .A(_0019_),
    .B(_0021_),
    .Y(_0125_)
  );
  NOR _0753_ (
    .A(state[2]),
    .B(_0020_),
    .Y(_0126_)
  );
  NOR _0754_ (
    .A(_0125_),
    .B(_0126_),
    .Y(_0127_)
  );
  NAND _0755_ (
    .A(pin_tecleado[0]),
    .B(_0127_),
    .Y(_0128_)
  );
  NAND _0756_ (
    .A(DIGITO[0]),
    .B(_0125_),
    .Y(_0129_)
  );
  NAND _0757_ (
    .A(_0128_),
    .B(_0129_),
    .Y(_0130_)
  );
  NOT _0758_ (
    .A(_0130_),
    .Y(_0131_)
  );
  NOR _0759_ (
    .A(rst),
    .B(_0131_),
    .Y(_0008_[0])
  );
  NAND _0760_ (
    .A(pin_tecleado[1]),
    .B(_0127_),
    .Y(_0132_)
  );
  NAND _0761_ (
    .A(DIGITO[1]),
    .B(_0125_),
    .Y(_0133_)
  );
  NAND _0762_ (
    .A(_0132_),
    .B(_0133_),
    .Y(_0134_)
  );
  NOT _0763_ (
    .A(_0134_),
    .Y(_0135_)
  );
  NOR _0764_ (
    .A(rst),
    .B(_0135_),
    .Y(_0008_[1])
  );
  NAND _0765_ (
    .A(pin_tecleado[2]),
    .B(_0127_),
    .Y(_0136_)
  );
  NAND _0766_ (
    .A(DIGITO[2]),
    .B(_0125_),
    .Y(_0137_)
  );
  NAND _0767_ (
    .A(_0136_),
    .B(_0137_),
    .Y(_0138_)
  );
  NOT _0768_ (
    .A(_0138_),
    .Y(_0139_)
  );
  NOR _0769_ (
    .A(rst),
    .B(_0139_),
    .Y(_0008_[2])
  );
  NAND _0770_ (
    .A(pin_tecleado[3]),
    .B(_0127_),
    .Y(_0140_)
  );
  NAND _0771_ (
    .A(DIGITO[3]),
    .B(_0125_),
    .Y(_0141_)
  );
  NAND _0772_ (
    .A(_0140_),
    .B(_0141_),
    .Y(_0142_)
  );
  NOT _0773_ (
    .A(_0142_),
    .Y(_0143_)
  );
  NOR _0774_ (
    .A(rst),
    .B(_0143_),
    .Y(_0008_[3])
  );
  NAND _0775_ (
    .A(pin_tecleado[4]),
    .B(_0127_),
    .Y(_0144_)
  );
  NAND _0776_ (
    .A(pin_tecleado[0]),
    .B(_0125_),
    .Y(_0145_)
  );
  NAND _0777_ (
    .A(_0144_),
    .B(_0145_),
    .Y(_0146_)
  );
  NOT _0778_ (
    .A(_0146_),
    .Y(_0147_)
  );
  NOR _0779_ (
    .A(rst),
    .B(_0147_),
    .Y(_0008_[4])
  );
  NAND _0780_ (
    .A(pin_tecleado[5]),
    .B(_0127_),
    .Y(_0148_)
  );
  NAND _0781_ (
    .A(pin_tecleado[1]),
    .B(_0125_),
    .Y(_0149_)
  );
  NAND _0782_ (
    .A(_0148_),
    .B(_0149_),
    .Y(_0150_)
  );
  NOT _0783_ (
    .A(_0150_),
    .Y(_0151_)
  );
  NOR _0784_ (
    .A(rst),
    .B(_0151_),
    .Y(_0008_[5])
  );
  NAND _0785_ (
    .A(pin_tecleado[6]),
    .B(_0127_),
    .Y(_0152_)
  );
  NAND _0786_ (
    .A(pin_tecleado[2]),
    .B(_0125_),
    .Y(_0153_)
  );
  NAND _0787_ (
    .A(_0152_),
    .B(_0153_),
    .Y(_0154_)
  );
  NOT _0788_ (
    .A(_0154_),
    .Y(_0155_)
  );
  NOR _0789_ (
    .A(rst),
    .B(_0155_),
    .Y(_0008_[6])
  );
  NAND _0790_ (
    .A(pin_tecleado[7]),
    .B(_0127_),
    .Y(_0156_)
  );
  NAND _0791_ (
    .A(pin_tecleado[3]),
    .B(_0125_),
    .Y(_0157_)
  );
  NAND _0792_ (
    .A(_0156_),
    .B(_0157_),
    .Y(_0158_)
  );
  NOT _0793_ (
    .A(_0158_),
    .Y(_0159_)
  );
  NOR _0794_ (
    .A(rst),
    .B(_0159_),
    .Y(_0008_[7])
  );
  NAND _0795_ (
    .A(pin_tecleado[8]),
    .B(_0127_),
    .Y(_0160_)
  );
  NAND _0796_ (
    .A(pin_tecleado[4]),
    .B(_0125_),
    .Y(_0161_)
  );
  NAND _0797_ (
    .A(_0160_),
    .B(_0161_),
    .Y(_0162_)
  );
  NOT _0798_ (
    .A(_0162_),
    .Y(_0163_)
  );
  NOR _0799_ (
    .A(rst),
    .B(_0163_),
    .Y(_0008_[8])
  );
  NAND _0800_ (
    .A(pin_tecleado[9]),
    .B(_0127_),
    .Y(_0164_)
  );
  NAND _0801_ (
    .A(pin_tecleado[5]),
    .B(_0125_),
    .Y(_0165_)
  );
  NAND _0802_ (
    .A(_0164_),
    .B(_0165_),
    .Y(_0166_)
  );
  NOT _0803_ (
    .A(_0166_),
    .Y(_0167_)
  );
  NOR _0804_ (
    .A(rst),
    .B(_0167_),
    .Y(_0008_[9])
  );
  NAND _0805_ (
    .A(pin_tecleado[10]),
    .B(_0127_),
    .Y(_0168_)
  );
  NAND _0806_ (
    .A(pin_tecleado[6]),
    .B(_0125_),
    .Y(_0169_)
  );
  NAND _0807_ (
    .A(_0168_),
    .B(_0169_),
    .Y(_0170_)
  );
  NOT _0808_ (
    .A(_0170_),
    .Y(_0171_)
  );
  NOR _0809_ (
    .A(rst),
    .B(_0171_),
    .Y(_0008_[10])
  );
  NAND _0810_ (
    .A(pin_tecleado[11]),
    .B(_0127_),
    .Y(_0172_)
  );
  NAND _0811_ (
    .A(pin_tecleado[7]),
    .B(_0125_),
    .Y(_0173_)
  );
  NAND _0812_ (
    .A(_0172_),
    .B(_0173_),
    .Y(_0174_)
  );
  NOT _0813_ (
    .A(_0174_),
    .Y(_0175_)
  );
  NOR _0814_ (
    .A(rst),
    .B(_0175_),
    .Y(_0008_[11])
  );
  NAND _0815_ (
    .A(pin_tecleado[12]),
    .B(_0127_),
    .Y(_0176_)
  );
  NAND _0816_ (
    .A(pin_tecleado[8]),
    .B(_0125_),
    .Y(_0177_)
  );
  NAND _0817_ (
    .A(_0176_),
    .B(_0177_),
    .Y(_0178_)
  );
  NOT _0818_ (
    .A(_0178_),
    .Y(_0179_)
  );
  NOR _0819_ (
    .A(rst),
    .B(_0179_),
    .Y(_0008_[12])
  );
  NAND _0820_ (
    .A(pin_tecleado[13]),
    .B(_0127_),
    .Y(_0180_)
  );
  NAND _0821_ (
    .A(pin_tecleado[9]),
    .B(_0125_),
    .Y(_0181_)
  );
  NAND _0822_ (
    .A(_0180_),
    .B(_0181_),
    .Y(_0182_)
  );
  NOT _0823_ (
    .A(_0182_),
    .Y(_0183_)
  );
  NOR _0824_ (
    .A(rst),
    .B(_0183_),
    .Y(_0008_[13])
  );
  NAND _0825_ (
    .A(pin_tecleado[14]),
    .B(_0127_),
    .Y(_0184_)
  );
  NAND _0826_ (
    .A(pin_tecleado[10]),
    .B(_0125_),
    .Y(_0185_)
  );
  NAND _0827_ (
    .A(_0184_),
    .B(_0185_),
    .Y(_0186_)
  );
  NOT _0828_ (
    .A(_0186_),
    .Y(_0187_)
  );
  NOR _0829_ (
    .A(rst),
    .B(_0187_),
    .Y(_0008_[14])
  );
  NAND _0830_ (
    .A(pin_tecleado[15]),
    .B(_0127_),
    .Y(_0188_)
  );
  NAND _0831_ (
    .A(pin_tecleado[11]),
    .B(_0125_),
    .Y(_0189_)
  );
  NAND _0832_ (
    .A(_0188_),
    .B(_0189_),
    .Y(_0190_)
  );
  NOT _0833_ (
    .A(_0190_),
    .Y(_0191_)
  );
  NOR _0834_ (
    .A(rst),
    .B(_0191_),
    .Y(_0008_[15])
  );
  NOR _0835_ (
    .A(_0020_),
    .B(state[3]),
    .Y(_0192_)
  );
  NOR _0836_ (
    .A(rst),
    .B(_0192_),
    .Y(_0193_)
  );
  NOT _0837_ (
    .A(_0193_),
    .Y(_0194_)
  );
  NOR _0838_ (
    .A(intentos[0]),
    .B(state[3]),
    .Y(_0195_)
  );
  NAND _0839_ (
    .A(intentos[0]),
    .B(state[3]),
    .Y(_0196_)
  );
  NAND _0840_ (
    .A(_0193_),
    .B(_0196_),
    .Y(_0197_)
  );
  NOR _0841_ (
    .A(_0195_),
    .B(_0197_),
    .Y(_0007_[0])
  );
  NOR _0842_ (
    .A(_0018_),
    .B(_0196_),
    .Y(_0198_)
  );
  NAND _0843_ (
    .A(_0018_),
    .B(_0196_),
    .Y(_0199_)
  );
  NAND _0844_ (
    .A(_0193_),
    .B(_0199_),
    .Y(_0200_)
  );
  NOR _0845_ (
    .A(_0198_),
    .B(_0200_),
    .Y(_0007_[1])
  );
  NOR _0846_ (
    .A(_0023_),
    .B(_0024_),
    .Y(_0201_)
  );
  NAND _0847_ (
    .A(_0063_),
    .B(MONTO[30]),
    .Y(_0202_)
  );
  NAND _0848_ (
    .A(_0064_),
    .B(MONTO[31]),
    .Y(_0203_)
  );
  NAND _0849_ (
    .A(_0202_),
    .B(_0203_),
    .Y(_0204_)
  );
  NOR _0850_ (
    .A(_0064_),
    .B(MONTO[31]),
    .Y(_0205_)
  );
  NAND _0851_ (
    .A(BALANCE_INICIAL[31]),
    .B(_0095_),
    .Y(_0206_)
  );
  NAND _0852_ (
    .A(BALANCE_INICIAL[30]),
    .B(_0094_),
    .Y(_0207_)
  );
  NAND _0853_ (
    .A(BALANCE_INICIAL[29]),
    .B(_0093_),
    .Y(_0208_)
  );
  NAND _0854_ (
    .A(_0206_),
    .B(_0207_),
    .Y(_0209_)
  );
  NOR _0855_ (
    .A(_0204_),
    .B(_0209_),
    .Y(_0210_)
  );
  NAND _0856_ (
    .A(_0208_),
    .B(_0210_),
    .Y(_0211_)
  );
  NOR _0857_ (
    .A(BALANCE_INICIAL[28]),
    .B(_0092_),
    .Y(_0212_)
  );
  NOR _0858_ (
    .A(BALANCE_INICIAL[29]),
    .B(_0093_),
    .Y(_0213_)
  );
  NOR _0859_ (
    .A(_0212_),
    .B(_0213_),
    .Y(_0214_)
  );
  NOR _0860_ (
    .A(_0062_),
    .B(MONTO[28]),
    .Y(_0215_)
  );
  NOR _0861_ (
    .A(_0211_),
    .B(_0215_),
    .Y(_0216_)
  );
  NAND _0862_ (
    .A(_0214_),
    .B(_0216_),
    .Y(_0217_)
  );
  NAND _0863_ (
    .A(_0061_),
    .B(MONTO[27]),
    .Y(_0218_)
  );
  NAND _0864_ (
    .A(BALANCE_INICIAL[27]),
    .B(_0091_),
    .Y(_0219_)
  );
  NAND _0865_ (
    .A(_0218_),
    .B(_0219_),
    .Y(_0220_)
  );
  NOR _0866_ (
    .A(BALANCE_INICIAL[26]),
    .B(_0090_),
    .Y(_0221_)
  );
  NAND _0867_ (
    .A(_0060_),
    .B(MONTO[26]),
    .Y(_0222_)
  );
  NAND _0868_ (
    .A(BALANCE_INICIAL[26]),
    .B(_0090_),
    .Y(_0223_)
  );
  NAND _0869_ (
    .A(_0222_),
    .B(_0223_),
    .Y(_0224_)
  );
  NOR _0870_ (
    .A(_0220_),
    .B(_0224_),
    .Y(_0225_)
  );
  NOR _0871_ (
    .A(BALANCE_INICIAL[24]),
    .B(_0088_),
    .Y(_0226_)
  );
  NOR _0872_ (
    .A(BALANCE_INICIAL[25]),
    .B(_0089_),
    .Y(_0227_)
  );
  NOR _0873_ (
    .A(_0226_),
    .B(_0227_),
    .Y(_0228_)
  );
  NAND _0874_ (
    .A(BALANCE_INICIAL[25]),
    .B(_0089_),
    .Y(_0229_)
  );
  NOR _0875_ (
    .A(_0059_),
    .B(MONTO[24]),
    .Y(_0230_)
  );
  NAND _0876_ (
    .A(_0228_),
    .B(_0229_),
    .Y(_0231_)
  );
  NOR _0877_ (
    .A(_0230_),
    .B(_0231_),
    .Y(_0232_)
  );
  NAND _0878_ (
    .A(_0225_),
    .B(_0232_),
    .Y(_0233_)
  );
  NOR _0879_ (
    .A(_0217_),
    .B(_0233_),
    .Y(_0234_)
  );
  NOR _0880_ (
    .A(_0056_),
    .B(MONTO[21]),
    .Y(_0235_)
  );
  NAND _0881_ (
    .A(_0058_),
    .B(MONTO[23]),
    .Y(_0236_)
  );
  NOR _0882_ (
    .A(BALANCE_INICIAL[22]),
    .B(_0086_),
    .Y(_0237_)
  );
  NOR _0883_ (
    .A(_0057_),
    .B(MONTO[22]),
    .Y(_0238_)
  );
  NOR _0884_ (
    .A(_0237_),
    .B(_0238_),
    .Y(_0239_)
  );
  NAND _0885_ (
    .A(BALANCE_INICIAL[23]),
    .B(_0087_),
    .Y(_0240_)
  );
  NAND _0886_ (
    .A(_0236_),
    .B(_0240_),
    .Y(_0241_)
  );
  NOR _0887_ (
    .A(_0235_),
    .B(_0241_),
    .Y(_0242_)
  );
  NAND _0888_ (
    .A(_0239_),
    .B(_0242_),
    .Y(_0243_)
  );
  NOR _0889_ (
    .A(BALANCE_INICIAL[20]),
    .B(_0084_),
    .Y(_0244_)
  );
  NOR _0890_ (
    .A(BALANCE_INICIAL[21]),
    .B(_0085_),
    .Y(_0245_)
  );
  NOR _0891_ (
    .A(_0244_),
    .B(_0245_),
    .Y(_0246_)
  );
  NOR _0892_ (
    .A(_0055_),
    .B(MONTO[20]),
    .Y(_0247_)
  );
  NOR _0893_ (
    .A(_0243_),
    .B(_0247_),
    .Y(_0248_)
  );
  NAND _0894_ (
    .A(_0246_),
    .B(_0248_),
    .Y(_0249_)
  );
  NOT _0895_ (
    .A(_0249_),
    .Y(_0250_)
  );
  NOR _0896_ (
    .A(_0052_),
    .B(MONTO[17]),
    .Y(_0251_)
  );
  NOR _0897_ (
    .A(_0053_),
    .B(MONTO[18]),
    .Y(_0252_)
  );
  NOR _0898_ (
    .A(_0054_),
    .B(MONTO[19]),
    .Y(_0253_)
  );
  NOR _0899_ (
    .A(BALANCE_INICIAL[19]),
    .B(_0083_),
    .Y(_0254_)
  );
  NOR _0900_ (
    .A(BALANCE_INICIAL[18]),
    .B(_0082_),
    .Y(_0255_)
  );
  NAND _0901_ (
    .A(_0053_),
    .B(MONTO[18]),
    .Y(_0256_)
  );
  NOR _0902_ (
    .A(_0253_),
    .B(_0254_),
    .Y(_0257_)
  );
  NOR _0903_ (
    .A(_0252_),
    .B(_0255_),
    .Y(_0258_)
  );
  NAND _0904_ (
    .A(_0257_),
    .B(_0258_),
    .Y(_0259_)
  );
  NOR _0905_ (
    .A(_0251_),
    .B(_0259_),
    .Y(_0260_)
  );
  NAND _0906_ (
    .A(_0051_),
    .B(MONTO[16]),
    .Y(_0261_)
  );
  NAND _0907_ (
    .A(_0052_),
    .B(MONTO[17]),
    .Y(_0262_)
  );
  NAND _0908_ (
    .A(_0261_),
    .B(_0262_),
    .Y(_0263_)
  );
  NAND _0909_ (
    .A(BALANCE_INICIAL[16]),
    .B(_0081_),
    .Y(_0264_)
  );
  NAND _0910_ (
    .A(_0260_),
    .B(_0264_),
    .Y(_0265_)
  );
  NOR _0911_ (
    .A(_0249_),
    .B(_0265_),
    .Y(_0266_)
  );
  NAND _0912_ (
    .A(_0234_),
    .B(_0266_),
    .Y(_0267_)
  );
  NOR _0913_ (
    .A(_0263_),
    .B(_0267_),
    .Y(_0268_)
  );
  NOT _0914_ (
    .A(_0268_),
    .Y(_0269_)
  );
  NOR _0915_ (
    .A(BALANCE_INICIAL[14]),
    .B(_0079_),
    .Y(_0270_)
  );
  NAND _0916_ (
    .A(_0049_),
    .B(MONTO[14]),
    .Y(_0271_)
  );
  NOR _0917_ (
    .A(BALANCE_INICIAL[15]),
    .B(_0080_),
    .Y(_0272_)
  );
  NAND _0918_ (
    .A(_0050_),
    .B(MONTO[15]),
    .Y(_0273_)
  );
  NOR _0919_ (
    .A(_0270_),
    .B(_0272_),
    .Y(_0274_)
  );
  NAND _0920_ (
    .A(_0271_),
    .B(_0273_),
    .Y(_0275_)
  );
  NOR _0921_ (
    .A(_0050_),
    .B(MONTO[15]),
    .Y(_0276_)
  );
  NAND _0922_ (
    .A(BALANCE_INICIAL[15]),
    .B(_0080_),
    .Y(_0277_)
  );
  NAND _0923_ (
    .A(BALANCE_INICIAL[14]),
    .B(_0079_),
    .Y(_0278_)
  );
  NAND _0924_ (
    .A(BALANCE_INICIAL[13]),
    .B(_0078_),
    .Y(_0279_)
  );
  NAND _0925_ (
    .A(_0277_),
    .B(_0278_),
    .Y(_0280_)
  );
  NOR _0926_ (
    .A(_0275_),
    .B(_0280_),
    .Y(_0281_)
  );
  NAND _0927_ (
    .A(_0279_),
    .B(_0281_),
    .Y(_0282_)
  );
  NOT _0928_ (
    .A(_0282_),
    .Y(_0283_)
  );
  NAND _0929_ (
    .A(_0047_),
    .B(MONTO[12]),
    .Y(_0284_)
  );
  NAND _0930_ (
    .A(_0048_),
    .B(MONTO[13]),
    .Y(_0285_)
  );
  NAND _0931_ (
    .A(_0284_),
    .B(_0285_),
    .Y(_0286_)
  );
  NOT _0932_ (
    .A(_0286_),
    .Y(_0287_)
  );
  NOR _0933_ (
    .A(_0047_),
    .B(MONTO[12]),
    .Y(_0288_)
  );
  NOR _0934_ (
    .A(_0286_),
    .B(_0288_),
    .Y(_0289_)
  );
  NAND _0935_ (
    .A(_0283_),
    .B(_0289_),
    .Y(_0290_)
  );
  NOT _0936_ (
    .A(_0290_),
    .Y(_0291_)
  );
  NOR _0937_ (
    .A(BALANCE_INICIAL[11]),
    .B(_0077_),
    .Y(_0292_)
  );
  NAND _0938_ (
    .A(_0046_),
    .B(MONTO[11]),
    .Y(_0293_)
  );
  NAND _0939_ (
    .A(BALANCE_INICIAL[10]),
    .B(_0076_),
    .Y(_0294_)
  );
  NAND _0940_ (
    .A(_0293_),
    .B(_0294_),
    .Y(_0295_)
  );
  NAND _0941_ (
    .A(BALANCE_INICIAL[9]),
    .B(_0075_),
    .Y(_0296_)
  );
  NOR _0942_ (
    .A(_0046_),
    .B(MONTO[11]),
    .Y(_0297_)
  );
  NAND _0943_ (
    .A(BALANCE_INICIAL[11]),
    .B(_0077_),
    .Y(_0298_)
  );
  NOR _0944_ (
    .A(BALANCE_INICIAL[10]),
    .B(_0076_),
    .Y(_0299_)
  );
  NAND _0945_ (
    .A(_0045_),
    .B(MONTO[10]),
    .Y(_0300_)
  );
  NOR _0946_ (
    .A(_0297_),
    .B(_0299_),
    .Y(_0301_)
  );
  NAND _0947_ (
    .A(_0296_),
    .B(_0301_),
    .Y(_0302_)
  );
  NAND _0948_ (
    .A(_0293_),
    .B(_0298_),
    .Y(_0303_)
  );
  NAND _0949_ (
    .A(_0294_),
    .B(_0300_),
    .Y(_0304_)
  );
  NOR _0950_ (
    .A(_0303_),
    .B(_0304_),
    .Y(_0305_)
  );
  NOR _0951_ (
    .A(_0295_),
    .B(_0302_),
    .Y(_0306_)
  );
  NAND _0952_ (
    .A(_0296_),
    .B(_0305_),
    .Y(_0307_)
  );
  NOR _0953_ (
    .A(BALANCE_INICIAL[8]),
    .B(_0074_),
    .Y(_0308_)
  );
  NAND _0954_ (
    .A(_0043_),
    .B(MONTO[8]),
    .Y(_0309_)
  );
  NOR _0955_ (
    .A(BALANCE_INICIAL[9]),
    .B(_0075_),
    .Y(_0310_)
  );
  NAND _0956_ (
    .A(_0044_),
    .B(MONTO[9]),
    .Y(_0311_)
  );
  NOR _0957_ (
    .A(_0308_),
    .B(_0310_),
    .Y(_0312_)
  );
  NAND _0958_ (
    .A(_0309_),
    .B(_0311_),
    .Y(_0313_)
  );
  NOR _0959_ (
    .A(_0043_),
    .B(MONTO[8]),
    .Y(_0314_)
  );
  NAND _0960_ (
    .A(BALANCE_INICIAL[8]),
    .B(_0074_),
    .Y(_0315_)
  );
  NOR _0961_ (
    .A(_0313_),
    .B(_0314_),
    .Y(_0316_)
  );
  NAND _0962_ (
    .A(_0312_),
    .B(_0315_),
    .Y(_0317_)
  );
  NOR _0963_ (
    .A(_0307_),
    .B(_0317_),
    .Y(_0318_)
  );
  NAND _0964_ (
    .A(_0306_),
    .B(_0316_),
    .Y(_0319_)
  );
  NOR _0965_ (
    .A(BALANCE_INICIAL[6]),
    .B(_0072_),
    .Y(_0320_)
  );
  NAND _0966_ (
    .A(_0041_),
    .B(MONTO[6]),
    .Y(_0321_)
  );
  NOR _0967_ (
    .A(BALANCE_INICIAL[7]),
    .B(_0073_),
    .Y(_0322_)
  );
  NAND _0968_ (
    .A(_0042_),
    .B(MONTO[7]),
    .Y(_0323_)
  );
  NOR _0969_ (
    .A(_0320_),
    .B(_0322_),
    .Y(_0324_)
  );
  NAND _0970_ (
    .A(_0321_),
    .B(_0323_),
    .Y(_0325_)
  );
  NOR _0971_ (
    .A(_0042_),
    .B(MONTO[7]),
    .Y(_0326_)
  );
  NAND _0972_ (
    .A(BALANCE_INICIAL[7]),
    .B(_0073_),
    .Y(_0327_)
  );
  NAND _0973_ (
    .A(BALANCE_INICIAL[6]),
    .B(_0072_),
    .Y(_0328_)
  );
  NAND _0974_ (
    .A(BALANCE_INICIAL[5]),
    .B(_0071_),
    .Y(_0329_)
  );
  NAND _0975_ (
    .A(_0327_),
    .B(_0328_),
    .Y(_0330_)
  );
  NOR _0976_ (
    .A(_0325_),
    .B(_0330_),
    .Y(_0331_)
  );
  NAND _0977_ (
    .A(_0321_),
    .B(_0328_),
    .Y(_0332_)
  );
  NOR _0978_ (
    .A(_0322_),
    .B(_0326_),
    .Y(_0333_)
  );
  NAND _0979_ (
    .A(_0329_),
    .B(_0333_),
    .Y(_0334_)
  );
  NOR _0980_ (
    .A(_0332_),
    .B(_0334_),
    .Y(_0335_)
  );
  NAND _0981_ (
    .A(_0329_),
    .B(_0331_),
    .Y(_0336_)
  );
  NOR _0982_ (
    .A(BALANCE_INICIAL[4]),
    .B(_0070_),
    .Y(_0337_)
  );
  NAND _0983_ (
    .A(_0039_),
    .B(MONTO[4]),
    .Y(_0338_)
  );
  NOR _0984_ (
    .A(BALANCE_INICIAL[5]),
    .B(_0071_),
    .Y(_0339_)
  );
  NAND _0985_ (
    .A(_0040_),
    .B(MONTO[5]),
    .Y(_0340_)
  );
  NOR _0986_ (
    .A(_0337_),
    .B(_0339_),
    .Y(_0341_)
  );
  NAND _0987_ (
    .A(_0338_),
    .B(_0340_),
    .Y(_0342_)
  );
  NOR _0988_ (
    .A(_0336_),
    .B(_0341_),
    .Y(_0343_)
  );
  NAND _0989_ (
    .A(_0335_),
    .B(_0342_),
    .Y(_0344_)
  );
  NOR _0990_ (
    .A(_0324_),
    .B(_0326_),
    .Y(_0345_)
  );
  NAND _0991_ (
    .A(_0325_),
    .B(_0327_),
    .Y(_0346_)
  );
  NOR _0992_ (
    .A(_0343_),
    .B(_0345_),
    .Y(_0347_)
  );
  NAND _0993_ (
    .A(_0344_),
    .B(_0346_),
    .Y(_0348_)
  );
  NOR _0994_ (
    .A(_0319_),
    .B(_0347_),
    .Y(_0349_)
  );
  NAND _0995_ (
    .A(_0318_),
    .B(_0348_),
    .Y(_0350_)
  );
  NOR _0996_ (
    .A(_0307_),
    .B(_0312_),
    .Y(_0351_)
  );
  NAND _0997_ (
    .A(_0306_),
    .B(_0313_),
    .Y(_0352_)
  );
  NOR _0998_ (
    .A(_0297_),
    .B(_0300_),
    .Y(_0353_)
  );
  NAND _0999_ (
    .A(_0298_),
    .B(_0299_),
    .Y(_0354_)
  );
  NOR _1000_ (
    .A(_0292_),
    .B(_0353_),
    .Y(_0355_)
  );
  NAND _1001_ (
    .A(_0293_),
    .B(_0354_),
    .Y(_0356_)
  );
  NOR _1002_ (
    .A(_0351_),
    .B(_0356_),
    .Y(_0357_)
  );
  NAND _1003_ (
    .A(_0352_),
    .B(_0355_),
    .Y(_0358_)
  );
  NOR _1004_ (
    .A(_0038_),
    .B(MONTO[3]),
    .Y(_0359_)
  );
  NAND _1005_ (
    .A(BALANCE_INICIAL[3]),
    .B(_0069_),
    .Y(_0360_)
  );
  NOR _1006_ (
    .A(BALANCE_INICIAL[3]),
    .B(_0069_),
    .Y(_0361_)
  );
  NAND _1007_ (
    .A(_0038_),
    .B(MONTO[3]),
    .Y(_0362_)
  );
  NAND _1008_ (
    .A(_0360_),
    .B(_0362_),
    .Y(_0363_)
  );
  NOR _1009_ (
    .A(BALANCE_INICIAL[2]),
    .B(_0068_),
    .Y(_0364_)
  );
  NAND _1010_ (
    .A(_0037_),
    .B(MONTO[2]),
    .Y(_0365_)
  );
  NAND _1011_ (
    .A(BALANCE_INICIAL[2]),
    .B(_0068_),
    .Y(_0366_)
  );
  NAND _1012_ (
    .A(_0365_),
    .B(_0366_),
    .Y(_0367_)
  );
  NOR _1013_ (
    .A(_0363_),
    .B(_0367_),
    .Y(_0368_)
  );
  NOT _1014_ (
    .A(_0368_),
    .Y(_0369_)
  );
  NOR _1015_ (
    .A(BALANCE_INICIAL[1]),
    .B(_0067_),
    .Y(_0370_)
  );
  NAND _1016_ (
    .A(_0036_),
    .B(MONTO[1]),
    .Y(_0371_)
  );
  NAND _1017_ (
    .A(BALANCE_INICIAL[1]),
    .B(_0067_),
    .Y(_0372_)
  );
  NOR _1018_ (
    .A(_0035_),
    .B(MONTO[0]),
    .Y(_0373_)
  );
  NOR _1019_ (
    .A(_0370_),
    .B(_0373_),
    .Y(_0374_)
  );
  NAND _1020_ (
    .A(_0371_),
    .B(_0372_),
    .Y(_0375_)
  );
  NOR _1021_ (
    .A(_0373_),
    .B(_0375_),
    .Y(_0376_)
  );
  NAND _1022_ (
    .A(_0372_),
    .B(_0374_),
    .Y(_0377_)
  );
  NOR _1023_ (
    .A(_0370_),
    .B(_0376_),
    .Y(_0378_)
  );
  NAND _1024_ (
    .A(_0371_),
    .B(_0377_),
    .Y(_0379_)
  );
  NOR _1025_ (
    .A(_0369_),
    .B(_0378_),
    .Y(_0380_)
  );
  NAND _1026_ (
    .A(_0368_),
    .B(_0379_),
    .Y(_0381_)
  );
  NOR _1027_ (
    .A(_0359_),
    .B(_0365_),
    .Y(_0382_)
  );
  NAND _1028_ (
    .A(_0360_),
    .B(_0364_),
    .Y(_0383_)
  );
  NOR _1029_ (
    .A(_0361_),
    .B(_0382_),
    .Y(_0384_)
  );
  NAND _1030_ (
    .A(_0362_),
    .B(_0383_),
    .Y(_0385_)
  );
  NOR _1031_ (
    .A(_0380_),
    .B(_0385_),
    .Y(_0386_)
  );
  NAND _1032_ (
    .A(_0381_),
    .B(_0384_),
    .Y(_0387_)
  );
  NOR _1033_ (
    .A(_0039_),
    .B(MONTO[4]),
    .Y(_0388_)
  );
  NAND _1034_ (
    .A(BALANCE_INICIAL[4]),
    .B(_0070_),
    .Y(_0389_)
  );
  NOR _1035_ (
    .A(_0342_),
    .B(_0388_),
    .Y(_0390_)
  );
  NAND _1036_ (
    .A(_0341_),
    .B(_0389_),
    .Y(_0391_)
  );
  NOR _1037_ (
    .A(_0336_),
    .B(_0391_),
    .Y(_0392_)
  );
  NAND _1038_ (
    .A(_0335_),
    .B(_0390_),
    .Y(_0393_)
  );
  NOR _1039_ (
    .A(_0319_),
    .B(_0393_),
    .Y(_0394_)
  );
  NAND _1040_ (
    .A(_0318_),
    .B(_0392_),
    .Y(_0395_)
  );
  NOR _1041_ (
    .A(_0386_),
    .B(_0395_),
    .Y(_0396_)
  );
  NAND _1042_ (
    .A(_0387_),
    .B(_0394_),
    .Y(_0397_)
  );
  NOR _1043_ (
    .A(_0358_),
    .B(_0396_),
    .Y(_0398_)
  );
  NAND _1044_ (
    .A(_0357_),
    .B(_0397_),
    .Y(_0399_)
  );
  NOR _1045_ (
    .A(_0349_),
    .B(_0399_),
    .Y(_0400_)
  );
  NAND _1046_ (
    .A(_0350_),
    .B(_0398_),
    .Y(_0401_)
  );
  NOR _1047_ (
    .A(_0290_),
    .B(_0400_),
    .Y(_0402_)
  );
  NAND _1048_ (
    .A(_0291_),
    .B(_0401_),
    .Y(_0403_)
  );
  NOR _1049_ (
    .A(_0282_),
    .B(_0287_),
    .Y(_0404_)
  );
  NAND _1050_ (
    .A(_0283_),
    .B(_0286_),
    .Y(_0405_)
  );
  NOR _1051_ (
    .A(_0274_),
    .B(_0276_),
    .Y(_0406_)
  );
  NAND _1052_ (
    .A(_0275_),
    .B(_0277_),
    .Y(_0407_)
  );
  NOR _1053_ (
    .A(_0404_),
    .B(_0406_),
    .Y(_0408_)
  );
  NAND _1054_ (
    .A(_0405_),
    .B(_0407_),
    .Y(_0409_)
  );
  NOR _1055_ (
    .A(_0402_),
    .B(_0409_),
    .Y(_0410_)
  );
  NAND _1056_ (
    .A(_0403_),
    .B(_0408_),
    .Y(_0411_)
  );
  NOR _1057_ (
    .A(_0269_),
    .B(_0410_),
    .Y(_0412_)
  );
  NAND _1058_ (
    .A(_0268_),
    .B(_0411_),
    .Y(_0413_)
  );
  NAND _1059_ (
    .A(_0260_),
    .B(_0263_),
    .Y(_0414_)
  );
  NOR _1060_ (
    .A(_0253_),
    .B(_0256_),
    .Y(_0415_)
  );
  NOR _1061_ (
    .A(_0254_),
    .B(_0415_),
    .Y(_0416_)
  );
  NAND _1062_ (
    .A(_0414_),
    .B(_0416_),
    .Y(_0417_)
  );
  NAND _1063_ (
    .A(_0250_),
    .B(_0417_),
    .Y(_0418_)
  );
  NOR _1064_ (
    .A(_0243_),
    .B(_0246_),
    .Y(_0419_)
  );
  NAND _1065_ (
    .A(_0237_),
    .B(_0240_),
    .Y(_0420_)
  );
  NAND _1066_ (
    .A(_0236_),
    .B(_0420_),
    .Y(_0421_)
  );
  NOR _1067_ (
    .A(_0419_),
    .B(_0421_),
    .Y(_0422_)
  );
  NAND _1068_ (
    .A(_0418_),
    .B(_0422_),
    .Y(_0423_)
  );
  NAND _1069_ (
    .A(_0234_),
    .B(_0423_),
    .Y(_0424_)
  );
  NAND _1070_ (
    .A(_0219_),
    .B(_0221_),
    .Y(_0425_)
  );
  NAND _1071_ (
    .A(_0218_),
    .B(_0425_),
    .Y(_0426_)
  );
  NAND _1072_ (
    .A(_0225_),
    .B(_0229_),
    .Y(_0427_)
  );
  NOR _1073_ (
    .A(_0228_),
    .B(_0427_),
    .Y(_0428_)
  );
  NOR _1074_ (
    .A(_0426_),
    .B(_0428_),
    .Y(_0429_)
  );
  NOR _1075_ (
    .A(_0217_),
    .B(_0429_),
    .Y(_0430_)
  );
  NOR _1076_ (
    .A(_0211_),
    .B(_0214_),
    .Y(_0431_)
  );
  NOR _1077_ (
    .A(_0202_),
    .B(_0205_),
    .Y(_0432_)
  );
  NOR _1078_ (
    .A(_0431_),
    .B(_0432_),
    .Y(_0433_)
  );
  NAND _1079_ (
    .A(_0203_),
    .B(_0433_),
    .Y(_0434_)
  );
  NOR _1080_ (
    .A(_0430_),
    .B(_0434_),
    .Y(_0435_)
  );
  NAND _1081_ (
    .A(_0424_),
    .B(_0435_),
    .Y(_0436_)
  );
  NOT _1082_ (
    .A(_0436_),
    .Y(_0437_)
  );
  NOR _1083_ (
    .A(_0412_),
    .B(_0436_),
    .Y(_0438_)
  );
  NAND _1084_ (
    .A(_0413_),
    .B(_0437_),
    .Y(_0439_)
  );
  NAND _1085_ (
    .A(_0035_),
    .B(MONTO[0]),
    .Y(_0440_)
  );
  NAND _1086_ (
    .A(_0368_),
    .B(_0440_),
    .Y(_0441_)
  );
  NOR _1087_ (
    .A(_0377_),
    .B(_0441_),
    .Y(_0442_)
  );
  NAND _1088_ (
    .A(_0394_),
    .B(_0442_),
    .Y(_0443_)
  );
  NOR _1089_ (
    .A(_0290_),
    .B(_0443_),
    .Y(_0444_)
  );
  NAND _1090_ (
    .A(_0268_),
    .B(_0444_),
    .Y(_0445_)
  );
  NOR _1091_ (
    .A(BALANCE_INICIAL[52]),
    .B(BALANCE_INICIAL[53]),
    .Y(_0446_)
  );
  NOR _1092_ (
    .A(BALANCE_INICIAL[54]),
    .B(BALANCE_INICIAL[55]),
    .Y(_0447_)
  );
  NAND _1093_ (
    .A(_0446_),
    .B(_0447_),
    .Y(_0448_)
  );
  NOR _1094_ (
    .A(BALANCE_INICIAL[48]),
    .B(BALANCE_INICIAL[49]),
    .Y(_0449_)
  );
  NOR _1095_ (
    .A(BALANCE_INICIAL[50]),
    .B(BALANCE_INICIAL[51]),
    .Y(_0450_)
  );
  NAND _1096_ (
    .A(_0449_),
    .B(_0450_),
    .Y(_0451_)
  );
  NOR _1097_ (
    .A(_0448_),
    .B(_0451_),
    .Y(_0452_)
  );
  NOR _1098_ (
    .A(BALANCE_INICIAL[60]),
    .B(BALANCE_INICIAL[61]),
    .Y(_0453_)
  );
  NOR _1099_ (
    .A(BALANCE_INICIAL[62]),
    .B(BALANCE_INICIAL[63]),
    .Y(_0454_)
  );
  NAND _1100_ (
    .A(_0453_),
    .B(_0454_),
    .Y(_0455_)
  );
  NOR _1101_ (
    .A(BALANCE_INICIAL[56]),
    .B(BALANCE_INICIAL[57]),
    .Y(_0456_)
  );
  NOR _1102_ (
    .A(BALANCE_INICIAL[58]),
    .B(BALANCE_INICIAL[59]),
    .Y(_0457_)
  );
  NAND _1103_ (
    .A(_0456_),
    .B(_0457_),
    .Y(_0458_)
  );
  NOR _1104_ (
    .A(_0455_),
    .B(_0458_),
    .Y(_0459_)
  );
  NAND _1105_ (
    .A(_0452_),
    .B(_0459_),
    .Y(_0460_)
  );
  NOR _1106_ (
    .A(BALANCE_INICIAL[36]),
    .B(BALANCE_INICIAL[37]),
    .Y(_0461_)
  );
  NOR _1107_ (
    .A(BALANCE_INICIAL[38]),
    .B(BALANCE_INICIAL[39]),
    .Y(_0462_)
  );
  NAND _1108_ (
    .A(_0461_),
    .B(_0462_),
    .Y(_0463_)
  );
  NOR _1109_ (
    .A(BALANCE_INICIAL[32]),
    .B(BALANCE_INICIAL[33]),
    .Y(_0464_)
  );
  NOR _1110_ (
    .A(BALANCE_INICIAL[34]),
    .B(BALANCE_INICIAL[35]),
    .Y(_0465_)
  );
  NAND _1111_ (
    .A(_0464_),
    .B(_0465_),
    .Y(_0466_)
  );
  NOR _1112_ (
    .A(_0463_),
    .B(_0466_),
    .Y(_0467_)
  );
  NOR _1113_ (
    .A(BALANCE_INICIAL[44]),
    .B(BALANCE_INICIAL[45]),
    .Y(_0468_)
  );
  NOR _1114_ (
    .A(BALANCE_INICIAL[46]),
    .B(BALANCE_INICIAL[47]),
    .Y(_0469_)
  );
  NAND _1115_ (
    .A(_0468_),
    .B(_0469_),
    .Y(_0470_)
  );
  NOR _1116_ (
    .A(BALANCE_INICIAL[40]),
    .B(BALANCE_INICIAL[41]),
    .Y(_0471_)
  );
  NOR _1117_ (
    .A(BALANCE_INICIAL[42]),
    .B(BALANCE_INICIAL[43]),
    .Y(_0472_)
  );
  NAND _1118_ (
    .A(_0471_),
    .B(_0472_),
    .Y(_0473_)
  );
  NOR _1119_ (
    .A(_0470_),
    .B(_0473_),
    .Y(_0474_)
  );
  NAND _1120_ (
    .A(_0467_),
    .B(_0474_),
    .Y(_0475_)
  );
  NOR _1121_ (
    .A(_0460_),
    .B(_0475_),
    .Y(_0476_)
  );
  NAND _1122_ (
    .A(_0445_),
    .B(_0476_),
    .Y(_0477_)
  );
  NOR _1123_ (
    .A(_0438_),
    .B(_0477_),
    .Y(_0478_)
  );
  NAND _1124_ (
    .A(_0201_),
    .B(_0478_),
    .Y(_0479_)
  );
  NOR _1125_ (
    .A(BALANCE_INICIAL[60]),
    .B(BALANCE_INICIAL[63]),
    .Y(_0480_)
  );
  NOR _1126_ (
    .A(BALANCE_INICIAL[52]),
    .B(BALANCE_INICIAL[55]),
    .Y(_0481_)
  );
  NOR _1127_ (
    .A(BALANCE_INICIAL[37]),
    .B(BALANCE_INICIAL[38]),
    .Y(_0482_)
  );
  NOT _1128_ (
    .A(_0482_),
    .Y(_0483_)
  );
  NOR _1129_ (
    .A(BALANCE_INICIAL[41]),
    .B(BALANCE_INICIAL[42]),
    .Y(_0484_)
  );
  NOR _1130_ (
    .A(BALANCE_INICIAL[50]),
    .B(BALANCE_INICIAL[61]),
    .Y(_0485_)
  );
  NOR _1131_ (
    .A(BALANCE_INICIAL[56]),
    .B(BALANCE_INICIAL[62]),
    .Y(_0486_)
  );
  NAND _1132_ (
    .A(_0485_),
    .B(_0486_),
    .Y(_0487_)
  );
  NOR _1133_ (
    .A(BALANCE_INICIAL[33]),
    .B(BALANCE_INICIAL[39]),
    .Y(_0488_)
  );
  NOR _1134_ (
    .A(BALANCE_INICIAL[35]),
    .B(BALANCE_INICIAL[44]),
    .Y(_0489_)
  );
  NAND _1135_ (
    .A(_0488_),
    .B(_0489_),
    .Y(_0490_)
  );
  NOR _1136_ (
    .A(_0487_),
    .B(_0490_),
    .Y(_0491_)
  );
  NAND _1137_ (
    .A(_0066_),
    .B(_0481_),
    .Y(_0492_)
  );
  NOR _1138_ (
    .A(BALANCE_INICIAL[34]),
    .B(BALANCE_INICIAL[36]),
    .Y(_0493_)
  );
  NOR _1139_ (
    .A(BALANCE_INICIAL[32]),
    .B(BALANCE_INICIAL[47]),
    .Y(_0494_)
  );
  NAND _1140_ (
    .A(_0493_),
    .B(_0494_),
    .Y(_0495_)
  );
  NOR _1141_ (
    .A(_0492_),
    .B(_0495_),
    .Y(_0496_)
  );
  NAND _1142_ (
    .A(_0491_),
    .B(_0496_),
    .Y(_0497_)
  );
  NOR _1143_ (
    .A(BALANCE_INICIAL[40]),
    .B(BALANCE_INICIAL[46]),
    .Y(_0498_)
  );
  NOR _1144_ (
    .A(BALANCE_INICIAL[51]),
    .B(BALANCE_INICIAL[53]),
    .Y(_0499_)
  );
  NAND _1145_ (
    .A(_0498_),
    .B(_0499_),
    .Y(_0500_)
  );
  NAND _1146_ (
    .A(_0065_),
    .B(_0480_),
    .Y(_0501_)
  );
  NOR _1147_ (
    .A(BALANCE_INICIAL[49]),
    .B(BALANCE_INICIAL[58]),
    .Y(_0502_)
  );
  NAND _1148_ (
    .A(_0484_),
    .B(_0502_),
    .Y(_0503_)
  );
  NOR _1149_ (
    .A(_0501_),
    .B(_0503_),
    .Y(_0504_)
  );
  NOR _1150_ (
    .A(BALANCE_INICIAL[43]),
    .B(BALANCE_INICIAL[45]),
    .Y(_0505_)
  );
  NOR _1151_ (
    .A(BALANCE_INICIAL[48]),
    .B(BALANCE_INICIAL[54]),
    .Y(_0506_)
  );
  NAND _1152_ (
    .A(_0505_),
    .B(_0506_),
    .Y(_0507_)
  );
  NOR _1153_ (
    .A(_0483_),
    .B(_0507_),
    .Y(_0508_)
  );
  NAND _1154_ (
    .A(_0504_),
    .B(_0508_),
    .Y(_0509_)
  );
  NOR _1155_ (
    .A(_0500_),
    .B(_0509_),
    .Y(_0510_)
  );
  NAND _1156_ (
    .A(_0445_),
    .B(_0510_),
    .Y(_0511_)
  );
  NOR _1157_ (
    .A(_0497_),
    .B(_0511_),
    .Y(_0512_)
  );
  NAND _1158_ (
    .A(_0439_),
    .B(_0512_),
    .Y(_0513_)
  );
  NAND _1159_ (
    .A(_0032_),
    .B(_0479_),
    .Y(_0514_)
  );
  NOR _1160_ (
    .A(state[0]),
    .B(_0032_),
    .Y(_0515_)
  );
  NOR _1161_ (
    .A(state[5]),
    .B(_0515_),
    .Y(_0516_)
  );
  NAND _1162_ (
    .A(_0017_),
    .B(_0514_),
    .Y(_0517_)
  );
  NOR _1163_ (
    .A(_0516_),
    .B(_0517_),
    .Y(_0004_)
  );
  NAND _1164_ (
    .A(_0017_),
    .B(_0198_),
    .Y(_0518_)
  );
  NAND _1165_ (
    .A(BLOQUEO),
    .B(_0193_),
    .Y(_0519_)
  );
  NAND _1166_ (
    .A(_0518_),
    .B(_0519_),
    .Y(_0002_)
  );
  NAND _1167_ (
    .A(_0016_),
    .B(state[3]),
    .Y(_0520_)
  );
  NOR _1168_ (
    .A(_0018_),
    .B(_0520_),
    .Y(_0521_)
  );
  NOR _1169_ (
    .A(ADVERTENCIA),
    .B(_0521_),
    .Y(_0522_)
  );
  NOR _1170_ (
    .A(_0194_),
    .B(_0522_),
    .Y(_0000_)
  );
  NOR _1171_ (
    .A(state[3]),
    .B(PIN_INCORRECTO),
    .Y(_0523_)
  );
  NOR _1172_ (
    .A(_0194_),
    .B(_0523_),
    .Y(_0005_)
  );
  NAND _1173_ (
    .A(_0201_),
    .B(_0513_),
    .Y(_0524_)
  );
  NAND _1174_ (
    .A(_0033_),
    .B(_0524_),
    .Y(_0525_)
  );
  NOR _1175_ (
    .A(state[0]),
    .B(_0033_),
    .Y(_0526_)
  );
  NOR _1176_ (
    .A(state[5]),
    .B(_0526_),
    .Y(_0527_)
  );
  NAND _1177_ (
    .A(_0017_),
    .B(_0525_),
    .Y(_0528_)
  );
  NOR _1178_ (
    .A(_0527_),
    .B(_0528_),
    .Y(_0003_)
  );
  NOR _1179_ (
    .A(_0024_),
    .B(_0513_),
    .Y(_0529_)
  );
  NOR _1180_ (
    .A(_0023_),
    .B(_0529_),
    .Y(_0530_)
  );
  NOR _1181_ (
    .A(BALANCE_ACTUALIZADO),
    .B(_0530_),
    .Y(_0531_)
  );
  NOR _1182_ (
    .A(state[0]),
    .B(_0034_),
    .Y(_0532_)
  );
  NOR _1183_ (
    .A(state[5]),
    .B(_0532_),
    .Y(_0533_)
  );
  NOR _1184_ (
    .A(rst),
    .B(_0533_),
    .Y(_0534_)
  );
  NOT _1185_ (
    .A(_0534_),
    .Y(_0535_)
  );
  NOR _1186_ (
    .A(_0531_),
    .B(_0535_),
    .Y(_0001_)
  );
  NOR _1187_ (
    .A(_0031_),
    .B(PIN[15]),
    .Y(_0536_)
  );
  NOR _1188_ (
    .A(pin_tecleado[15]),
    .B(_0101_),
    .Y(_0537_)
  );
  NOR _1189_ (
    .A(_0536_),
    .B(_0537_),
    .Y(_0538_)
  );
  NOR _1190_ (
    .A(pin_tecleado[5]),
    .B(_0099_),
    .Y(_0539_)
  );
  NAND _1191_ (
    .A(_0029_),
    .B(PIN[5]),
    .Y(_0540_)
  );
  NOR _1192_ (
    .A(_0029_),
    .B(PIN[5]),
    .Y(_0541_)
  );
  NAND _1193_ (
    .A(pin_tecleado[5]),
    .B(_0099_),
    .Y(_0542_)
  );
  NOR _1194_ (
    .A(_0028_),
    .B(PIN[3]),
    .Y(_0543_)
  );
  NOR _1195_ (
    .A(pin_tecleado[3]),
    .B(_0098_),
    .Y(_0544_)
  );
  NOR _1196_ (
    .A(_0543_),
    .B(_0544_),
    .Y(_0545_)
  );
  NAND _1197_ (
    .A(pin_tecleado[13]),
    .B(PIN[13]),
    .Y(_0546_)
  );
  NOR _1198_ (
    .A(pin_tecleado[13]),
    .B(PIN[13]),
    .Y(_0547_)
  );
  NOT _1199_ (
    .A(_0547_),
    .Y(_0548_)
  );
  NAND _1200_ (
    .A(_0546_),
    .B(_0548_),
    .Y(_0549_)
  );
  NOR _1201_ (
    .A(pin_tecleado[9]),
    .B(_0100_),
    .Y(_0550_)
  );
  NOR _1202_ (
    .A(pin_tecleado[6]),
    .B(PIN[6]),
    .Y(_0551_)
  );
  NOT _1203_ (
    .A(_0551_),
    .Y(_0552_)
  );
  NAND _1204_ (
    .A(pin_tecleado[6]),
    .B(PIN[6]),
    .Y(_0553_)
  );
  NAND _1205_ (
    .A(_0552_),
    .B(_0553_),
    .Y(_0554_)
  );
  NOR _1206_ (
    .A(pin_tecleado[7]),
    .B(PIN[7]),
    .Y(_0555_)
  );
  NOT _1207_ (
    .A(_0555_),
    .Y(_0556_)
  );
  NAND _1208_ (
    .A(pin_tecleado[7]),
    .B(PIN[7]),
    .Y(_0557_)
  );
  NAND _1209_ (
    .A(_0556_),
    .B(_0557_),
    .Y(_0558_)
  );
  NOR _1210_ (
    .A(pin_tecleado[12]),
    .B(PIN[12]),
    .Y(_0559_)
  );
  NOT _1211_ (
    .A(_0559_),
    .Y(_0560_)
  );
  NAND _1212_ (
    .A(pin_tecleado[12]),
    .B(PIN[12]),
    .Y(_0561_)
  );
  NAND _1213_ (
    .A(_0560_),
    .B(_0561_),
    .Y(_0562_)
  );
  NOR _1214_ (
    .A(pin_tecleado[1]),
    .B(PIN[1]),
    .Y(_0563_)
  );
  NOT _1215_ (
    .A(_0563_),
    .Y(_0564_)
  );
  NAND _1216_ (
    .A(pin_tecleado[1]),
    .B(PIN[1]),
    .Y(_0565_)
  );
  NOT _1217_ (
    .A(_0565_),
    .Y(_0566_)
  );
  NOR _1218_ (
    .A(_0563_),
    .B(_0566_),
    .Y(_0567_)
  );
  NAND _1219_ (
    .A(_0564_),
    .B(_0565_),
    .Y(_0568_)
  );
  NOR _1220_ (
    .A(pin_tecleado[0]),
    .B(_0096_),
    .Y(_0569_)
  );
  NAND _1221_ (
    .A(_0026_),
    .B(PIN[0]),
    .Y(_0570_)
  );
  NOR _1222_ (
    .A(_0027_),
    .B(PIN[2]),
    .Y(_0571_)
  );
  NOR _1223_ (
    .A(pin_tecleado[2]),
    .B(_0097_),
    .Y(_0572_)
  );
  NOR _1224_ (
    .A(_0571_),
    .B(_0572_),
    .Y(_0573_)
  );
  NOR _1225_ (
    .A(_0026_),
    .B(PIN[0]),
    .Y(_0574_)
  );
  NAND _1226_ (
    .A(pin_tecleado[0]),
    .B(_0096_),
    .Y(_0575_)
  );
  NOR _1227_ (
    .A(_0030_),
    .B(PIN[9]),
    .Y(_0576_)
  );
  NAND _1228_ (
    .A(pin_tecleado[8]),
    .B(PIN[8]),
    .Y(_0577_)
  );
  NOR _1229_ (
    .A(pin_tecleado[8]),
    .B(PIN[8]),
    .Y(_0578_)
  );
  NOT _1230_ (
    .A(_0578_),
    .Y(_0579_)
  );
  NAND _1231_ (
    .A(_0577_),
    .B(_0579_),
    .Y(_0580_)
  );
  NOR _1232_ (
    .A(_0550_),
    .B(_0571_),
    .Y(_0581_)
  );
  NAND _1233_ (
    .A(_0580_),
    .B(_0581_),
    .Y(_0582_)
  );
  NOR _1234_ (
    .A(_0539_),
    .B(_0572_),
    .Y(_0583_)
  );
  NAND _1235_ (
    .A(_0549_),
    .B(_0583_),
    .Y(_0584_)
  );
  NOR _1236_ (
    .A(_0582_),
    .B(_0584_),
    .Y(_0585_)
  );
  NAND _1237_ (
    .A(pin_tecleado[4]),
    .B(PIN[4]),
    .Y(_0586_)
  );
  NOR _1238_ (
    .A(pin_tecleado[4]),
    .B(PIN[4]),
    .Y(_0587_)
  );
  NOT _1239_ (
    .A(_0587_),
    .Y(_0588_)
  );
  NAND _1240_ (
    .A(_0586_),
    .B(_0588_),
    .Y(_0589_)
  );
  NOR _1241_ (
    .A(pin_tecleado[14]),
    .B(PIN[14]),
    .Y(_0590_)
  );
  NOT _1242_ (
    .A(_0590_),
    .Y(_0591_)
  );
  NAND _1243_ (
    .A(pin_tecleado[14]),
    .B(PIN[14]),
    .Y(_0592_)
  );
  NAND _1244_ (
    .A(_0591_),
    .B(_0592_),
    .Y(_0593_)
  );
  NAND _1245_ (
    .A(_0589_),
    .B(_0593_),
    .Y(_0594_)
  );
  NAND _1246_ (
    .A(pin_tecleado[11]),
    .B(PIN[11]),
    .Y(_0595_)
  );
  NOR _1247_ (
    .A(pin_tecleado[11]),
    .B(PIN[11]),
    .Y(_0596_)
  );
  NOT _1248_ (
    .A(_0596_),
    .Y(_0597_)
  );
  NAND _1249_ (
    .A(_0595_),
    .B(_0597_),
    .Y(_0598_)
  );
  NAND _1250_ (
    .A(_0568_),
    .B(_0598_),
    .Y(_0599_)
  );
  NOR _1251_ (
    .A(_0594_),
    .B(_0599_),
    .Y(_0600_)
  );
  NAND _1252_ (
    .A(_0585_),
    .B(_0600_),
    .Y(_0601_)
  );
  NOR _1253_ (
    .A(pin_tecleado[10]),
    .B(PIN[10]),
    .Y(_0602_)
  );
  NOT _1254_ (
    .A(_0602_),
    .Y(_0603_)
  );
  NAND _1255_ (
    .A(pin_tecleado[10]),
    .B(PIN[10]),
    .Y(_0604_)
  );
  NOT _1256_ (
    .A(_0604_),
    .Y(_0605_)
  );
  NOR _1257_ (
    .A(_0602_),
    .B(_0605_),
    .Y(_0606_)
  );
  NAND _1258_ (
    .A(_0603_),
    .B(_0604_),
    .Y(_0607_)
  );
  NAND _1259_ (
    .A(_0554_),
    .B(_0607_),
    .Y(_0608_)
  );
  NOR _1260_ (
    .A(_0569_),
    .B(_0574_),
    .Y(_0609_)
  );
  NAND _1261_ (
    .A(_0570_),
    .B(_0575_),
    .Y(_0610_)
  );
  NAND _1262_ (
    .A(_0545_),
    .B(_0609_),
    .Y(_0611_)
  );
  NOR _1263_ (
    .A(_0608_),
    .B(_0611_),
    .Y(_0612_)
  );
  NAND _1264_ (
    .A(_0558_),
    .B(_0562_),
    .Y(_0613_)
  );
  NOR _1265_ (
    .A(_0541_),
    .B(_0576_),
    .Y(_0614_)
  );
  NAND _1266_ (
    .A(_0538_),
    .B(_0614_),
    .Y(_0615_)
  );
  NOR _1267_ (
    .A(_0613_),
    .B(_0615_),
    .Y(_0616_)
  );
  NAND _1268_ (
    .A(_0612_),
    .B(_0616_),
    .Y(_0617_)
  );
  NOR _1269_ (
    .A(_0606_),
    .B(_0610_),
    .Y(_0618_)
  );
  NAND _1270_ (
    .A(_0545_),
    .B(_0554_),
    .Y(_0619_)
  );
  NAND _1271_ (
    .A(_0562_),
    .B(_0589_),
    .Y(_0620_)
  );
  NOR _1272_ (
    .A(_0619_),
    .B(_0620_),
    .Y(_0621_)
  );
  NAND _1273_ (
    .A(_0549_),
    .B(_0558_),
    .Y(_0622_)
  );
  NAND _1274_ (
    .A(_0593_),
    .B(_0598_),
    .Y(_0623_)
  );
  NOR _1275_ (
    .A(_0622_),
    .B(_0623_),
    .Y(_0624_)
  );
  NAND _1276_ (
    .A(_0621_),
    .B(_0624_),
    .Y(_0625_)
  );
  NAND _1277_ (
    .A(_0540_),
    .B(_0573_),
    .Y(_0626_)
  );
  NOR _1278_ (
    .A(_0550_),
    .B(_0576_),
    .Y(_0627_)
  );
  NAND _1279_ (
    .A(_0580_),
    .B(_0627_),
    .Y(_0628_)
  );
  NOR _1280_ (
    .A(_0626_),
    .B(_0628_),
    .Y(_0629_)
  );
  NAND _1281_ (
    .A(_0538_),
    .B(_0542_),
    .Y(_0630_)
  );
  NOR _1282_ (
    .A(_0567_),
    .B(_0630_),
    .Y(_0631_)
  );
  NAND _1283_ (
    .A(_0629_),
    .B(_0631_),
    .Y(_0632_)
  );
  NOR _1284_ (
    .A(_0625_),
    .B(_0632_),
    .Y(_0633_)
  );
  NOR _1285_ (
    .A(_0601_),
    .B(_0617_),
    .Y(_0634_)
  );
  NAND _1286_ (
    .A(_0618_),
    .B(_0633_),
    .Y(_0635_)
  );
  NAND _1287_ (
    .A(_0017_),
    .B(state[6]),
    .Y(_0636_)
  );
  NOR _1288_ (
    .A(_0635_),
    .B(_0636_),
    .Y(_0009_)
  );
  NOR _1289_ (
    .A(rst),
    .B(_0102_),
    .Y(_0012_)
  );
  NAND _1290_ (
    .A(state[0]),
    .B(TARJETA_RECIBIDA),
    .Y(_0637_)
  );
  NOR _1291_ (
    .A(rst),
    .B(_0637_),
    .Y(_0011_)
  );
  NOR _1292_ (
    .A(_0634_),
    .B(_0636_),
    .Y(_0010_)
  );
  DFF _1293_ (
    .C(clk),
    .D(_0013_),
    .Q(state[0])
  );
  DFF _1294_ (
    .C(clk),
    .D(_0009_),
    .Q(state[1])
  );
  DFF _1295_ (
    .C(clk),
    .D(_0014_),
    .Q(state[2])
  );
  DFF _1296_ (
    .C(clk),
    .D(_0010_),
    .Q(state[3])
  );
  DFF _1297_ (
    .C(clk),
    .D(_0011_),
    .Q(state[4])
  );
  DFF _1298_ (
    .C(clk),
    .D(_0012_),
    .Q(state[5])
  );
  DFF _1299_ (
    .C(clk),
    .D(_0015_),
    .Q(state[6])
  );
  (* src = "cajeroAutomatico.v:133" *)
  DFF _1300_ (
    .C(clk),
    .D(_0001_),
    .Q(BALANCE_ACTUALIZADO)
  );
  (* src = "cajeroAutomatico.v:133" *)
  DFF _1301_ (
    .C(clk),
    .D(_0003_),
    .Q(ENTREGAR_DINERO)
  );
  (* src = "cajeroAutomatico.v:133" *)
  DFF _1302_ (
    .C(clk),
    .D(_0005_),
    .Q(PIN_INCORRECTO)
  );
  (* src = "cajeroAutomatico.v:133" *)
  DFF _1303_ (
    .C(clk),
    .D(_0000_),
    .Q(ADVERTENCIA)
  );
  (* src = "cajeroAutomatico.v:133" *)
  DFF _1304_ (
    .C(clk),
    .D(_0002_),
    .Q(BLOQUEO)
  );
  (* src = "cajeroAutomatico.v:133" *)
  DFF _1305_ (
    .C(clk),
    .D(_0004_),
    .Q(FONDOS_INSUFICIENTES)
  );
  (* src = "cajeroAutomatico.v:133" *)
  DFF _1306_ (
    .C(clk),
    .D(_0007_[0]),
    .Q(intentos[0])
  );
  (* src = "cajeroAutomatico.v:133" *)
  DFF _1307_ (
    .C(clk),
    .D(_0007_[1]),
    .Q(intentos[1])
  );
  (* src = "cajeroAutomatico.v:133" *)
  DFF _1308_ (
    .C(clk),
    .D(_0008_[0]),
    .Q(pin_tecleado[0])
  );
  (* src = "cajeroAutomatico.v:133" *)
  DFF _1309_ (
    .C(clk),
    .D(_0008_[1]),
    .Q(pin_tecleado[1])
  );
  (* src = "cajeroAutomatico.v:133" *)
  DFF _1310_ (
    .C(clk),
    .D(_0008_[2]),
    .Q(pin_tecleado[2])
  );
  (* src = "cajeroAutomatico.v:133" *)
  DFF _1311_ (
    .C(clk),
    .D(_0008_[3]),
    .Q(pin_tecleado[3])
  );
  (* src = "cajeroAutomatico.v:133" *)
  DFF _1312_ (
    .C(clk),
    .D(_0008_[4]),
    .Q(pin_tecleado[4])
  );
  (* src = "cajeroAutomatico.v:133" *)
  DFF _1313_ (
    .C(clk),
    .D(_0008_[5]),
    .Q(pin_tecleado[5])
  );
  (* src = "cajeroAutomatico.v:133" *)
  DFF _1314_ (
    .C(clk),
    .D(_0008_[6]),
    .Q(pin_tecleado[6])
  );
  (* src = "cajeroAutomatico.v:133" *)
  DFF _1315_ (
    .C(clk),
    .D(_0008_[7]),
    .Q(pin_tecleado[7])
  );
  (* src = "cajeroAutomatico.v:133" *)
  DFF _1316_ (
    .C(clk),
    .D(_0008_[8]),
    .Q(pin_tecleado[8])
  );
  (* src = "cajeroAutomatico.v:133" *)
  DFF _1317_ (
    .C(clk),
    .D(_0008_[9]),
    .Q(pin_tecleado[9])
  );
  (* src = "cajeroAutomatico.v:133" *)
  DFF _1318_ (
    .C(clk),
    .D(_0008_[10]),
    .Q(pin_tecleado[10])
  );
  (* src = "cajeroAutomatico.v:133" *)
  DFF _1319_ (
    .C(clk),
    .D(_0008_[11]),
    .Q(pin_tecleado[11])
  );
  (* src = "cajeroAutomatico.v:133" *)
  DFF _1320_ (
    .C(clk),
    .D(_0008_[12]),
    .Q(pin_tecleado[12])
  );
  (* src = "cajeroAutomatico.v:133" *)
  DFF _1321_ (
    .C(clk),
    .D(_0008_[13]),
    .Q(pin_tecleado[13])
  );
  (* src = "cajeroAutomatico.v:133" *)
  DFF _1322_ (
    .C(clk),
    .D(_0008_[14]),
    .Q(pin_tecleado[14])
  );
  (* src = "cajeroAutomatico.v:133" *)
  DFF _1323_ (
    .C(clk),
    .D(_0008_[15]),
    .Q(pin_tecleado[15])
  );
  (* src = "cajeroAutomatico.v:133" *)
  DFF _1324_ (
    .C(clk),
    .D(_0006_[0]),
    .Q(digitos_ingresados[0])
  );
  (* src = "cajeroAutomatico.v:133" *)
  DFF _1325_ (
    .C(clk),
    .D(_0006_[1]),
    .Q(digitos_ingresados[1])
  );
endmodule
